### ISSUE TITLE
General approach to Java collections? -> UnmodifiableCollections do not seem to be de/serializable using Kryo

### ISSUE THREAD

**Issue by RafaShobr** [EsotericSoftware/kryo#1022]
Hi!
we are currently in the process of migrating from hessian to Kryo and so far its looking good, I really like Kryo :)
Our tests have shown, that not all java collection classes seem to be supported however.

For example trying to de/serialize unmodifiableCollection (Collection unmodifiableCollection = Collections.unmodifiableCollection(testList);) throws:
com.esotericsoftware.kryo.KryoException: Class cannot be created (missing no-arg constructor): java.util.Collections$UnmodifiableCollection

I wanted to ask if this is an oversight, or what the general guideline or approach of Kryo is regarding the standard collection classes of the JDK. I'm trying to find out if we can rely on the standard collections or if we need to be implementing custom serializers for some of those and if there would be an exhaustive list of in or excluded standard collection classes or something like that? :)

Thanks and regards,
Rafa

**Comment by theigl** [comment]
@RafaShobr: Sorry for the slow reply. I was AFK for the whole month. 

Kryo does not have built-in support UnmodifiableCollections. You need a third party serializer. See #997.
