### ISSUE TITLE
failed to lazily initialize a collection, no session or session was closed while trying to deserialize  SPRING_SECURITY_CONTEXT

### ISSUE THREAD

**Issue by rmageshkumar-greytip** [EsotericSoftware/kryo#1043]
We are using Memcache Session Backup manager to store the sessions. 
But when we try to find the session from memcache, it is failing to due to deserialization. 
Spring security storing SECURITY_CONTEXT in the session. 
We are storing below AuthenticatedUser object in the session. 
We are getting below error, try to fetch the session from session manager. 

**de.javakaffee.web.msm.TranscoderDeserializationException: com.esotericsoftware.kryo.KryoException: org.hibernate.LazyInitializationException: failed to lazily initialize a collection, no session or session was closed
Serialization trace:
features (com.magesh.common.model.user.Role)
role (com.magesh.common.model.user.RoleFeature)
roleFeatures (com.magesh.common.model.user.AcegiRoleSet)
roleSet (com.magesh.cougar.model.user.EdbNamedUser)
user (com.magesh.common.model.AuthenticatedUser)**
principal (org.springframework.security.web.authentication.preauth.PreAuthenticatedAuthenticationToken)
authentication (org.springframework.security.core.context.SecurityContextImpl)
	at de.javakaffee.web.msm.serializer.kryo.KryoTranscoder.deserializeAttributes(KryoTranscoder.java:213)
	at de.javakaffee.web.msm.TranscoderService.deserializeAttributes(TranscoderService.java:167)
	at de.javakaffee.web.msm.TranscoderService.deserialize(TranscoderService.java:124)
	at de.javakaffee.web.msm.MemcachedSessionService.loadFromMemcached(MemcachedSessionService.java:1155)
	at de.javakaffee.web.msm.MemcachedSessionService.findSession(MemcachedSessionService.java:605)
	at de.javakaffee.web.msm.MemcachedBackupSessionManager.findSession(MemcachedBackupSessionManager.java:201)
	at org.apache.catalina.connector.Request.doGetSession(Request.java:2932)
	at org.apache.catalina.connector.Request.getSessionInternal(Request.java:2677)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:451)

User .java;

	private Integer employee;
	private String userName;	
	private String password;
	private String email;
	@Optional("com.magesh.common.model.user.User.roles")
	private Set<Role> roles;
	@Optional("com.magesh.common.model.user.User.roleSet")
	private RoleSet roleSet;

AcegiRoleset/ Roleset.java

	@Optional("com.magesh.common.model.user.RoleSet.roles")
	private Set<Role> roles;
	private Map<String, RoleFeature> roleFeatures;
	private String accessRights;

Role.java

     private int id;
    private String name;
    @Optional("com.magesh.common.model.user.Role.features")
    private Set<RoleFeature> features = new HashSet<RoleFeature>();(one to many association, declared in xml (lazy = false))

Rolefeature:

    private int id;
    private Role role;(many to one association declared in xml lazy = false)
    private Feature feature;

**Environment:**
 - OS: ubunutu or mac or windows
 - JDK Version: 1.8
 - Kryo Version: 3.x 
 - tomcat version: tomcat9
 - memcache session manager : 2.3
 - msm kryo serializer : 1.9.7
 - kryoserializer: 0.37 and other dependencies.

**Comment by theigl** [comment]
Closing for now. Please re-open if you need further help.

**Comment by rmageshkumar-greytip** [comment]
Thanks, it is working now that I've changed it to a DTO.
