### ISSUE TITLE
Allow Kryo instances to be compared using .equals() & .hashcode() 

### ISSUE THREAD

**Issue by MrNavaStar** [EsotericSoftware/kryo#1047]
**Is your feature request related to a problem? Please describe.**
I am working on a networking library for creating custom protocols. The client and the server exchange protocol hashes to ensure they are on the same version. As I am using kryo as the backend for my packet registration system, it would be great if I could compare kryo instances to see if they are the same or not. Currently two separate but Identical kryo instances seem to produce different hash codes. I am not sure how large of a change this would require, so perhaps its not worth implementing. 

Either way, Cheers and thanks for this awesome library! 

**Describe the solution you'd like**
Allow for Kryo instances to be compared using `.equals()` & `.hashcode()` in a consistent and predicable way. 

**Describe alternatives you've considered**
I can always store packet registration data externally and calculate hashes separately (how I am doing it now),  but it would be nice (and very cool 😎) to not have to worry about it.

**Comment by MrNavaStar** [comment]
Also quick additional note, if this is something you decide to move forward and need an extra hand please let me know as I am always happy to contribute.

**Comment by theigl** [comment]
Implementing equals/hashCode for Kryo is complicated. It would need to consider *all* settings and the *current state* of the resolvers and various other objects used in the serialization process.

Most people will never need Kryo to implement these contracts.

You can always wrap Kryo in another object and implement equals/hashCode yourself.

**Comment by MrNavaStar** [comment]
Okay that's what I was wondering. No worries!
