### ISSUE TITLE
Equals objects produce different byte sequences.

### ISSUE THREAD

**Issue by ghost** [EsotericSoftware/kryo#105]
_From [a.solov...@tinkoffdigital.ru](https://code.google.com/u/113816139368312594170/) on March 22, 2013 10:16:01_

<b>What steps will reproduce the problem?</b>
&#13;
  1. Create a composite Object (object0) . Serialize the object0 to a   file0 with default settings.&#13;
  2. Save the object0, for example, to a database.&#13;
  3. Restore the object (object1) from the database.&#13;
  4. Be sure that the object1 equals object0;&#13;
  5. Serialize object1 to a file1.&#13;
  6. Compare file0 and file1. They are different.&#13;
&#13;
<b>What is the expected output? What do you see instead?</b>
&#13;
  Equals objects produce equals byte sequence; &#13;
&#13;
&#13;
<b>What version of the Kryo are you using?</b>
2.20&#13;
&#13;
<b>Please provide any additional information below.</b>
There is a workaround - kryo.setReferences(false);&#13;

**Attachment:** [objectStructure.7z](http://code.google.com/p/kryo/issues/detail?id=105)

_Original issue: http://code.google.com/p/kryo/issues/detail?id=105_

**Comment by magro** [comment]
Closing, reopen if still relevant.
