### ISSUE TITLE
How to configure CompatibleFieldSerializer in Kryo3 ?

### ISSUE THREAD

**Issue by geekthread** [EsotericSoftware/kryo#1081]
Hi team,

We are currently using Kryo3 and need assistance with setting the readUnknownFieldData option as mentioned [here](https://github.com/EsotericSoftware/kryo?tab=readme-ov-file#compatiblefieldserializer). Although we have successfully tested it on Kryo5, we are unable to find any configuration related to this field in Kryo3. The documentation does not specify the version compatibility. Migrating to Kryo5 would require a huge effort. Could you please help us?

**Comment by theigl** [comment]
Kryo 3 is 10 years old and completely unsupported for years. This option does not exist in Kryo 3.

**Comment by geekthread** [comment]
thanks for the confirmation @theigl
