### ISSUE TITLE
Invalid JDK version in profile 'jdk11ge': Unbounded range: [11, for project com.esotericsoftware:kryo-parent

### ISSUE THREAD

**Issue by manojkrishna1991** [EsotericSoftware/kryo#1103]
**When i try to  get dependency information from pom fails with unbounded range error**
Invalid JDK version in profile 'jdk11ge': Unbounded range: [11, for project com.esotericsoftware:kryo-parent

**To Reproduce**
kyro version used : 5.6.0

run ant task setup-classpath:

 <target name="setup-classpath" unless="classpath.setup">
        <artifact:dependencies pomRefId="maven.project" pathId="alldependency.libs" versionsId="alldependency.versions" filesetId="alldependency.fileset" />

   </target>

**Environment:**
 - OS: Ubuntu
 - JDK Version:17
 - Kryo Version: 5.6.0

we need to add closing tag to )	<jdk>[11,</jdk> similar to google gson 

 <jdk>[21,)</jdk> in pom.xml

**Comment by theigl** [comment]
Fixed. Thanks for reporting this.
