### ISSUE TITLE
Coordinates referenced in readme for com.esotericsoftware.kryo:kryo5:5.6.0 do not exist on maven central

### ISSUE THREAD

**Issue by philsttr** [EsotericSoftware/kryo#1124]
The readme says to use the `com.esotericsoftware.kryo:kryo5:5.6.0` dependency:

https://github.com/EsotericSoftware/kryo/blob/fbb62ca5321327250356816562be0b2db31e7440/README.md#L123-L131

However, this dependency does not exist.

The groupid changed for the kryo5 artifact between 5.5.0 and 5.6.0.

* [com.esotericsoftware.kryo:kryo5:5.5.0](https://repo1.maven.org/maven2/com/esotericsoftware/kryo/kryo5/5.5.0)
* [com.esotericsoftware.kryo5:5.6.0](https://repo1.maven.org/maven2/com/esotericsoftware/kryo5/5.6.0)

This change does not appear intentional, since the readme references the old coordinates (`com.esotericsoftware.kryo:kryo5`), and the [release notes for 5.6.0](https://github.com/EsotericSoftware/kryo/releases/tag/kryo-parent-5.6.0) don't mention the coordinate switch.

You could just update the readme to reflect the new coordinates, but I would prefer if the old `com.esotericsoftware.kryo:kryo5` coordinates were continued to be used, since there is lots of code referencing those coordinates.  Changing coordinates is always a major pain, since there is a high likelihood of both artifacts ending up on the classpath if different libraries pull in artifacts different coordinates.

**Comment by theigl** [comment]
This is a bug and has already been fixed on main. I will do a new release with correct coordinates shortly.

**Comment by theigl** [comment]
Should be fixed in 5.6.1. Please verify once the artifact appears in Maven central.
