### ISSUE TITLE
DefaultClassResolver: Attempt Thread.currentThread().getContextClassloader()

### ISSUE THREAD

**Issue by melloware** [EsotericSoftware/kryo#1145]
**Describe the bug**
We ran into this with Quarkus which uses 6 different classloaders.  We were able to fix it with...

```java
kryo.setClassLoader( Thread.currentThread().getContextClassLoader());
```

But shouldn't that be one of the classloaders tested by default?

```java
try {
    type = Class.forName(className, false, kryo.getClassLoader());
} catch (ClassNotFoundException ex) {
    // Fallback to current thread classloader
    try {
        type = Class.forName(className, false, Thread.currentThread().getContextClassLoader());
    } catch (ClassNotFoundException ex2) {
        // Fallback to Kryo's class loader.
        try {
            type = Class.forName(className, false, Kryo.class.getClassLoader());
        } catch (ClassNotFoundException ex2) {
            throw new KryoException("Unable to find class: " + className, ex);
        }
    }
}
```

**Comment by melloware** [comment]
Reproducer: https://github.com/suchwerk/quarkus-kryo-classloader-problem

**Comment by theigl** [comment]
That probably makes sense. Could you provide a PR?

**Comment by melloware** [comment]
Absolutely!

**Comment by melloware** [comment]
As a follow up Quarkus users are reporting this...

> Its a little bit confusing. The class loading issue persists if you don't set references to true.

**This is working:**
```java
        Kryo kryo = new Kryo();
        kryo.setRegistrationRequired(false);
        kryo.setReferences(true);
        kryo.setClassLoader(Thread.currentThread().getContextClassLoader());
```
**but this not:**

```java
        Kryo kryo = new Kryo();
        kryo.setRegistrationRequired(false);
        kryo.setClassLoader(Thread.currentThread().getContextClassLoader());
```

**Comment by theigl** [comment]
This doesn't make sense to me. Is the user able to provide a reproducer? Can you link the respective issues in Quarkus?

**Comment by melloware** [comment]
@theigl we can make you a runnable reproducer and get back to you.  Most of this conversation is happening on the Quarkus Zulip channel.

**Comment by melloware** [comment]
here you go: https://github.com/suchwerk/quarkus-kryo-classloader-problem

Just run `mvn quarkus:dev` to see the issue

**Comment by theigl** [comment]
Is it possible that the class-loader changes between invocations?

You could try invoking `kryo.setClassLoader(Thread.currentThread().getContextClassLoader());` before every object graph serialization and deserialization to see if it resolves the issue.

I will try to look into the reproducer.

**Comment by theigl** [comment]
@melloware: Sorry this took so long. I just managed to look at your reproducer and was able to fix it like this:

```java
@ApplicationScoped
public class FooService {

    static final ThreadLocal<Kryo> kryos = new ThreadLocal<Kryo>() {
        protected Kryo initialValue() {
            Kryo kryo = new Kryo();
            kryo.setClassLoader(Thread.currentThread().getContextClassLoader());
            kryo.setRegistrationRequired(false);
            kryo.setReferences(true);
            return kryo;
        };
    };

    static File file = new File("foo.bin");

    public void write(Foo foo) throws Exception {
        try (Output output = new Output(new FileOutputStream(file))) {
            final Kryo kryo = kryos.get();
            kryo.writeObject(output, foo);
        } catch (FileNotFoundException | KryoException e) {
            throw e;
        }
    }

    @Startup
    public void read() throws Exception {
        if (file.exists()) {
            try (Input input = new Input(new FileInputStream(file))) {
                final Kryo kryo = kryos.get();
                Foo foo = kryo.readObject(input, Foo.class);
                System.out.println(foo);
            } catch (FileNotFoundException | KryoException e) {
                throw e;
            }
        } else {
            System.err.println("Please generate: " + file.getAbsolutePath());
        }
    }
}
```

Kryo is used as a `ThreadLocal` because Kryo instances should always be re-used. I don't know if `ThreadLocal` or a pooled solution makes more sense in Quarkus, but it should definitely be re-used.

**Comment by melloware** [comment]
Awesome I will post this on the Quarkus Zulip channel where it was asked!
