### ISSUE TITLE
CompatibleFieldSerializer performance issue

### ISSUE THREAD

**Issue by ghost** [EsotericSoftware/kryo#120]
_From [njz...@gmail.com](https://code.google.com/u/105929176084098242792/) on July 19, 2013 08:41:45_

Both CompatibleFieldSerializer & TaggeFieldSerializer typically generate a way larger byte stream due to :
for (int i = 0, n = fields.length; i < n; i++)
      output.writeString(fields[i].field.getName());

However,using FieldSerializer provides zero backward compatibility.

Should there be an optional annotation/setting that allows an "integer-field" mapping that replaces "output.writeString(fields[i].field.getName())" by "output.writeInt(fieldId)" ?

_Original issue: http://code.google.com/p/kryo/issues/detail?id=120_

**Comment by magro** [comment]
Closing, reopen if still relevant.
