### ISSUE TITLE
KryoException because Input.require() does not properly compact full Input buffer

### ISSUE THREAD

**Issue by ghost** [EsotericSoftware/kryo#124]
_From [pbailis@gmail.com](https://code.google.com/u/pbailis@gmail.com/) on August 07, 2013 03:55:02_

<b>What steps will reproduce the problem?</b>
1. Use Kryo to serialize at least two objects of lengths M and N&#13;
2. Create an new Input of size M.&#13;
3. Read the first object from the Input, then attempt to read the second object.&#13;
&#13;
(See an example below where M=N=512b.)&#13;
&#13;
<b>What is the expected output? What do you see instead?</b>
&#13;
Instead of deserialization, a a "Buffer underflow" KryoException is thrown.&#13;
&#13;
Exception in thread "main" java.lang.RuntimeException: com.esotericsoftware.kryo.KryoException: Buffer underflow.&#13;
    at org.bailis.kryobug.main(KryoBug.java:64)&#13;
Caused by: com.esotericsoftware.kryo.KryoException: Buffer underflow.&#13;
    at com.esotericsoftware.kryo.io.Input.require(Input.java:159)&#13;
    at com.esotericsoftware.kryo.io.Input.readBytes(Input.java:321)&#13;
    at com.esotericsoftware.kryo.io.Input.readBytes(Input.java:306)&#13;
    at org.bailis.kryobug.main(KryoBug.java:61)&#13;
&#13;
<b>What version of the Kryo are you using?</b>
2.21&#13;
&#13;
<b>Please provide any additional information below.</b>
&#13;
This appears to have been introduced as part of <a title="Make input.java not compact if no stream is available (with patch)" class="closed_ref" href="/p/kryo/issues/detail?id=89"> Issue 89 </a> (<a href="/p/kryo/source/detail?r=352">r352</a>).&#13;
&#13;
It appears that, to fix this bug, the first invocation of fill() in require() should only occur if remaining &gt; 0. This can be accomplished via the patch below.&#13;
&#13;
Fortunately, 2.20 does not have this error since it compacts correctly:&#13;
<a href="https://code.google.com/p/kryo/source/browse/trunk/src/com/esotericsoftware/kryo/io/Input.java?r=338#148" rel="nofollow">https://code.google.com/p/kryo/source/browse/trunk/src/com/esotericsoftware/kryo/io/Input.java?r=338#148</a>&#13;
&#13;
Example below:&#13;
&#13;
ByteBuffer buf = ByteBuffer.allocate(1024);&#13;
ByteBufferOutputStream byteBufferOutputStream = new ByteBufferOutputStream(buf);&#13;
Output testOutput = new Output(byteBufferOutputStream);&#13;
testOutput.writeBytes(new byte[512]);&#13;
testOutput.writeBytes(new byte[512]);&#13;
testOutput.flush();&#13;
&#13;
ByteBufferInputStream testInputs = new ByteBufferInputStream();&#13;
buf.flip();&#13;
testInputs.setByteBuffer(buf);&#13;
Input input = new Input(testInputs, 512);&#13;
byte[] toRead = new byte[512];&#13;
input.readBytes(toRead);&#13;
&#13;
//this will throw a KryoException&#13;
input.readBytes(toRead);&#13;
&#13;
PATCH&#13;
&#13;
Index: src/com/esotericsoftware/kryo/io/Input.java&#13;
===================================================================&#13;
--- src/com/esotericsoftware/kryo/io/Input.java (<a href="/p/kryo/source/detail?r=384">revision 384</a>)&#13;
+++ src/com/esotericsoftware/kryo/io/Input.java (working copy)&#13;
@@ -154,14 +154,18 @@&#13;
        if (remaining &gt;= required) return remaining;&#13;
        if (required &gt; capacity) throw new KryoException("Buffer too small: capacity: " + capacity + ", required: " + required);&#13;
 &#13;
-       int count;&#13;
  +&#13;
      // Try to fill the buffer.&#13;
-       int count = fill(buffer, limit, capacity - limit);&#13;
-       if (count == -1) throw new KryoException("Buffer underflow.");&#13;
-       remaining += count;&#13;
-       if (remaining &gt;= required) {&#13;
-           limit += count;&#13;
-           return remaining;&#13;
-       }&#13;
-       if (remaining &gt; 0) {&#13;
-           count = fill(buffer, limit, capacity - limit);&#13;
-           if (count == -1) throw new KryoException("Buffer underflow.");&#13;
-           remaining += count;&#13;
-           if (remaining &gt;= required) {&#13;
-               limit += count;&#13;
-                   return remaining;&#13;
-       }&#13;
-        }&#13;
  &#13;
        // Was not enough, compact and try again.&#13;
        System.arraycopy(buffer, position, buffer, 0, remaining);

_Original issue: http://code.google.com/p/kryo/issues/detail?id=124_

**Comment by kjsingh** [comment]
Is this fixed in 2.21 or 2.24?
