### ISSUE TITLE
Patch to get KryoNet working with Kryo 2.21

### ISSUE THREAD

**Issue by ghost** [EsotericSoftware/kryo#125]
_From [robin.ki...@gmail.com](https://code.google.com/u/114916895304570456707/) on August 18, 2013 18:32:47_

Kryonet fails tests if you try to use kryo 2.21 with it.  Attached is a patch to apply to both kryo and kryonet to fix the issues.

Patch summary:
* Fix ByteBufferInputStream#read to not return -1 (indicating EOF) if length is zero.
* New ThrowableSerializer, because FieldSerializer won't work on Throwables as of Java 1.7
* KryoSerialization now supports references (and requires them for some RMI tests)

**Attachment:** [kryo_kryonet_patch.txt](http://code.google.com/p/kryo/issues/detail?id=125)

_Original issue: http://code.google.com/p/kryo/issues/detail?id=125_

**Comment by magro** [comment]
Closing, reopen if still relevant.
