### ISSUE TITLE
Performance Outliers

### ISSUE THREAD

**Issue by ghost** [EsotericSoftware/kryo#138]
_From [moru0...@gmail.com](https://code.google.com/u/109956740682506252532/) on October 08, 2013 13:09:50_

<b>What steps will reproduce the problem?</b>
&#13;
Run fast-serialization benchmarks :-)&#13;
&#13;
<b>What version of the Kryo are you using?</b>
2.2.2&#13;
&#13;
<a href="http://fast-serialization.googlecode.com/files/result-1.24.html" rel="nofollow">http://fast-serialization.googlecode.com/files/result-1.24.html</a>&#13;
&#13;
deserialization of large arrays and large strings seem broken. Other stuff has improved significantly, congrats ;-)&#13;
&#13;
this&#13;
<a href="http://code.google.com/p/fast-serialization/source/browse/trunk/src/test/java/de/ruedigermoeller/serialization/testclasses/basicstuff/LargeNativeArrays.java" rel="nofollow">http://code.google.com/p/fast-serialization/source/browse/trunk/src/test/java/de/ruedigermoeller/serialization/testclasses/basicstuff/LargeNativeArrays.java</a>&#13;
&#13;
and this&#13;
<a href="http://code.google.com/p/fast-serialization/source/browse/trunk/src/test/java/de/ruedigermoeller/serialization/testclasses/basicstuff/StringPerformance.java" rel="nofollow">http://code.google.com/p/fast-serialization/source/browse/trunk/src/test/java/de/ruedigermoeller/serialization/testclasses/basicstuff/StringPerformance.java</a>&#13;

_Original issue: http://code.google.com/p/kryo/issues/detail?id=138_

**Comment by magro** [comment]
@NathanSweet maybe this gives ideas for some specific benchmarks, perhaps also to identify potential further optimizations?

**Comment by NathanSweet** [comment]
FST is likely worth a closer look. We don't need this very old issue anymore though.
