### ISSUE TITLE
ReflectASM doesn't use primitive serializers

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/kryo#149]
From here:
https://groups.google.com/forum/#!topic/kryonet-users/AspUPsZcNu0

It seems ObjectField$ObjectIntField uses ObjectField#write/read which uses the registered serializer for primitive int. However AsmCachedField$AsmIntField does not use a serializer. This means something written on the desktop via ASM cannot be read on Android without ASM.

Here is an example:
https://github.com/EsotericSoftware/kryonet/blob/master/src/com/esotericsoftware/kryonet/rmi/ObjectSpace.java#L594
ObjectField#write will use this serializer, AsmIntField#read won't.

**Comment by magro** [comment]
Closing, reopen if still relevant.
