### ISSUE TITLE
Replacing bundle at runtime may cause ClassCastException

### ISSUE THREAD

**Issue by m-niedermaier** [EsotericSoftware/kryo#160]
Problem is, that DefaultClassResolver.nameToClass map contains the name to Class References

When bundle is exchanged in OSGI, it gets a new ClassLoader. When then a deserialize uses the cached class, it will not be usable by the new bundle

Reproduce:
Run OSGI
deserialize an object available in Bundle X using the classloader of Bundle X ==> Kryo caches the name to class
exchange Bundle X by uninstalling and installing it again while OSGI Runtime is running
deserialize an object available in Bundle X using the classloader of Bundle X ==> Kryo uses the cached class what will cause a ClassCastException

Caused by: java.lang.ClassCastException: my.package.MyObject cannot be cast to my.package.MyObject 

creating a new instance for Kryo would solve the problem

but we have the problem, that we registered the kryo instance as OSGI service and the instance stays the same even if another bundle gets echanged by e.g. a new version.

some solution suggestions:
but maybe its also a good idea to either
make the caching configurable 
or to 
check that classloader fits to the cached class like this:
...........
			if (nameToClass != null) type = nameToClass.get(className);
			if (type!=null && !(type.getClassLoader().equals(kryo.getClassLoader()))) type = null;
			
(this option may be improved to dont lead to load the class everytime if object is coming from a parent classloader)

3rd possibility is to reset the cached classes when the setClassLoader method is called with another classloader

see: https://groups.google.com/forum/#!searchin/kryo-users/nameToClass/kryo-users/JYVRpazVJDE/seNld7QhQhIJ

**Comment by magro** [comment]
Closing, reopen if still relevant.
