### ISSUE TITLE
Support serialization of Kryo and Kryo serializers instances

### ISSUE THREAD

**Issue by romix** [EsotericSoftware/kryo#174]
It could be very useful if one could serialize instances of Kryo and serializers.  This would essentially provide a meta-information about Kryo's configuration. And this can be used to create/configure a Kryo instance on the deserializing side exactly in the same way without   any need for manual coding. 

Such a feature could be also interesting for use-cases, where Kryo is used as a representation for a long-term storage of data. In such scenarios, one typically needs to store some sort of meta-information (a "schema", so to say), so that later it is possible to determine, which format is used for the stored data. While this proposal does not completely solve this issue, it is probably a step in the right direction.

**Comment by NathanSweet** [comment]
I understand the need, but I think with the provided serializers it's hard to serialize an entire, configured Kryo instance. I think I prefer not going down that road, at least for now.
