### ISSUE TITLE
Make originalToCopy accessible for copying

### ISSUE THREAD

**Issue by Philipp15b** [EsotericSoftware/kryo#179]
Sometimes I want to clone large graphs, but I need to keep a reference to the root object and some other object in the graph. When copying the root object however, I lose the reference to the other object. I think it would help quite a lot to make `Kryo#originalToCopy` accessible or provide another alternative to copy an object while keeping some references.

**Comment by Jason-purse** [comment]
getOriginalToCopyMap  

Only when a copy method is used, but in the latest kryo#copy method, it is only valid for every full cycle of copy? Shouldn't it be the same as the other methods? Cleaned up only when setAutoReset(true)? This method note makes me ambiguous
