### ISSUE TITLE
Provide an efficient way to create new Kryo instances or serializer instances based on already constructed instances

### ISSUE THREAD

**Issue by romix** [EsotericSoftware/kryo#188]
In some scenarios (e.g. multi-threaded applications, app servers, etc), it is often required to create a number of Kryo instances which are exactly the same in terms of registered serializers and other configuration aspects. This is done because Kryo instances and serializer instances are not thread-safe and hence each thread needs its own copy to be able to (de)serialize concurrently with other threads.

Creation of Kryo instances usually introduces quite some overhead. Most of it can be attributed to a pretty expensive creation of certain serializers. The most expensive (when it comes to the serializer creation overhead) and most widely used serializer is FieldSerializer and serializers based on it.  FieldSerializer is so expensive e.g. due to extensive use of Java reflection and some other mechanisms. Most other serializers do not involve a lot of overhead when they are being created.

To make Kryo more suitable for usage in described scenarios, it could be interesting to provide an efficient way to create new Kryo instances or serializer instances based on already constructed instances. 

There are most likely different ways to achieve it. 

One of the simplest possibilities, IMHO, is to provide a sort of "clone" method for Kryo and serializer instances. Such a method would create a new instance of a serializer or of a Kryo instance by (re)using information from the existing instance. Since the internal state of the existing instance is already known, creating a copy would be very cheap. For example, FieldSerializer#clone()  would not need to use any reflection and perform any analysis of a class over and over again. It can simply copy all the required information from an already constructed instance. The same applies to Kryo instances - the new instance would simply create a clone of all registrations from the old instance by recursively creating clones of all registered serializers.

Would such a feature be useful? Do you think that a proposed solution makes sense? Do you see simpler and/or more elegant ways to achieve the same?

P.S. This issue seems to be somewhat related to the #174 (serialization of Kryo instances)

**Comment by NathanSweet** [comment]
FWIW, I'm still not excited about this. I just have doubts that it is important to be able to create many Kryo instances fast/cheap. Using a pool of Kryo instances is likely sufficient.

**Comment by igreenfield** [comment]
What the status of that issue? I am using spark version 2.3.1 and in thread-dump, I see all my threads are blocking on newInstance

**Comment by NathanSweet** [comment]
It is unlikely we will attempt to make Kryo instance creation cheap. Consider [pooling](https://github.com/EsotericSoftware/kryo#pooling).
