### ISSUE TITLE
Shaded dependencies should be removed or have provided scope

### ISSUE THREAD

**Issue by sslavic** [EsotericSoftware/kryo#189]
Kryo shaded artifact (with all dependencies, like minlog) replaces main Kryo Maven artifact (jar without dependencies) and becomes the one that gets published to repositories and used. Problem is that the Kryo pom artifact published on repositories does not reflect that dependencies are shaded, it still lists them as compile scoped. So shading a project which depends on Kryo produces merge conflicts, same classes provided from Kryo, and from its dependencies.

Please adjust Kryo build script to have published pom list shaded dependencies as with provided scope, or removed from dependencies list. See [maven-shade-plugin configuration](http://maven.apache.org/plugins/maven-shade-plugin/shade-mojo.html)

**Comment by magro** [comment]
Was not reported any more.
