### ISSUE TITLE
Automatically register classes

### ISSUE THREAD

**Issue by T3rm1** [EsotericSoftware/kryo#196]
I read about Kryo in the latest Java Spektrum magazine. They compared several serialization frameworks. Kryo was very promising.

I immediately tried out Kryo but failed to succeed. I have a very complicated class which is serialized by XStream just fine. Kryo however is not able to do that. I get "encountered unregistered class id" error. I'm not sure if I understand correctly. The documentation isn't quite clear on that. If I want to serialize an object do I have to register every class which is used by that object?

I'm using writeClassAndObject and readClassAndObject. I debuged the code and found out that com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(Input).registration contains only the primitive types and none of my classes.

**Comment by Amitkumar13** [comment]
Hi,

How i explicitly register class in kryo, please suggest the method, how can i do this.

Please help me.

**Comment by Amitkumar13** [comment]
Hi,

How i explicitly register class in kryo, please suggest the method, how can i do this.

Please help me.

why i need to  explicitly register class in kryo ?

**Comment by romix** [comment]
If you register classes in Kryo, then your data is serialized and deserialized faster and the serialized representation is also (much) smaller, because the fully-qualified class names are not written into the serialized data. In addition to that, registration allows you to define and register your own custom serializers. And last, but not least, it ensures the deterministic order of IDs assigned to your classes during serialization.

You can register you class by:
```java

Kryo kryo = new Kryo();
kryo.register(MyClass.class);
// or alternatively
kryo.register(MyClass.class, new MySerializer());
```

**Comment by NathanSweet** [comment]
@Amitkumar13 This is an issue tracker, not a general help forum. Please read the docs and use the mailing list for questions.

**Comment by Amitkumar13** [comment]
I really appreciate your quick help, thank you so much.

I have a below issue, so my frnds suggest to resister the class explicitly.

"past 2 days, I’ve been running the same Hive queries.  ~80% of the time they fail with this KyroException, thrown from the Hive code.  20% of the time the same job, runs successfully.  No code differences between runs.

Yesterday, this same Hive Query failed with the KyroException all afternoon.  Then around 8:00 PM at night it ran fine.  This morning (4/23), I ran the same code again, processing 2 rows of data, and the job failed."

**Comment by Amitkumar13** [comment]
I really appreciate your quick help, thank you so much.

I have a below issue, so my frnds suggest to resister the class explicitly.

"past 2 days, I’ve been running the same Hive queries. ~80% of the time they fail with this KyroException, thrown from the Hive code. 20% of the time the same job, runs successfully. No code differences between runs.

Yesterday, this same Hive Query failed with the KyroException all afternoon. Then around 8:00 PM at night it ran fine. This morning (4/23), I ran the same code again, processing 2 rows of data, and the job failed."

Below are the logs :

2015-04-23 10:35:57,893 INFO [main] org.apache.hadoop.hive.ql.exec.Utilities: Deserializing MapWork via kryo
2015-04-23 10:35:58,290 ERROR [main] org.apache.hadoop.hive.ql.exec.Utilities: Failed to load plan: hdfs://nameservice1/tmp/hive-dks0344135/hive_2015-04-23_10-34-25_211_2333815521043174815-4/-mr-10016/b7fe67d9-5471-4e66-bdf4-6280f840f5ec/map.xml
org.apache.hive.com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: -848874534
Serialization trace:
startTimes (org.apache.hadoop.hive.ql.log.PerfLogger)
perfLogger (org.apache.hadoop.hive.ql.exec.MapJoinOperator)
parentOperators (org.apache.hadoop.hive.ql.exec.SelectOperator)
parentOperators (org.apache.hadoop.hive.ql.exec.MapJoinOperator)
parentOperators (org.apache.hadoop.hive.ql.exec.FilterOperator)
parentOperators (org.apache.hadoop.hive.ql.exec.SelectOperator)
parentOperators (org.apache.hadoop.hive.ql.exec.UnionOperator)
childOperators (org.apache.hadoop.hive.ql.exec.TableScanOperator)
aliasToWork (org.apache.hadoop.hive.ql.plan.MapWork)
	at org.apache.hive.com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:119)

**Comment by Amitkumar13** [comment]
Sorry nathan,i m between the issue, thaty why searching for help, will not do again.

Thank you.
