### ISSUE TITLE
Default serializer choice is unintuitive

### ISSUE THREAD

**Issue by brianfromoregon** [EsotericSoftware/kryo#200]
class B extends A

kryo.addDefaultSerializer(A, ASer)
kryo.addDefaultSerializer(B, BSer)

kryo.write(new B())

In the above example, ASer will be chosen to serialize B even though BSer is a better choice. 

Suggest that in addDefaultSerializer you choose the list position smarter by walk thru existing types and if there is a child class then DO NOT insert in front of that entry.

**Comment by magro** [comment]
Closing, reopen if still relevant.

**Comment by brianfromoregon** [comment]
I view this as a bug still fwiw.

**Comment by magro** [comment]
@brianfromoregon Do you want to submit a pull request?

**Comment by magro** [comment]
@NathanSweet maybe now there's time for this improvement?

**Comment by NathanSweet** [comment]
@brianfromoregon It was implemented in f07a1317b839ad49043f0ae1405715fc59826fba. If there is a bug with it, please open a new issue detailing the problem.

**Comment by brianfromoregon** [comment]
Oh nice. Sorry for the noise, I must have misread the history.
