### ISSUE TITLE
Bug in Kryo#register(Class, int)

### ISSUE THREAD

**Issue by brianfromoregon** [EsotericSoftware/kryo#224]
Today register(Class, int) looks like this

	public Registration register (Class type, int id) {
		Registration registration = classResolver.getRegistration(type);
		if (registration != null) return registration;
		return register(type, getDefaultSerializer(type), id);
	}

I think it should be this

	public Registration register (Class type, int id) {
		return register(type, getDefaultSerializer(type), id);
	}

I have a data store where a class C is associated with multiple ids. I need to create a Kryo which can read this store, but if I can't register the same class with multiple ids then I have a problem. register(Class, Serializer, int) is already correct, register(Class, int) just needs to be changed to match.

**Comment by magro** [comment]
Closing, reopen if still relevant.

**Comment by brianfromoregon** [comment]
I view this as a bug still fwiw.

**Comment by brianfromoregon** [comment]
Hi, I still think this is a valid bug, worth keeping open in case someone finds the cycles to fix?
