### ISSUE TITLE
Zero-copy builder

### ISSUE THREAD

**Issue by brianfromoregon** [EsotericSoftware/kryo#234]
At work I'm seeing a need to remove Kryo from the critical path of certain systems. What I see is a convenient Kryo based serialization offering for most people and a less convenient non-Kryo based serialization offering for folks with extreme speed requirements. Ideally for me Kryo could be used in both cases and I have a single stack to maintain. The issue is that folks are wanting zero-copy behavior, where by zero-copy I mean the description given here http://kentonv.github.io/capnproto/news/2014-06-17-capnproto-flatbuffers-sbe.html 

Is there any interest in such a feature?

**Comment by magro** [comment]
Closing, reopen if still relevant.
