### ISSUE TITLE
new Kyro() give not found InstantiatorStrategy

### ISSUE THREAD

**Issue by MauroMombelli** [EsotericSoftware/kryo#242]
following the example https://github.com/EsotericSoftware/kryo#copyingcloning i have a 

"
java.lang.NoClassDefFoundError: org/objenesis/strategy/InstantiatorStrategy
[...]
Caused by: java.lang.ClassNotFoundException: org.objenesis.strategy.InstantiatorStrategy
"

my object implements Serializable, and i just need to deep copy them (there is no map or recursion involved, just some (serializable) subclass or variable.

**Comment by helpermethod** [comment]
This also happens when using Maven.
