### ISSUE TITLE
Allow a SerializerFactory to decline to construct a Serializer

### ISSUE THREAD

**Issue by shevek** [EsotericSoftware/kryo#246]
In Kryo.java:

```
        for (int i = 0, n = defaultSerializers.size(); i < n; i++) {
            DefaultSerializerEntry entry = defaultSerializers.get(i);
            if (entry.type.isAssignableFrom(type)) {
                Serializer defaultSerializer = entry.serializerFactory.makeSerializer(this, type);
                return defaultSerializer;
            }
        }
```

It would be nice if makeSerializer() could return null to instruct the loop to continue to the next serializer.

Example: I want to serialize all types which are subclasses of A _and_ B, e.g. guava-Predicate && Serializable. I can't write a Kryo serializer for just one or just the other.

**Comment by magro** [comment]
@NathanSweet maybe also a candidate for 5.0?
