### ISSUE TITLE
Strange JVM crashes when using Kryo

### ISSUE THREAD

**Issue by a701440** [EsotericSoftware/kryo#249]
On MacOS using Java build 1.7.0_60-b19 and kryo 2.24.0. I get core dumps when trying to use Kryo for serialization / deserialization of large object graphs. The problems go away when the only thing that is changed is the low level serialization code switch back to ObjectOutputStream/ObjectInputStream. 

I also see some exceptions in de-serialization code like the sample below where the call-stack seems to be corrupt - it show functions on the call-stack which do not correspond to the source-code. For example the call stack may show that function A calls function B, where in fact function B is never called from function A, the line numbers don't make sense, etc.

I am not sure how to narrow this down yet. Going to try and remove Objenesis first. I currently have this call made:
((Kryo.DefaultInstantiatorStrategy) kryo.getInstantiatorStrategy()).setFallbackInstantiatorStrategy(new StdInstantiatorStrategy()); 

and add some default constructors to classes where they are missing,

Sample corrupt call stack:

        at com.xxx.xxx.xxx.xxx.XXXComparator.compare(XXXComparator.java:1)
        at java.util.TreeMap.compare(TreeMap.java:1188)
        at java.util.TreeMap.put(TreeMap.java:531)
        at java.util.TreeSet.add(TreeSet.java:255)
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:116)
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:22)
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106)

Sample JVM crash:

# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000102fa338a, pid=83371, tid=151043
#
# JRE version: Java(TM) SE Runtime Environment (7.0_60-b19) (build 1.7.0_60-b19)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (24.60-b09 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.dylib+0x3a338a]
.......
Stack: [0x000000012013e000,0x000000012023e000],  sp=0x0000000120238b40,  free space=1002k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.dylib+0x3a338a]
V  [libjvm.dylib+0x2d649a]
j  com.xxx.xxx.xxx.xxx.XXXComparator.compare(Lcom/xxx/xxx/xxx/xxx/XXX;Lcom/xxx/xxx/xxx/xxx/XXX;)I+72
j  com.xxx.xxx.xxx.xxx.XXXComparator.compare(Ljava/lang/Object;Ljava/lang/Object;)I+15
J 2862 C2 java.util.TreeMap.put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (342 bytes) @ 0x00000001059aa3ac [0x00000001059a9ce0+0x6cc]
J 4139 C2 java.util.TreeSet.add(Ljava/lang/Object;)Z (34 bytes) @ 0x0000000105c913c0 [0x0000000105c91360+0x60]
j  com.esotericsoftware.kryo.serializers.CollectionSerializer.read(Lcom/esotericsoftware/kryo/Kryo;Lcom/esotericsoftware/kryo/io/Input;Ljava/lang/Class;)Ljava/util/Collection;+192
j  com.esotericsoftware.kryo.serializers.CollectionSerializer.read(Lcom/esotericsoftware/kryo/Kryo;Lcom/esotericsoftware/kryo/io/Input;Ljava/lang/Class;)Ljava/lang/Object;+10
j  com.esotericsoftware.kryo.Kryo.readObject(Lcom/esotericsoftware/kryo/io/Input;Ljava/lang/Class;Lcom/esotericsoftware/kryo/Serializer;)Ljava/lang/Object;+183
j  com.esotericsoftware.kryo.serializers.ObjectField.read(Lcom/esotericsoftware/kryo/io/Input;Ljava/lang/Object;)V+167
j  com.esotericsoftware.kryo.serializers.FieldSerializer.read(Lcom/esotericsoftware/kryo/Kryo;Lcom/esotericsoftware/kryo/io/Input;Ljava/lang/Class;)Ljava/lang/Object;+84
j  com.esotericsoftware.kryo.Kryo.readObject(Lcom/esotericsoftware/kryo/io/Input;Ljava/lang/Class;Lcom/esotericsoftware/kryo/Serializer;)Ljava/lang/Object;+183
j  com.esotericsoftware.kryo.serializers.ObjectField.read(Lcom/esotericsoftware/kryo/io/Input;Ljava/lang/Object;)V+167
j  com.esotericsoftware.kryo.serializers.FieldSerializer.read(Lcom/esotericsoftware/kryo/Kryo;Lcom/esotericsoftware/kryo/io/Input;Ljava/lang/Class;)Ljava/lang/Object;+84
j  com.esotericsoftware.kryo.Kryo.readObject(Lcom/esotericsoftware/kryo/io/Input;Ljava/lang/Class;Lcom/esotericsoftware/kryo/Serializer;)Ljava/lang/Object;+183
j  com.esotericsoftware.kryo.serializers.ObjectField.read(Lcom/esotericsoftware/kryo/io/Input;Ljava/lang/Object;)V+167
j  com.esotericsoftware.kryo.serializers.FieldSerializer.read(Lcom/esotericsoftware/kryo/Kryo;Lcom/esotericsoftware/kryo/io/Input;Ljava/lang/Class;)Ljava/lang/Object;+84
j  com.esotericsoftware.kryo.Kryo.readObject(Lcom/esotericsoftware/kryo/io/Input;Ljava/lang/Class;Lcom/esotericsoftware/kryo/Serializer;)Ljava/lang/Object;+183
j  com.esotericsoftware.kryo.serializers.ObjectField.read(Lcom/esotericsoftware/kryo/io/Input;Ljava/lang/Object;)V+167
j  com.esotericsoftware.kryo.serializers.FieldSerializer.read(Lcom/esotericsoftware/kryo/Kryo;Lcom/esotericsoftware/kryo/io/Input;Ljava/lang/Class;)Ljava/lang/Object;+84
j  com.esotericsoftware.kryo.Kryo.readObject(Lcom/esotericsoftware/kryo/io/Input;Ljava/lang/Class;Lcom/esotericsoftware/kryo/Serializer;)Ljava/lang/Object;+183
j  com.esotericsoftware.kryo.serializers.ObjectField.read(Lcom/esotericsoftware/kryo/io/Input;Ljava/lang/Object;)V+167
j  com.esotericsoftware.kryo.serializers.FieldSerializer.read(Lcom/esotericsoftware/kryo/Kryo;Lcom/esotericsoftware/kryo/io/Input;Ljava/lang/Class;)Ljava/lang/Object;+84
j  com.esotericsoftware.kryo.Kryo.readClassAndObject(Lcom/esotericsoftware/kryo/io/Input;)Ljava/lang/Object;+177
j  com.esotericsoftware.kryo.serializers.CollectionSerializer.read(Lcom/esotericsoftware/kryo/Kryo;Lcom/esotericsoftware/kryo/io/Input;Ljava/lang/Class;)Ljava/util/Collection;+189
j  com.esotericsoftware.kryo.serializers.CollectionSerializer.read(Lcom/esotericsoftware/kryo/Kryo;Lcom/esotericsoftware/kryo/io/Input;Ljava/lang/Class;)Ljava/lang/Object;+10
j  com.esotericsoftware.kryo.Kryo.readClassAndObject(Lcom/esotericsoftware/kryo/io/Input;)Ljava/lang/Object;+177
j  com.esotericsoftware.kryo.io.KryoObjectInput.readObject()Ljava/lang/Object;+14

**Comment by magro** [comment]
Closing, reopen if still relevant.
