### ISSUE TITLE
When using StdInstantiatorStrategy CollectionSerializer is broken

### ISSUE THREAD

**Issue by a701440** [EsotericSoftware/kryo#254]
CollectionSerializer makes this call in read:

if (collection instanceof ArrayList) ((ArrayList)collection).ensureCapacity(length);

which crashes with the NullPointerException because the ArrayList does not have it's elementData member initialized when using StdInstantiatorStrategy.

**Comment by magro** [comment]
@NathanSweet reconsider for 5.0, or should we close it?

**Comment by NathanSweet** [comment]
CollectionSerializer special cases ArrayList in a different way for 5.0, so this problem should go away. It may still occur for other classes, but it is a problem with using StdInstantiatorStrategy on the wrong classes, not  a problem with Kryo.
