### ISSUE TITLE
Read methods should not mutate direct buffer

### ISSUE THREAD

**Issue by brianfromoregon** [EsotericSoftware/kryo#259]
Somewhat related to #128. UnsafeMemoryInput's readAscii is calling nioBuffer.put to temporarily mutate the data. This is no good, my buffer is a region of mmap file and a process bounce inside readAscii could corrupt the data. Read methods _cannot_ write to the buffer.

**Comment by magro** [comment]
@NathanSweet I think this is fixed in 5.0, right?

**Comment by NathanSweet** [comment]
Yep.
