### ISSUE TITLE
java.lang.IllegalAccessError: tried to access class sun.nio.cs.UTF_8 from class sun.nio.cs.UTF_8ConstructorAccess

### ISSUE THREAD

**Issue by haochun** [EsotericSoftware/kryo#260]
When I was in use kryo as serialization tools, an exception occurred: Java. Lang. IllegalAccessError: tried to access a class sun. Nio. Cs, UTF_8 from class sun. Nio. Cs. UTF_8ConstructorAccess

I was using kryo to serialize the Google BloomFilter this class, serialized to a file successfully, but when I deserialization returned an error has occurred, the code is as follows:

Kryo kryo = new Kryo();
		Input input;
		try {
			input = new Input(new FileInputStream("d:/similar.kryo"));
			BloomFilter<String> bloomFilter = kryo.readObject(input, BloomFilter.class);
			input.close();
			System.out.println(bloomFilter);
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		}

**Comment by jagrutmehta** [comment]
This error is not just limited to UTF-8 but to other Charsets as well like UTF-16, UTF-16BE, UTF-16LE, ISO_8859_1. These classes may be used internally by java lang objects and without user knowing it. 

Is it a good idea to supply serializer for these Charsets? Serializer code is very simple but may be very useful and moreover streamlined for all kryo users. Please let me know if its a good idea or not. If yes then I will submit PR.

**Comment by magro** [comment]
This should solved with #364

**Comment by becomehero** [comment]
I have the problem that "com.esotericsoftware.kryo.KryoException: Error constructing instance of class: sun.nio.cs.UTF_8", I have seen  "EsotericSoftware/kryo#364" on github, but I don't know to do for the problem, can you give me a help with a clear explanation.
