### ISSUE TITLE
CompatibleFieldSerializer does not support fields with the same name in sub classes

### ISSUE THREAD

**Issue by a701440** [EsotericSoftware/kryo#261]
Since the serializer writes out just the field names it does not support sub classes where there is a field with the same name such as "currency" in the example below. The field name "currency" will be written into the output two times, but on read both will update the subclass field and not the base class field.

Granted it's an edge case. For us it was introduced temporarily for backwards compatibility reasons.

public class SubClass1 extends Base1 {
        private Currency currency;
        public void setSubCurrency(Currency currency) {
            this.currency = currency;
        }

```
    public Currency getSubCurrency() {
        return this.currency;
    }
}

public class Base1 {
    private Currency currency;
    void setBaseCurrency(Currency currency) {
        this.currency = currency;
    }

    Currency getBaseCurrency() {
        return this.currency;
    }
}
```

**Comment by magro** [comment]
Fixed with #424
