### ISSUE TITLE
Input.readAscii multithreaded bug

### ISSUE THREAD

**Issue by devinrsmith** [EsotericSoftware/kryo#264]
After lots of debugging and testing out different theories, I found a multithreaded bug that causes non-deterministic results in Input.readAscii. 

Specifically, Input.readAscii modifies the user's passed in buffer. If the user passes in the same buffer pointer to multiple Inputs, then readAscii instances may read past the proper end.

While it might seem rare that somebody is deserializing the same exact buffer multiple times, it definitely comes into play when running DBs in memory.

It looks like this is the only place in Input that modifies the buffer.

**Comment by magro** [comment]
@NathanSweet fixed in 5.0?

**Comment by NathanSweet** [comment]
Yep.
