### ISSUE TITLE
Read performance issue with FieldSerializer ?

### ISSUE THREAD

**Issue by a701440** [EsotericSoftware/kryo#265]
Not positive yet, but it seems like it's possible to optimize FieldSerializer.rebuildCachedFields where it calls genericsUtil.buildGenericsScope to pass the typeParameters member instead of calling typ.getTypeParameters() inside of the utils. It appears that getTypeParameters may be called on each field read. As far as I understand it that array can not change.

The call stack I see:
CompatibleFieldSerializer.read->ObjectField.read->FieldSerializer.setGenerics->FieldSerializer.rebuildCachedFields->FieldSerializerGenericsUtil.buildGenericsScope->Class.getTypeParameters()

In my profile this call was taking 25% of the time.

**Comment by kodekat123** [comment]
Seeing a similar performance issue (twice as slow as Java ser-des) with generics as reported by @a701440 

Attaching test code to demonstrate this.

[TestKryo.java.txt](https://github.com/EsotericSoftware/kryo/files/298163/TestKryo.java.txt)

Not sure if this belongs in a new issue.
