### ISSUE TITLE
can simplify kryo3 serializer register

### ISSUE THREAD

**Issue by vongosling** [EsotericSoftware/kryo#275]
Often，I use the following code in my kryo codec：

    private static final ThreadLocal<Kryo> kryos = new ThreadLocal<Kryo>() {
        protected Kryo initialValue() {
            Kryo kryo = new Kryo();
            kryo.setRegistrationRequired(true);
            kryo.setReferences(false);
            kryo.register(Class.class);
            kryo.register(HashMap.class);
            kryo.register(Date.class);
            kryo.register(BigDecimal.class);
            kryo.register(Timestamp.class);
            kryo.register(ZoneInfo.class);
            kryo.register(ArrayList.class);
            kryo.register(Locale.class);
            kryo.register(BitSet.class);

            kryo.register(byte[].class);
            kryo.register(char[].class);
            kryo.register(short[].class);
            kryo.register(int[].class);
            kryo.register(long[].class);

too many register method，if i ignore some java type，may be exception occur

**Comment by NathanSweet** [comment]
This is how kryo works. Please use the mailing list for discussion, not the issue tracker.
