### ISSUE TITLE
Enum register error

### ISSUE THREAD

**Issue by vongosling** [EsotericSoftware/kryo#276]
env: jdk7
when i using kryo.register(Enum.class),I encountered the following excepton:
    Caused by: java.lang.IllegalArgumentException: The type must be an enum: class java.lang.Enum

through simple code analysis,i found the error occurs in the following code:
   //here  type.getEnumConstants() is null
    public EnumSerializer (Class<? extends Enum> type) {
            enumConstants = type.getEnumConstants();
            if (enumConstants == null) throw new IllegalArgumentException("The type must be an enum: " + type);
        }

**Comment by magro** [comment]
Already fixed.
