### ISSUE TITLE
CollectionSerializer NPE with Arrays.asList

### ISSUE THREAD

**Issue by brianfromoregon** [EsotericSoftware/kryo#277]
With kryo 3.0.0 and java7 or java8, this fails:

```
new Kryo().copy(Arrays.asList(new Object()));
```

java.lang.NullPointerException
    at java.util.Arrays$ArrayList.size(Arrays.java:2847)
    at java.util.AbstractList.add(AbstractList.java:108)
    at com.esotericsoftware.kryo.serializers.CollectionSerializer.copy(CollectionSerializer.java:131)
    at com.esotericsoftware.kryo.serializers.CollectionSerializer.copy(CollectionSerializer.java:22)
    at com.esotericsoftware.kryo.Kryo.copy(Kryo.java:887)

What is the suggested workaround, to use [ArraysAsListSerializer](https://github.com/magro/kryo-serializers/blob/master/src/main/java/de/javakaffee/kryoserializers/ArraysAsListSerializer.java)?

**Comment by prasanthj** [comment]
Any updates on this issue? I am hitting this issue as well in 3.0.3

**Comment by magro** [comment]
Sorry for missing this one. Yes, I'd suggest to use the mentioned ArraysAsListSerializer.

**Comment by magro** [comment]
@NathanSweet I guess this is still an issue for 5.0, right? Since that was reported oftentimes IIRC, maybe we should make an exception here and pull in ArraysAsListSerializer from kryo-serializers?

**Comment by NathanSweet** [comment]
We already have issue #151 to bring all the serializers over, as long as they are quarantined in their own package and not registered by default.

**Comment by NathanSweet** [comment]
No, Kryo doesn't support it by default. I think `Arrays.asList` can't be supported without being unsafe. Users either need to avoid it or use an usafe serializer.

**Comment by NathanSweet** [comment]
Actually I just pushed a safe Arrays.asList serializer.
