### ISSUE TITLE
KryoPool misuses generics

### ISSUE THREAD

**Issue by shevek** [EsotericSoftware/kryo#283]
If the queue provided to `KryoPool.Builder` is truly a specialized `Queue<Kryo>` not a generic `Queue<T>` with `Kryo` as the type-parameter, then the softreference code will cause a `ClassCastException` because it discards the type parameter in the constructor of `SoftReferenceQueue`.

Really, the generic type of the queue should be `Queue<Object>` which would free the KryoPool to put either `Kryo` or `SoftReference<Kryo>` in it as it sees fit.

The computational cost should be the same, as the `CHECKCAST` instruction is performed after a `get()`, but with the "correct" implementation of generics, the cast will have to be explicit with `KryoPoolQueueImpl`.

**Comment by magro** [comment]
Can you make an example that shows how to produce the `ClassCastException`? AFAICS this should work without throwing a CCE: `new KryoPool.Builder(factory).queue(new ConcurrentLinkedQueue<Kryo>()).softReferences().build()`.

Technically we could change the queue to Queue<Object>. The downside is that it breaks binary and source incompatibility, so I'd opt for doing this only for a good reason.

**Comment by shevek** [comment]
While I spotted the bug academically, I accept your challenge! Here you go:

```
public class KryoPoolTest {

    private static class KryoQueue extends AbstractQueue<Kryo> {

        private final LinkedList<Kryo> list = new LinkedList<>();

        @Override
        public Iterator<Kryo> iterator() {
            return list.iterator();
        }

        @Override
        public int size() {
            return list.size();
        }

        @Override
        public boolean offer(Kryo e) {
            return list.offer(e);
        }

        @Override
        public Kryo poll() {
            return list.poll();
        }

        @Override
        public Kryo peek() {
            return list.peek();
        }
    }

    @Test
    public void testCCE() throws Exception {
        KryoFactory factory = new KryoFactory() {
            @Override
            public Kryo create() {
                return new Kryo();
            }
        };
        KryoPool pool = new KryoPool.Builder(factory).queue(new KryoQueue()).softReferences().build();
        for (int i = 0; i < 5; i++) {
            pool.run(new KryoCallback<Object>() {
                @Override
                public Object execute(Kryo kryo) {
                    return null;
                }
            });
        }
    }
}
```

Results in
```
    java.lang.ClassCastException: java.lang.ref.SoftReference cannot be cast to com.esotericsoftware.kryo.Kryo
        at org.anarres.common.kryo.KryoPoolTest$KryoQueue.offer(KryoPoolTest.java:18)
        at com.esotericsoftware.kryo.pool.SoftReferenceQueue.offer(SoftReferenceQueue.java:38)
        at com.esotericsoftware.kryo.pool.SoftReferenceQueue.offer(SoftReferenceQueue.java:18)
        at com.esotericsoftware.kryo.pool.KryoPoolQueueImpl.release(KryoPoolQueueImpl.java:37)
        at com.esotericsoftware.kryo.pool.KryoPoolQueueImpl.run(KryoPoolQueueImpl.java:45)
        at org.anarres.common.kryo.KryoPoolTest.testCCE(KryoPoolTest.java:58)
```

**Comment by shevek** [comment]
Key points: I made a specialized Queue implementation which requires a Kryo object in JVM bytecode, rather than requiring a Kryo object in Java which is type-erased in the JVM. The type-erasure is hidden from the compiler by the unchecked cast in the constructor of `SoftReferenceQueue`.

```
	public SoftReferenceQueue (Queue<?> delegate) {
		this.delegate = (Queue<SoftReference<Kryo>>)delegate;
	}
```

Should just be Queue<Object> throughout this entire subsystem, since the user doesn't know whether we are going to put Kryo or SoftReference<Kryo> objects in it, and Object is the greatest lower bound of the two.

**Comment by NathanSweet** [comment]
Even if Builder `queue` took a `Queue` you'd have the same problem because your KryoQueue only accepts Kryo objects. The solution is `Queue<? super Object>`, which only allows a queue which stores objects (the common super class of Kryo and SoftReference).
