### ISSUE TITLE
Registering classes with same ID does not throw exception

### ISSUE THREAD

**Issue by szymex** [EsotericSoftware/kryo#288]
According to javadoc comment for Kryo.register(..) method, registering classes with same id should thrown exception, it does not happen. Below is a simple test:

```java
    public void testRegistrationWithSameId(){
        Kryo kryo = new Kryo();
        kryo.register(LinkedHashMap.class, 20);
        try {
            kryo.register(ArrayList.class, 20);
            fail("expected KryoException");
        } catch (KryoException ex){
            //expected
        }
    }
```

**Comment by rcoh** [comment]
+1 for this issue.

**Comment by NathanSweet** [comment]
The exception is only throw when `DEBUG` logging is on. @romix any idea why?

**Comment by romix** [comment]
It doesn't look like we thrown any exception at all currently. The only thing I see is this:
```
https://github.com/EsotericSoftware/kryo/blob/master/src/com/esotericsoftware/kryo/Kryo.java#L445-L448
```

But we only issue a debug message here. No exceptions are thrown.

**Comment by rcoh** [comment]
I ended up just adding a wrapper around Kryo to check if the id had been registered first. The code should probably throw an exception, but I suspect people are currently relying on the broken behavior.

**Comment by magro** [comment]
@romix @NathanSweet Shall we commit on the new behaviour, or change it back to the previous one?

FYI, this change was introduced with commit 7c8bc3b329da6d2e0b5f2e325ad59325e70547c8:

> Changed registration of a different class with the same ID to a debug message.
> 
> The use case is in KryoNet's RMI, where we want to send the implementation of an object on the server as if it were the interface. This means the interface and the implementation use the same class ID.

**Comment by NathanSweet** [comment]
Ah right. We should not throw an exception and the javadocs should not say one is thrown.
