### ISSUE TITLE
Question: How to ignore private fields.

### ISSUE THREAD

**Issue by chakrit** [EsotericSoftware/kryo#289]
How do I make `Kryo` only checks and reads/writes public fields and not private ones?
Is this possible without having to specify a custom serializer?

My model class sometimes contains cached references to some complex object (which shouldn't be serialized). Those are stored in private fields.

I'm using `CompatibleFieldSerializer.class` if that matters.

**Comment by chakrit** [comment]
In the meantime I worked around this by tagging the field with `@FieldSerializer.Optional("ignored")` and never sets the value. But I think there should be a way to configure this at a higher level than at each individual attributes.

**Comment by NathanSweet** [comment]
You can use FieldSerializer#setFieldsAsAccessible(false). Extend Kryo and
override newDefaultSerializer to return a new FieldSerializer configured as
you like.

**Comment by chakrit** [comment]
@NathanSweet Hmm, I took a look at the code. Seems I can override the list of cached fields. I'll try that out thanks!
