### ISSUE TITLE
Is there a simple way to prevent serialization of an object?

### ISSUE THREAD

**Issue by spyhunter99** [EsotericSoftware/kryo#293]
I have a class object with a Calendar object in it. Serializing this as a long (time since epoch) is much more efficient than serializing the entire object. 4 bytes instead of over 60 bytes!

Other serializers, such as Jackson's ObjectMapper has a nifty annotation "@JsonIgnore" which obviously ignores that field when serializing. Does Kryo have such a feature?

**Comment by magro** [comment]
Just mark the field as transient.

**Comment by borjapenman** [comment]
There is an @Optional annotation as well

**Comment by krishna81m** [comment]
How do you programmatically ignore specific classes when they are from another dependency/library?

**Comment by isaki** [comment]
You can always register your own serializer for the class that does what you need. Then, you can use different Kryo instances for disk vs. network and have different serializers for different use cases.
