### ISSUE TITLE
kryo need more typesafe

### ISSUE THREAD

**Issue by hepin1989** [EsotericSoftware/kryo#294]
there are to many cast in the kryo ,and infact the current dependency objenesis is typesafe,but we put the jar in lib.which is an old one.
the new is 

```
public interface ObjectInstantiator<T> {

   /**
    * Returns a new instance of an object. The returned object's class is defined by the
    * implementation.
    * 
    * @return A new instance of an object.
    */
   T newInstance();

}
```

so I think we may need to rework at the kryo implement ,and more types

**Comment by hepin1989** [comment]
like this
https://github.com/EsotericSoftware/kryo/pull/295

**Comment by magro** [comment]
Is this still relevant or can we close this issue?
