### ISSUE TITLE
Buffering ByteArrayOutputStream is Pointless

### ISSUE THREAD

**Issue by MartinKersten** [EsotericSoftware/kryo#298]
Kryo 3 always uses an extra buffer to buffer the output stream. Using a ByteArrayOutputStream it feels pointless and also requires additional space and time. Since the overhead appears to be very limited, it is not that kind of an issue but having thousands of messages being serialized per second it feels unnecessary komplex.

**Comment by NathanSweet** [comment]
Output can grow it's byte[] buffer just like ByteArrayOutputStream (with
additional options like a max size) and you can access the byte[] directly.
I suggest you use Output instead of ByteArrayOutputStream. If you really
must use ByteArrayOutputStream, you would need to extend Output to write
directly to the stream (similar to ByteBufferOutput), but this isn't
suggested since it's a lot of code.

**Comment by MartinKersten** [comment]
Is there any plan to support it directly? I often write to memory / byte array so supporting it directly and making buffering optional would be a great to have feature for me.

**Comment by romix** [comment]
How about using UnsafeMemoryOutput? It allows you to provide a memory address (and length) in the constructor?

**Comment by MartinKersten** [comment]
I would like to stick to the Java world. A byte buffer may be moving in heap so I might run into trouble here. Also this code will not be subject of native. Others yes but not message writing and such. But is an option which is nice to have. I will remember that.

Would it be hard to make buffering optional? Maybe even using a null buffer value as marker?

**Comment by NathanSweet** [comment]
On Fri, Apr 3, 2015 at 5:13 PM, Martin Kersten <notifications@github.com>
wrote:

> Is there any plan to support it directly? I often write to memory / byte
> array so supporting it directly and making buffering optional would be a
> great to have feature for me.
>
Again, use Output to write directly to a byte[] without an intermediary
buffer. You don't need ByteArrayOutputStream.

-​Nate​

**Comment by MartinKersten** [comment]
Can I replace the byte [] because I build a larger stream of smaller parts. If I would use another byte buffer its again an unnecessary buffer. I have another idea about a solution I would like to use kryo with. It requires storing about 100000 objects in a way that they are all independently deserializeable. Therefore I would love to write to that byte stream directly (its a bit different to ByteArrayOutputStream).

**Comment by NathanSweet** [comment]
Output lets you write to a byte[] directly. Alternatively, you can extend Output like ByteBufferOutput does. Also, it appears you are optimizing prematurely since you don't actually have a problem even if you chose to use Output to buffer to a stream.

**Comment by MartinKersten** [comment]
> optimizing prematurely
You are correct and that is why I wrote it feels like unnecessary and I do not understand why buffering is even a design goal. If I need buffering would I not offer a BufferedOutputStream instead or is this implementation flawed or undesired?

**Comment by NathanSweet** [comment]
Output often writes multiple bytes at once: float, int, long, etc and especially strings. A method call per byte to write to a stream is not ideal.

If you want to write to a byte[] or buffer output to a stream, doing it directly in Output is better. Those are the most common use cases. If you wanted to write to a stream without buffering (why would not buffering be a requirement?), then is writing byte by byte to the stream better than buffering and writing many bytes at once? Most likely buffering will be faster, though Java microbenchmarks have many variables. In the unlikely chance that writing directly to a stream is actually faster, the buffering overhead is very likely to be negligible and yet is still better in the most common use cases.

**Comment by MartinKersten** [comment]
Ok. I just do not like creating many unneeded objects. I also checked the Unsafe class again and will see what I can do with it. I will let it be this way until I see a time worthy problem in a profiler run. I also understand why you use the buffer after all. It actually even saves a lots of method calls for accessing streams. So you are right. Thanks for taking care!
