### ISSUE TITLE
in kryo i am using Compress Serialization(Deflated Serializer) ,It is not getting deserialized properly , 

### ISSUE THREAD

**Issue by gzagarwal** [EsotericSoftware/kryo#300]
In kryo i am using Compress Serialization(Deflated Serializer) ,It is not getting deserialized properly , But if i change the register proces to normal kryo serialization, it works properly for us.Could any help what is the issue with kryo compress deserialization process.

public static void register(Class classes) {
        kryo.register(Order.class,new DeflateSerializer(kryo.getDefaultSerializer(Order.class)));
}

public static byte[] writes(Object obj){
        //ByteArrayOutputStream os= new ByteArrayOutputStream();
        Output output = new Output(100,Integer.MAX_VALUE);
        kryo.writeClassAndObject(output, obj);
        byte[] b= output.toBytes();
        output.close();
        output.flush();
        int i =b.length;
        System.out.println("compressed object   "+i);
        return b;
    }

    public static Order reads(byte[] bytes){
        //ByteArrayInputStream stream = new ByteArrayInputStream(bytes);
        Input inputs = new Input(bytes);
        Order obj =(Order) kryo.readClassAndObject(inputs);
        inputs.close();
        return obj;
    }

public class Order {

    @SuppressWarnings("unused")
    private int orderID;

    /**
     * @return the orderID
     */
    public int getOrderID() {
        return orderID;
    }

    /**
     * @return the quantity
     */
    public int getQuantity() {
        return quantity;
    }

    /**
     * @return the product
     */
    public List<String> getProduct() {
        return product;
    }

    /**
     * @return the products
     */
    public Map<String, String> getProducts() {
        return products;
    }
    @SuppressWarnings("unused")
    private int quantity;
    private List<String> product;
    private Map<String,String> products;

    public Order() {
        // TODO Auto-generated constructor stub
    }
    public Order(int orderID, int quantity, List<String> product, Map<String, String> products) {
        this.orderID = orderID;
        this.quantity = quantity;
        this.product = product;
        this.products = products;
    }

    @Override
    public boolean equals(Object obj) {
        // TODO Auto-generated method stub
        return true;
    }

    @Override
    public int hashCode() {
        // TODO Auto-generated method stub
        return 5;
    }

public class TestKryo {

    @Test
    public void testKryo() throws FileNotFoundException{

        List<String> list = new ArrayList<String>();
        for(int i =0;i<10000;i++){
        list.add("i"+i);
        }
        Map<String,String> map = new HashMap<String,String>();
        for(int i =0;i<10000;i++){
            map.put(new String("i"+i),new String("i"+i));
            }

        Order order = new Order(1, 1,list,map);
KryoSerializer.register(Order.class);
        byte[] compresed = KryoSerializer.writes(order);
        Order ordr =(Order)KryoSerializer.reads(compresed);
        System.out.println(ordr.getOrderID());
}

**Comment by NathanSweet** [comment]
https://github.com/libgdx/libgdx/wiki/Getting-help
Read with emphasis on the *executable* part of executable example code.

http://pastebin.com/8jniuT3u
Code works fine.

**Comment by gzagarwal** [comment]
@Nathan do you mean code is working fine this is getting deserialized properly.

**Comment by gzagarwal** [comment]
Hi Nathan 

I tried your code in kryo-2.21.jar , Still getting the null object of Order .and got null Pointer exception .Please elp and let us know is there any change in jar required.

**Comment by magro** [comment]
Is this still relevant?

**Comment by magro** [comment]
Please reopen if still relevant.
