### ISSUE TITLE
how to use kryo serialize Tuple message ?

### ISSUE THREAD

**Issue by bwzhang2011** [EsotericSoftware/kryo#301]
@magro or someone else, I encounter some problem when serializing Tuple message. for example, please take a look at reactor Tuple design: https://github.com/reactor/reactor/blob/master/reactor-core/src/main/java/reactor/fn/tuple/Tuple.java.  As Tuple componds a lot of class from Tuple1 to TupleN to make it chain for stream data organization. it's very helpful to cope with stream data without concrete data like Person,Address class and also with its class. so hence, how to serialize such class, as Kryo must assign the default constructor and I don't want to change the original class to make every one the constructor and as you know some has a lot of constructor parameters. so please leave me some suggest for how to solve that. thanks for view.

**Comment by bwzhang2011** [comment]
@magro, would you mind sparing some time to take a look at ? please give me some advice on how to solve that ?

**Comment by bwzhang2011** [comment]
Can everybody take interest to look at such issue ?

**Comment by romix** [comment]
Why can't you write your own custom serializer for Tuple and register it with your Kryo instance?

And regarding the default constructor issues, please read the docs about configuring the instantiation strategy.

**Comment by bwzhang2011** [comment]
@romix, thanks for view and advice. for I don't quite understand or sure about the use cases for instantiation strategy of kryo. so please help me to point out the exact way. from the document, I just add the kryo.setInstantiatorStrategy(new DefaultInstantiatorStrategy(new StdInstantiatorStrategy()))  for testing. the exception gone without default empty constructor needed but I still could not deserialize that.

**Comment by bwzhang2011** [comment]
@romix, my test class simplified like this:

SimpleKryoSerializer<Tuple> tupleSerializer = SimpleKryoSerializer.make(Tuple.class);
		
		Tuple data = Tuple.of(new Object[] {"aa"});
		
		byte[] array = tupleSerializer.write(data);
		
		Tuple _data = tupleSerializer.read(array);
		
		System.out.println("" + Base64Helper.encodeToString(array));
		
		System.out.println("" + CommonHelper.safe2String(_data.toArray()));

 for the above one, the tuple data is serialized into byte[] and encoded in Base64 way for printing, then call the read method for deserializing, but I could not get the tuple data for it returnt empty.so please help me solve that

**Comment by romix** [comment]
Take a look at the collection serializer:
https://github.com/EsotericSoftware/kryo/blob/master/src/com/esotericsoftware/kryo/serializers/CollectionSerializer.java

You can essentially create a very similar serializer. It would be registered for a Tuple class and thus automatically handle all its subclasses.

When it is serializing, it would write the number of tuple elements first and then iterate over tuple elements and write them one-by-one.

When it would deserialize, it would first read the number of tuple elements. Then it would read the corresponding number of serialized elements. And then, since it knows the number of elements, it would invoke the appropriate constructor or invoke the appropriate Tuple.of method with the deserialized elements as arguments. This would create the object that you need.

Does it answer your question?

**Comment by jbrisbin** [comment]
@bwzhang2011 It sounds like @romix's suggestion to encode the number of elements in the first 4 bytes is the right way to achieve what you're looking for. You would read the elements into an array of the correct size, then call `Tuple.of`.

**Comment by bwzhang2011** [comment]
@jbrisbin and @romix, as your suggestion, I write the class like follows:

public class TupleSerializer extends Serializer<Tuple> {

	@Override
	public Tuple read(Kryo kryo, Input input, Class<Tuple> tuplecls) {
		int length = input.readVarInt(true);

		Object[] list = new Object[length];

		for (int i = 0; i < length; i++) {
			list[i] = kryo.readClassAndObject(input);
		}

		return Tuple.of(list);
	}

	@Override
	public void write(Kryo kryo, Output output, Tuple tuple) {
		int length = tuple.size();
		output.writeVarInt(length, true);

		Object[] array = tuple.toArray();

		for (Object element : array) {
			kryo.writeClassAndObject(output, element);
		}
	}

}

when I register kryo with Tuple.class matched with TupleSerializer. but it doesn't work, hope you could point out my mistake.

**Comment by romix** [comment]
You seem to go in the right direction. The serializer looks quite OK.

Can you please provide a full JUnit test? I'd like to see how you register your serializer with Kryo and what you try to serialize/deserialize.

**Comment by bwzhang2011** [comment]
@romix, would you mind leaving me more message for kryo register, when I run debug mode. I could not see it step into the TupleSerializer write or read method for  serialize/deserialize. I just set

Kryo kryo = new Kryo();
kryo.register(Tuple.class, new TupleSerializer());

I think it was wrong that I could not register the concrete class (just the subclass of Tuple).

**Comment by bwzhang2011** [comment]
@romix, how could I register the subclass with kryo for Tuple class. for simple test cases for Tuple.of it would the TupleN class if you register that the Tuple serializer works. but if turned to other class like Tuple1 to Tuple8 it was wrong that could not match with the class.

**Comment by bwzhang2011** [comment]
@romix, I write some class with package scan to register all the Tuple class arranged from Tuple1 to TupleN class which registered with TupleSerializer. and my class runs ok, but hope more helpful method could be provided.

**Comment by romix** [comment]
You should use the `addDefaultSerializer(Tuple.class, new TupleSerializer());`

This is supposed to work for any class which can be assigned to Tuple, i.e. for all its subclasses.

**Comment by bwzhang2011** [comment]
@romix, thanks for your suggestion. I did replace with addDefaultSerializer method and it worked as expected. thanks a lot.
