### ISSUE TITLE
explicitly register class in kryo

### ISSUE THREAD

**Issue by Amitkumar13** [EsotericSoftware/kryo#303]
I have a below issue, so my friend suggest me to register the class explicitly in kryo.

Is it the issue of not register the class in kryo ?

"past 2 days, I’ve been running the same Hive queries. ~80% of the time they fail with this KyroException, thrown from the Hive code. 20% of the time the same job, runs successfully. No code differences between runs.

Yesterday, this same Hive Query failed with the KyroException all afternoon. Then around 8:00 PM at night it ran fine. This morning (4/23), I ran the same code again, processing 2 rows of data, and the job failed."

Below are the logs :

2015-04-23 10:35:57,893 INFO [main] org.apache.hadoop.hive.ql.exec.Utilities: Deserializing MapWork via kryo
2015-04-23 10:35:58,290 ERROR [main] org.apache.hadoop.hive.ql.exec.Utilities: Failed to load plan: hdfs://nameservice1/tmp/hive-dks0344135/hive_2015-04-23_10-34-25_211_2333815521043174815-4/-mr-10016/b7fe67d9-5471-4e66-bdf4-6280f840f5ec/map.xml
org.apache.hive.com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: -848874534
Serialization trace:
startTimes (org.apache.hadoop.hive.ql.log.PerfLogger)
perfLogger (org.apache.hadoop.hive.ql.exec.MapJoinOperator)
parentOperators (org.apache.hadoop.hive.ql.exec.SelectOperator)
parentOperators (org.apache.hadoop.hive.ql.exec.MapJoinOperator)
parentOperators (org.apache.hadoop.hive.ql.exec.FilterOperator)
parentOperators (org.apache.hadoop.hive.ql.exec.SelectOperator)
parentOperators (org.apache.hadoop.hive.ql.exec.UnionOperator)
childOperators (org.apache.hadoop.hive.ql.exec.TableScanOperator)
aliasToWork (org.apache.hadoop.hive.ql.plan.MapWork)
at org.apache.hive.com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:119)

Please help me on this,

**Comment by romix** [comment]
It is always a good idea to register your classes with Kryo, especially if you serialize and deserialize using different Kryo instances (and may be on different machines). Doing a registration ensures the deterministic results, because all instances of Kryo would register the same classes in the same order and assign the same integer IDs to them.

**Comment by Amitkumar13** [comment]
could you please let me know how to check kryo version ?

We are just running HQL (Hive) queries, not the java code.

I have a below issue, so my friends suggest to resister the class explicitly.

"past 2 days, I’ve been running the same Hive queries. ~80% of the
time they fail with this KyroException, thrown from the Hive code. 20%
of the time the same job, runs successfully. No code differences
between runs.

Yesterday, this same Hive Query failed with the KyroException all
afternoon. Then around 8:00 PM at night it ran fine. This morning
(4/23), I ran the same code again, processing 2 rows of data, and the
job failed."

Below are the logs :

2015-04-23 10:35:57,893 INFO [main]
org.apache.hadoop.hive.ql.exec.Utilities: Deserializing MapWork via
kryo
2015-04-23 10:35:58,290 ERROR [main]
org.apache.hadoop.hive.ql.exec.Utilities: Failed to load plan:
hdfs://nameservice1/tmp/hive-dks0344135/hive_2015-04-23_10-34-25_211_2333815521043174815-4/-mr-10016/b7fe67d9-5471-4e66-bdf4-6280f840f5ec/map.xml
org.apache.hive.com.esotericsoftware.kryo.KryoException: Encountered
unregistered class ID: -848874534
Serialization trace:
startTimes (org.apache.hadoop.hive.ql.log.PerfLogger)
perfLogger (org.apache.hadoop.hive.ql.exec.MapJoinOperator)
parentOperators (org.apache.hadoop.hive.ql.exec.SelectOperator)
parentOperators (org.apache.hadoop.hive.ql.exec.MapJoinOperator)
parentOperators (org.apache.hadoop.hive.ql.exec.FilterOperator)
parentOperators (org.apache.hadoop.hive.ql.exec.SelectOperator)
parentOperators (org.apache.hadoop.hive.ql.exec.UnionOperator)
childOperators (org.apache.hadoop.hive.ql.exec.TableScanOperator)
aliasToWork (org.apache.hadoop.hive.ql.plan.MapWork)
at org.apache.hive.com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:119)

**Comment by NathanSweet** [comment]
This is an issue tracker. Do not post questions here!
