### ISSUE TITLE
com.esotericsoftware.kryo.KryoException: Buffer underflow

### ISSUE THREAD

**Issue by kutoman** [EsotericSoftware/kryo#308]
Hi, I'm trying kryo the first time but I couldn't get it working in my first test use case. I'm getting the mentioned exception when calling `readClassAndObject`:

```
public class TestKryo {

    val sut = Kryo()
    val out = Output(1024)
    val inp = Input(1024)

    Test public fun simple() {

        val obj = 5

        sut.writeClassAndObject(out, obj)
        out.close()

        sut.readClassAndObject(inp)
        inp.close()
    }
```

What am I doing wrong? 
Note: kryo version is 3.0.1

**Comment by NathanSweet** [comment]
Turn on trace logging. But, please use the mailing list for support. This is an issue tracker.

**Comment by kutoman** [comment]
sorry I thought it's an issue concerning kyro:
I recently got it fixed as I replaced 
``sut.readClassAndObject(inp)`` by
``sut.readClassAndObject(Input(out.toBytes()))``
