### ISSUE TITLE
KryoException: Encountered unregistered class ID: 380 

### ISSUE THREAD

**Issue by Amitkumar13** [EsotericSoftware/kryo#309]
Hi Guys,

While executing a script containing hive queries through Control-M, we are getting following error:
Error: java.lang.RuntimeException: org.apache.hive.com/esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 380 

We tried setting ‘hive.plan.serialization.format’ property to ‘javaXML’ but it did not work. Also checked kryo version, it is 2.22.

Cluster information:
CDH-5.2.1
Hadoop-2.5.0
Hive-0.13
Java 1.7

Please suggest any pointers related to above issue.

**Comment by NathanSweet** [comment]
See #307

**Comment by Amitkumar13** [comment]
Thank you Nathan, its really very helpful for me,
Is this issue on coding, are we need to check the code,

i using the some pointers to solve the issue but still facing the same error,

<property>
<name>hive.plan.serialization.format</name>
<value>javaXML</value>
</property>

But That setting caused instant and consistent failure in Hive and was removed within 10 minutes of implementation.

what else i can do, please suggest,

**Comment by Amitkumar13** [comment]
Nathan,

how can i  turn on trace logging ?

is it  kryo-trace =  true ?
