### ISSUE TITLE
How to force Kryo to use shallow copying for specific fields?

### ISSUE THREAD

**Issue by niksabaldun** [EsotericSoftware/kryo#311]
I am copying a question from StackOverflow, which didn' get much attention:

I am using Kryo for creating deep copies of objects (using FieldSerializer). Consider a following simplified example:

    public class Parent {
        private List<Child> children;
        // Followed by other fields, getters and setters
    }

    public class Child {
        private Parent parent;
        // Followed by other fields, getters and setters
    }

When I use Kryo to make a deep copy of parent:

    Parent newParent = kryo.copy(parent);

Kryo understands that parent field in Child object refers to actual object being copied, so it avoids circular references and everything works fine.

However, sometimes I need to create a deep copy of child object, independent of parent. In that case, I don't want to make a deep copy of parent field, I would like a shallow copy instead. Is there a generic way to achieve this, without having to create a specific FieldSerializer instance for each parent/child combination (and I have many in my project)?

**Comment by NathanSweet** [comment]
How would Kryo know an object is a "parent"?

Maybe you can override Kryo#copy and `return copyShallow(object)` when you want a shallow copy.

**Comment by niksabaldun** [comment]
I know it can't know, I am asking how I can tell it. :-) I thought there might be a way to mark a field to always be shallow-copied, with annotation perhaps.

So, my options are to override copy method and devise a way to recognize parent fields, or use a different serializer for each class?

**Comment by klaus7** [comment]
You could just implement `KryoCopyable` and do something like this:
```java
	@Override
	public Object copy(Kryo kryo) {
		if (shallow) {
			return this;
		} else {
			return kryo.getSerializer(getClass()).copy(kryo, this);
		}
	}
```
