### ISSUE TITLE
clirr-maven-plugin failure when building Kryo using Java8

### ISSUE THREAD

**Issue by romix** [EsotericSoftware/kryo#315]
The automated build system reports errors building Kryo using Java8:
https://jenkins.inoio.de/job/kryo%20(oracle-jdk-8)/4/console

It happens since the 24th of April. 

@magro Could you have a look at it? I guess it should be something totally stupid.

**Comment by romix** [comment]
See #314 for some related information.

**Comment by isakidbn** [comment]
I was able to build with Java 8 by first building BCEL 6.0-SNAPSHOT with the install task and forcing the dependency in Kryo's pom-main.xml.

Here is my Kryo POM change:

```diff
diff --git a/pom-main.xml b/pom-main.xml
index 11d2266..f153706 100644
--- a/pom-main.xml
+++ b/pom-main.xml
@@ -89,6 +89,13 @@
                                                </difference>
                                        </ignored>
                                </configuration>
+                <dependencies>
+                    <dependency>
+                        <groupId>org.apache.bcel</groupId>
+                        <artifactId>bcel</artifactId>
+                        <version>6.0-SNAPSHOT</version>
+                    </dependency>
+                </dependencies>
                        </plugin>
                </plugins>
        </build>
```

I am not sure why the 6.0 version doesn't have a release build.

**Comment by magro** [comment]
@isakidbn Thanks for the hint, this is fixed now in master: https://jenkins.inoio.de/job/kryo/ is green again.

**Comment by isakidbn** [comment]
Happy to be of help.
