### ISSUE TITLE
StringSerializer is slower than Java serialization for long strings

### ISSUE THREAD

**Issue by marianogonzalez** [EsotericSoftware/kryo#316]
The StringSerializer delegates into Output.writeString() which for non ascii characters ends up in a for loop which writes one character at a time. This is extremelly slow for long values (1KB an above) and ends up being slower than Java serialization

**Comment by marianogonzalez** [comment]
the method in which it gets slow com.esotericsoftware.kryo.io.Output#writeString_slow

**Comment by romix** [comment]
This could be relevant for this discussion:

http://psy-lob-saw.blogspot.com/2012/12/encode-utf-8-string-to-bytebuffer-faster.html

**Comment by magro** [comment]
@NathanSweet consider for 5.0?

**Comment by NathanSweet** [comment]
Agreed, we should look at it for Kryo 5.
