### ISSUE TITLE
Deserialization seems not to work for large strings

### ISSUE THREAD

**Issue by toni-l-d** [EsotericSoftware/kryo#322]
Hi,

Deserialization seems to have a problem with strings that are somewhat large (I'm getting the error with XML strings under 5.000 bytes). I'm using version 3.0.1. this simple main method reproduces the test:

```
public static void main(String[] args) {		
                Output out = new Output(new ByteArrayOutputStream());
                System.out.println("String size: " + MY_XML_STRING.getBytes().length + " bytes"); // Prints approx. 5000 bytes            
		out.writeString(MY_XML_STRING);
		out.close();
		
		Input in = new Input(out.getBuffer());		
		String result = in.readString(); // Throws the exception
		in.close();

		System.out.println("Read object: " + result);//		
}
```

The exception is as follows:

Exception in thread "main" com.esotericsoftware.kryo.KryoException: Buffer underflow.
	at com.esotericsoftware.kryo.io.Input.require(Input.java:199)
	at com.esotericsoftware.kryo.io.Input.readAscii_slow(Input.java:616)
	at com.esotericsoftware.kryo.io.Input.readAscii(Input.java:594)
	at com.esotericsoftware.kryo.io.Input.readString(Input.java:472)

I'm getting problems with these rather large strings even if nested within an object (using Kryo for serialization and deserialization instead of Output/Input directly), in which case I get the following:

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 7, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.esotericsoftware.kryo.util.MapReferenceResolver.getReadObject(MapReferenceResolver.java:60)
	at com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:831)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:681)

This happens even if I set the JavaSerializer, the ExternalizableSerializer and a custom serializer.

Note that all cases work fine when using smaller strings. Note as well that it's not a problem with the large string's format itself, as if I cut it short (using the same XML tags) it works fine as well. Seems to be an internal buffer size or something related.

Thanks for your attention

**Comment by NathanSweet** [comment]
Can you show an executable example?

**Comment by toni-l-d** [comment]
Hi,

I have, check the previous comment with the main method (it didn't get formatted properly but all the code lines are there. Just insert a large enough XML string in place of the variable MY_XML_STRING, eventually you'll likely get the same exception (com.esoteric.software.kryo.KryoException: Buffer underflow), it should be quite easy to run.

**Comment by NathanSweet** [comment]
If it can't be copy/pasted and run, it isn't executable. :)

I don't see a bug here, just a mistake using the API:

```
	public static void main (String[] args) {
		String MY_XML_STRING = "";
		for (int i = 0; i < 10000; i++)
			MY_XML_STRING += i;
		ByteArrayOutputStream outStream = new ByteArrayOutputStream();
		Output out = new Output(outStream, 1024);
		System.out.println("String size: " + MY_XML_STRING.getBytes().length + " bytes"); // Prints approx. 5000 bytes
		out.writeString(MY_XML_STRING);
		out.close();

		Input in = new Input(outStream.toByteArray());
		String result = in.readString();
		in.close();

		System.out.println("Read object: " + result);//

		// Better:

		out = new Output(1024, -1);
		System.out.println("String size: " + MY_XML_STRING.getBytes().length + " bytes"); // Prints approx. 5000 bytes
		out.writeString(MY_XML_STRING);
		out.close();

		in = new Input(out.getBuffer(), 0, out.position());
		result = in.readString();
		in.close();

		System.out.println("Read object: " + result);//
	}
```

**Comment by toni-l-d** [comment]
It does work when setting the Output's max buffer size (unlimited in the example above) - I would suggest documenting this in some 'Issues' or 'FAQ' session, as I had to check the code for the class itself in order to find that 'A buffer size of 4096 is used'.

Thanks for your attention and for the prompt answer.

**Comment by NathanSweet** [comment]
Your problem wasn't necessarily the buffer size, but `Input in = new Input(out.getBuffer());`. This uses the Output's internal buffer, but you had set up the Output to write to a stream. You either want to use the data from the stream, or just let the Output buffer resize instead of doing an extra copy to the stream and a second extra copy to get the byte[] from the stream.
