### ISSUE TITLE
Class cannot be created (missing no-arg constructor) on a static member class with a default constructor

### ISSUE THREAD

**Issue by spyhunter99** [EsotericSoftware/kryo#325]
https://github.com/EsotericSoftware/kryo/blob/master/src/com/esotericsoftware/kryo/Kryo.java#L1265

Hi, I have a xjc generated class with a nested public static member class. Kryo is barfing on converting byte[] to back into an object with the subject's error message.

In this case, there is a public constructor, it is static and it is a member class. From my naive look at the logic in the above link, it looks this may is edge case that isn't handled.

**Comment by NathanSweet** [comment]
sscce?

**Comment by spyhunter99** [comment]
sscce? i don't understand. why this was closed. Are you asking me for a source example?

**Comment by NathanSweet** [comment]
I was, but on second thought this has been discussed before, see here:
https://groups.google.com/forum/m/#!topic/kryo-users/jgAU18bLyN0
