### ISSUE TITLE
Exception serialization on java > 7

### ISSUE THREAD

**Issue by ilfenomeno1** [EsotericSoftware/kryo#329]
With few code rows I'm showing you how the serialization is going to break:

		Kryo kryo = new Kryo();
		Exception e = new NullPointerException();
		
		ByteArrayOutputStream serializedOutputStream = new ByteArrayOutputStream();
		Output output = new Output(serializedOutputStream);
		kryo.writeClassAndObject(output, e);
		output.flush();
		output.close();
		
		// Fine, the object is serialized
	
		ByteArrayInputStream deserializedIntputStream = new ByteArrayInputStream(serializedOutputStream.toByteArray());
		Input deserializedInput = new Input(deserializedIntputStream);
		
		Object deserializedObject= kryo.readClassAndObject(deserializedInput);
		deserializedInput.close();
		
		// Now deserializedObject should be a 'clone' of e.
		// I'm going to serialize that last object
				
		serializedOutputStream = new ByteArrayOutputStream();
		output = new Output(serializedOutputStream);
		kryo.writeClassAndObject(output, deserializedObject); // <---- at this line the system crash
		output.flush();

This is due to a possible issue on CollectionSerializer, while working with immutable types.

**Comment by NathanSweet** [comment]
FieldSerializer is used on Exception and probably tries to serializer
private fields that it shouldn't. You need to consider how FieldSerializer
will serialize each type in your object graph.

**Comment by ilfenomeno1** [comment]
Take in care that in this example I have not used any private Object.
All the Object involved on the serialization are part of the Oracle JDK 7.
My suggestion is to change you default serializers for that case. For instance, for solve the issue I have changed the default serializer for immutable collection with the one provided by magro/kryo-serializers

**Comment by NathanSweet** [comment]
It doesn't matter that the objects are in the JDK, you are still serializing them using FieldSerializer to access private fields. You still need to consider every class and make sure it serializes correctly.

**Comment by ilfenomeno1** [comment]
Thanks a lot for your answer.
FieldSerializer have no trouble on serializing private field, so I really don't understand what you want to highlight me.

In my mind, when I use a library like this wonderful one, by default it should work with all the base object. Only in that way I can say that a library works.
In a next step I can make any kind of optimization, but if in some usage test I found a serialization issue on base Exception Java object, I think there is something strange.
