### ISSUE TITLE
Incompatibility Kryo 3.0.0 / Kryo 3.0.2

### ISSUE THREAD

**Issue by andreaszielke** [EsotericSoftware/kryo#330]
Hi,

to stay current I've just exchanged 3.0.0 for 3.0.2.

I'm now getting

    07-23 13:15:28.290  12736-12736/x.y.z E/AndroidRuntime﹕ FATAL EXCEPTION: main
        Process: x.y.z.A, PID: 12736
        com.esotericsoftware.kryo.KryoException: Class cannot be created (missing no-arg constructor): x.y.z.B

This goes away when using 3.0.0 again. I can reproduce this by exchanging versions and doing a clean build.

Kryo is configured like so:

            final Kryo kryo = new Kryo();
            kryo.setAsmEnabled(true);
            kryo.register(EnumMap.class, new EnumMapSerializer());
            final FieldSerializer<Blah> blahSerializer = new FieldSerializer<>(kryo, Blah.class);
            blahSerializer.setUseAsm(true); // no sun on android
            kryo.register(Blah.class, blahSerializer);
            return kryo;

Due to time restrictions, I've to revert to 3.0.0 for now.

All the best
Andreas

**Comment by andreaszielke** [comment]
As a quickfix I tried 
    
    kryo.setInstantiatorStrategy(new StdInstantiatorStrategy());

but I'm now getting NPEs during object creation.
I guess something basic/default behaviour has been changed.

**Comment by NathanSweet** [comment]
What is the unobfuscated class? Is it class missing a no-arg constructor?
Kryo doesn't construct objects without calling a constructor by default any
longer, I forget when that changed exactly.

**Comment by andreaszielke** [comment]
Yes, it is missing a no-arg constructor. But as the changelog indicated backward compatibility from 3.0.2 to 3.0.1 and onward to 3.0.0, I assumed that such a thing would not happen (at least not in a minor release).

I'm perfactly happy with 3.0.0 (THANK's A LOT for providing it :-) ), but I thought that it should at least be documented as changed behaviour.

Is there a way to revert to 3.0.0 behaviour by configuration? I'd hate to have to implement no-args cursors all over the place, whose sole purpose is to make the serialization engine happy...

**Comment by magro** [comment]
We're checking/reporting source and binary compatibility, not runtime compatibility. You're right saying that this have been highlighted in the release notes, perhaps it's a good idea to somehow "flag" the related commit message (e.g. start with BREAKING) in the future. 

The change was introduced by commit bfc02be, according to that you should use `kryo.setInstantiatorStrategy(new DefaultInstantiatorStrategy(new StdInstantiatorStrategy()));` to get the former behavior. Does this solve your issue?

**Comment by andreaszielke** [comment]
Sorry, that was my misunderstanding; maybe "storage format" compatibility would be more expressive.

Thank you very much for the line of code, that seems to re-establish the former behaviour. I'll continue with 3.0.2 to see whether I run into any other obsatcles.

All the best!
