### ISSUE TITLE
how kryo serialize field object with enum class within some object

### ISSUE THREAD

**Issue by bwzhang2011** [EsotericSoftware/kryo#333]
Hi, I encountered some problem when serialize field object with enum class within my bean between different jvm. here comes my bean like this:
1. bean with enum class:
public class MonitorCtrlBean implements java.io.Serializable {
	private static final long serialVersionUID = 9082640203431233882L;

	private String instanceKey;

	private MonitorResourceType monitorResType;

	private MonitorOperType monitorOperType;

	public MonitorCtrlBean() {
		super();
	}

	public MonitorCtrlBean(String instanceKey, MonitorResourceType monitorResType,
			MonitorOperType monitorOperType) {
		this.instanceKey = instanceKey;
		this.monitorResType = monitorResType;
		this.monitorOperType = monitorOperType;
	}

	public String getInstanceKey() {
		return instanceKey;
	}

	public void setInstanceKey(String instanceKey) {
		this.instanceKey = instanceKey;
	}

	public MonitorResourceType getMonitorResType() {
		return monitorResType;
	}

	public void setMonitorResType(MonitorResourceType monitorResType) {
		this.monitorResType = monitorResType;
	}

	public MonitorOperType getMonitorOperType() {
		return monitorOperType;
	}

	public void setMonitorOperType(MonitorOperType monitorOperType) {
		this.monitorOperType = monitorOperType;
	}

	@Override
	public String toString() {
		return new StringBuilder("MonitorCtrlInfo: ").append("instanceKey:").append(instanceKey)
				.append(",resourcceType:").append(monitorResType).append(",operateType:")
				.append(monitorOperType).toString();

	}

}

2. enum class
public enum MonitorResourceType {

	ALL, SQL, AOP, INTERFACE, HTTP, JEDIS, EJB
}

public enum MonitorOperType {

	ENABLE, DISABLE, RESET;
}

3. when I used kryo within jdk1.6 env to serialize MonitorCtrlBean  to be transferred to another application while in jdk1.8. I found that it could not be read. but the similar jdk1.8 (e.g jdk1.8.0_11 to jdk.1.8.0_51) or similiar jdk1.6 is OK. 

when I read the default serializers in kryo, I found there was no implicit support for enum class. so how to solve such problem. while I try to implement the serializer special for MonitorCtrlBean class like this (and also could not resolve the problem):

private static class MonitorCtrlBeanSerializer extends Serializer<MonitorCtrlBean> {

		@Override
		public void write(Kryo kryo, Output output, MonitorCtrlBean object) {
			output.writeString(object.getInstanceKey());
			kryo.writeClassAndObject(output, object.getMonitorResType());
			kryo.writeClassAndObject(output, object.getMonitorOperType());
		}

		@Override
		public MonitorCtrlBean read(Kryo kryo, Input input, Class<MonitorCtrlBean> type) {
			String instanceKey = input.readString();
			MonitorResourceType monitorResType = kryo.readObject(input, MonitorResourceType.class);
			MonitorOperType monitorOperType = kryo.readObject(input, MonitorOperType.class);
			return new MonitorCtrlBean(instanceKey, monitorResType, monitorOperType);
		}

	}

**Comment by bwzhang2011** [comment]
@romix or someone else, would you mind sparing some time and take a look it ?

**Comment by bwzhang2011** [comment]
@magro, could you take a look at it ? as enum class serialization is not supported implicitly. so how could I make a special serializer towars that .

**Comment by romix** [comment]
I don't quite understand the question. What is the problem if you'd use https://github.com/EsotericSoftware/kryo/blob/master/src/com/esotericsoftware/kryo/serializers/EnumNameSerializer.java or EnumSerializer?

**Comment by magro** [comment]
@bwzhang2011 And can you share the exception / stacktrace?

**Comment by bwzhang2011** [comment]
@magro, it did not generate the exception/stacktrace. as I use kryo to be the stream serialization implementation for hazelcast. from my testing,  the same simliar jdk version just jdk1.6+ or jdk1.8+ worked fine, but if you did the serialization between jdk1.6 and jdk1.8, the problem was forthcoming. I could not get the result.
@romix, would you mind sharing some example towards the pure enum class, from your comment, if the bean field marked with enum class, I should explicitly do it with EnumNameSerializer or EnumSerializer or not. for from the document and source codes, I could not find the direct support for enum class like other primitive type in java like int, long, etc.

**Comment by romix** [comment]
Please provide a self-contained unit test, which performs serialization and deserialization. It should expose the problem you have. No need to include any Hazelcast specific code.

**Comment by romix** [comment]
Also, have a look at:
https://github.com/EsotericSoftware/kryo/blob/master/test/com/esotericsoftware/kryo/serializers/EnumNameSerializerTest.java

and 

https://github.com/EsotericSoftware/kryo/blob/master/test/com/esotericsoftware/kryo/DefaultSerializersTest.java#L222-L262

**Comment by bwzhang2011** [comment]
@romix, I knew these example when encountered those problem while serializing enum class within fields. why not kryo done it behind as default support if the bean with more enum class we should do more register operation to let kryo know that such field class is enum type. I changed my serializer class to judge such. that is if is some bean with enum class it will call the method addDefaultSerializer(Enum.class, EnumNameSerializer.class and register the bean class together.

**Comment by bwzhang2011** [comment]
@romix, the problem still exits just as your suggestion followed by EnumNameSerializer.  @romix, as for the bean I referred as above. I just use kryo like the example:
kryo.addDefaultSerializer(Enum.class, EnumNameSerializer.class);
kryo.register(MonitorCtrlBean .class);

as I commented above, there's no problem with jdk1.6 or jdk1.8, but once you serialized it from jdk1.6 to jdk1.8 (both for jdk 64bit version), it would fail.

**Comment by bwzhang2011** [comment]
@romix, any update with such issue ? for I did try but it failed from jdk1.6 to jdk1.8 with kryo serialization so would you mind sparing some time to leave us such example not just simply refer to the  class not completely matched.

**Comment by romix** [comment]
No, no updates.  As I mentioned before:

Please provide a self-contained unit test, which performs serialization and deserialization. It should expose the problem you have.

Once we get your code, we could look into it and try to fix it.

**Comment by magro** [comment]
Reopen if still relevant.

**Comment by lincentpega** [comment]
I've encountered this problem while migrating from java 8 to java 11 while using the same cassandra cluster. I'm just getting enum ordinal value overflow 16384 while deserialization. Issue isn't present with database initialized over java 11.
