### ISSUE TITLE
Unable to deserialize large map

### ISSUE THREAD

**Issue by pablo-rago** [EsotericSoftware/kryo#336]
I'm having a problem deserializing maps greater than a certain size. The production code is a little bit more complex but I've reduced the problem to the following:

```java
@Test
    public void test() {

        Map<String,String> object = new HashMap<String, String>();

        int top = 150;

        for(int i = 0; i < top; i++) {
            object.put("key: " + i, "Some Large String: " + i);
        }

        Kryo kryo = new Kryo();

        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

        Output unsafeOutput = new Output(outputStream);
        kryo.writeClassAndObject(unsafeOutput, object);

        byte[] bytes = unsafeOutput.toBytes();
        ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(bytes);

        unsafeOutput.flush();
        unsafeOutput.close();

        Input input = new Input(byteArrayInputStream, (int) bytes.length);

        Object result = kryo.readClassAndObject(input);
    }
```

If the map is smaller, everything is fine (with size 50 for example), but larger maps throw the exception:

com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 81
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:137)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:670)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:781)
	at com.project.Test.test(Test.java:219)
	...

With slight variations in the Strings I also get sometimes an IndexOutOfBoundsException something like:

java.lang.IndexOutOfBoundsException: Index: 54, Size: 0
	at java.util.ArrayList.RangeCheck(ArrayList.java:547)
	at java.util.ArrayList.get(ArrayList.java:322)
	at com.esotericsoftware.kryo.util.MapReferenceResolver.getReadObject(MapReferenceResolver.java:42)
	at com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:830)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:680) 

The issue seems to be very similar to http://code.google.com/p/kryo/issues/detail?id=150.
I'm using kryo 3.0.3

Any idea what the problem might be?

**Comment by psmarcos** [comment]
+1

**Comment by causis** [comment]
We're having the same issue!

**Comment by romix** [comment]
I'll try to look into this issue. 

Does it happen only with Input/Output? Or can you reproduce it with UnsafeInput/UnsafeOutput and so on?

**Comment by pablo-rago** [comment]
Yes, it can also be reproduced with UnsafeInput/UnsafeOutput but the size of the map you need to reproduce may be greater. Also the id of the "Encountered unregistered class ID" may vary.

**Comment by pablo-rago** [comment]
I get the impression that even when the exception is thrown when reading, the actual problem happens while writing. Looking to the first bits in the serilization which, as far as I understand, should represent the class, I see that for maps with a size that result in an error those bits are not the same that returns something like kryo.writeClass(unsafeOutput, new HashMap<String, String>().getClass()). Maps which can be written and read successfully share all the same first bits but the ones that result in error have different bits each. I guess that could be resulting in the <id> in "Encountered unregistered class ID: <id>" being always different when it fails. Maybe those first bits are somehow getting lost or shifted or something and then the bits that intend to represent the class when reading are other and that's why the class can't be found. I don't know if I'm getting it entirely right, but hope this helps.

**Comment by romix** [comment]
I think your code is wrong, when it comes to working with IO streams. Please see my version below:

```java
@Test
    public void test() {

        Map<String,String> object = new HashMap<String, String>();

        int top = 150;

        for(int i = 0; i < top; i++) {
            object.put("key: " + i, "Some Large String: " + i);
        }

        Kryo kryo = new Kryo();

        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

        Output unsafeOutput = new Output(outputStream);
        kryo.writeClassAndObject(unsafeOutput, object);
        unsafeOutput.flush();
        unsafeOutput.close();

        // Take the bytes from the actual output stream.
        byte[] bytes = outputStream.toByteArray();
        ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(bytes);


        Input input = new Input(byteArrayInputStream, (int) bytes.length);

        Object result = kryo.readClassAndObject(input);
    }
```

**Comment by pablo-rago** [comment]
That was it. With that change it works just fine. The fact that it was working for me most of the time but not always had me really confused. Thanks!
