### ISSUE TITLE
com.esotericsoftware.kryo.io.ByteBufferInputStream violates InputStream contract

### ISSUE THREAD

**Issue by esialb** [EsotericSoftware/kryo#337]
The method ByteBufferInputStream.read() violates the contract of InputStream.  The method body in 3.0.0 is:

	public int read () throws IOException {
		if (!byteBuffer.hasRemaining()) return -1;
		return byteBuffer.get();
	}

And should be:

	public int read () throws IOException {
		if (!byteBuffer.hasRemaining()) return -1;
		return byteBuffer.get() & 0xFF;
	}

The issue appears whenever a byte whose most-significant-bit is read from the buffer; the ByteBufferInputStream, by failing to mask to 0xFF, returns a negative value (indicating end of input) rather than a positive int ranged 128-255 inclusive.

**Comment by esialb** [comment]
Created a pull request https://github.com/EsotericSoftware/kryo/pull/338

**Comment by magro** [comment]
Fixed with #338
