### ISSUE TITLE
Update clirr exclusions for Kryo 5

### ISSUE THREAD

**Issue by magro** [EsotericSoftware/kryo#343]
As mentioned in #342, we should make all classes/methods package private that are not intended to be part of the public api, to reduce the possibility of binary incompatible changes.
Classes for that the visibility cannot be reduced should explicitely be marked as _INTERNAL_, to make clear that they're not part of the public api (and might be changed).

Classes part of the internal api only should be excluded from compatibility (clirr) checks.

**Comment by NathanSweet** [comment]
In the kryo-5.0.0-dev branch few files are public needlessly. Some classes like IntArray or GenericsUtil are, but who is to say they are not useful to Kryo users? I think just listing the files for clirr is sufficient. Likely the clirr list needs to be updated for 5.0.0.
