### ISSUE TITLE
CompatibleFieldSerializer will produce a big binary if objects contains lots of null fields.

### ISSUE THREAD

**Issue by phamtm** [EsotericSoftware/kryo#345]
If one object has lots of null fields, the fields name will occupy most of the size of the binary. Can we not store these null fields in the output?

**Comment by NathanSweet** [comment]
Maybe there could be something done, but CompatibleFieldSerializer is not very efficient already. VersionFieldSerializer provides the smallest serialized size while still having some compatibility. TaggedFieldSerializer provides a slightly larger but still very efficient serialized size while also provided more compatibility. Only use CompatibleFieldSerializer if you must have forward compatibility (meaning older classes can read bytes serialized from newer classes).

**Comment by phamminh91** [comment]
@NathanSweet `TaggedFieldSerializer` downside is that we have to add an annotation to each field. CompatibleFieldSerializer while inefficient, is more convenient to use. I am currently looking into whether I can improve CompatibleFieldSerializer.

**Comment by ankitjhil** [comment]
We are in a situation that we have to use CompatibleFieldSerializer since the older classes needs to read the serialized bytes form newer classes.
Is there any way of reducing the overhead incurred by CompatibleFieldSerializer?

**Comment by phamminh91** [comment]
@ankitjhil You can implement `KryoSerializable`.

**Comment by NathanSweet** [comment]
CompatibleFieldSerializer is just somewhat inefficient, there's not much that can be done. Deflate on the data might help. You can load the old data and transform it to new classes which are serialized differently. TaggedFieldSerializer has "annexed" fields which are similar to CompatibleFieldSerializer.
