### ISSUE TITLE
KRYO serialization registering classes

### ISSUE THREAD

**Issue by shyam4u** [EsotericSoftware/kryo#347]
Hi Team ,

I am trying to use KRYO to serialize my cache keys and values which are plain JAVA domain objects .Before I cache these objects and store in a hazelcast cache I serialize the objects via KRYO and store then my cache.I have a few questions regarding the registration of classes being used by KRYO.

The cache which I use is actually a DB cache involving at-least hundereds of JAVA domain POJO and it is practically impossible for me to register them all .Below is a quick look of my serialization class details

I am using a thread local to wrap my KRYO instance and am registering my classes in my serialize and deserialize method .

private static final ThreadLocal<Kryo> serializerInstance = new ThreadLocal<Kryo>() {

    @Override
    protected Kryo initialValue() {
        final Kryo kryo = new Kryo();
        kryo.setRegistrationRequired(true);
        kryo.setAutoReset(false);
        return new Kryo();
    }
};

public static byte[] serialize(final Object target, Class<?> type) throws Exception {
    ByteArrayOutputStream outStream = null;
    Output output = null;
    try {
        // The buffer capacity is initially 32 bytes,and its size increases if necessary.
        outStream = new ByteArrayOutputStream();
        //Kryo to use this buffer to write the object we sent
        output = new Output(outStream, 512);
        final Kryo kyroInstance = serializerInstance.get();
        kyroInstance.register(type);
        kyroInstance.writeObject(output, target);
        output.flush();
        return output.getBuffer();
    } catch (Exception e) {
        throw e;
    } finally {
        if (output != null)
            output.close();
        if (outStream != null)
            outStream.close();
    }
}

public static Object deserialize(byte[] bytes, Class<?> type) throws Exception {
    Input input = null;
    try {
        input = new Input(new ByteArrayInputStream(bytes), 512);
        final Kryo kyroInstance = serializerInstance.get();
        kyroInstance.register(type);
        final Object obj = kyroInstance.readObject(input, type);
        return obj;
    } catch (Exception e) {
        throw e;
    } finally {
        if (input != null)
            input.close();
    }
}

I am registering the classes at run time whenever I have an object to serialize of deserialize .I am experiencing some class not registered exceptions notably not in a particular pattern .Can anybody advice looking into this code and suggest some changes here ???

**Comment by shyam4u** [comment]
Can anybody help me fix this issue please

**Comment by romix** [comment]
Registering your classes on-demand using automatically assigned IDs is a very bad idea, because it may lead to a non-deterministic behaviour. You should try to register your classes in advance, if possible. If it is not possible, you should try to at least assign custom IDs to your classes during their registration. This will ensure that the same IDs are used by serializing and deserializing side.

**Comment by shyam4u** [comment]
@romix It is not possible for me to register the classes before hand ..if you say we can assign custom Id ..hw will the custom Id be assigned ....Say we have 2 classes A and B ..and we have A being used in B .In this case what shld be the sequence of registration ?

**Comment by romix** [comment]
Basically, you need to ensure that both sides always use the same ID for the same class.
This can be achieved, e.g.:
- by registering the classes on both sides exactly in the same order. Then they'll get the same IDs assigned.
- by registering the classes on both sides by providing your own custom and deterministic ID. E.g. some kind of a hash of the fully qualified class name (IIRC, there are very few collisions with good hashes).
- If you know the set of your classes in advance (which does not mean you'll use all of them in a specific scenario; may be you can scan your JARs/classpath and just register everything that could potentially be serialized?, ....), you can register all of the classes in advance and assign the same unique IDs to them on both sides.


Regarding A being used in B: First register A then B.

**Comment by shyam4u** [comment]
@romix  Lets assume I have a list of all the classes scanned from my class-path but that doesn't give me the idea of the sequence of how they are used .Like the example I gave above ,I have A and B available with me but I have no idea if I should have A registered first or B .This sequence you come to know when you know the code .In that case any change in class code would mean revisiting the sequence of the class registered .

**Comment by romix** [comment]
Sorry, I think I was too fast typing my answer. Actually, now that I think about it, the order of registration when you use your custom deterministic IDs is not important. I.e. you can register B before A or vice versa. It does not matter. The reason for this is the fact that FieldSerializer fetches a real serializer for a a given field only during a serialization, but not during the registration of a class.

I hope this should be enough for you, to register all you classes in advance with deterministic IDs.

**Comment by magro** [comment]
Maybe I've missed s.th., but why not just setRegistrationRequired(false)
and let kryo write class names into the serialized bytes?

Cheers,
Martin
Am 17.09.2015 19:52 schrieb "romix" <notifications@github.com>:

**Comment by shyam4u** [comment]
@magro I have tried using the setRegistrationRequired(false) on kryo instance but am getting the class not registered exception intermittently .Another trade off is appending class name into the serialized bytes results in a higher size which I guess we cannot overlook .

@romix Thanks Romix for your answers .I appreciate your help .
With all the approach and code snippets above -Do you see any other glaring issues which needs to be handled .

**Comment by romix** [comment]
I don't see obviously wrong things in your code above. 
May be I'm not 100% sure about `kryo.setAutoReset(false);`
What do you need to use ByteArrayOutputStream? You want to get your byte[] at the end, right? Why not using byte[] as buffers directly? It may be faster. 
Eventually, you may want to cache your Input/Output buffers, just like you do for Kryo instances. This may reduce the GC pressure.

**Comment by shyam4u** [comment]
@romix  
The used case is as below - I have a Java object which is stored in a hazel cast cache .I don't want to tie my Java object to any serialization mechanism like implementing externalizable or any such so what I have done is as below.

I have created a custom class say CustomisedValue which has two fields 
1.bytes[] - the bytes[] of the java object and 
2.classType - class of the original Java object .
Internally the constructor of this class invoke my Kryo serialization method above to get the bytes[] .
In same way when I need the original JAVA object back ,I have the logic to desrialize via kryo embedded in the same class in a readObject() method which gives back the Java object .

Do you say we need use  output.toBytes(); instead of  output.getBuffer();???Not clear in your last statement though .

And also how do you measure the size of the serialized object formed via the kryo serialization here ?

**Comment by romix** [comment]
I meant output.toBytes(). This will give you only the bytes representing the serialized value, not the whole buffer.

But I also meant that you probably want to use Output(buf_size) instead of providing the underlying ByteArrayOutputStream to it. new Output(buf_size) would allocate a byte[] itself.

But may be you have to use the ByteArrayOutputStream because Hazelcast mandates it or something like this.

**Comment by shyam4u** [comment]
@romix  I don't think using ByteArrayOutputStream is something necessary from hazelcast end .I can do away with this if I see any performance benefit in that ...How would I get the size of the serialized objects .Do u suggest using the length()on the bytes[].I need to compare the performance of Kryo and this approach altogether ...

**Comment by romix** [comment]
output.toBytes().length should give you the exact size of serialized representation of your object-graph.

**Comment by romix** [comment]
BTW, Kryo is able to write into buffer/memory already provided. So, if Hazelcast offers something, you could use it to avoid copying from output into byte[] and then from byte[] into Hazelcast buffer/stream/whatever.

**Comment by romix** [comment]
@shyam4u  Any progress on this? Is it still an issue?

**Comment by shyam4u** [comment]
@romix 
I have taken the following approach to register my classes .
I am trying to get all classes present inside the package of domain classes using reflection and then trying to register all those classes .The only problem is the inner classes present inside the concrete classes .These classes are compiled as concreteclass1$.class and am not sure hw to register them .Using the below code to get all classes and have them registered while creating Kryo instances. 

        final ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
        final String packagePath = packageName.replace('.', '/');
        final Enumeration<URL> resourcesList = classLoader.getResources(packagePath);

**Comment by romix** [comment]
Please search on the kryo-users google group. There were some questions about it, e.g.:
https://groups.google.com/forum/#!searchin/kryo-users/inner$20classes%7Csort:date/kryo-users/9yobtSM9mmg/QGnNPLijVboJ

Hopefully, one of those discussions could help you.
