### ISSUE TITLE
'Enum' has no zero-arg constructor and this will affect the serialization performance

### ISSUE THREAD

**Issue by kemp-john** [EsotericSoftware/kryo#350]
I defined a class like this:
```
public class ActiveDevice implements Serializable {
	private static final long serialVersionUID = -3568056716964263234L;
	private String name;
	private ToolbarStatus toolbarStatus; 

	public enum ToolbarStatus {
		Working,
		Waiting,
		Oning,
		Offed
	}
}
```
When I'm running the application, I got a warning like this:

[09-28 10:08:02,977] New I/O worker #1  WARN kryo.CompatibleKryo:  class com.test.api.domain.ActiveDevice$ToolbarStatus has no zero-arg constructor and this will affect the serialization performance

JDK: java version "1.7.0_79"
kryo: v2.24
kryo-serializers: v0.26

Does anyone know how to fixed it? Thanks!

**Comment by magro** [comment]
Please try to make ToolbarStatus static.

**Comment by kemp-john** [comment]
Hey magro,
Thank you for the reply! I made ToolbarStatus static, but it didn't work, the warning is still appearing.
```
public static enum ToolbarStatus {
		Working,
		Waiting,
		Oning,
		Offed
	}
```

**Comment by kemp-john** [comment]
I figured out the warning wasn't caused by kryo, close the issue.
Thanks Magro!

**Comment by magro** [comment]
Great that you figured it out!
