### ISSUE TITLE
Kryo 3.0.0 java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Raycoms** [EsotericSoftware/kryo#351]
java.lang.IndexOutOfBoundsException: Index: 134, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.esotericsoftware.kryo.util.MapReferenceResolver.getReadObject(MapReferenceResolver.java:42)
	at com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:830)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:680)
	at ThreadClasses.Learner.deserialize(Learner.java:56)
	at ThreadClasses.Learner.run(Learner.java:80)
	at java.lang.Thread.run(Thread.java:745)

java.lang.IndexOutOfBoundsException: Index: 666, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.esotericsoftware.kryo.util.MapReferenceResolver.getReadObject(MapReferenceResolver.java:42)
	at com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:830)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:680)
	at ThreadClasses.Learner.deserialize(Learner.java:56)
	at ThreadClasses.Learner.run(Learner.java:80)
	at java.lang.Thread.run(Thread.java:745)

I tried different runs.
I also tried using
FieldSerializer, TaggedFieldSerializer and VersionFieldSerializer.

public class TransactionStorage implements Serializable
{
    public int ringNodeId;

    public ArrayList<NodeStorage> readSetNode;
    public ArrayList<RelationshipStorage> readSetRelationship;

    public HashMap<NodeStorage, NodeStorage> writeSetNode;
    public HashMap<RelationshipStorage, RelationshipStorage> writeSetRelationship;

    public ArrayList<NodeStorage> createSetNode;
    public ArrayList<RelationshipStorage> createSetRelationship;

    public ArrayList<NodeStorage> deleteSetNode;
    public ArrayList<RelationshipStorage> deleteSetRelationship;

    public long snapShotId;
    public int client;

    public TransactionStorage(ArrayList<NodeStorage> readSetNode,ArrayList<RelationshipStorage> readSetRelationship,  HashMap<NodeStorage, NodeStorage> writeSetNode,
                              HashMap<RelationshipStorage, RelationshipStorage> writeSetRelationship,ArrayList<NodeStorage> createSetNode,
                              ArrayList<RelationshipStorage> createSetRelationship,ArrayList<NodeStorage> deleteSetNode, ArrayList<RelationshipStorage> deleteSetRelationship, long snapShotId,int client)
    {
        this.readSetNode = readSetNode;
        this.readSetRelationship = readSetRelationship;
        this.writeSetNode = writeSetNode;
        this.writeSetRelationship = writeSetRelationship;
        this.createSetNode = createSetNode;
        this.createSetRelationship = createSetRelationship;
        this.deleteSetNode = deleteSetNode;
        this.deleteSetRelationship = deleteSetRelationship;

        this.snapShotId = snapShotId;
        this.client = client;
    }

    public int getRingNodeId()
    {
        return ringNodeId;
    }

    public void setRingNodeId(int ringNodeId)
    {
        this.ringNodeId = ringNodeId;
    }

}

Node and Relationship storage are serializable and do contain arraylists and hashmaps containing strings and integers.

**Comment by romix** [comment]
Could you provide a complete self-contained example that would reproduce your problem?

**Comment by Naitonium** [comment]
I had the same issue.
It was thread safe problem in my code.
Are you sure that your serialization/deserealization code thread safe and not used already used serializer/deserializer?

**Comment by Raycoms** [comment]
There is only one thread serializing and one thread de serializing.

When I use the taggedserializer he runs but all my arraylist finish empty.
Am 29.09.2015 19:41 schrieb "Aleh" <notifications@github.com>:

**Comment by Naitonium** [comment]
Could you provide your serialization/deserialization code samle?

**Comment by Raycoms** [comment]
public static Object deserialize(byte[] data) throws IOException, ClassNotFoundException
    {
        Input input = new Input(new ByteArrayInputStream(data));
        return kryo.readObject(input, TransactionStorage.class);
    }

    public byte[] serialize(TransactionStorage packages)
    {
        Output output = new Output(new ByteArrayOutputStream());

        kryo.writeObject(output, packages);
        //kryo.writeObject(output, packages);
        return output.toBytes();
    }

**Comment by Naitonium** [comment]
It's code running in only one thread?

**Comment by romix** [comment]
How about:
```java
public byte[] serialize(TransactionStorage packages)
{
    ByteArrayOutputStream baos = new ByteArrayOutputStream(); 
    Output output = new Output(baos);

    kryo.writeObject(output, packages);
    //kryo.writeObject(output, packages);
    // Flush the stream
    output.flush();
    // Get the byte array from the underlying ByteArrayOutputStream, 
    // as it may be longer than the size of the Output stream.
    return baos.toByteArray();
}
```

**Comment by Naitonium** [comment]
romix +1. I forget about it.

**Comment by Raycoms** [comment]
Thanks, worked
