### ISSUE TITLE
version 3.3.0:ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Martin404** [EsotericSoftware/kryo#353]
java.lang.ArrayIndexOutOfBoundsException: 25
	at com.esotericsoftware.kryo.util.IntArray.add(IntArray.java:79) ~[kryo-3.0.3.jar:na]
	at com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:820) ~[kryo-3.0.3.jar:na]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:788) ~[kryo-3.0.3.jar:na]
	at com.supuy.core.util.KryoRedisSerializer.deserialize(KryoRedisSerializer.java:36) ~[KryoRedisSerializer.class:na]
	at org.springframework.data.redis.core.AbstractOperations.deserializeHashKey(AbstractOperations.java:308) ~[spring-data-redis-1.5.0.RELEASE.jar:1.5.0.RELEASE]
	at org.springframework.data.redis.core.AbstractOperations.deserializeHashMap(AbstractOperations.java:277) ~[spring-data-redis-1.5.0.RELEASE.jar:1.5.0.RELEASE]
	at org.springframework.data.redis.core.DefaultHashOperations.entries(DefaultHashOperations.java:227) ~[spring-data-redis-1.5.0.RELEASE.jar:1.5.0.RELEASE]

When I use ab to benchmark,the error happened above. The script of ab benchmark like this:
ab -p c:\testspace\json.txt -T application/json -n 1000 -c 1000   "http://***".
My serialization/deserialization code follow:

public class KryoRedisSerializer<T> implements RedisSerializer<T> {

    private Kryo kryo = new Kryo();

    @Override
    public byte[] serialize(Object t) throws SerializationException {
        if(t != null){
            byte[] buffer = new byte[40960];
            Output output = new Output(buffer);
            kryo.writeClassAndObject(output, t);
            return output.toBytes();
        }else {
            return new byte[0];
        }

    }

    @Override
    public T deserialize(byte[] bytes) throws SerializationException {
        if(bytes != null && bytes.length > 0){
            Input input = new Input(new ByteArrayInputStream(bytes),65535);
            @SuppressWarnings("unchecked")
            T t = (T) kryo.readClassAndObject(input);
            return t;
        }else {
            return null;
        }

    }

**Comment by romix** [comment]
Please provide a self-contained example reproducing your problem. The code you provided is not self-contained.

**Comment by Martin404** [comment]
spring xml file:
    <bean id="redisTemplate" class="org.springframework.data.redis.core.RedisTemplate">
        <property name="connectionFactory" ref="jedisConnectionFactory"/>
        <property name="KeySerializer" ref="stringRedisSerializer" />
        <property name="ValueSerializer" ref="stringRedisSerializer" />
        <property name="hashKeySerializer" ref="kryoRedisSerializer"/>
        <property name="hashValueSerializer" ref="kryoRedisSerializer"/>
    </bean>

 service code:
    public Map<Integer,String> getDictMapByKey(String dictKey){
        HashOperations<String, Object, Object> opsForHash = redisTemplate.opsForHash();
        Map<Object, Object> entries = opsForHash.entries(dictKey);
        Map<Integer, String> result = new HashMap<>();
        for(Map.Entry<Object, Object> entry:entries.entrySet()){
            result.put((Integer) entry.getKey(), (String) entry.getValue());
        }
        return result;
    }

The self-contained example used kryo to serialize/deserialize the hash structure of redis.  Send a request that calls the method of service was fine,but using ab benchmark call the method of service would appear errors like above.

**Comment by romix** [comment]
Yes, this gives more information. But what we need is:
- something that we can simply copy/paste in our editor or unpack into our folder and then just run JUnit or Maven or any other kind of build tool and just reproduce the crasher.

With the information you provided we'll spend more time just get it up and running (and crashing ;-) than analyzing this bug.

**Comment by magro** [comment]
@Martin404 Can you provide a self contained test case?
