### ISSUE TITLE
Kryo stopped to work on Android 6.0, the same code and binaries works on Android 4.x-5.x

### ISSUE THREAD

**Issue by krymlov** [EsotericSoftware/kryo#354]
Kryo stopped to work on Android 6.0, the same code and binaries works on Android 4.x-5.x

I am trying to debug code but right now have some difficulties with Android 6.0 Emulator,
so, I will attach a snippet from a log later.

**Comment by krymlov** [comment]
ok, the issue is the following:
1) There is a final class with a package visibility - name it Outer
2) There is a final local static class with a package visibility - name it Inner

In Android 6 the Kryo cannot anymore instantiate/deserialise such Inner class due to its visibility
issue at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:686)

Trace:
10-12 18:37:50.378: E/_EkadasiApp(3781): com.esotericsoftware.kryo.KryoException: Error constructing instance of class: org.holidates.ekadasi.place.WorldCitiesManager$CityInfo
10-12 18:37:50.378: E/_EkadasiApp(3781): 	at com.esotericsoftware.kryo.Kryo$DefaultInstantiatorStrategy$2.newInstance(Kryo.java:1262)
10-12 18:37:50.378: E/_EkadasiApp(3781): 	at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1090)
10-12 18:37:50.378: E/_EkadasiApp(3781): 	at com.esotericsoftware.kryo.serializers.FieldSerializer.create(FieldSerializer.java:570)
10-12 18:37:50.378: E/_EkadasiApp(3781): 	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:546)
10-12 18:37:50.378: E/_EkadasiApp(3781): 	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:790)
10-12 18:37:50.378: E/_EkadasiApp(3781): 	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134)
10-12 18:37:50.378: E/_EkadasiApp(3781): 	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40)
10-12 18:37:50.378: E/_EkadasiApp(3781): 	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:686)

If i change Inner class visibility from package to public, then everything is OK

**Comment by romix** [comment]
Could you provide a self-contained test-case please (sources, build instructions/scripts, etc)?

**Comment by magro** [comment]
@krymlov Any feedback on this, can you provide a self-contained test-case?
