### ISSUE TITLE
serializing a class that extends an ArrayList

### ISSUE THREAD

**Issue by jtviegas** [EsotericSoftware/kryo#355]
hello,

default serializers seem not to serialize/deserialize correctly the x field in the class below.
JavaSerializer works like a charm, but I'd like not to add that opt-out clause for this partuicular class in the Kryo instance, and use it as I do for any other class, so I was trying to find a way to implement a custom serializer and I
can't find it. Example class:

public class ExtendedList<E> extends ArrayList<E> {
	private static final long serialVersionUID = 5355823494664240059L;
	private double x;
.... setter and getter, hashcode, equals and so on....
}

can anyone help?

**Comment by magro** [comment]
The mailing list is the place for questions. You should share the custom serializer you tried to write which is not working as expected. You may also have a look at existing serializers for inspiration. I'd say you should be able to extend some list or collection serializer and just additionally serialize/deserialize field x.
