### ISSUE TITLE
Parent scope can be set just once - multi thread

### ISSUE THREAD

**Issue by ARUNSETHIA** [EsotericSoftware/kryo#357]
Hi,

Please can someone help me understand how to resolve the below exception

Exception in thread "pool-1-thread-4" java.lang.RuntimeException: com.esotericsoftware.kryo.KryoException: java.lang.IllegalStateException: Parent scope can be set just once

The scenario is as following:

1. We are serializing multiple objects by multiple threads and each thread serialize multiple objects in the loop. 
2. We have created wrapper for Kryo serialization, where we have kryo object as static final
private static final Kryo kryo = new Kryo(); 
3. serialization is being done using same Kryo object, which is shared across the threads.

The program is able to do process serialization successful except one of the thread start giving this error and everything fails from that one of the thread.

Thanks,

**Comment by magro** [comment]
As said in the readme https://github.com/EsotericSoftware/kryo/#threading "Kryo is not thread safe. Each thread should have its own Kryo, Input, and Output instances. Also, the byte[] Input uses may be modified and then returned to its original state during deserialization, so the same byte[] "should not be used concurrently in separate threads."

**Comment by ARUNSETHIA** [comment]
Thanks Magro, so quick response.
