### ISSUE TITLE
Support for Java 8 date/time classes

### ISSUE THREAD

**Issue by lichtin** [EsotericSoftware/kryo#358]
Can you add support for Java 8 date/time classes?

Using kryo.setInstantiatorStrategy(new DefaultInstantiatorStrategy(new StdInstantiatorStrategy()));
I can already serialize them, but I guess native support is more efficient (citing @magro ).

**Comment by magro** [comment]
The main issue here is to support java 8 specific serializers and the adjustments of the build process. I just submitted issue #360 to track/discuss this.
