### ISSUE TITLE
Kryo IndexOutofBoundsException in MapReferenceResolver

### ISSUE THREAD

**Issue by Raycoms** [EsotericSoftware/kryo#363]
Executed this in my code,
I can reproduce it.
It happens when the packages become larger.

The to string description which is normally something with ArrayList... becomes 

SKIP:1446576003485:8115097513201

public static Object deserialize(byte[] data) throws IOException, ClassNotFoundException
{
        Input input = new Input(new ByteArrayInputStream(data));
        return kryo.readObject(input, TransactionStorage.class);
}

I am sending this 

public class TransactionStorage implements Serializable
{
    public int ringNodeId;

    public ArrayList<NodeStorage> readSetNode;
    public ArrayList<RelationshipStorage> readSetRelationship;

    public HashMap<NodeStorage, NodeStorage> writeSetNode;
    public HashMap<RelationshipStorage, RelationshipStorage> writeSetRelationship;

    public ArrayList<NodeStorage> createSetNode;
    public ArrayList<RelationshipStorage> createSetRelationship;

    public ArrayList<NodeStorage> deleteSetNode;
    public ArrayList<RelationshipStorage> deleteSetRelationship;

    public long snapShotId;
    public int client;

    public TransactionStorage(ArrayList<NodeStorage> readSetNode,ArrayList<RelationshipStorage> readSetRelationship,  HashMap<NodeStorage, NodeStorage> writeSetNode,
                              HashMap<RelationshipStorage, RelationshipStorage> writeSetRelationship,ArrayList<NodeStorage> createSetNode,
                              ArrayList<RelationshipStorage> createSetRelationship,ArrayList<NodeStorage> deleteSetNode, ArrayList<RelationshipStorage> deleteSetRelationship, long snapShotId,int client)
    {
        this.readSetNode = readSetNode;
        this.readSetRelationship = readSetRelationship;
        this.writeSetNode = writeSetNode;
        this.writeSetRelationship = writeSetRelationship;
        this.createSetNode = createSetNode;
        this.createSetRelationship = createSetRelationship;
        this.deleteSetNode = deleteSetNode;
        this.deleteSetRelationship = deleteSetRelationship;

        this.snapShotId = snapShotId;
        this.client = client;
    }

    public TransactionStorage()
    {

    }

    public int getRingNodeId()
    {
        return ringNodeId;
    }

    public void setRingNodeId(int ringNodeId)
    {
        this.ringNodeId = ringNodeId;
    }

}

Exception in thread "Learner" java. lang.IndexOutOfBoundsException: Index: 47, Size: 0 
at java.util.ArrayList.rangeCheck(ArrayList.java:653) 
at java.util.ArrayList.get( ArrayList.java:429) 
at com.esotericsoftware.kryo.util.MapReferenceResolver.getRead Object(MapReferenceResolver.java:60 ) 
at com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:834) 
at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:684) 
at ThreadClasses.Learner.deserialize(Learner.java:55) 
at ThreadClasses.Learner.run(Learner.java:79) 
at java.lang.Thread.run(Thread.java:745)

**Comment by magro** [comment]
Before submitting an issue please check for similar issues to see if that was previously reported and some potential solution helps in your case as well. Filtering issues by IndexOutOfBoundsException returns #351 as first match - does this help? If not, does any of the other similar issues provide any insights?

**Comment by Raycoms** [comment]
#351 I posted a time ago, this fix I used, but now the problem seems to be
another one

2015-11-04 12:04 GMT-02:00 Martin Grotzke <notifications@github.com>:

**Comment by magro** [comment]
Then can you please provide a self contained test case?
Am 04.11.2015 15:32 schrieb "Raycoms" <notifications@github.com>:

**Comment by Raycoms** [comment]
This error only happens when I execute it on Linux in a multi server
environment (4 servers) not when I execute it with 4jvm on my windows pc.
If you have 4 servers I may send you the jars in order to reproduce.



2015-11-04 15:36 GMT-02:00 Martin Grotzke <notifications@github.com>:

**Comment by Raycoms** [comment]
The main question is why it returns
"SKIP:1446576003485:8115097513201"

This doesnt happen when I run it at my single pc...

**Comment by magro** [comment]
Not sure why this is printed. 

Can you try to reproduce this issue in isolation, maybe by stimulating things that are leading to this issue? When we have something we can run to reproduce this we are able to analyze.

**Comment by Raycoms** [comment]
You should be able to reproduce it with arraylists or hasmaps consisting
more than 1000 elements on Linux.
But It also may be zookeeper destroying the messages to the skip thing and
kryo is then unable to read.
Am 07.11.2015 07:37 schrieb "Martin Grotzke" <notifications@github.com>:

**Comment by magro** [comment]
Please provide an example where you're sure that this allows to reproduce the issue. http://sscce.org

**Comment by magro** [comment]
@Raycoms Is this still an issue for you, or can we close this?

**Comment by Raycoms** [comment]
I build a workaround, and won't need it for now, you can close this.
Thank you.

2016-02-19 22:35 GMT-02:00 Martin Grotzke <notifications@github.com>:

**Comment by magro** [comment]
Ok

**Comment by Kamil-D** [comment]
@Raycoms Could you please share with this workaround? I encountered the same problem and completely I don't know how to solve it...
