### ISSUE TITLE
Few of the java Charsets classes from rt.jar can not be deserialized

### ISSUE THREAD

**Issue by jagrutmehta** [EsotericSoftware/kryo#364]
Charsets like sun.nio.cs.UTF_8,  UTF-16, UTF-16BE, UTF-16LE, ISO_8859_1 are defined package or private scope and are unable to be deserialized. These classes may be used internally by java objects and without user knowing it.

Is it a good idea to supply serializer for these Charsets? Serializer code is very simple but may be very useful and moreover streamlined for all kryo users. Please let me know if its a good idea or not. If yes then I will submit PR.

**Comment by jagrutmehta** [comment]
Meanwhile you can use my solution (derived from haochan post in this issue list) which works for all of such java internal Charset classes

https://github.com/jagrutmehta/kryo-UTF/blob/master/KryoCharsetSeralizer.java 
https://github.com/jagrutmehta/kryo-UTF

**Comment by magro** [comment]
Until now kryo does not provide jdk specific serializers, they're kept in [kryo-serializers] (https://github.com/magro/kryo-serializers).
I'd assume that since 1.7 they're replaces by java.nio.charset.StandardCharsets. Can you describe your case a bit more?

**Comment by jagrutmehta** [comment]
Take below simple example and it will fail. 

`import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.io.Input;
import com.esotericsoftware.kryo.io.Output;

import java.io.ByteArrayOutputStream;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;

public class KryoTest {

    Charset charsetUsed;

    public KryoTest(Charset charsetUsed) {
        this.charsetUsed = charsetUsed;
    }


    //Test this simple class in kryo
    public static void main(String... argv) {
        KryoTest testObject = new KryoTest(StandardCharsets.UTF_8);

        //firs serialize it
        Kryo kryo = new Kryo();
        ByteArrayOutputStream bst = new ByteArrayOutputStream();
        Output out = new Output(bst);
        kryo.writeObject(out, testObject);
        out.close();


        //try to deserialize it now.
        Input input = new Input(bst.toByteArray());
        //below line throws java.lang.IllegalAccessError: tried to access class sun.nio.cs.UTF_8 from class sun.nio.cs.UTF_8ConstructorAccess
        KryoTest newTestObject = kryo.readObject(input, KryoTest.class);
        System.out.println(newTestObject.charsetUsed);

    }
}`

**Comment by magro** [comment]
@jagrutmehta Ok, thanks, I got it now :-) I just submitted a PR that adds the default serializer, you then have still to `kryo.register(StandardCharsets.ISO_8859_1.getClass());` etc.

**Comment by becomehero** [comment]
I have the problem that "com.esotericsoftware.kryo.KryoException: Error constructing instance of class: sun.nio.cs.UTF_8", I have seen  "EsotericSoftware/kryo#364" on github, but I don't know to do for the problem, can you give me a help with a clear explanation.
