### ISSUE TITLE
Support guava BloomFilter please.

### ISSUE THREAD

**Issue by jiming** [EsotericSoftware/kryo#366]
Deserialize by kryo exception 
com.esotericsoftware.kryo.KryoException: Class cannot be created (missing no-arg constructor): com.google.common.hash.BloomFilter

**Comment by magro** [comment]
Sorry for the late response. Have you tried `kryo.getInstantiatorStrategy().setFallbackInstantiatorStrategy(new StdInstantiatorStrategy());`? If that doesn't work you should write a custom serializer.
