### ISSUE TITLE
copyTransient is not global

### ISSUE THREAD

**Issue by prasanthj** [EsotericSoftware/kryo#370]
In apache hive we are planning to use Kryo's object to object deep copy functionality. We have a scenario where we have many transient fields in base Operator class. Every other SQL operator class inherit from this base class. The way we clone the operator tree is to serialize it to ByteArrayOutputStream (baos.write is synchronized too) and read it back. I am guessing Kryo.copy() will be much faster than the current approach. But Kryo.copy seems to copy the transient fields (this goes all the way to slf4j and log4j instances) from base class. I see that #148 added a config to disable copying transient fields but that can only be set at field serializer level. With this approach I have to get the serializers of all derived classes and setCopyTransient to false. This seems to be painful approach. Is there an alternative to that? Can we control the copying transient in a global way?

**Comment by magro** [comment]
Resolved with #375
