### ISSUE TITLE
Serialization / Deserialization problems

### ISSUE THREAD

**Issue by Skerberus** [EsotericSoftware/kryo#371]
We would like to use Kryo in our project in order to serialize and deserialize objects that can contain Strings in different languages, that is why we would like to support UTF-8.

This is an example I wrote:
```java    
Wayne wayne = new Wayne("test");
Kryo kryo = new Kryo();
((Kryo.DefaultInstantiatorStrategy)      kryo.getInstantiatorStrategy()).setFallbackInstantiatorStrategy(new StdInstantiatorStrategy());
		kryo.register(ArrayList.class);
		String string;
		try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
				Output output = new Output(outputStream);) {
			kryo.writeObjectOrNull(output, wayne, Wayne.class);
			output.close();
			string = outputStream.toString("UTF-8");
		}
		System.out.println(wayne.get());
		Wayne result = null;
		try(Input input = new Input(string.getBytes("UTF-8")))
		{
			result = kryo.readObject(input, Wayne.class);
			input.close();
		}
		
		System.out.println(result.get());
```

The Wayne.class looks like this:
           
```java
    public class Wayne{
	private ArrayList<String> list;

	public Wayne(String wayne)
	{
		list = new ArrayList<String>();
		list.add(wayne);
	}
	
	public String get()
	{
		return list.get(0);
	}
    }
```

So I put in the String "test" and get as a result "teso". What is wrong here?

**Comment by magro** [comment]
@Skerberus Is this still an issue for you?

**Comment by lingwooc** [comment]
Some of the other serialisers give even more cryptic errors such as out of bounds exceptions but it all comes back to the fact you've corrupted the byte array. The key to fixing this is here http://stackoverflow.com/questions/9098022/problems-converting-byte-array-to-string-and-back-to-byte-array 

If you do something like this it's fine:
```
String yourString = new String(bos.toByteArray(),StandardCharsets.ISO_8859_1);
ByteArrayInputStream bis = new ByteArrayInputStream(yourString.getBytes(StandardCharsets.ISO_8859_1));
```
Took me ages to work that out so I thought I would share. Some other ways of encoding the array are in that post which may or may not be more suitable for you. Not really a kryo bug but it doesn't do you any favours not having any helpers (that I am aware of) to get to strings and back. You could argue its out of the scope of kryo but note in the docs at least have saved me some time.

**Comment by magro** [comment]
Why do you convert the bytes from the Outputstream to a string? You should just use the bytes from the Outputstream and for deserialization put them into the Input.

**Comment by magro** [comment]
And yes, converting bytes to string and back is nothing I'd see in kryo, there are existing libraries for that.

**Comment by lingwooc** [comment]
Mainly because I can't directly write byte arrays to my storage method (which I can't change). Kryo seemed to be the path of least resistance (I already had serialisers and it's compact and fast) but I'm wondering if a JSON based solution might be better.

**Comment by magro** [comment]
Out of interest: which storage accepts string only? 
You might consider writing/using an Outputstream that writes directly to a String (Builder), or use e.g. common-io's ByteArrayOutputStream which provides toString(Charset charset).

**Comment by lingwooc** [comment]
Accountancy software (quickbooks), I need more fields than it has in its stock database so I'm putting rather more into one of them (hence the need for compactness). Right now I'm stuck with that as the "master" database. I didn't try in the end but I suspect it would have changed the encoding and broken it anyway. I've converted the code to json now which I think was a better solution for me, certainly more robust in this situation.

No idea what @Skerberus needed to do, but at least now, somewhere on the internet, there is a comment on why kryo gets confused when you go via a string (and a suggestion that it might not be wise anyway).

**Comment by magro** [comment]
Ok, thanks for sharing that. I'm closing this for now.
