### ISSUE TITLE
Kryo eagerly reads all available input bytes, causing EOF issues when used together with other serializers reading from the same stream

### ISSUE THREAD

**Issue by fschuh** [EsotericSoftware/kryo#372]
It seems Kryo reads more than it should from a given input stream. It could be doing this due to some internal optimization, but it leads to EOF errors if a different serializer tries to read from the same stream Kryo is reading from.
This issue happened while integrating Kryo with Hazelcast (specifically the upcoming 3.6 release).

The following link contains the issue discussion and reproduction code:
https://github.com/hazelcast/hazelcast/issues/6781

Here's the 100% reproduction code:

    static class DummyValue {
        String value;

        public DummyValue(String value) {
            this.value = value;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;

            DummyValue value1 = (DummyValue) o;

            return !(value != null ? !value.equals(value1.value) : value1.value != null);
        }

        @Override
        public int hashCode() {
            return value != null ? value.hashCode() : 0;
        }
    }

    public static void testKryo() throws IOException {
        Kryo kryo = new Kryo();
        kryo.setInstantiatorStrategy(new Kryo.DefaultInstantiatorStrategy(new StdInstantiatorStrategy()));

        DummyValue value = new DummyValue("test");

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        Output output = new Output(out);
        kryo.writeObject(output, value);
        output.flush();
        out.write(1);

        ByteArrayInputStream in = new ByteArrayInputStream(out.toByteArray());
        Input input = new Input(in);

        Assert.assertEquals(value, kryo.readObject(input, DummyValue.class));
        Assert.assertEquals(1, in.read());  // <------- Here in.read() will return -1, EOF.
    }

Kryo version is 3.0.3.

**Comment by romix** [comment]
OK. I figured out what is the problem. Basically, when Kryo's Input starts reading from a ByteArrayInputStream, it tries to fill its internal buffer, which has a size of 4096 bytes by default. In your case, the ByteArrayInputStream is much smaller, so it reads the whole contents of it. Then it deserializes an object and consumes only the required number of input bytes. But the remaining bytes are still in the Input's buffer and thus are not available from ByteArrayInputStream anymore.

But there is a workaround, I think. Once you've read what you need from the Input, you could call input.total() to get the number of bytes read from the underlying stream. Then you can rewind the underlying stream (or open a new one with the same underlying byte array) to the position returned by input.total() and continue reading from it like in your test-case.

**Comment by fschuh** [comment]
I've found that if I use OutputChunked and InputChunked instead, I don't run into this issue anymore.
The performance seems to be exactly the same as using the regular Output and Input, as long as I use the same buffer size (4096 bytes).

Using the Chunked streams, Kryo seems to be respecting the size of each chunk and is not reading/writing more than it should.

**Comment by magro** [comment]
AFAICS this can be closed, otherwise reopen.
