### ISSUE TITLE
String from output

### ISSUE THREAD

**Issue by FabianTerhorst** [EsotericSoftware/kryo#378]
I want to encrypt the output and want to override the kryooutput with the encrypted string, but when i read the string from the output with ```String text = new String(kryoOutput.toBytes(), "UTF-8");``` the strings looks a liitle bit broken ```��java.util.ArrayLis���```. Is there a better way to get the string from the output to encryt and decrypt the string?

**Comment by FabianTerhorst** [comment]
for example when im overriding the output with String text = new String(kryoOutput.toBytes(), "UTF-8");
                ```Log.d("readText", text);
                kryoOutput.clear();
                kryoOutput.write(text.getBytes());```

i get ```Caused by: java.lang.ClassNotFoundException: java.util.ArrayLiso```

**Comment by magro** [comment]
Can you explain your use case a bit more? I don't think the serialized
bytes make any sense as String...

Btw, the mailing list is a better place for these kinds of questions.
Am 07.01.2016 19:08 schrieb "Fabian Terhorst" <notifications@github.com>:

**Comment by magro** [comment]
@FabianTerhorst Can we close this issue?
