### ISSUE TITLE
Update tests to use junit 4 (instead of 3)

### ISSUE THREAD

**Issue by magro** [EsotericSoftware/kryo#397]
Tests inheriting from KryoTestCase are run by junit 3 runner which lacks some features of junit 4 (e.g. does not support Assume to skip tests, which was introduced in 4.4).

Changing KryoTestCase to run with junit 4 would need changes to various tests: assert\* would have to be imported,  @Test would have to be added and @Before would have to be used.

**Comment by NathanSweet** [comment]
#600
