### ISSUE TITLE
Consider switching Kryo pool from CLQ to MpmcArrayQueue

### ISSUE THREAD

**Issue by guidomedina** [EsotericSoftware/kryo#403]
Original discussion was started at akka-kryo, just resuming here and see what you guys think:

https://github.com/romix/akka-kryo-serialization/issues/78

Suggested implementation: https://github.com/JCTools/JCTools/blob/master/jctools-core/src/main/java/org/jctools/queues/MpmcArrayQueue.java

@romix @luben

**Comment by romix** [comment]
I agree that the mentioned queue is probably faster in general. The question is: Is there any real performance difference, if this queue is used instead of the standard one provided by the JDK?

Kryo currently tries to avoid any external dependencies, unless they are really necessary. So, there should be a really convincing argument for adding a new dependency on the queue from JCTools.

If you are interested in this proposal being considered, how about providing a PR containing an implementation and a benchmark demonstrating that the new approach is much faster? You may want to include only the required queue classes, instead of pulling the whole JCTools dependency.

**Comment by guidomedina** [comment]
TBH, I don't use Kryo directly so I wouldn't really know how to measure it, that directly, I could give you a benchmark of both queues but we are almost certain of what is going to be the result.

My reasoning for the suggestion are merely about mechanical sympathy and GC as my application which is written is based on Akka uses many small messages.

Let me know if you would still consider such motive, another I don't which I can probably figure out by looking at the queue is how you use CLQ which is unbounded vs a bounded implementation (a circular buffer which is what this is all about), wouldn't that add an configuration parameter?

**Comment by guidomedina** [comment]
@romix is there a way to pass a queue for the Kryo builder?

**Comment by romix** [comment]
@guidomedina Have a look at https://github.com/EsotericSoftware/kryo/blob/master/src/com/esotericsoftware/kryo/pool/KryoPool.java

You can provide your own queue to the builder. It may allow you to quite easily benchmark different queues,  I guess.

**Comment by guidomedina** [comment]
Now I wonder from akka-kryo how friendly it would be to say, don't use `ObjectPool`, instead, use whatever KryoPool, but allow the user to specify which KryoPool implementation, and then we can create a example configuration using MpmcArrayQueue from JCtools, that way no API is intrusive, but it will require akka-kryo and kryo to be both modified, I'm not a Scala developer unfortunately or I would give you the PR.

**Comment by guidomedina** [comment]
@romix or some trick to pass the a _bounded queue (which will require a size)_, which ever way is easier.

**Comment by magro** [comment]
I'm also hesitant about adding another dependency to kryo without a clear motivation. While it's fairly clear that jctools queues perform better than CLQ when compared directly, I'd say that for most of the users serialization should be an order of magnitude more expensive than queue interaction.

And as @romix said, one can already set the preferred queue implementation on the builder (e.g. via `new KryoPool.Builder(kryoFactory).queue(new MpmcArrayQueue<Kryo>(42)).build();`).

I don't know akka-kryo well, but I could imagine that it might provide a `KryoPoolQueueFactory` with the default implementation `KryoPoolCLQueueFactory` (fqn can be configured/set in application.conf) - this would allow the user to implement and configure a `KryoPoolMpmcArrayQueueFactory` or another one depending on the specific use case (maybe a growing one or a SPSC queue is more appropriate?). akka-kryo could check if the `KryoPoolQueueFactory` provides a constructor taking a `Config`, this way the `KryoPoolMpmcArrayQueueFactory` could read the configured queue capacity from the config.

**Comment by guidomedina** [comment]
@magro the main reason I wanted this was because atm akka-kryo is using an ArrayBlockingQueue and Kryo a CLQ plus the fact that akka-kryo wants to eliminate their ObjectPool (their KryoPool counterpart) to use the KryPool to keep it minimal.

Then I thought, well, maybe going 2 steps up will actually bring some performance benefits, but then you are also right about adding more dependencies or a set of classes as not every case is the same as my application then I think we can agree that the configurable KryoPool is enough and that the flexibility would be more needed at the akka-kryo side?

**Comment by magro** [comment]
Sounds good to me.

I just saw that akka-kryo provides a `kryo-custom-serializer-init = "CustomKryoSerializerInitFQCN"` config - maybe a `kryo-pool-builder-init = "CustomPoolBuilderInitFQCN"` might be even better than a `KryoPoolCLQueueFactory` because it's more generic and would support potential future customization of the built kryo pool.

**Comment by guidomedina** [comment]
Closing as this is a problem that can be solved at akka-kryo-serialization, thanks all for the quick responses now let try to do something with my poor Scala knowledge :(

Feel free to check romix/akka-kryo-serialization#78
