### ISSUE TITLE
Which branch used for kryo-shaded-3.0.1

### ISSUE THREAD

**Issue by jasonstack** [EsotericSoftware/kryo#408]
Hi , I want to know which branch here used for kryo-shaded-3.0.1? Is it kryo-parent-3.0.1?

**Comment by magro** [comment]
kryo-shaded is built from the master branch, have a look at the poms. You can just `mvn install` to build the shaded jar.

Btw, for asking questions we have also a mailing list and even a gitter room :-)

**Comment by jasonstack** [comment]
Hi Magro, thanks for your reply. I am unable to find the Gitter for kryo.

I am curious which branch/tag is used to build "kryo-shaded-3.0.1" because I need to make some customization..Now I am using "kryo-parent-3.0.1" branch with shaded-pom to customize. Is it correct?

**Comment by jasonstack** [comment]
I will email on mailing-list. thank you
