### ISSUE TITLE
Serializing ZonedDateTime with ZoneOffset.UTC results in invalid ZoneOffset

### ISSUE THREAD

**Issue by YuvalItzchakov** [EsotericSoftware/kryo#409]
I'm using Kryo 2.21 on Java8 with Scala 2.10.6. Kryo  comes packaged along with Apache Spark.

As part of an object I'm trying to serialize, I have a ZonedDateTime which I'm trying to serialize/deserialize. When I do so, the `Z` part of the offset is replaced with `null`.

Reproduce:

    import java.io.{ByteArrayInputStream, ByteArrayOutputStream}
    import java.time.{ZoneOffset, ZonedDateTime}
    import com.esotericsoftware.kryo.io.{Input, Output}
    import com.twitter.chill.ScalaKryoInstantiator

    object X {
      val dt = ZonedDateTime.now(ZoneOffset.UTC)

      val kryo = new ScalaKryoInstantiator().setRegistrationRequired(false).newKryo()
      val stream = new ByteArrayOutputStream()
      val output = new Output(stream)
      kryo.writeObject(output, dt)
      output.close()

      val inputStream = new ByteArrayInputStream(stream.toByteArray)
      val input = new Input(inputStream)
      kryo.readObject(input, classOf[ZonedDateTime])
    }

Yields:

    res2: java.time.ZonedDateTime = 2016-03-17T14:39:48.117null

**Comment by magro** [comment]
Which serializer is used to serialize ZonedDateTime? This is an issue of this serializer.

**Comment by YuvalItzchakov** [comment]
How can I know which serializer is being chosen?

**Comment by magro** [comment]
Before de/serialization set `com.esotericsoftware.minlog.Log.TRACE()`.
Am 17.03.2016 17:08 schrieb "Yuval Itzchakov" <notifications@github.com>:

**Comment by magro** [comment]
To fix this you could create your own ZonedDateTimeSerializer and register it however this is done for spark/chill. 
For inspiration you could check out the serializer that will be shipped with the next kryo version: https://github.com/EsotericSoftware/kryo/blob/master/src/com/esotericsoftware/kryo/serializers/TimeSerializers.java

**Comment by YuvalItzchakov** [comment]
I saw that. I'm wondering if this issue was already fixed in the nexy Kryo version or perhaps I should create a pull request? I'm assuming your TimeSerializers have it covered.

**Comment by magro** [comment]
Not sure what's causing / responsible for this issue. Pull requests are always great, I just don't know against which repo this should go and what it should do. Can you elaborate a bit?

**Comment by YuvalItzchakov** [comment]
From debugging the code, what I'm currently seeing:

Kryo is trying to deserialize the `ZonedDateTime` and see that it has three fields. It first creates the `LocalDateTime` field properly, and then it's turn for `ZoneOffset` to be deserialized, this is where it gets interesting. It's trying to pick the `ObjectInstansiator` for the type, and it ends up picking `SunReflectionFactoryInstantiator<T>` which has an odd `newInstance` method:

    return mungedConstructor.newInstance((Object[]) null);

Thus, it returns `null` for the object instance, so `ZonedOffSet` ends up being `null`.

**Comment by YuvalItzchakov** [comment]
It seems like when `ZonedOffset` is being serialized, the `this.fields` member has only 1 element, which is the `totalSeconds` field. It's missing the `id` field.

**Comment by magro** [comment]
This default is intentional. To change it, you can register a FieldSerializer with serializeTransient=true for ZonedOffset.

**Comment by YuvalItzchakov** [comment]
How? I don't see a `serializeTransient` field:

val fs = new FieldSerializer[ZonedDateTime](kryo, classOf[ZonedDateTime])
fs.???

**Comment by YuvalItzchakov** [comment]
I'm not seeing any relevant method on FieldSerializer with Kryo 2.21.

**Comment by magro** [comment]
Ok, if kryo 2.21 does not yet support this then you create your own ZonedDateTimeSerializer and register it, as said before.

**Comment by YuvalItzchakov** [comment]
Thanks for all your help Martin! Appreciate it.

**Comment by magro** [comment]
You're welcome :-) And it should be sufficient to create a ZonedOffsetSerializer...

**Comment by fredijude** [comment]
@magro / @YuvalItzchakov: Is there a way that we can support for the backward compatibility. i.e. data which were serialized earlier using default field serializer, could it be identified and deserialized in the older way itself?
