### ISSUE TITLE
Possible documentation correction: Thread locals

### ISSUE THREAD

**Issue by jjzazuet** [EsotericSoftware/kryo#420]
Hi. The `README.md` file says that one can create thread local `Kryo` instances since these are expensive to instantiate. I think the `ThreadLocal` declaration in the example needs to change from:

    private ThreadLocal<Kryo> kryos = new ThreadLocal<Kryo>();

to

    private static final ThreadLocal<Kryo> kryos = new ThreadLocal<Kryo>();

When I tried this in my tests, my `main` thread was always getting a new `Kryo` instance from `kryos`. The second declaration did return the same instance for my `main` thread. Let me know if I'm missing something.

Thanks!

**Comment by magro** [comment]
It depends on the life cycle of the enclosing class. If it's a singleton then no static is needed, but otherwise you're right. We can change it to reduce/prevent potential errors - I'll update the README. Thanks for pointing at this!
