### ISSUE TITLE
Misleading debug message when registering classes

### ISSUE THREAD

**Issue by cypherdare** [EsotericSoftware/kryo#421]
To reproduce:

```
Log.DEBUG();
kryo = new Kryo();
kryo.register(SomeObject.class, new SomeObjectSerializer(), 1);
```
Resulting log:
```
DEBUG: An existing registration with a different type already uses ID: 1
Existing registration: [1, String]
Unable to set registration: [1, com.mypackage.SomeObject]
```

The Javadoc on the other hand says that existing registrations are merely replaced. And from briefly viewing the code, it appears to proceed with registration.

**Comment by magro** [comment]
@cypherdare thanks for reporting, so you want to submit a pull request?

**Comment by cypherdare** [comment]
@magro Submitted. This did lead me to notice another potential issue: #430
