### ISSUE TITLE
Serializer Support for Google's AutoValue

### ISSUE THREAD

**Issue by ZakTaccardi** [EsotericSoftware/kryo#423]
[AutoValue Extensions](http://angusmorton.com/autovalue-extensions/) are now a thing, so automatically generating a custom serializer for an `@AutoValue` class should exist.

**Comment by magro** [comment]
This is something for kryo-serializers rather than kryo. Pull request welcome :-)

**Comment by magro** [comment]
Replaced by https://github.com/magro/kryo-serializers/issues/48
