### ISSUE TITLE
visit the app of ejb that make up of hibernate , throw exception

### ISSUE THREAD

**Issue by maohui1993** [EsotericSoftware/kryo#427]
Sorry , my English is bad!

in the app, there is PersistantSet and it set the lazy = true;

e.x:
`kryoSerializer = new Kryo() { 
    @Override 
    public Serializer<?> getDefaultSerializer( final Class type ) { 
      if (AbstractPersistentCollection.class.isAssignableFrom( type )) { 
        return new FieldSerializer( kryoSerializer, type ); 
      } 
      return super.getDefaultSerializer( type ); 
    } 
  } ` 
I use it to handle. But It will still throw exception.

**Comment by magro** [comment]
Can you please post the thrown exception with stack trace? For general help and support requests we prefer to use the mailing list btw.

**Comment by maohui1993** [comment]
It have resolved, THX

**Comment by magro** [comment]
Can you share the solution?

**Comment by maohui1993** [comment]
ok..but wait tomorrow or more day. i need some time to it

**Comment by maohui1993** [comment]
`package hooyee.mao.serialize.kryo.test;

import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.io.Input;
import com.esotericsoftware.kryo.io.Output;
import com.esotericsoftware.kryo.serializers.FieldSerializer;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.HashMap;

/**
 * Created by hooyee on 2016/6/1.
 * e-mail maohui_dream@outlook.com
 */
public class KryoHibernateCollectionSerializer extends FieldSerializer<Object> {

    private static ArrayList emptyList = new ArrayList();
    private static HashMap emptyMap = new HashMap();
    private Class hibernate = null;
    private Method isInitialized = null;
    private boolean hibernateEnviroment = false;
    private Class persistentCollection = null;
    private Class persistentMap = null;

    public KryoHibernateCollectionSerializer(Kryo kryo, Class type) {
        super(kryo, type);
    }

    public void init() {
        ClassLoader loader = Thread.currentThread().getContextClassLoader();
        try {
            hibernate = loader.loadClass("org.hibernate.Hibernate");
            persistentCollection = loader.loadClass("org.hibernate.collection.PersistentCollection");
            persistentMap = loader.loadClass("org.hibernate.collection.PersistentMap");
        } catch (ClassNotFoundException e) {
            try {
                hibernate = loader.loadClass("net.sf.hibernate.Hibernate");
                persistentCollection = loader.loadClass("net.sf.hibernate.collection.PersistentCollection");
                persistentMap = loader.loadClass("net.sf.hibernate.collection.Map");
            } catch (ClassNotFoundException e1) {
                e1.printStackTrace();
            }
        }

        if (hibernate != null && persistentCollection != null) {
            try {
                isInitialized = hibernate.getDeclaredMethod("isInitialized", new Class[]{Object.class});
                hibernateEnviroment = true;
            } catch (NoSuchMethodException e) {
                e.printStackTrace();
            }
        }
    }

    public void write(Kryo kryo, Output output, Object obj) {
        boolean isInit = false;
        try {
            isInit = ((Boolean)isInitialized.invoke(hibernate, new Object[]{obj})).booleanValue();
        } catch (IllegalAccessException e) {
            isInit = false;
        } catch (InvocationTargetException e) {
            isInit = false;
        }

        if(persistentMap.isAssignableFrom(obj.getClass())) {
            if(isInit) {
                kryo.writeObject(output, obj.getClass());
                super.write(kryo, output, obj);
            } else {
                kryo.writeObject(output, emptyMap.getClass());
                super.write(kryo, output, emptyMap);
            }
        } else {
            if(isInit) {
                kryo.writeObject(output, obj.getClass());
                super.write(kryo, output, obj);
            } else {
                kryo.writeObject(output, emptyList.getClass());
                super.write(kryo, output, emptyList);
            }
        }
    }

    public Object read(Kryo kryo, Input input, Class type) {
        Class realType = kryo.readObject(input, Class.class);

        if (realType.isAssignableFrom(type)) {
            realType = type;
        }

        return super.read(kryo, input, realType);
    }
}
`

The basic way is that make serializer succeed when load lazy . so I use a "emptyList" instead of the primitive Object.

**Comment by magro** [comment]
Thanks for sharing!
