### ISSUE TITLE
Unclear that indices 0-9 already registered for primitives

### ISSUE THREAD

**Issue by cypherdare** [EsotericSoftware/kryo#430]
There is no way short of reading the source code that I've found for a user to know that Kryo has already used indices 0-9 to register all the primitives and String, and so can accidentally overwrite those registrations if explicitly setting the ID with `kryo.register(class, id)`. A typical user (if I'm one) starts registering classes at index 0 or 1 and up from there, thereby wiping out the registrations of all the primitives.

I'm not sure if there's a clean solution. It might be adequate to update the documentation to recommend assigning with indices >= 10. But when registration is set to required, and in light of #398, enforcement might be necessary.

**Comment by magro** [comment]
Sounds reasonable.

@NathanSweet WDYT?

**Comment by magro** [comment]
@NathanSweet WDYT about this?

**Comment by magro** [comment]
Closed with #509

**Comment by NathanSweet** [comment]
Sorry I'm late. Updating the docs in #509 is good.

Note that a user can clear and re-register all classes to have control of the ordinals.
