### ISSUE TITLE
Timeline for kryo point release

### ISSUE THREAD

**Issue by lbergelson** [EsotericSoftware/kryo#431]
I was wondering what the timeline for a new kryo release is?  We'd like an official version that includes the changes from #400.  It looks like there hasn't been a new release since July of last year.

**Comment by magro** [comment]
Basically we could have a release at any time. The only thing that's holding me back a bit is the situation around generics support, which might be worse for some cases compared to 3.0.3. Let's see what we can do here. I'll also check issues / PRs to see if there's anything critical left. I won't have much time for kryo this week, next week will be better. Do you have a schedule to be met?

**Comment by lbergelson** [comment]
Thanks for the reply! 

We don't have a specific schedule to meet.  We get hit by the bug fixed in #400 and have to have some awkward work arounds.  I just wanted to ask since there wasn't a release for a long time.  We need an official release so we can lobby our cluster management provider to update their kryo version.  

Next week would be totally fine for us.

**Comment by magro** [comment]
Sorry, I've been busy this week. I'd like to get #433 into the next release, this will take some days to finish - I hope we can have a release around next week. Is this ok for you?

**Comment by lbergelson** [comment]
Yes, thanks, that would be great for us.

**Comment by nkconnor** [comment]
Any updates here? Looking forward to #433 :+1:

**Comment by magro** [comment]
This evening I prepared release notes and final compatibility tests, so
4.0.0 is just around the corner :-)

Nicholas Connor <notifications@github.com> schrieb am Sa., 2. Juli 2016,
00:23:

**Comment by magro** [comment]
We just released kryo 4.0.0...

**Comment by lbergelson** [comment]
That's excellent.  Thank you!
