### ISSUE TITLE
OutOfMemory when deserializing cached data

### ISSUE THREAD

**Issue by szhou1234** [EsotericSoftware/kryo#434]
I got OOM crash when deserializing data on Android. The data was serialized using Kryo. After looking into Kryo implementation, this should be caused by that a wrong char length was deserialized. There is no way my data size is 2843933264 bytes! This only happens with a few users but I cannot reproduce it. Maybe the root cause is data encoding problem when backend sends back the data.

Here is the stacktrace:

> 	java.lang.OutOfMemoryError: Failed to allocate a 2843933264 byte allocation with 16299867 free bytes and 104MB until OOM
	 at com.esotericsoftware.kryo.io.Input.readString(SourceFile:464)
	 at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.read(SourceFile:57)
	 at com.esotericsoftware.kryo.Kryo.readObject(SourceFile:679)
	 at com.esotericsoftware.kryo.serializers.ObjectField.read(SourceFile:106)
	 at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.read(SourceFile:90)
	 at com.esotericsoftware.kryo.Kryo.readObject(SourceFile:657)

>

**Comment by magro** [comment]
Can you get the data that's deserialized when deserialization fails? Perhaps if you know for which user this happened at a certain time you can get hold of the data that must have been serialized, or get it from the OOME'ed process directly?

**Comment by szhou1234** [comment]
Thanks magro for the quick reply. Unfortunately I cannot reproduce the issue after trying the data for some affected users. Is there any other debugging approach for this?

**Comment by magro** [comment]
Not sure about your setup/system, perhaps it's possible to guard deserialization with try/catch(OOME) and send the data (that should be deserialized but failed) to some of your backends for storage + later analysis?

Another option might be to enable trace logging via `Log.TRACE();` (see also [Logging](https://github.com/EsotericSoftware/kryo#logging)).

**Comment by szhou1234** [comment]
One thing to note is that we use SnappyDB, which uses kryo directly. At first I also thought this could be caused by threading issue. Then I ruled it out since all the data read/write operations happen on the main thread. I'll try to get some data before further involving you. Thanks!
