### ISSUE TITLE
Enum inside an object is not serialized

### ISSUE THREAD

**Issue by saravanadharshan** [EsotericSoftware/kryo#436]
Hi,
I'm trying to transfer a object DataTransferObject via object stream using kryo serialization.
The DatatransferObject contains an enum 'DataOutputFlag { SUCCESS, FAILURE;}'
Eventhough all other fields are proper after de-serialization, this enum filed is null at target environment. Is there something I'm missing out. Im quite new to Kryo. Apologies if my question is basic.
Thanks.

**Comment by saravanadharshan** [comment]
Class im trying to serialize `public class DataTransferObject extends HashMap<DataTransferKey, List<? extends DataObjectCommonInterface>> implements Serializable{

	private DataOutputFlag outputFlag;

	public DataOutputFlag getOutputFlag() {
		return outputFlag;
	}

	public void setOutputFlag(DataOutputFlag theOutputFlag) {
		outputFlag = theOutputFlag;
	}

	private String messageKey;
	public String getMessageKey() {
		return messageKey;
	}
	public void setMessageKey(String theMessageKey) {
		// begin-user-code
		messageKey = theMessageKey;
		// end-user-code
	}

	private boolean sessionValid;

	public boolean isSessionValid() {
		return sessionValid;
	}

	public void setSessionValid(boolean sessionValid) {
		this.sessionValid = sessionValid;
	}

	private boolean userValid;

	public boolean isUserValid() {
		return userValid;
	}

	public void setUserValid(boolean userValid) {
		this.userValid = userValid;
	}

	public void addDOs(DataTransferKey transferKey, List<? extends DataObjectCommonInterface> dataObjList) {
		this.put(transferKey, dataObjList);
	}
}`

Enum structure:
`	public enum DataOutputFlag {
		SUCCESS,
		FAILURE;
	}
`

Code for serialization at Servlet:
`
DataTransferObject returnDTO = new DataTransferObject();
returnDTO.setOutputFlag(DataOutputFlag.SUCCESS);
				response.setContentType("application/octet-stream");
				response.encodeURL(request.getRequestURL().toString());
				outputStream = new ObjectOutputStream(response
						.getOutputStream());
				
				kryOutput = new Output(outputStream);
				
				kryoInstance.writeClassAndObject(kryOutput, returnDTO);

				if (outputStream != null) {
					kryOutput.flush();
					kryOutput.close();
				}

`
Code for de-serialization at Client:
`			inputStream = new ObjectInputStream(httpURLConnection
					.getInputStream());
			kryoInput = new Input(inputStream);
			returnDTO = (DataTransferObject)kryoInstance.readClassAndObject(kryoInput);
`

**Comment by NaserAli** [comment]
Assign integer values to the enum class and try.

**Comment by magro** [comment]
Not sure about the usage of ObjectOutput/InputStream here, what do you get with ByteArrayOutput/InputStream?

**Comment by magro** [comment]
Is there still an issue?

**Comment by magro** [comment]
Closed for now, please reopen if still relevant.
