### ISSUE TITLE
Optimizations for common special cases

### ISSUE THREAD

**Issue by manuel-hegner** [EsotericSoftware/kryo#439]
Hey,
you could optimize some common special cases to reduce the number of generated bytes.
The specific idea I had in this direction is improving the CollectionSerializer. Common special cases are a collection of objects of the same type, a collection of objects of the same type without nulls or a collection of nulls. These could all be optimized by storing some metadata with the collection. The same optimizations could also be done for the MapSerializer

I implemented an example code in c19810917fe267f648074121c55c2c23eae6a9bb. It is backwards (but not forwards) compatible by using the sign of the length as a flag for a special case. In non-special cases, or if the metadata is larger than the savings, this generates the same bytecode as the default serializer. Otherwise it writes the metadata byte and if needed/useful the class that all non-null values share.

It reduces the byte size by 2 bytes per element if all elements share the same class, 1 byte if they share a class and some are null (which could be further reduced by writing one null byte only every eight elements). If all elements are null only the length and the metadata byte is written.

Are optimizations (pull requests) like these welcome/useful in Kryo? Or would it be better to write optimizations that are not compatible for the next breaking release? Or did I overlook a disadvantage optimizations like these have?

**Comment by romix** [comment]
It looks pretty interesting! 

As far as I can see, it performs two traversals over the collection. The first pass collects the information about the collection and the second pass actually writes it. At the same time, the new serializer writes less information in many cases, e.g. if all elements are of the same class, etc.   Do you have any data on the performance of your serializer?  We care a lot about the speed of serialization and deserialization.

**Comment by manuel-hegner** [comment]
Yeah, it has to do two traversals. But the first meta information gathering traversal can be stopped as soon as it is clear that the collection is no special case. I created a simple  benchmark 8949fb1bbd217a997269b8edeedef93fe4263966 to test the speed. In my benchmark (default kryo, output delegates to default ByteArrayOutputStream) the extra cost of the traversal was small if the collection was large enough. The results for smaller collection sizes were erratic. The format is space required / time required compared to the normal CollectionSerialization. The interesting columns for the speed are the two MIXED_CLASSES columns. Those are the cases that in the end serialize the same way as before.

My results:

| List Size | SAME_CLASS_NO_NULL | SAME_CLASS_NULL | MIXED_CLASS_NO_NULL | MIXED_CLASS_NULL | ONLY_NULL |
| ---: | ---: | ---: | ---: | ---: | ---: |
| 1 | 0% / -31% | 0% / 4% | 0% / 97% | 0% / -2% | 0% / -59% |
| 2 | 0% / 4% | 0% / 0% | 0% / 33% | 0% / -8% | 0% / 21% |
| 3 | 0% / -3% | 0% / -8% | 0% / 1% | 0% / -1% | 0% / -5% |
| 4 | -2% / 19% | 0% / 1% | 0% / -37% | 0% / -1% | 0% / 44% |
| 5 | -4% / 23% | 0% / -20% | 0% / -1% | 0% / 2% | 0% / -2% |
| 6 | -6% / -15% | 0% / -20% | 0% / 0% | 0% / -3% | -13% / -13% |
| 7 | -7% / 9% | 0% / -1% | 0% / 43% | 0% / 26% | -23% / 11% |
| 8 | -9% / 73% | -2% / 56% | 0% / -1% | 0% / -1% | -30% / -70% |
| 9 | -10% / 13% | -4% / 28% | 0% / 4% | 0% / 0% | -37% / 0% |
| 10 | -12% / 11% | -3% / 32% | 0% / -30% | 0% / 1% | -42% / -4% |
| 100 | -38% / 6% | -28% / 30% | 0% / 4% | 0% / 3% | -94% / -65% |
| 1000 | -40% / -28% | -33% / -23% | 0% / -10% | 0% / -3% | -100% / -79% |
| 10000 | -39% / -29% | -33% / -24% | 0% / 0% | 0% / -1% | -100% / -82% |
| 10000 | -39% / -25% | -33% / -23% | 0% / -1% | 0% / -1% | -100% / -83% |
| 100000 | -34% / -23% | -29% / -18% | 0% / -4% | 0% / -4% | -100% / -81% |

If you have any tips how to improve the benchmark please let me know. It bugs me a little that it behaves so erraticly.

**Comment by romix** [comment]
BTW, have you seen the `setElementClass` and `setElementsCanBeNull` methods of the original Collection serializer? They serve essentially the same role. The major difference from your approach is that these two methods are not so dynamic. They are typically not meant to be invoked per instance of a collection. Instead, they are supposed to be used when you know that a given field of a collection type will always have elements of the same type or it will always have only non-null elements. You approach does essentially the same, but on a per-instance basis.

**Comment by romix** [comment]
As for the benchmark results: You can try to run multiple rounds. I.e. run the whole thing for all sizes and then do it again and again. I suspect that for small sizes, the JIT was not kicking in or something like that. IIRC, JIT kicks in after 10000 invocations of method (with default settings).

Use first (couple of) rounds to "wam-up" the JIT. And only then perform a measurement. 

Also, I'd get rid of calling `new ByteArrayOutputStream();` in `getObjectBytes` on the hot path, because doing memory allocations on the hot path is not the best idea. May be you can try to allocate the buffer in advance (as byte[]?) and then simply reuse it on each operation? I.e. you can create a new `Output` stream and provide this byte array as the buffer? Also, you probably can get rid of `baos.toByteArray()` because it will create a new byte array.  Instead, you can return the original pre-allocated byte array used as a buffer and the size of the serialized data and use it to initialize the new `Input` stream.

**Comment by romix** [comment]
@magro Assuming that benchmarking shows no negative performance impacts and reasonable size improvements, do you think we should include a polished version of this PR into 4.0.0? IIUC, it would break the format, so it could be a good idea to include it together with other format breaking changes. WDYT?

By polished version I mean a version that would have e.g. the following features:
- API to disable this optimization. If it is disabled, it won't perform a preparation pass to collect information about the concrete instance of a collection and thus it would assume that it may contain nulls and may have elements of different classes. I.e. it would be equivalent to what we use today by default.
- Using a proper encoding instead of "misusing" the negative value as an indication of using the optimized encoding.

**Comment by manuel-hegner** [comment]
Okay, so I did a real benchmarking with JMH with everything but the call to the write method packed in the setupt method. This shows that the slow down due to the extra iteration over the collection is in the worst case (all same class not null except last element) still within the margin of error. In the special cases it is always faster or as fast as the classical serialization. The size improvement is, as stated, one or two bytes per element.

I would want to say in favour of such imrovements: While they may only cover special cases, these special cases can be very common. I would argue that having a collection of elements of the same type is a very common usecase.

While I would also like to have this properly encoded I would hate for such improvements to make the general case larger and I don't see another way to encode this properly. There could be a writeVarInt method that uses one bit for the meta information flag and uses the other 7 bits for the number. This is maybe also helpful in other cases. Otherwise every collection has one byte for metainformation.

If we are talking about breaking improvements I think we could find a lot more ideas that could improve the bytecode. For example in the known-type-case bytecode could be improved by using one byte to mark the nullness of 8 objects instead of just one. And this would even work without the extraiteration. The same thing could be done for maps and we can probably find more ideas for other serializers.

**Comment by magro** [comment]
Regarding inclusion in 4.0, what do you think about the option to provide the new optimization optionally and keep the existing format as default? This way we could take time as needed for the optimizations.

**Comment by romix** [comment]
@magro Yeah, it would buy us some time. So, may be it is a safer approach.

**Comment by manuel-hegner** [comment]
So I started implementing a clean approach with an optional switch to the breaking format. Now I asked myself what is the best way to implement the flag, if there are metainformation. Spending a whoe byte on each collection seems like a waste to me, so I would like to only add a bit. But maybe I am overengineering this.
Two 1-bit solutions I see:

- Add a writeFlagAndVarInt method to output, that uses one bit for the flag. This would be fast and easy to implement but not that clean.
- Expand output/input by methods that allow to write out of byte alignment. Variable encodings and booleans would be made smaller by that. It would be a bit slower, because Output would write to a BitSet first and then to the buffer. This would be a cleaner approach though.

What do you think? Which version do you prefer, or should I simply write the meta byte in any case? Or do you have a better idea?

**Comment by romix** [comment]
IMHO, write out of a byte alignment would introduce a lot of performance issues and other headaches for us. It would become very difficult to skip some fields/objects, etc.

**Comment by manuel-hegner** [comment]
So I have finally some time again and created a clean implementation for the improved collection serializer. You can find it in 7532d90. Could you look into it if this solution and the implementation is okay. If it is I would like to contribute similar improvements for other serializers in the same style before making a pull request out of it.

**Comment by NathanSweet** [comment]
I like the ideas here. The approach in your last post has 2 downsides:

1) varint normally stores 128 values (7 bits) in 1 byte. Adding bit flags of course causes varint to use more bytes sooner. For 1, 2, or 3 flags varint can store 64, 32, or 16 values in the first byte. Using more than 3 bits for flags increases varint from1-5 bytes to 1-6 bytes (or more), which is probably not great.

2) An extra byte is written when the flag is true.

So while it is 1 extra byte, it also costs an additional byte for collections sized >= 64 and < 128. Given that the savings are large when the special cases occur AND that special cases are relatively common, it could be worthwhile.

Another approach could be to use a special length value (anything that fits in 1 varint byte, eg 127). If the length is that value, then read another varint for the length, then a byte for the extra metadata. This has less impact when the metadata is not needed, but is sure to use ~2 bytes when it is. If the metadata was not needed very often, this might be better.

All null collections are written as a zero per item, so RLE or any type of compression would do well. While it's always nice to avoid work entirely when possible, all null collections are probably not terribly common. Most useful are knowing if "items are the same type" and if "no elements are null":

1) If all items are the same type and no elements are null, then we save a varint (1+ byte) per item.
2) If all items are the same type and some elements are null, we save a varint per item only if the serializer accepts null.
3) If all items are not the same type and no elements are null, we don't save any bytes.
4) If all items are not the same type and some elements are null, we don't save any bytes.

If we only support number 1, then we could get away with just 1 bit flag. If we want numbers 1 and 2 we could do 2 bit flags or write an extra byte. If we write an extra byte, we have room for more optimizations. We could use a flag for number 1, then only read another byte if the serializer accepts null. That seems best.
