### ISSUE TITLE
TaggedFieldSerializer tag values cannot overlap those of superclass

### ISSUE THREAD

**Issue by cypherdare** [EsotericSoftware/kryo#440]
It's not immediately clear that you cannot tag a field with the same number as a tagged field in a superclass. And even if one is aware of this requirement, we must be very vigilant about checking class hierarchies for the possible clashes. I'm suggesting that during serialization, TaggedFieldSerializer could check for tag value clashes in the hierarchy and throw an error if any exist.

On a related note, it might also be nice if superclasses are checked for complete omission of tags and a warning shown if they don't have any.

**Comment by magro** [comment]
Sounds good! For the second case perhaps one might also want to force an exception, not sure. Do you want to submit a pull request (or 2)?
Btw, what happens in the first case?

**Comment by cypherdare** [comment]
I'll give it a shot when I have some free time. It looks like for the first issue, we don't need to look at class hierarchy...we only need to check for any reused tag values since that's all the problem really is.

During serialization, TaggedFieldSerializer makes no complaints. I haven't dug into what is actually happening, but in my case, I got a ClassNotFoundException during deserialization because a class name was corrupted.

For the second case, I don't know if an exception is right because there are possible (rare) cases where you might want to omit all the fields of a superclass.

**Comment by magro** [comment]
Ok, great. Regarding the second case I meant that we add a switch to choose between warning and exception.

**Comment by cypherdare** [comment]
I have an idea for how to do the second case. But I'm not sure if the warning should only be shown at the TRACE or DEBUG log level. Is there already a precedent for warnings like this?

I suppose the option to throw an error could go into TaggedFieldSerializerConfig, if we need that. However, I'm thinking that if someone knows enough about this issue to turn the setting on, they'd already know to be checking the logs during testing.

**Comment by magro** [comment]
Perhaps we can allow to choose from throw exception, warn and debug?

**Comment by NathanSweet** [comment]
Less configuration is always better, if it can be avoided. If we aren't sure, avoid it.

I'm not sure the warning makes sense though. It could be fine that a super class has no tags, otherwise it is likely it would be discovered quickly. If you'd like to add it, I'd choose TRACE. I'll close this issue, feel free to submit a PR.
