### ISSUE TITLE
what's the liscene of the library?

### ISSUE THREAD

**Issue by jiqimaogou** [EsotericSoftware/kryo#446]
BSD?

**Comment by magro** [comment]
Right, see also license.txt and pom.xml.

**Comment by richardfontana** [comment]
I just noticed that two source files have Apache License 2.0 notices though they contain @author tags indicating Nathan Sweet:  
[IdentityMap.java](https://github.com/EsotericSoftware/kryo/blob/master/src/com/esotericsoftware/kryo/util/IdentityMap.java)
[IntMap.java](https://github.com/EsotericSoftware/kryo/blob/master/src/com/esotericsoftware/kryo/util/IntMap.java)
Is this an error, or are these files taken from some other project? There is also a reference to an AUTHORS file which I believe is not present.

**Comment by magro** [comment]
@NathanSweet Can you comment on this?

**Comment by NathanSweet** [comment]
The comment headers are wrong, I will fix them in a commit soon. The code was ported from libgdx and I have the copyrights.

@magro Related, I see some files have your copyright notice on them. This may make it awkward to respect the BSD license. I think we should have a single copyright header for all files. We could use my name, Esoteric Software LLC, or a list of names if you'd like your name there. Or maybe better, we could use `Copyright (c) 2016, See AUTHORS file` ala [libgdx](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/Gdx.java#L2). libgdx has almost ~400 contributors but the AUTHORS file isn't a place for every contributor (it lists only 2). In fact, contributors of any significant portion of the Kryo codebase should really be signing a [CLA](https://github.com/libgdx/libgdx/blob/master/CLA.txt) so the ownership of the source cannot be questioned.

**Comment by magro** [comment]
I don't need to see my name anywhere, not sure about others. 
A CLA in fact would make sense, but then it should be easy, i.e online signing should be possible (e.g via https://cla-assistant.io/). Probably existing contributors would have to sign as well, right?

**Comment by NathanSweet** [comment]
Copyright headers are up to date in kryo-5.0.0-dev branch.
