### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by kapodes** [EsotericSoftware/kryo#448]
Hello. I've seen similar issues buy didn't find a solution. I started to use Kryo and was impressed by it's speed. But right now i have this error while trying to serializa a very large object. My Kryo version is 4.0. Full stack trace is:

```
Exception in thread "" 
java.lang.ArrayIndexOutOfBoundsException: 33554431
	at com.esotericsoftware.kryo.util.IdentityObjectIntMap.clear(IdentityObjectIntMap.java:466)
	at com.esotericsoftware.kryo.util.MapReferenceResolver.reset(MapReferenceResolver.java:65)
	at com.esotericsoftware.kryo.Kryo.reset(Kryo.java:888)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:559)
```

My serialize method:     

```
private void serializeCache() {
        File cache = new File(baseDir.getPath() + "\\cache.ser");

        try (FileOutputStream outputStream = new FileOutputStream(cache)) {
            Kryo serializer = new Kryo();
            Output serOutput = new Output(outputStream);
            serializer.writeObject(serOutput, quoteLists);
            outputStream.flush();
            serOutput.close();
        } catch (IOException e) {
            e.printStackTrace();
            System.out.println("Failed to serialize cache");
        }
   }
```

Object is ArrayList<HistoryStockQuote>[] quoteLists;

Classed that are serialized:

```
public class HistoryStockQuote extends StockQuote implements Serializable {
    private static final long serialVersionUID = 1L;
    private String ticker;
    private BigDecimal bid, ask;
    private Date date;
    private LastTradeQuote lastTrade;
```

```
public class LastTradeQuote implements Serializable{
    private static final long serialVersionUID = 1L;
    private BigDecimal price;
    private long volume;
    private long orderId;
    private boolean isBuy;
    private Date date;
```

Serialized object is about 1.5Gb in total. When it was about couple hundred gigs everything was just fine.

**Comment by magro** [comment]
Can you provide a self contained test case that allows to reproduce the issue?

**Comment by kapodes** [comment]
I figured out the problem. Actually my object was bigger than i expected and just didn't fit in memory. So if you have this exception with large objects, try increasing Max Heap size and see if problem goes away. Seems that sometimes we get this exception faster than Out Of Memory but the cause is the same.

**Comment by izhaknys** [comment]
@kapodes 

Having similar issue, could you advice which Max Heap Size you have tweaked?

**Comment by kapodes** [comment]
Standart JVM option "java -Xmx3000m" for 3 GB

**Comment by izhaknys** [comment]
Didn't work for me.
