### ISSUE TITLE
Provide kryo-scala artifact with scala serializers

### ISSUE THREAD

**Issue by magro** [EsotericSoftware/kryo#452]
Kryo should publish an artifact with serializers for standard scala classes. This could then be used by chill and akka-kryo-serialization. Serializers could probably be taken from both projects (retaining the existing copyright headers).

The artifact should be published for the 2 latest scala versions. While akka-kryo-serialization uses only 2.11, chill is published for 2.10 as well. Publishing for 2.12 already would also be nice. The build should be integrated in the existing maven build.

**Comment by magro** [comment]
The idea was to consolidate things for the scala world.

**Comment by NathanSweet** [comment]
I think it's better to break up the maintenance burden into separate projects, especially since I don't personally use Scala and would not be able to support or maintain it.
