### ISSUE TITLE
InputChunked throws if first length of fill() is 0

### ISSUE THREAD

**Issue by llowrey** [EsotericSoftware/kryo#458]
``` java
if (chunkSize == -1) // No current chunk, expect a new chunk.
    readChunkSize();
else if (chunkSize == 0) // End of chunks.
    return -1;
```

That 'else if' should be just 'if' because readChunkSize() could return 0.

**Comment by magro** [comment]
A pull request with the fix and a unit test that shows the issue would be awesome! :-)

**Comment by NathanSweet** [comment]
1) `readChunkSize` returns void.
2) chunkSize is always -1 after `readChunkSize`.
3) All issues need reproduction code.
