### ISSUE TITLE
IncompatibleClassChangeError: Found interface org.objectweb.asm.MethodVisitor, but class was expected

### ISSUE THREAD

**Issue by maxio89** [EsotericSoftware/kryo#460]
Guys,

Could you advise why below error could possibly happen? 

`java.lang.IncompatibleClassChangeError: Found interface org.objectweb.asm.MethodVisitor, but class was expected
    at com.esotericsoftware.reflectasm.ConstructorAccess.insertConstructor(ConstructorAccess.java:128)
    at com.esotericsoftware.reflectasm.ConstructorAccess.get(ConstructorAccess.java:98)`

We got rid of all old versions of asm from our classpath, but it didn't help, so this command return nothing right now:
mvn dependency:tree -Dverbose -Dincludes=asm
Before we used old version of cxf which depends on asm.asm 3.3.1 and I read that it could be a problem here, because in all asm versions before 4.0. MethodVisitor was an interface and not class. 

Our project has a lot of libraries on classpath, including apache cxf or some other with their own implementation of asm, so it's hard to track and validate all dependencies without knowing where exactly problem lies.

Generally we try to use Kryo in serialization of our Tomcat session, to save it in Redis with Spring Session.
We tried with Jackson, but we did encounter some problems, like low performance, map serializations etc.

Below you can find snippet of our pom which shows which exactly versions we use.

`````` <dependency>
      <groupId>org.springframework.session</groupId>
      <artifactId>spring-session-data-redis</artifactId>
      <version>1.2.2.RELEASE</version>
      <type>pom</type>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-web</artifactId>
      <version>4.2.0.RELEASE</version>
    </dependency>
    <dependency>
      <groupId>com.esotericsoftware</groupId>
      <artifactId>kryo</artifactId>
      <version>4.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.tomcat</groupId>
      <artifactId>tomcat-catalina</artifactId>
      <version>8.5.4</version>
      <scope>provided</scope>
    </dependency>```

I thought that adding below change something, but nothing has changed.

    ```<dependency>
      <groupId>org.ow2.asm</groupId>
      <artifactId>asm</artifactId>
      <version>5.0.4</version>
    </dependency>
    <dependency>
      <groupId>com.esotericsoftware</groupId>
      <artifactId>reflectasm</artifactId>
      <version>1.11.3</version>
    </dependency>```
``````

**Comment by magro** [comment]
Can we close this issue?

**Comment by maxio89** [comment]
Yes, of course. Thanks for help.
