### ISSUE TITLE
Arrays.asList is not serialized correctly : it throws NullPointerException

### ISSUE THREAD

**Issue by bkuchcik** [EsotericSoftware/kryo#461]
With the kryo version 4.0.0, I wrote this test :

`public class ArraysAsListKryoUnserializeTest {

```
private Kryo kryo;

@Before
public void before() {
    kryo = new Kryo();
    kryo.setStreamFactory(new FastestStreamFactory());
    kryo.setInstantiatorStrategy(new DefaultInstantiatorStrategy(new StdInstantiatorStrategy()));
}

// NullPointerException is raised when collection serializer tries to use size() method
// of Arrays.asList(). As you can see Arrays.asList() is a specific implementation named
// Arrays.ArrayList !
@Test(expected = NullPointerException.class)
public void kryoSerializeDoesNotWorkWhenSerializingArraysAsList() {
    kryo.copy(Arrays.asList("a", "b", "c"));
}

@Test
public void kryoSerializeWorksWithFieldSerializerInseadOfCollectionSeralizerForArraysAsList() {
    final Class<?> arraysAsListClass = Arrays.asList().getClass();
    kryo.addDefaultSerializer(arraysAsListClass, new FieldSerializer<T>(this.kryo, arraysAsListClass));
    Assert.assertEquals(Arrays.asList("a", "b", "c"), kryo.copy(Arrays.asList("a", "b", "c")));
}
```

}`

**Comment by bkuchcik** [comment]
I found similar issues with all Collections.unmodifiable() :+1: 
- Collections.unmodifiableCollection()
- Collections.unmodifiableList()
- Collections.unmodifiableSet()
- Collections.unmodifiableSortedSet()
- Collections.unmodifiableMap()
- Collections.unmodifiableSortedMap()

**Comment by romix** [comment]
You may want to have a look at https://github.com/magro/kryo-serializers

**Comment by reda-alaoui** [comment]
Hello,

Why magro serializers are not part of kryo core?

**Comment by magro** [comment]
@reda-alaoui this is tracked with #151. Regarding the ArraysAsListSerialiser: this is not included by default because it uses unsafe (reflection based) access to the underlying list, which could break on jvms that we don't have in our CI setup. So right now kryo provides only serializers based on the public api of the jdk. We could of course rethink this decision, I suggested this once in #376.
