### ISSUE TITLE
Wrong byte order if the ByteBuffer of the ByteBufferOutput has to grow during writeVarInt / writeVarLong

### ISSUE THREAD

**Issue by ahilsend** [EsotericSoftware/kryo#464]
Growing the ByteBuffer while writing varInt or varLong will change the byte order first, and then perform the require.

If the ByteBuffer needs to grow the setBuffer will again change the ByteOrder, but this time the one set by the varInt method. Thus the final ByteOrder was incorrect.

**Comment by magro** [comment]
Closed with #465
