### ISSUE TITLE
Serialization bug for doubles

### ISSUE THREAD

**Issue by pemadeep** [EsotericSoftware/kryo#468]
Hi,

I am using **com.esotericsoftware:kryo-shaded:4.0.0**.

I found a suble bug when serializing doubles.  When providing a ByteBuffers with BIG_ENDIAN byte order, the serialization fails.  

When writing a long, the byte order is set to to LITTLE_ENDIAN first and then is set back to BIG_ENDIAN (see ByteBufferOutput:622).  

This logic fails when the byte buffer needs to be expanded just before writing the long (see ByteBufferOutput:217).

Find the code below, that I used to reproduce this bug.

To get around this bug, I had to change all our ByteBuffers to use LITTLE_ENDIAN by default.

Regards,
Pemadeep
pemadeep.ramsokul@imc.com

---

import com.google.common.collect.ImmutableList;
import com.google.common.collect.Lists;
import com.google.common.io.BaseEncoding;
import org.assertj.core.data.Offset;
import org.objenesis.strategy.StdInstantiatorStrategy;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.util.ArrayList;
import java.util.List;

import static com.google.common.collect.Sets.newHashSet;
import static com.imc.analysis.core.shared.serialization.KryoFactory.noCaching;
import static org.assertj.core.api.Assertions.assertThat;

 @Test
    public void shouldEncodeAndDecodeDoubleValues() {
        final byte[] myFillerBytes = new byte[3990];
        final Payload myPayload = new Payload(5L, Lists.newArrayList(myFillerBytes, 123456789L, 2.0));
        final byte[] mySerialize = newKryoSerializer().serialize(myPayload);

```
    final Payload myDeserialize = (Payload) newKryoSerializer().deserialize(mySerialize);
    assertThat(myDeserialize.theUnprocessedList.get(1)).isEqualTo(123456789L);
    assertThat(myDeserialize.theUnprocessedList.get(2)).isEqualTo(2.0);
}

public static class Payload {

    private final long theTimestamp;
    private final List<Object> theUnprocessedList;

    public Payload(long aTimestamp, List<Object> aObjects) {
        theTimestamp = aTimestamp;
        theUnprocessedList = aObjects;
    }
}

private KryoSerializer newKryoSerializer() {
    final Kryo myKryo = new Kryo();
    myKryo.setInstantiatorStrategy(new Kryo.DefaultInstantiatorStrategy(new StdInstantiatorStrategy()));

    final FieldSerializerConfig mySerializerConfig = myKryo.getFieldSerializerConfig();
    mySerializerConfig.setUseAsm(true);
    return new KryoSerializer(myKryo);
}
```

---

import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.io.ByteBufferInput;
import com.esotericsoftware.kryo.io.ByteBufferOutput;
import com.esotericsoftware.kryo.io.Input;
import com.esotericsoftware.kryo.io.Output;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class KryoSerializer extends ByteSerializer {
    private static final Logger LOGGER = LoggerFactory.getLogger(KryoSerializer.class);
    private static final ByteOrder DEFAULT_BYTE_ORDER = ByteOrder.BIG_ENDIAN;

```
private final Kryo theKryo;

public KryoSerializer(Kryo aKryo) {
    theKryo = aKryo;
}

@Override
public synchronized byte[] serialize(Object aWrite) {
    try (final Output myOutput = newOutput()) {
        theKryo.writeClassAndObject(myOutput, aWrite);
        myOutput.flush();
        return myOutput.toBytes();
    } catch (final Throwable myException) {
        LOGGER.warn("Couldn't serialize {}.", aWrite, myException);
    }
    return new byte[0];
}

private ByteBufferOutput newOutput() {
    final ByteBuffer myBuffer = ByteBuffer.allocate(4096);
    myBuffer.order(DEFAULT_BYTE_ORDER);
    return new ByteBufferOutput(myBuffer, -1);
}

@Override
public synchronized Object deserialize(byte[] aBytes) {
    try (final Input myInput = newInput(aBytes)) {
        final Object myObject = theKryo.readClassAndObject(myInput);
        LOGGER.trace("Deserialized: {}", myObject);
        return myObject;
    } catch (final Throwable myException) {
        LOGGER.warn("Couldn't deserialize.", myException);
    }
    return new Object();
}

private ByteBufferInput newInput(byte[] aBytes) {
    final ByteBuffer myBuffer = ByteBuffer.wrap(aBytes);
    myBuffer.order(DEFAULT_BYTE_ORDER);
    return new ByteBufferInput(myBuffer);
}
```

}

**Comment by NathanSweet** [comment]
ByteBuffer output/input not longer relies on byte order in the kryo-5.0.0-dev branch.
