### ISSUE TITLE
com.esotericsoftware.kryo.KryoException: java.lang.IndexOutOfBoundsException: Index: 199999998, Size: 1

### ISSUE THREAD

**Issue by Bogon** [EsotericSoftware/kryo#471]
com.esotericsoftware.kryo.KryoException: java.lang.IndexOutOfBoundsException: Index: 199999998, Size: 1

Excuse me, what is the problem, how to solve it?

**Comment by magro** [comment]
How to reproduce it?

**Comment by Bogon** [comment]
Jar packet collision
