### ISSUE TITLE
Handle class changes?

### ISSUE THREAD

**Issue by kmtong** [EsotericSoftware/kryo#473]
The problem may not be related to Kryo itself, but more of the usage scenario.

We have serialized some objects of class A and persisted in some message queue.
When class A needs to be changed (say adding some fields), then reading back the old message fails.

Are there any suggestions to handle it (in Kryo or some other ways)

**Comment by magro** [comment]
@kmtong You should read the [section about compatibility](https://github.com/EsotericSoftware/kryo#compatibility) in the README and decide what's most appropriate according to your requirements.
