### ISSUE TITLE
Kryo throwing “ Encountered unregistered class ID: 44”

### ISSUE THREAD

**Issue by Raycoms** [EsotericSoftware/kryo#475]
But I registered the classes I am going to serialize.

More here:

https://stackoverflow.com/questions/40342996/kryo-throwing-encountered-unregistered-class-id-44

**Comment by magro** [comment]
Is this still an issue for you? If so, can you provide a self contained test case that allows to reproduce the issue?

**Comment by Raycoms** [comment]
Resolved it. Thanks.

Problem was that I was feeding a different type of map without noticing.

2016-12-28 16:29 GMT-02:00 Martin Grotzke <notifications@github.com>:

**Comment by magro** [comment]
Good to hear that you solved it!
