### ISSUE TITLE
Buffer underflow exception when reading

### ISSUE THREAD

**Issue by mtdaleiden** [EsotericSoftware/kryo#478]
We are using Kryo to serialize/deserialize a complex object graph. The serialized data is stored as a Base64-encoded string in a database table:
```
ByteArrayOutputStream baos = new ByteArrayOutputStream();
Output output = new Output(baos);
kryo.writeObject(output, event);
output.flush();
output.close();
String dbString = Base64.getEncoder().encodeToString(baos.toByteArray());
       ... code to store dbString in database...
```
When we try to deserialize this data again after fetching it from the database, it fails with a `Error: com.esotericsoftware.kryo.KryoException: Buffer underflow.` error:
```
String base64EventData = ...from database record...
ByteArrayInputStream bais = new ByteArrayInputStream(Base64.getDecoder().decode(base64EventData));
Input input = new Input(bais);
ContextualizedEvent c = kryo.readObject(input, ContextualizedEvent.class); <== fails here with underflow
input.close();
bais.close();
return c;
```
Both the writer and reader are using identically constructed instances of Kryo:
```
Kryo kryo = new Kryo();
kryo.setInstantiatorStrategy(new DefaultInstantiatorStrategy(new StdInstantiatorStrategy()));
kryo.register(JsonNode.class, new JsonNodeSerializer(), 88888);
kryo.register(JsonNode.class, new JsonNodeSerializer(), 99999);
return kryo;
```
Any guidance you can provide on this would be greatly appreciated, as we are under extreme pressure to get this solution working.

**Comment by mtdaleiden** [comment]
[EventData.txt](https://github.com/EsotericSoftware/kryo/files/589986/EventData.txt)
Not sure if this is helpful or not, but this is one example of Base64 data that fails when converted to a byte array input stream and then deserialization is attempted.

**Comment by magro** [comment]
It's important to reproduce the full roundtrip, so can you provide a self contained reproducable example?

**Comment by mtdaleiden** [comment]
Let me see what I can do.

**Comment by magro** [comment]
Btw, why do you register `JsonNode.class` twice,  with different ids? This shouldn't cause the issue however.

**Comment by mtdaleiden** [comment]
Closing this issue as it turned out that there was a logic bug causing incomplete data to be written to the database table.

**Comment by magro** [comment]
@mtdaleiden Great you found it!
