### ISSUE TITLE
Not Serializing Class Names Properly.

### ISSUE THREAD

**Issue by Valdearg20** [EsotericSoftware/kryo#481]
When trying to serialize some fields inside of a domain object, it appears that the serialization process for the class names is getting the final character cut off. When trying to deserialize, it throws a ClassNotFoundException because it cannot find the class name in the classloader. This is occurring in a single threaded Unit Test, so there aren't any concurrency issues in play here.

I believe I've found the potential issue in the code when debugging it. 

I'm using the Kryo version 4.0.0 from Maven.

Output.java - Line 353 
if (ascii) {
	if (capacity - position < charCount)
		writeAscii_slow(value, charCount);
	else {
		value.getBytes(0, charCount, buffer, position);
		position += charCount;
	}

	buffer[position - 1] |= 0x80;     <------- The class name properly loads into the buffer until this line.
} else { 
    ....

It appears that "buffer[position - 1] |= 0x80" is modifying the final byte of the class name in the buffer, which is causing the deserializer to fail to find the required class  when it tries to read the object.

**Comment by magro** [comment]
@Valdearg20 can you please share the unit test that demonstrates the issue?

**Comment by NathanSweet** [comment]
The buffer is no longer modified in the kryo-5.0.0-dev branch. Otherwise, we need reproduction code.
