### ISSUE TITLE
kryo input class require method issues  (buffer underflow)

### ISSUE THREAD

**Issue by ToniYang** [EsotericSoftware/kryo#485]
int remaining = limit - position;
		if (remaining >= required) return remaining;
		if (required > capacity) throw new KryoException("Buffer too small: capacity: " + capacity + ", required: " + required);

		int count;
		// Try to fill the buffer.
		if (remaining > 0) {
			count = fill(buffer, limit, capacity - limit);
			if (count == -1) throw new KryoException("Buffer underflow.");
			remaining += count;
			if (remaining >= required) {
				limit += count;
				return remaining;
			}
		}

when remainning is 1,but require is 2 case kryo exception.
capacity is 4096 and limit is 4096 and position is 4095

Any solutions?

**Comment by ToniYang** [comment]
This may be not an issue,because when I used BZip2CompressorInputStream ,when call method read(byte[],offset,length) in BZip2CompressorInputStream,it implemented that when read length is 0,return -1;this may BZip2CompressorInputStream's bug.

but why need to read zero byte from inputstream? I am thinking this code can be better,if read lenght is 0,there is no need to read.

**Comment by magro** [comment]
@ToniYang if you think there's an issue in kryo can you provide a test case that demonstrates it? Otherwise I think we can can close this one.

**Comment by magro** [comment]
Closing for now, please reopen if necessary.
