### ISSUE TITLE
NPE at com.esotericsoftware.kryo.Kryo.readObject using with Apache Flink

### ISSUE THREAD

**Issue by sohimankotia** [EsotericSoftware/kryo#487]
Hi, 

I am using Flink and custom kryo for my pojo class . But getting 

`Caused by: java.lang.NullPointerException
	at MyTreeSerializer.read(MyTreeSerializer.java:36)
	at MyTreeSerializer.read(MyTreeSerializer.java:11)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:657)
	at org.apache.flink.api.java.typeutils.runtime.kryo.KryoSerializer.copy(KryoSerializer.java:172)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:414)
	... 16 more`

Here are details -

1. **Kryo 2.24.0**

2. **My Pojo Class** 

```
public class MyTree extends TreeMap<String, Object> {

	private String id;
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
}
```

3. **Serializer For Pojo** 

```
import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.Serializer;
import com.esotericsoftware.kryo.io.Input;
import com.esotericsoftware.kryo.io.Output;
import com.esotericsoftware.kryo.serializers.MapSerializer;


public class MyTreeSerializer extends Serializer<MyTree> {


	public MyTreeSerializer() {
	}


	@Override
	public void write(Kryo kryo, Output output, MyTree object) {
		output.writeString(object.getId());
		kryo.writeObject(output, object, new MapSerializer());

	}

	@Override
	public MyTree read(Kryo kryo, Input input, Class<MyTree> type) {
		String id = input.readString();
		System.out.println("Serialized Id " + id);
		MyTree myTree = kryo.readObject(input, type, new MapSerializer());
		System.out.println("Serialized Object " + myTree);
		myTree.setId(id);
		return myTree;
	}
}


```

4. **Flink Streaming Main Program** 

```

import org.apache.flink.api.common.functions.MapFunction;
import org.apache.flink.streaming.api.datastream.DataStream;
import org.apache.flink.streaming.api.datastream.DataStreamSource;
import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment;
import org.apache.flink.streaming.api.functions.sink.SinkFunction;


public class MultiSinkTest {

	public static void main(String[] args) throws Exception {

		StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
		env.setParallelism(1);

		// Setting Serializer
		env.getConfig().addDefaultKryoSerializer(MyTree.class, MyTreeSerializer.class);

		DataStreamSource<String> data = env.fromElements("1", "2");

		DataStream<MyTree> returns = data.map(new MapFunction<String, MyTree>() {
			@Override
			public MyTree map(String s) throws Exception {
				MyTree myTree = new MyTree();
				myTree.setId(s);
				myTree.put("name", "sohi");
				return myTree;
			}
		}).returns(MyTree.class);


		returns.addSink(new SinkFunction<MyTree>() {
			@Override
			public void invoke(MyTree myTree) throws Exception {
				System.out.println("==> " + myTree.toString());
			}
		});

		env.execute();
	}
}
```

#### By using all code mentioned only id is getting serialized not the map part of MyTree .

**But If I replace** 

```
env.getConfig().addDefaultKryoSerializer(MyTree.class, MyTreeSerializer.class);
```
**with**

```
env.getConfig().addDefaultKryoSerializer(MyTree.class, MapSerializer.class);

```

**then** id is not serialized but map is getting serialized .

Just need help why it is not working when using **MyTreeSerializer.class**.

Thanks in advance .

**Comment by magro** [comment]
Can you try the kryo TreeMapSerializer, perhaps extend it? https://github.com/EsotericSoftware/kryo/blob/master/test/com/esotericsoftware/kryo/MapSerializerTest.java tests a fairly similar case.

**Comment by sohimankotia** [comment]
Thanks for reply magro . Just wondering how would **id** field will be serialized if I extend TreeMapSerializer .

**Comment by magro** [comment]
You'd write/read the id and delegate writing/reading reading of the treemap to "super". Instead of inheritance you could also use delegation.

**Comment by sohimankotia** [comment]
I tried 

```
public class MyTreeSer2 extends DefaultSerializers.TreeMapSerializer {

	public void write(Kryo kryo, Output output, MyTree map) {
		output.writeString(map.getId());
		super.write(kryo, output, map);
	}


	@Override
	public MyTree read(Kryo kryo, Input input, Class<Map> type) {
		String id = input.readString();
		Map map = super.read(kryo, input, type);

		MyTree mt = new MyTree();
		mt.putAll(map);
		mt.setId(id);
		return mt;
	}
}

```

 Kryo is not even running it  . when using 


`env.getConfig().addDefaultKryoSerializer(MyTree.class, MyTreeSer2.class);`

**Comment by magro** [comment]
You should have a look at how the `TreeMapSerializer` works. So your `MyTree` must define a constructor accepting a `Comparator`. Then the following should work:

```
	@Override
	public void write(Kryo kryo, Output output, TreeMap map) {
		super.write(kryo, output, map);
		output.writeString(((MyTree)map).getId());
	}
	
	@Override
	public MyTree read(Kryo kryo, Input input, Class<Map> type) {
		MyTree map = (MyTree)super.read(kryo, input, type);
		map.setId(input.readString());
		return map;
	}
```

**Comment by magro** [comment]
Is this still relevant, or can we close this issue?

**Comment by sohimankotia** [comment]
Hi Martin ,

You can close it.

Thanks and Regards
Sohanvir

On 14-Jul-2017 1:06 AM, "Martin Grotzke" <notifications@github.com> wrote:

Is this still relevant, or can we close this issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/EsotericSoftware/kryo/issues/487#issuecomment-315180024>,
or mute the thread
