### ISSUE TITLE
deserialize for class has two field with same name but not same type failed

### ISSUE THREAD

**Issue by z3ronp** [EsotericSoftware/kryo#493]
```java
class Base {
    private Long id;
}
```
```java
class Sub extends Base {
    private long id;
}
```
kryo serialize Sub instance with two id fields, one with ObjectField ,the other with ObjectLongField.
but deserialize Sub instance with two id fields, both with ObjectLongField.  deserialize fail
the reason in class CompatibleFieldSerializer 
```java
outer:
for (int i = 0, n = names.length; i < n; i++) {
    String schemaName = names[i];
    for (int ii = 0, nn = allFields.length; ii < nn; ii++) {
        if (allFields[ii].field.getName().equals(schemaName)) {
            fields[i] = allFields[ii];
            continue outer;
        }
    }
    if (TRACE) trace("kryo2", "Ignore obsolete field: " + schemaName);
}
```
fields will both assigned with the first found one in allFields

**Comment by magro** [comment]
Can you try `CachedFieldNameStrategy.EXTENDED` as mentioned in the readme?

**Comment by z3ronp** [comment]
I found the system used old version,there is not CachedFieldNameStrategy nested class in FieldSerializer class. tried current version, It's ok. sorry for that have not read the Readme, just debug the code

**Comment by magro** [comment]
No problem, great that it's working now :-)
