### ISSUE TITLE
partial deserialization / direct access to fields for POJOs

### ISSUE THREAD

**Issue by nqzero** [EsotericSoftware/kryo#494]
this is a wishlist item / feature request that [mongonix asked me to enter as an issue](https://groups.google.com/d/msg/kryo-users/znicuE7w1hE/CCekSoV4BwAJ)

in a number of use cases for deserialization, most visibly use in a database, it can be inefficient to deserialize an entire object graph if only a small portion is required. eg, consider an array of objects with an int ID field, and wanting to select the objects with a particular value

the following (related ?) features are requested:
* a (an optional) fixed layout for POJOs allowing direct access to fields without creation of the corresponding object, eg by providing the fixed offset that could then be used with unsafe
* partial deserialization of a POJO, eg only the top-level object, with a callback enabling deserialization of sub-objects and storing the reference in the appropriate field

**Comment by NathanSweet** [comment]
While FieldSerializer and others make this difficult, Kryo serializers are pluggable. Serializers could be written which track byte offsets for each field, allowing fields to be read without reading the whole object. It's a big project and I don't have plans to add this myself, but a PR would be considered.
