### ISSUE TITLE
async support

### ISSUE THREAD

**Issue by nqzero** [EsotericSoftware/kryo#495]
this is a wishlist item / feature request that [mongonix asked me to enter as an issue](https://groups.google.com/d/msg/kryo-users/znicuE7w1hE/CCekSoV4BwAJ)

when working with a large object graph and blocking io, kryo blocks a thread. given the expense of the kryo object, it's non-thread-safe behavior, the cost of threads and the potentially large size of the serialization, this can impact the application footprint

* async deserialization. given a blocking byte source, to deserialize the portion of the object that is available without blocking and provide a callback enabling continuation. this could be achieved with callback-passing-style or continuations
* an api to determine whether a particular field is valid, ie has been deserialized
* async serialization
* improvements to thread safety. define a subset of operations that are non-thread-safe and provide the ability to yield when such a condition is reached. this might be aided by breaking the kryo object into thread-safe and non-thread-safe portions

**Comment by NathanSweet** [comment]
There are many factors to consider, such as avoiding mutation of your objects during serialization. This very likely needs to be done in application code. You can write something similar to FieldSerializer (use Kryo 5.0, where it is simpler) to do callbacks, track which fields have been deserialized, yield with continutations, etc.

**Comment by NathanSweet** [comment]
I should say, this is likely to be very complex and I doubt we'll implement it.
