### ISSUE TITLE
Jenkins build fails for jdk6

### ISSUE THREAD

**Issue by magro** [EsotericSoftware/kryo#500]
The latest build on jenkins failed for jdk 6 (running test with previously compiled classes): https://jenkins.inoio.de/job/kryo%20(sun-jdk-6)/263/console

```
java.lang.UnsupportedClassVersionError: hudson/remoting/Launcher : Unsupported major.minor version 51.0
```

This was not caused by a code change but by an update of the jenkins that was done in the meantime. 

The last successful build with jdk 6 https://jenkins.inoio.de/job/kryo%20(sun-jdk-6)/262/console logged an error regarding the java version and it might be the case that the build job fell back to jdk 7, so that tests already have actually been run with jdk 7 (I'm not 100% sure if this was really the case, as some jenkins remoting is involved):

```
[kryo@2] $ /usr/lib/jvm/java-6-oracle/bin/java -cp /var/lib/jenkins/plugins/maven-plugin/WEB-INF/lib/maven3-agent-1.6.jar:/var/lib/jenkins/tools/hudson.tasks.Maven_MavenInstallation/maven3/boot/plexus-classworlds-2.4.jar org.jvnet.hudson.maven3.agent.Maven3Main /var/lib/jenkins/tools/hudson.tasks.Maven_MavenInstallation/maven3 /var/cache/jenkins/war/WEB-INF/lib/remoting-2.53.2.jar /var/lib/jenkins/plugins/maven-plugin/WEB-INF/lib/maven3-interceptor-1.6.jar /var/lib/jenkins/plugins/maven-plugin/WEB-INF/lib/maven3-interceptor-commons-1.6.jar 34662
<===[JENKINS REMOTING CAPACITY]===>channel started
ERROR: [JENKINS-18403] JDK 5 not supported to run Maven; retrying with slave Java and setting compile/test properties to point to /usr/lib/jvm/java-6-oracle
[kryo@2] $ /usr/lib/jvm/java-7-oracle/jre/bin/java -cp /var/lib/jenkins/plugins/maven-plugin/WEB-INF/lib/maven3-agent-1.6.jar:/var/lib/jenkins/tools/hudson.tasks.Maven_MavenInstallation/maven3/boot/plexus-classworlds-2.4.jar org.jvnet.hudson.maven3.agent.Maven3Main /var/lib/jenkins/tools/hudson.tasks.Maven_MavenInstallation/maven3 /var/cache/jenkins/war/WEB-INF/lib/remoting-2.53.2.jar /var/lib/jenkins/plugins/maven-plugin/WEB-INF/lib/maven3-interceptor-1.6.jar /var/lib/jenkins/plugins/maven-plugin/WEB-INF/lib/maven3-interceptor-commons-1.6.jar 39833
<===[JENKINS REMOTING CAPACITY]===>channel started
Executing Maven:  -B -f /var/lib/jenkins/sharedspace/kryo@2/pom-main.xml surefire:test
```

One option is to further analyze this and try to fix it, another option would be to drop java 6 support. 

@NathanSweet @romix WDYT?

**Comment by magro** [comment]
Asked on the mailing list: https://groups.google.com/d/msg/kryo-users/tPvHjTgYb9g/svjxxEliDQAJ

Twitter poll: https://twitter.com/martin_grotzke/status/840876050376732672

**Comment by lbergelson** [comment]
👍 For dropping support of everything below 8...

**Comment by magro** [comment]
The [twitter poll](https://twitter.com/martin_grotzke/status/840876050376732672) resulted in 5% java 6, 15% java 7 and 80% java 8.
I'll drop support for java 6, the jenkins build is changed to no longer cover jdk 6.

**Comment by NathanSweet** [comment]
I'm a bit late, but I would expect it should not be difficult for Jenkins to be able to compile with Java 6. Dropping support for 6 is OK, people needing that can compile themselves. We should not drop support for 7 though.
