### ISSUE TITLE
Let a custom ObjectInputStream be set in JavaSerializer

### ISSUE THREAD

**Issue by theoDiefenthal** [EsotericSoftware/kryo#502]
Hi there,

I have a project where I load some classes from hard-drive at runtime. I use my own URLClassLoader for this purpose. 
I set this classloader as Kryo class loader and almost everything works fine with Kryo and (De-)Serialization of those classes.

However, today I wanted to use the JavaSerializer for one of those classes.
Sadly, deserialization crashed due to a ClassNotFoundException.
This problem arises as the JavaSerializer uses the standard ObjectInputStream without using my custom set ClassLoader for Kryo. 

What I would like to write in my Java Serialization code is something like this:
```
ObjectInputStream objectStream = new ObjectInputStream(input) {
            @Override
            protected java.lang.Class<?> resolveClass(java.io.ObjectStreamClass desc) throws java.io.IOException, ClassNotFoundException {
                return myLoader.resolveClass(classnameReplacement(desc.getName()));
            }
        }
```
instead of 
```
objectStream = new ObjectInputStream(input);
```
as written in the JavaSerializer from Kryo. So I just want to subclass the ObjectInputStream used by Kryo (Ideally, this would be done automatically with a ClassLoader already set for Kryo). 

Of course, I can just subclass my own JavaSerializer and override the `read`-method, but this seems to not be a nice solution. Could you source out the `new ObjectInputStream(input)` to a factory function which I then can subclass?

Best regards

**Comment by magro** [comment]
JavaSerializer already uses its ObjectInputStreamWithKryoClassLoader, which is doing what you want, right? Maybe you're on an older version of kryo?

**Comment by theoDiefenthal** [comment]
Hi magro,

You are totally right! Sorry for this unnecessary ticket then. I really checked my sources only (4.0.0) and didn't look into the github version. I thought, I am already on the latest release and nothing would have changed. My mistake! So this can be closed and I hope, a new version will be released soon. 

PS: I like the solution with the ObjectInputStreamWithKryoClassLoader much more then my naive suggesion.

**Comment by magro** [comment]
Thanks for the hint that we should release that, will do that as soon as I find time! :-)
