### ISSUE TITLE
kryo stalling at writeString()

### ISSUE THREAD

**Issue by Raycoms** [EsotericSoftware/kryo#503]
I am writing some strings and custom objects with kryo into an output buffer but it stalls currently at writing strings directly.

```
 /**
 * Serializes the data and returns it in byte format.
 * @return the data in byte format.
 */
private byte[] serialize(@NotNull String reason, long localTimestamp, final Object...args)
{
    KryoPool pool = new KryoPool.Builder(factory).softReferences().build();
    Kryo kryo = pool.borrow();

    //Todo probably will need a bigger buffer in the future. size depending on the set size?
    final Output output = new Output(0, 10024);

    output.writeString(reason);
    output.writeLong(localTimestamp);
    for(Object identifier: args)
    {
        if(identifier instanceof NodeStorage || identifier instanceof RelationshipStorage)
        {
            kryo.writeClassAndObject(output, identifier);
        }
    }

    byte[] bytes = output.toBytes();
    output.close();
    pool.release(kryo);
    return bytes;
}
```

In this case, I debug it until output.writeString(reason) and it will stay there forever without ever returning the byteArray.

The string in this case is: "node/read".

The timeStamp is 1 and the object arguments are empty.

**Comment by Raycoms** [comment]
Anyone with an idea?
I'm using this for my thesis implementation and need to fix that soon =/

**Comment by romix** [comment]
Could you provide a self-contained example, e.g. in form of a JUnit test? I could have a look.

**Comment by Raycoms** [comment]
Calling the method I posted here with the provided String and timeStamp without arguments should cause the same outcome.

**Comment by romix** [comment]
OK. You actually found a bug in Kryo! Thanks and congrats! I'll commit a fix in a couple of minutes.

But aside from that, keep in mind that `new Output(0, 10024)` allocates a buffer with initial size of 0. And this was the issue. If you'd allocate a buffer with initial size >0, you'd have no issues with it.
