### ISSUE TITLE
readAscii in ByteBufferInput will modify the original niobuffer

### ISSUE THREAD

**Issue by zliu-fd** [EsotericSoftware/kryo#505]
In the following code of ByteBufferInput, the readAscii function modify the original niobuffer when reading. Is it an issue? Because this behavior means that before reading from a buffer, we have to copy this buffer to avoid modify the original buffer, if the original buffer is not writable.

`
private String readAscii () {
		int end = position;
		int start = end - 1;
		int limit = this.limit;
		int b;
		do {
			if (end == limit) return readAscii_slow();
			end++;
			b = niobuffer.get();
		} while ((b & 0x80) == 0);
		niobuffer.put(end - 1, (byte)(niobuffer.get(end - 1) & 0x7F)); // Mask end of ascii bit.
		byte[] tmp = new byte[end - start];
		niobuffer.position(start);
		niobuffer.get(tmp);
		String value = new String(tmp, 0, 0, end - start);
		niobuffer.put(end - 1, (byte)(niobuffer.get(end - 1) | 0x80));
		position = end;
		niobuffer.position(position);
		return value;
	}
`

Thanks.

**Comment by romix** [comment]
This is a known feature. It is described here: https://github.com/EsotericSoftware/kryo#threading

**Comment by romix** [comment]
If you don't like this trade-off, you can always provide your own String serializer, which would not modify the buffer, but would be eventually slower. Such a thing was discussed on the Kryo Google Group in the past.
