### ISSUE TITLE
CompatibleFieldSerializer has issues with ObjectMapper when two fields have same values

### ISSUE THREAD

**Issue by fayanneking** [EsotericSoftware/kryo#507]
Hi,

I encountered an issue when serializing an object to bytes using the CompatibleFieldSerializer with Jackson2’s ObjectMapper. The issue only happens when the object being serialized has at least two fields with the same values.

The use case is:
1. Jackson2 parses a JSON string to object1
2. Kryo serializes object1 to bytes1
3. object2 with same set of fields is created using new operator
4. Kryo serializes object2 to bytes2
5. Issue: bytes1 != bytes2

I expect that bytes#1 is equal to bytes#2 because all fields match between the two POJO's. However, after serialization, the length of the two byte arrays differ as well as the contents.

Here's the source code that replicates the issue:

```
public static void main(String[] args) throws JsonParseException, JsonMappingException, IOException {
        Kryo kryo = new Kryo();
        kryo.register(TestObj.class, new CompatibleFieldSerializer<TestObj>(kryo, TestObj.class));
        String json = "{\"fieldName1\":\"NEW1\", \"fieldName2\":\"NEW2\",\"fieldName3\":\"NEW\",\"fieldName4\":\"NEW\"}";

        ObjectMapper mapper = new ObjectMapper();
        TestObj obj1 = mapper.readValue(json, TestObj.class);
        System.out.println("obj1 toString: " + obj1);

        Output out1 = new Output();
        out1.setBuffer(new byte[4096]);
        kryo.writeClassAndObject(out1, obj1);
        byte[] byte1 = out1.toBytes();
        
        TestObj obj2 = new TestObj();
        obj2.setFieldName1("NEW1");
        obj2.setFieldName2("NEW2");
        obj2.setFieldName3("NEW");
        obj2.setFieldName4("NEW");
        System.out.println("obj2 toString: " + obj2);
        System.out.println("obj1 equals obj2: " + obj1.equals(obj2));
        
        Output out2 = new Output();
        out2.setBuffer(new byte[4096]);
        kryo.writeClassAndObject(out2, obj2);
        byte[] byte2 = out2.toBytes();

        System.out.println("byte1 length: " + byte1.length);
        System.out.println("byte2 length: " + byte2.length);
        System.out.println("byte1 equals byte2: " + Arrays.equals(byte1, byte2));
}

public class TestObj {

    private String fieldName1;
    private String fieldName2;
    private String fieldName3;
    private String fieldName4;

    public String getFieldName1() {
        return fieldName1;
    }

    public void setFieldName1(String fieldName1) {
        this.fieldName1 = fieldName1;
    }

    public String getFieldName2() {
        return fieldName2;
    }

    public void setFieldName2(String fieldName2) {
        this.fieldName2 = fieldName2;
    }

    public String getFieldName3() {
        return fieldName3;
    }

    public void setFieldName3(String fieldName3) {
        this.fieldName3 = fieldName3;
    }

    public String getFieldName4() {
        return fieldName4;
    }

    public void setFieldName4(String fieldName4) {
        this.fieldName4 = fieldName4;
    }

    @Override
    public String toString() {
        return "TestObj [fieldName1=" + fieldName1 + ", fieldName2=" + fieldName2 + ", fieldName3=" + fieldName3
                + ", fieldName4=" + fieldName4 + "]";
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((fieldName1 == null) ? 0 : fieldName1.hashCode());
        result = prime * result + ((fieldName2 == null) ? 0 : fieldName2.hashCode());
        result = prime * result + ((fieldName3 == null) ? 0 : fieldName3.hashCode());
        result = prime * result + ((fieldName4 == null) ? 0 : fieldName4.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        TestObj other = (TestObj) obj;
        if (fieldName1 == null) {
            if (other.fieldName1 != null)
                return false;
        } else if (!fieldName1.equals(other.fieldName1))
            return false;
        if (fieldName2 == null) {
            if (other.fieldName2 != null)
                return false;
        } else if (!fieldName2.equals(other.fieldName2))
            return false;
        if (fieldName3 == null) {
            if (other.fieldName3 != null)
                return false;
        } else if (!fieldName3.equals(other.fieldName3))
            return false;
        if (fieldName4 == null) {
            if (other.fieldName4 != null)
                return false;
        } else if (!fieldName4.equals(other.fieldName4))
            return false;
        return true;
    }

}
```
The issue cannot be replicated if both objects are created using the new operator directly. It also won't happen if there are no fields with the same values.

I'm using kryo v4.0.0 and jackson-core v2.6.7, running on JDK 1.8.0_74.

**Comment by fayanneking** [comment]
We did a bit of investigation on this issue. It turns out that it has something to do with JVM's string pool.

**Scenario 1**
When manually creating the object using the new operator, the "NEW" string is saved into JVM's string pool. Both fieldName3 and fieldName4 refers to the same string instance in the string pool.

In this scenario, Kryo only serializes the field names and THREE strings ("NEW1", "NEW2", "NEW").

**Scenario 2**
On the other hand, Jackson is creating the object via reflection, calling new String("NEW") twice, once for fieldName3 and another time for fieldName4.

In this scenario, Kryo serializes the field names and FOUR strings ("NEW1", "NEW2", "NEW", "NEW").

This is the reason byte array length is different: Kryo serializes more objects in Scenario 2 vs Scenario 1.

**Comment by fayanneking** [comment]
We did a bit of investigation on this issue. It turns out that it has something to do with JVM's string pool.

Scenario 1
When manually creating the object using the new operator, the "NEW" string is saved into JVM's string pool. Both fieldName3 and fieldName4 refers to the same string instance in the string pool.

In this scenario, Kryo only serializes the field names and THREE strings ("NEW1", "NEW2", "NEW").

Scenario 2
On the other hand, Jackson is creating the object via reflection, calling new String("NEW") twice, once for fieldName3 and another time for fieldName4.

In this scenario, Kryo serializes the field names and FOUR strings ("NEW1", "NEW2", "NEW", "NEW").

This is the reason byte arrays are different: Kryo serializes more objects in Scenario 2 vs. Scenario 1.

I'm not sure if this is the expected behavior of Kryo serializer. However, in my opinion, Kryo should serialize all strings of an object, regardless of whether they are referring to the same String instance or not. Reason is that clients can create Strings whichever way they want (via new, reflection, constants, etc.). My expectation is that Kryo serializes two objects with the same hashcode and equals to the same byte array, regardless of how the Strings are referenced/created.

**Comment by magro** [comment]
What's the actual problem caused by this? Can't you achieve what you want by disabling references for kryo?

**Comment by fayanneking** [comment]
After setting Kryo#setReferences(false), issue is resolved. Thanks for your time.

**Comment by magro** [comment]
Great, you're welcome!
