### ISSUE TITLE
[Question] DeflateSerializer random overflows when used in kryonet

### ISSUE THREAD

**Issue by voidburn** [EsotericSoftware/kryo#508]
Hey guys, 

I've been using the DeflateSerializer for a while to compress some of the data streams for TCP communication in kryonet, and sometimes this happens:

1) Deserialization happens correctly
2) The kryonet buffer contains some extra bytes and it crashes:

Exception:
```
Exception in thread "Client" com.esotericsoftware.kryonet.KryoNetException: Incorrect number of bytes (2 remaining) used to deserialize object: com.unobtanium.data.world.WorldRegionData@4baffb99
	at com.esotericsoftware.kryonet.TcpConnection.readObject(TcpConnection.java:146)
	at com.esotericsoftware.kryonet.Client.update(Client.java:255)
	at com.esotericsoftware.kryonet.Client.run(Client.java:338)
	at java.lang.Thread.run(Thread.java:745)
```

TcpConnection's related code:
```
try {
	object = serialization.read(connection, readBuffer);
} catch (Exception ex) {
	throw new KryoNetException("Error during deserialization.", ex);
}

readBuffer.limit(oldLimit);
if (readBuffer.position() - startPosition != length)
	throw new KryoNetException("Incorrect number of bytes (" + 
								(startPosition + length - readBuffer.position()) +
								" remaining) used to deserialize object: " + object);

return object;
```

I tested all possible versions of Kryo with the "problematic" payload blob, and I was able to always serialize and deserialize correctly, so I devised a test that creates payloads of random sizes and transports them over TCP so that I can eventually find (and dump to disk) one that causes this.

Once a payload triggering the issue is found, it's 100% reproducible.

The average payload size (compressed) is around 30KB, I soon discovered that if I bumped up the OutputChunked buffer from 256 to 8192 bytes (along with the Output buffer that receives the deflater stream), the issue seemed to go away (I looked into the buffers that Netty uses internally for the same purpose, and that seemed to be the magic number they chose).

It lasted for a while, but eventually I found another payload that would cause the same issue. Since I had the stress test at hand I started poking at the problem blindly (I have no knowledge of compression algorithms to understand what could be possibly happening) by trying to make it either worse or better and gather some additional clues. 

After a while I stumbled on what seems to be a solution that for some obscure (to me) reason, makes the stress test pass (tested continuously for 28 hours at 120 transports per second).

The solution was this:

```
public DeflateSerializer (Serializer serializer) {
		this.serializer = serializer;
	}

	public void write (Kryo kryo, Output output, Object object) {
		OutputChunked outputChunked = new OutputChunked(output, **255**);
		Deflater deflater = new Deflater(compressionLevel, noHeaders);
		try {
			DeflaterOutputStream deflaterStream = new DeflaterOutputStream(outputChunked, deflater);
			Output deflaterOutput = new Output(deflaterStream, 256);
			serializer.write(kryo, deflaterOutput, object);
			deflaterOutput.flush();
			deflaterStream.finish();
		} catch (IOException ex) {
			throw new KryoException(ex);
		} finally {
			deflater.end();
		}
		outputChunked.endChunks();
	}

	public Object read (Kryo kryo, Input input, Class type) {
		// The inflater would read from input beyond the compressed bytes if chunked enoding wasn't used.
		Inflater inflater = new Inflater(noHeaders);
		try {
			InflaterInputStream inflaterStream = new InflaterInputStream(new InputChunked(input, **255**), inflater);
			return serializer.read(kryo, new Input(inflaterStream, 256), type);
		} finally {
			inflater.end();
		}
	}
```

I realized that the moment I don't use a power of 2 size for the Chunked buffer, this simply does not happen. In fact, while chunking at 256 bytes causes the problem very often (64 bytes being very fast at triggering the issue) , and a larger buffer reduces the occurrence of it, a chunking buffer of 252 or 255 or even 257 bytes simply never seems to trigger it. It seems to be an issue only when the chunking is aligned to powers of 2.

I was hoping that someone here with better knowledge on this topic could provide an explanation to my empirical findings.

Cheers

**Comment by NathanSweet** [comment]
I'm not sure what is going on. Maybe reproduce the problem without any networking at all? If you can post a standalone repro of the bug I can take a look.

**Comment by voidburn** [comment]
Hey Nate, thanks for taking an interest to it, as of today I'm still running with my dirty hack (which so far has proven stable), it makes me itch and I'm willing to devote any time required to assist you in figuring this out, would love to get some peace of mind about this!

The attached test suite comes with this default configuration (meant to quickly trigger the issues during stress testing):

`CompressionSerializer.java`:
- CHUNK_PAYLOAD_SIZE: 64 bytes
- IO_BUFFER_SIZE: 64 bytes

`Main.java`
- ENABLE_REGION_COMPRESSION: true
- RUN_WARMUP_WITH_PROBLEMATIC_REGION: false (used to reproduce the issue once a problematic blob has been found. One is provided in the zip file, found by me, you can toggle this flag to trigger the issue during warmup immediately.. assuming the bug is deterministic)
- default test running: testContinuousRandomRegionViaRmi() (this one will dump a fresh `problematic-region-data.bin` blob upon crash.

This is the fastest way the error can be found while running the continuous transport test (increasing the buffers size to 256, 8192 will simply take more time but it still hits a wall)

The rest of the code is just data structures that mimic the use case (streaming regions of a game world) that triggered the issue the first time for me.

The code is heavily commented and should prove easy to read and tweak, you can switch the test types (RMI/non RMI) at your heart's content. The suite includes a warmup test which uses either the `safe` or `problematic` blobs serialization/deserialization with kryo, and send/receive with kryonet for quick 100% reproduction of the crash.

Feel free to get in touch if you need assistance! Attached here is the zip with the code.

[kryonetCompressionTests.zip](https://github.com/EsotericSoftware/kryo/files/1151020/kryonetCompressionTests.zip)

**Comment by NathanSweet** [comment]
I see the problem using Kryo 2.23.0 (KryoNet's old Kryo version). Can you provided updated data once KryoNet is updated to Kryo 5? Currently it is only in the kryo-5.0.0-dev branch. I can't test Kryo 5 because your test data from the old Kryo version can't be read with the latest. If you grab Kryo 5 from the branch and update KryoNet, it's a drop in replacement except `Class<InvokeMethodResult>` in ObjectSpace needs to change to `Class<? extends InvokeMethodResult>`.

**Comment by voidburn** [comment]
I didn't notice I was using 2.24.0, forgot to exclude kryonet dependency in the pom. I moved on to Netty (which has no problem with the same payloads, kryo version and SSL on top of everything else) so I'm still pretty sure it's not Kryo's issue, but if it helps you debug kryonet I'll bundle together the compression tests using kryo's dev snapshots. Give me a day or two and it'll be done.

**Comment by NathanSweet** [comment]
If it's a KryoNet issue there's no rush, my current focus is Kryo.
