### ISSUE TITLE
CompatibleFieldSerializer misses deserializing some fields when new fields have been added to a Class with a large number of fields

### ISSUE THREAD

**Issue by barold419** [EsotericSoftware/kryo#519]
When a Class exists with a large number of fields, say m (where m > CompatibleFieldSerializer#THRESHOLD_BINARY_SEARCH) is serialized, then n new fields are added to the class before deserialization, then some of the preexisting fields may not be deserialized correctly and the deserialized object will have null values instead of the properly populated values. Further, if this class is part of a larger graph of objects, deserialization may fail completely as the internal deserialization tracking will be broken after missing the previous fields.

**Comment by magro** [comment]
Thanks for reporting! Do you want to submit a pull request?

**Comment by magro** [comment]
Ah, I just spotted #520, great! :-)

**Comment by magro** [comment]
Closed with #520
