### ISSUE TITLE
What is the Kryo release schedule?

### ISSUE THREAD

**Issue by angarron** [EsotericSoftware/kryo#526]
Many issues have been closed and PRs merged over the last year, but Kryo is still on 4.0.0. Is there a plan for an official release? In particular, https://github.com/EsotericSoftware/kryo/pull/514 being merged is significant to my team as Android O gets closer to an official release.

Thanks for the great work!
Andy

**Comment by magro** [comment]
Thanks for asking! I've been loaded (and still am) quite heavily by my "day" work and therfore found nearly no time for kryo. 
Yes, a new release definitely is outstanding, I'll try to find time for this during the next days / weeks.

Any help in maintaining/supporting kryo (reviewing issues and PRs) is highly appreciated btw :-)

**Comment by dekobon** [comment]
My team also is really eager for a new release. Is there anything we can do to help?

**Comment by tjcelaya** [comment]
@magro Are there any issues or PRs which you'd like to address before going ahead with the next release?

**Comment by magro** [comment]
No, I see nothing that's blocking the release. I need to prepare curated release notes, finally check compatibility and do the release. Hopefully during the next days, stay tuned.

**Comment by magro** [comment]
I just released 4.0.1, see [release notes](https://github.com/EsotericSoftware/kryo/releases/tag/kryo-parent-4.0.1). Thanks for your patience! ;-)
