### ISSUE TITLE
Read/write HashSet issue

### ISSUE THREAD

**Issue by andreysubbotin** [EsotericSoftware/kryo#528]
Data model contains classes: 

```
 public class Order  {
    protected UUID id;
    protected String field;
    protected Set<OrderLine> lines;
    public Order() {
         this.id = UUID.randomUUID();
    }
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Order order = (Order) o;
        return id != null ? id.equals(order.id) : order.id == null;
    }
    @Override
    public int hashCode() {
        return id != null ? id.hashCode() : 0;
    }
}
```

and 

```
public class OrderLine {
    protected Order aorder;
    protected UUID id;
    protected String field;

    public OrderLine() {
        this.id = UUID.randomUUID();
    }
   @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        OrderLine orderLine = (OrderLine) o;
        return id != null ? id.equals(orderLine.id) : orderLine.id == null;
    }
    @Override
    public int hashCode() {
        return id != null ? id.hashCode() : 0;
    }
}
```
Test Case: 
- Write list with orderLine and order and read after
- Try to execute `deserializedOrder.getLines().contains(deserializedOrder.getLines().toArray()[0]))`
Actual Result: Contains returns False. OrderLine exists in HashSet but it's not found.

See SerializationTest in a project:
[kryobug.zip](https://github.com/EsotericSoftware/kryo/files/1196171/kryobug.zip)

**Comment by isaki-x** [comment]
You have a circular object graph (Order depends on OrderLine which depends on Order) based just on the code you have included in the issue. Not sure if that has anything to do with the issue, but I use HashSets all the time with Kryo and have never had the issue you are seeing, so I suspect it is related.

**Comment by magro** [comment]
Sorry for the delay, I'm currently on vacation (writing on my phone). 

I suspect the default constructor (used by kryo during deserialization if present) which sets a random ID is related to the issue. You might try to get rid of this default constructor.

**Comment by andreysubbotin** [comment]
Hi, 
I tried unit-test without a default constructor, but the result is the same.

**Comment by magro** [comment]
You could use a debugger and inspect the objects to see what's unexpected.

**Comment by magro** [comment]
I'm closing this for now, please reopen if still relevant.

**Comment by andreysubbotin** [comment]
Hi @magro 
The issue is actually for us. 
The problem is that KRYO tries to deserialize HashSet before OrderLine is deserialized. So hashes in the HashSet doesn't correspond to hashes for OrderLines, 'Set#contains' operation can't find the item.
Original test project works correctly with standard JAVA serialization.

**Comment by magro** [comment]
@andreysubbotin I have the following test (using the classes you posted initially) and it's green:
```java
public void testOrder () {
	kryo.setRegistrationRequired(false);
	kryo.setReferences(true);
	kryo.setInstantiatorStrategy(new Kryo.DefaultInstantiatorStrategy(new StdInstantiatorStrategy()));

	Order order = new Order();
	order.field = "orderField";

	OrderLine line = new OrderLine();
	line.field = "lineField";
	line.aorder = order;
	order.lines = new HashSet<>();
	order.lines.add(line);

	Order deserializedOrder = roundTrip(195, 191, order);
	assertTrue(deserializedOrder.lines.contains(deserializedOrder.lines.toArray()[0]));
}
```

Does this work for you?

**Comment by andreysubbotin** [comment]
Hi @magro, 

Your test works fine (it's green). But the test is failed when `roundTrip` is used for the list with `line` and `order`:
```
Order order = new Order();
        order.field = "orderField";

        OrderLine line = new OrderLine();
        line.field = "lineField";
        line.aorder = order;
        order.lines = new HashSet<OrderLine>();
        order.lines.add(line);

        List list = new ArrayList();
        list.add(line);
        list.add(order);

        List result = (List) deserialize(serialize(list));
        Order deserializedOrder = (Order) result.get(1);

        assertTrue("Set without orderLine",
                deserializedOrder.getLines().contains(deserializedOrder.getLines().toArray()[0]));
```

Thanks

**Comment by magro** [comment]
@andreysubbotin can you find out what's the significant difference between the tests?

**Comment by andreysubbotin** [comment]
Hi @magro 
I tried to debug test case with  _roundTrip_ over a list. Deserialization contains following steps:
* FieldSerializer reads OrderLine
* FieldSerializer creates OrderLine and puts it into the reference map. The constructor of OrderLine fills id field with random UUID.
* FieldSerializer reads the first field _aorder_
** FieldSerializer create Order 
**  FieldSerializer tries to read _orderLines_ HashSet field. CollectionSerializer finds OrderLine in a reference map and adds it to the collection. OrderLine has incorrect hashCode because hashCode uses randomly generated id
** FieldSerializer completes Order deserialization
** FieldSerializer reads id field of the OrderLine

So OrderLine is added to the HashSet before all of it fields are deserialized.

**Comment by NathanSweet** [comment]
The FieldSerializer sorts the fields that will be serialized by alpha, so the order is known. This results in: aorder, field, id. This is why when deserializing aorder is deserialized before id is set. It is unfortunate, but there is no way for Kryo to know that id should be serialized first (or aorder serialized last). You'll need to customize the serializer for your particular class. Eg, you can swap the id field so it is first:
```
FieldSerializer serializer = new FieldSerializer(kryo, OrderLine.class);
CachedField idField = serializer.getField("id");
CachedField[] fields = serializer.getFields();
for (int i = 0, n = fields.length; i < n; i++) {
	CachedField field = fields[i];
	if (field == idField) {
		fields[i] = fields[0];
		fields[0] = idField;
		break;
	}
}
kryo.register(OrderLine.class, serializer);
```
