### ISSUE TITLE
Encountered unregistered class ID: 3174334

### ISSUE THREAD

**Issue by EXPEnbansal** [EsotericSoftware/kryo#534]
I have a class which has many complex fields and one of the fields is Set<String> a. While deserializing the class object I get the error Encountered unregistered class ID: 3174334.
The value that should get initialized to the variable a is null. Why am i getting the above error.

**Comment by isaki-x** [comment]
Please provide a minimal, runnable (as in builds and works in jUnit) test(s) that can reproduce this issue. Thanks.

**Comment by magro** [comment]
I'm closing this for now, please reopen with more info / a reproducer if this is still relevant.
