### ISSUE TITLE
Register all classes in kryo

### ISSUE THREAD

**Issue by EXPEnbansal** [EsotericSoftware/kryo#535]
Do I need to register all classes in kryo whether those are java classes which come packaged with jdk like all Collections classes, and even all 3rd party classes.

If this is the case is not this a pain point in registering kryo classes.
Java has a simple way of implementing Serializable Interface and providing a serialversionID.
IS there any similar way for Kryo as well

**Comment by isaki-x** [comment]
The documentation on the primary landing page talks about all this:

https://github.com/EsotericSoftware/kryo#default-serializers

https://github.com/EsotericSoftware/kryo#using-standard-java-serialization

**Comment by magro** [comment]
Thanks for responding, @isaki-x! :-)
