### ISSUE TITLE
4.0.0 Deserialization Bug with un-registered classes

### ISSUE THREAD

**Issue by bsandiford** [EsotericSoftware/kryo#540]
When an object is serialized, and contains a field whose class is not registered with Kryo, the serialization will include the class name.

The deserialize recognizes this, and on the first deserialize, will read the class name and correctly handle that field.

However - the second deserialize will fail.  The problem is in class DefaultClassResolver method 'readName'.  The first time in, where type is null, it will read the class name, and then add info to the maps that track the name / id mappings.  Everything is fine.  The second time through, type will not be null, so it bypasses the code in the if statement.  The problem is, the serialized object still contains the class name, and without doing the "input.readString()", the pointer in the input buffer is now pointing at the wrong place.  Any subsequent deserialize from that point on will either give bogus results, or throw an exception.

So - whether or not type is null in  method readName, the input.readString() MUST take place.

Thanks!

Bob.

**Comment by bsandiford** [comment]
(I can 'fix' it in my case by pre-registering the class with Kryo - but, that bug in the DefaultClassResolver should still get properly fixed...)

**Comment by isaki-x** [comment]
I use unregistered Kryo all the time and I have never had this problem. Please provide a fully functional test case that demonstrates the problem.

**Comment by bsandiford** [comment]
You are absolutely correct.  In trying to put together a test class for this, the fix I thought was required breaks a number of scenarios (caught by the unit tests).  Looking deeper, I found that the product that's using Kryo has gone and set the kryo.setAutoReset(false), meaning that the DefaultClassResolver method reset() isn't being called after each deserialization.  Once the auto reset is true, things work fine. 

Sorry for the bogus report :(

**Comment by isaki-x** [comment]
The report may not be valid, but I might be able to help you get a bit better performance.

Here is how I use unserialized Kryo:

```Java
        final Kryo kryo = new Kryo();
        kryo.setReferences(false);
        kryo.setRegistrationRequired(false);
        kryo.setAutoReset(false);
        kryo.getFieldSerializerConfig().setUseAsm(true);
```

In my case, this is used for a long lived input and output stream where I use a dedicated Kryo instance for each direction. When the streams are lost, I manually call reset (in my case, it is event driven). You only need to reset when you reach the end of a stream.

**Comment by bsandiford** [comment]
Thanks isaki-x - that is good to know, but unfortunately doesn't match the usage in this other product.  They're using Kryo for serialization / deserialization for memcached - so, each memcached 'get()' is going to use a completely separate stream :(

**Comment by isaki-x** [comment]
Yeah, in that use case autoReset is your best bet.
