### ISSUE TITLE
HashMaps don't deserialise the loadFactor property

### ISSUE THREAD

**Issue by SpencerArtisan** [EsotericSoftware/kryo#542]
When kryo deserialises a HashMap it has a loadFactor of zero, which is invalid and causes InvalidObjectExceptions if you attempt to write then read the map to an object stream.

This problem occurs because the loadFactors are set in the HashMap constructors, which Kryo deserialisation doesn't use.

**Comment by magro** [comment]
@SpencerArtisan Kryo's `MapSerializerTest` test hash maps, there the `HashMap` is created by invoking the default constructor. Maybe you have the instantiator strategy configured somehow specially?

**Comment by NathanSweet** [comment]
Can reopen when shown to be reproducible.
