### ISSUE TITLE
cannot support like this [public CustomBean setId(String id)  ]

### ISSUE THREAD

**Issue by icesx** [EsotericSoftware/kryo#544]
public class CustomBean implements Serializable {	
public CustomBean setId(String id) {
		this.id = id;
		return this;
	}
}

 when use this bean , the object that been read from byte[]  properties id is null

**Comment by icesx** [comment]
because this is not javabeans specification

**Comment by isaki-x** [comment]
Please provide a fully implemented unit test (i.e. contains all code necessary) that reproduces this issue.

**Comment by magro** [comment]
I'm closing this for now, please reopen with more information / a self contained test case if it's still relevent.
