### ISSUE TITLE
Collections.singleton and friends should not be considered immutable

### ISSUE THREAD

**Issue by alexandrebouchard** [EsotericSoftware/kryo#548]
By default, Kryo performs shallow copy of instances of Collections.singleton (and singletonList, etc). This is incorrect in cases where the element in the singleton is not immutable, for example a singleton containing an ArrayList.

**Comment by magro** [comment]
@alexandrebouchard Do you want to submit a pull request?

**Comment by alexandrebouchard** [comment]
Sure! Here it is: https://github.com/EsotericSoftware/kryo/pull/575
