### ISSUE TITLE
How to clear the kryo referenceResolver content?

### ISSUE THREAD

**Issue by ljkhello123** [EsotericSoftware/kryo#549]
In my code, I use kryo in pool like this:
`private static KryoPool pool = new KryoPool.Builder(new KryoFactory()
    {
        public Kryo create()
        {
            return initialValue();
        }
    }).softReferences().build();`

when I try to get a kryo object , I use `return pool.borrow();` 

So, if i run my code serveral times， a same kryo object is used many times. After that，I found the kryo object use big memory.  After analysis， I found ：
`K[] keyTable;
	int[] valueTable;` 
in MapReferenceResolver-->IdentityObjectIntMap is int[6072131], but size is 0

it means it always group up and use memory, but never release, so how can I release the content?
besides, kryo.reset only set each element of keyTable/valueTable to null, but memory is never released:
`public void clear () {
		K[] keyTable = this.keyTable;
		for (int i = capacity + stashSize; i-- > 0;)
			keyTable[i] = null;
		size = 0;
		stashSize = 0;
	}`

**Comment by ljkhello123** [comment]
I use kryo 4.0.0

**Comment by rajeevvs2007** [comment]
@ljkhello123 Do we have any fix for this?We are also seeing similar issue in load test.

**Comment by magro** [comment]
Do you want to submit a PR for this?

**Comment by rajeevvs2007** [comment]
@magro is the fix available in any version?

**Comment by ljkhello123** [comment]
Finally,  I use a customized ReferenceResolver in Kryo, code like follows :
`_kryo.setReferenceResolver(new Crm3ReferenceResolver());`

instead of the default reference : 
`com.esotericsoftware.kryo.util.MapReferenceResolver`

**Comment by ljkhello123** [comment]
`package com.huawei.crm3.base.serializer.impl;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.util.Util;


public class Crm3ReferenceResolver implements com.esotericsoftware.kryo.ReferenceResolver
{
    protected Kryo kryo;
    
    protected Map<Value, Integer> writtenObjects = new HashMap<Value, Integer>();
    
    protected final ArrayList<Object> readObjects = new ArrayList<Object>();
    
    private static class Value
    {
        private Object val;
        
        private int hash;
        
        public Value(Object val)
        {
            this.val = val;
            this.hash = System.identityHashCode(val);
        }
        
        @Override
        public int hashCode()
        {
            return hash;
        }
        
        @Override
        public boolean equals(Object obj)
        {
            if (!(obj instanceof Value))
            {
                return false;
            }
            return val == ((Value)obj).val;
        }
        
    }
    
    public void setKryo(Kryo kryo)
    {
        this.kryo = kryo;
    }
    
    public int addWrittenObject(Object object)
    {
        Value v = new Value(object);
        Integer i = writtenObjects.get(v);
        if (i == null)
        {
            int ret = writtenObjects.size();
            writtenObjects.put(v, ret);
            return ret;
        }
        else
        {
            return i;
        }
    }
    
    public int getWrittenId(Object object)
    {
        Value v = new Value(object);
        Integer i = writtenObjects.get(v);
        if (i == null)
        {
            return -1;
        }
        else
        {
            return i;
        }
    }
    
    @SuppressWarnings("rawtypes")
    public int nextReadId(Class type)
    {
        int id = readObjects.size();
        readObjects.add(null);
        return id;
    }
    
    public void setReadObject(int id, Object object)
    {
        readObjects.set(id, object);
    }
    
    @SuppressWarnings("rawtypes")
    public Object getReadObject(Class type, int id)
    {
        return readObjects.get(id);
    }
    
    public void reset()
    {
        readObjects.clear();
        writtenObjects.clear();
    }
    
    /** Returns false for all primitive wrappers. */
    @SuppressWarnings("rawtypes")
    public boolean useReferences(Class type)
    {
        return !Util.isWrapperClass(type) && !type.equals(String.class) && !type.equals(Date.class)
            && !type.equals(BigDecimal.class) && !type.equals(BigInteger.class);
    }
    
    public void addReadObject(int id, Object object)
    {
        while (id >= readObjects.size())
            readObjects.add(null);
        readObjects.set(id, object);
    }
}`

**Comment by magro** [comment]
@rajeevvs2007 I don't there's a fix already, that's why I asked if somebody of you would like to work on this and submit a pull request.

**Comment by isaki-x** [comment]
This was fixed; there is no release for it. If you look, at `MapReferenceResolver`, it invokes the following:

```java
	public void reset () {
		readObjects.clear();
		writtenObjects.clear(2048);
	}
```

The writtenObject member is the `IdentityObjectIntMap` in question.

Here is the definition for `IdentityObjectIntMap.clear(int)`:

```java
	/** Clears the map and reduces the size of the backing arrays to be the specified capacity if they are larger. */
	public void clear (int maximumCapacity) {
		if (capacity <= maximumCapacity) {
			clear();
			return;
		}
		size = 0;
		resize(maximumCapacity);
	}
```

**Comment by magro** [comment]
Thanks for the hint @isaki-x! I'll push a new kryo release asap.

**Comment by isaki-x** [comment]
No problem, glad to help!

**Comment by magro** [comment]
Sorry for the delay, I just released 4.0.2

**Comment by biswardas** [comment]
This fix is good, in addition could the arraylist be trimmed to size please?

**Comment by biswardas** [comment]
`public void reset () {
		readObjects.clear();
//While deserializing large graph it's retaining lots of memory
readObjects.trimToSize();
//End
		writtenObjects.clear(2048);
	}
`

**Comment by biswardas** [comment]
```
public void reset () { 
   readObjects.clear(); 
   readObjects.trimToSize(); 
   writtenObjects.clear(2048);
}
```

**Comment by NathanSweet** [comment]
@biswardas that is done in v5. You could also switch to using a HashMapReferenceResolver.
