### ISSUE TITLE
History of API changes for Kryo

### ISSUE THREAD

**Issue by lvc** [EsotericSoftware/kryo#550]
Hi,

I'd like to share report on API changes and backward compatibility for the Kryo library: https://abi-laboratory.pro/java/tracker/timeline/kryo/

The report is generated according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2 by the https://github.com/lvc/upstream-tracker-4j tool for jars at http://central.maven.org/maven2/com/esotericsoftware/kryo/.

Hope it will be helpful for users and maintainers of the library.

Thank you.

![kryo-1](https://user-images.githubusercontent.com/1517837/32402567-30a4427e-c138-11e7-87c1-d3409c0ba93d.png)

![kryo-2](https://user-images.githubusercontent.com/1517837/32402566-3063f28c-c138-11e7-9d58-c002b55cd9c9.png)

**Comment by NathanSweet** [comment]
It's sort of interesting, but this is an issue tracker.
