### ISSUE TITLE
IdentityObjectIntMap.clear taking more time.

### ISSUE THREAD

**Issue by divya7747** [EsotericSoftware/kryo#558]
More than 50% of the total time is spent in **IdentityObjectIntMap.clear.** 

Version :- com.esotericsoftware:kryo-parent:4.0.0
![gc1](https://user-images.githubusercontent.com/7350988/34092175-2d6bc848-e3e8-11e7-90c7-b3e76dd83a22.png)

**Comment by NathanSweet** [comment]
The 2048 was chosen arbitrarily, but it makes sense to have a limit.

**Comment by divya7747** [comment]
Can u please elaborate your statement?

**Comment by divya7747** [comment]
@NathanSweet : When will be the next release ?

**Comment by adithyank** [comment]
@NathanSweet 

Thanks for the commit 77935c6. When can we expect a release with this change???
We are badly affected by the performance of the `IdentityObjectIntMap.clear()`

**Comment by magro** [comment]
@adithyank Sorry for the delay, this was just released with 4.0.2

**Comment by adithyank** [comment]
Thanks a lot @magro
