### ISSUE TITLE
Using spark and h2o jobs in livy gives me kyro serlizer excpetion

### ISSUE THREAD

**Issue by Bazarganigilani** [EsotericSoftware/kryo#562]
Hi,

I am submitting spakr h2o models through livy . my POM fle is as follow:

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>au.com.vroc.mdm</groupId>
	<artifactId>mdm</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.version>1.8</java.version>
		<gson.version>2.8.0</gson.version>
		<java.home>${env.JAVA_HOME}</java.home>
	</properties>

	<dependencies>

		
		

		
		<dependency>
			<groupId>ai.h2o</groupId>
			<artifactId>h2o-core</artifactId>
			<version>3.10.4.2</version>
			
		</dependency>
		
		<dependency>
			<groupId>ai.h2o</groupId>
			<artifactId>h2o-algos</artifactId>
			<version>3.10.4.2</version>
			
		</dependency>
		
		<dependency>
			<groupId>ai.h2o</groupId>
			<artifactId>h2o-genmodel</artifactId>
			<version>3.10.4.2</version>
			
		</dependency>
		
		<dependency>
			

			<groupId>ai.h2o</groupId>
			<artifactId>sparkling-water-core_2.11</artifactId>
			<version>2.1.1</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>${gson.version}</version>
		</dependency>
		<dependency>
			<groupId>com.cloudera.livy</groupId>
			<artifactId>livy-client-http</artifactId>
			<version>0.3.0</version>
		</dependency>
		<dependency>
			<groupId>com.cloudera.livy</groupId>
			<artifactId>livy-api</artifactId>
			<version>0.3.0</version>
		</dependency>
		<dependency>
			<groupId>it.unimi.dsi</groupId>
			<artifactId>fastutil</artifactId>
			<version>7.1.0</version>
		</dependency>
		 <dependency>
			<groupId>org.scala-lang</groupId>
			<artifactId>scala-library</artifactId>
			<version>2.11.8</version>
		</dependency> 
		

		
		
		<dependency>
			<groupId>org.apache.phoenix</groupId>
			<artifactId>phoenix-spark</artifactId>
			<version>4.7.0-HBase-1.1</version>
			
		</dependency>

	
	<dependency>
		<groupId>org.apache.spark</groupId>
		<artifactId>spark-core_2.11</artifactId>
		<version>2.1.1</version>
	</dependency>
	<dependency>
		<groupId>org.apache.spark</groupId>
		<artifactId>spark-sql_2.11</artifactId>
		<version>2.1.1</version>
	</dependency>
	<dependency>
		<groupId>org.apache.spark</groupId>
		<artifactId>spark-hive_2.11</artifactId>
		<version>2.1.1</version>
	</dependency>
	<dependency>
		<groupId>org.apache.spark</groupId>
		<artifactId>spark-mllib_2.11</artifactId>
		<version>2.1.1</version>
	</dependency>
	<dependency>
		<groupId>com.databricks</groupId>
		<artifactId>spark-csv_2.11</artifactId>
		<version>1.5.0</version>
	</dependency>
	<dependency>
		<groupId>org.apache.spark</groupId>
		<artifactId>spark-launcher_2.11</artifactId>
		<version>2.1.1</version>
	</dependency>
	</dependencies>

	<repositories>
		<repository>
			<id>cloudera.repo</id>
			<url>https://repository.cloudera.com/artifactory/cloudera-repos</url>
			<name>Cloudera Repositories</name>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>Local repository</id>
			<url>file://${basedir}/lib</url>
		</repository>

	</repositories>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.6.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
					<encoding>UTF-8</encoding>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>2.5.2</version>
				
				<configuration>
					
					<descriptorRefs>
						<descriptorRef>jar-with-dependencies</descriptorRef>
					</descriptorRefs>
				</configuration>
				<executions>
					<execution>
						<id>make-assembly</id>
						
						
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		
		</plugins>
	</build>
</project>

When I run the job I got below exception
java.util.concurrent.ExecutionException: java.lang.RuntimeException: com.cloudera.livy.shaded.kryo.kryo.KryoException: java.lang.IndexOutOfBoundsException: Index: 61, Size: 8
Serialization trace:
_transform (hex.aggregator.AggregatorModel$AggregatorParameters)
aggregatorParameters (au.com.vroc.mdm.H2oModel)
com.cloudera.livy.shaded.kryo.kryo.serializers.ObjectField.read(ObjectField.java:125)
com.cloudera.livy.shaded.kryo.kryo.serializers.FieldSerializer.read(FieldSerializer.java:507)
com.cloudera.livy.shaded.kryo.kryo.Kryo.readObject(Kryo.java:694)
com.cloudera.livy.shaded.kryo.kryo.serializers.ObjectField.read(ObjectField.java:106)
com.cloudera.livy.shaded.kryo.kryo.serializers.FieldSerializer.read(FieldSerializer.java:507)
com.cloudera.livy.shaded.kryo.kryo.Kryo.readClassAndObject(Kryo.java:776)
com.cloudera.livy.client.common.Serializer.deserialize(Serializer.java:64)
com.cloudera.livy.rsc.driver.BypassJob.call(BypassJob.java:39)
com.cloudera.livy.rsc.driver.BypassJob.call(BypassJob.java:27)
com.cloudera.livy.rsc.driver.JobWrapper.call(JobWrapper.java:57)
com.cloudera.livy.rsc.driver.BypassJobWrapper.call(BypassJobWrapper.java:42)
com.cloudera.livy.rsc.driver.BypassJobWrapper.call(BypassJobWrapper.java:27)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

Does anyone know how to resolve above?

**Comment by magro** [comment]
@Bazarganigilani Can you reduce the issue to kryo and provide a reproducer, following the ideas of http://www.sscce.org/?

**Comment by NathanSweet** [comment]
We can reopen when the issue has an SSCCE.
