### ISSUE TITLE
Serialize object with not null filed

### ISSUE THREAD

**Issue by ans76** [EsotericSoftware/kryo#563]
public static class TestClassWithLock implements Serializable
    {
        private Integer id;
        private String name;
        private Lock lock = new ReentrantLock();

        public Integer getId()
        {
            return id;
        }

        public void setId(Integer id)
        {
            this.id = id;
        }

        public String getName()
        {
            return name;
        }

        public void setName(String name)
        {
            this.name = name;
        }

        public TestClassWithLock(int id, String name)
        {
            this.id = id;
            this.name = name;
        }

        public void operationNeedsLock()
        {
            lock.lock();
            try
            {
                System.out.println(name + " " + id);
            }
            finally
            {
                lock.unlock();
            }
        }
    }`

    @Test
    public void serializeWithLock()
    {
        TestClassWithLock before = new TestClassWithLock(1 , "test");

        try
        {
            Kryo kryo = new Kryo();
            kryo.setReferences(true);
                    kryo.setInstantiatorStrategy(new StdInstantiatorStrategy());
            kryo.register(TestClassWithLock.class, new BeanSerializer(kryo, TestClassWithLock.class));

            Output output = new Output(new FileOutputStream("files"));
            kryo.writeObject(output, before);
            output.close();

            Input input = new Input(new FileInputStream("files"));
            TestClassWithLock after = kryo.readObject(input, TestClassWithLock.class);

            assert before.getName().equals(after.getName());    //true
            assert before.getId() == after.getId();     //true

            after.operationNeedsLock(); //it will throw NullPointException, lock is null after deserialization
            input.close();
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }

it's may not a issue, I didn't process the not null field `lock` and have no idea about how to maintain the lock is not empty.

**Comment by magro** [comment]
@ans76 the issue is that you're using `BeanSerializer`. If you're removing the line
```java
kryo.register(TestClassWithLock.class, new BeanSerializer(kryo, TestClassWithLock.class));
```
the test passes.
