### ISSUE TITLE
java.util.Collections$ReverseComparator2 Fails to serialize correctly

### ISSUE THREAD

**Issue by magneticflux-** [EsotericSoftware/kryo#569]
```
Class cannot be created (missing no-arg constructor): java.util.Collections$ReverseComparator2
com.esotericsoftware.kryo.KryoException: Class cannot be created (missing no-arg constructor): java.util.Collections$ReverseComparator2
```

There should be a default serializer that handles this wrapper around an existing Comparator correctly.

**Comment by magro** [comment]
How can this be reproduced?

**Comment by magneticflux-** [comment]
If you serialized a custom comparator (one that is serializable) everything works properly. However, serializing the result of `Collections.reverseOrder(comparator);` causes this error:
```
Class cannot be created (missing no-arg constructor): java.util.Collections$ReverseComparator2
com.esotericsoftware.kryo.KryoException: Class cannot be created (missing no-arg constructor): java.util.Collections$ReverseComparator2
	at com.esotericsoftware.kryo.Kryo$DefaultInstantiatorStrategy.newInstantiatorOf(Kryo.java:1319)
	at com.esotericsoftware.kryo.Kryo.newInstantiator(Kryo.java:1127)
	at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1136)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.create(FieldSerializer.java:562)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:538)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
```

Google Guava's SortedSet/Map classes use that reverse method, so the `kryo-serializers` serializers for them fail with a newer version of Guava. Since it's a part of the JDK, it think it should be in `kryo` rather than `kryo-serializers`.

**Comment by magneticflux-** [comment]
Here is a minimal test case for the JDK (no Guava stuff):
```Java
	@Test
	public void testDescendingComparator() {
		final Comparator<String> naturalOrder = new NaturalComparator<>();
		final Comparator<String> reversed = Collections.reverseOrder(naturalOrder);

		final Output output = new Output(4096);
		_kryo.writeClassAndObject(output, reversed);
		output.flush();
		final byte[] serialized = output.getBuffer();
		final Comparator<?> deserialized = (Comparator<?>) _kryo.readClassAndObject(new Input(serialized));
		assertEquals(deserialized, reversed);
	}
```

Using this helper class:
```Java
	private static class NaturalComparator<T extends Comparable<T>> implements Comparator<T> {
		public NaturalComparator() {
		}

		@Override
		public int compare(T o1, T o2) {
			return o1.compareTo(o2);
		}

		@Override
		public boolean equals(Object obj) {
			return obj != null && this.getClass().equals(obj.getClass());
		}

		@Override
		public int hashCode() {
			return 0;
		}
	}
```

**Comment by magro** [comment]
Ok, thanks for the information! Would you like to submit a PR for this?

**Comment by magneticflux-** [comment]
Done! I'm not quite sure on the procedure for registering internal classes. I added it as a default serializer for the `ReverseComparator2` type, but is there some way to make it easier for consumers to actually register the type so they don't have to find an instance of `ReverseComparator2` in their code (or use `Class.forName("")`) to get a class reference?

**Comment by magro** [comment]
Thanks for the PR! Because jdk implementation details are used the serializer could fail on other jdks. Being registered as default serializer in consequence could fail the initialization of Kryo. Therefore it should not be registered as default serializer. The policy so far is exactly this: don't rely on jdk internals in default serializers.

Reading again this issue, I now wonder why you don't just use the StdInstantiatorStrategy to overcome the missing no-arg constructor issue? Like this: 
```
kryo.setInstantiatorStrategy(new Kryo.DefaultInstantiatorStrategy(new StdInstantiatorStrategy()));
```

**Comment by magro** [comment]
@magneticflux- I just tried your test case above with ```kryo.setInstantiatorStrategy(new Kryo.DefaultInstantiatorStrategy(new StdInstantiatorStrategy()));``` and the test passed.
Therefore I think we don't need to change anything (well being aware of the effort you put into the PR).
WDYT?
