### ISSUE TITLE
Transient fields not copied when using StdInstantiatorStrategy

### ISSUE THREAD

**Issue by emichael** [EsotericSoftware/kryo#573]
Whenever I create a basic kryo object with the `StdInstantiatorStrategy`, transient fields are not cloned. This leads to errors; for example, a null pointer when trying to use a cloned `HashSet` (it's backed by a `    private transient HashMap<E,Object> map`). When I use `DefaultInstantiatorStrategy(new StdInstantiatorStrategy())`, the `HashSet` is cloned properly. However, then `HashMultimap` from Guava fails in the exact same way, presumably because unlike `HashSet`, it doesn't have a 0 arg constructor.

See also: https://stackoverflow.com/questions/27771421/how-to-serialize-multimaps-with-kryo

I would rather not resort to one-at-a-time reverting to default serialization, though.

**Comment by isaki-x** [comment]
Most Guava collection objects do not play nice with Kryo. Your best bet when using Guava collections is to write your own serializer. I've written a few for Guava collections and will be open sourcing them in the relatively near future, but that doesn't help you right now.

**Comment by emichael** [comment]
Interesting.

So, my current solution is to use [this cloning library](https://github.com/kostaskougios/cloning) instead, which doesn't seem to special-case Guava collections at all. And from what I gather, both that library and kryo use objenesis, so that's probably not the issue?

Do you have any idea why kryo seems to be skipping transient fields, not just for Guava collections but also for HashSet when StdInstantiatorStrategy is used?

**Comment by isaki-x** [comment]
As an absolute blind guess, it might be defaulting to standard Java serialization for Guava due to the lack of no-arg constructor, which would of course skip transient fields. I'd have to dig through the code to see what is actually happening. Hopefully one of the kryo maintainers can shed some light on this.

**Comment by magro** [comment]
Kryo treats transient fields according to their intent - not to be serialized.

For 3rd party libs there's e.g. [kryo-serializers](https://github.com/magro/kryo-serializers), which also provides support for some guava collections (also for the `HashMultimap` you mentioned, with [HashMultimapSerializer](https://github.com/magro/kryo-serializers/blob/master/src/main/java/de/javakaffee/kryoserializers/guava/HashMultimapSerializer.java). Does this solve your issue, @emichael?

**Comment by emichael** [comment]
Transient fields aren't intended to be serialized **when the default serialization methods are used.** Not serializing them and not using the `writeObject(ObjectOutputStream out)` and `writeObject(ObjectOutputStream out)` is usually going to be wrong.

**Comment by magro** [comment]
@emichael You're probably speaking about your personal expectations / point of view ;-)

If transient fields (in general) are serialized by kryo is defined in [FieldSerializerConfig](https://github.com/EsotericSoftware/kryo/blob/master/src/com/esotericsoftware/kryo/serializers/FieldSerializerConfig.java#L39) which is `false` by default. A user can change this setting according to its needs.

For various classes there are dedicated serializers either to improve performance or to support them at all (for correctness). I already pointed to a solution for guavas `HashMultimap` - maybe you have missed that?

I'm currently not sure what you really want to achieve and which problem you'd like to solve. If what was written before does not help you, it would be good if you could make your motivation and desire more clear.

**Comment by emichael** [comment]
You're right. Failing silently and returning an empty datastructure is definitely the correct behavior.

**Comment by magro** [comment]
@emichael You might want to re-read my previous comment. And please be respectful and kind in your communication.

**Comment by NathanSweet** [comment]
Sarcasm is not welcome here.
