### ISSUE TITLE
Kryo and Hibernate Proxies - handling

### ISSUE THREAD

**Issue by menelaosbgr** [EsotericSoftware/kryo#580]
Hi, I came accross an issue recently when kryo is faced with an object containing a lazy loaded object from hibernate. Essentially the hibernate proxy (the generated class that doesn't really exist) is serialized, and there is later on an error when the object is being read.

For example, with _$$_jvst6bb_1 being the suffix appended to the original className.

```
com.esotericsoftware.kryo.KryoException: Unable to find class: 
XXX.XXX.XXX.CLASSNAME_$$_jvst6bb_1
Serialization trace:
...
com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:156) ~[kryo-shaded-3.0.3.jar!/:na]
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:133) ~[kryo-shaded-3.0.3.jar!/:na]
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:670) ~[kryo-shaded-3.0.3.jar!/:na]
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:118) ~[kryo-shaded-3.0.3.jar!/:na]
```

I am wondering whether there should be a detection and maybe a warning for this situation?
I imagine using reflection that the HibernateProxy instanceType could be detected without needing to include a hibernate dependency.

However, I imagine this is clearly an issue of whether it is in your project scope to detect such bugs and compatibility issues ( in relation to the incoming objects).

In my own case I am dealing with this currently with a forked copy of ObjectField.java that unproxies hibernate proxies to retrieve the actual object: https://gist.github.com/menelaosbgr/00b755fe8e75d622390e39e9151151b1/revisions

```
 			Object value = getField(object);			
			if (value instanceof HibernateProxy){
				HibernateProxy hibernateProxy = (HibernateProxy) value;
				LazyInitializer initializer = hibernateProxy.getHibernateLazyInitializer();
				value = initializer.getImplementation();

				if (INFO)
				    info("kryo", "Write field detected hibernate proxy and unproxying: " + this + " (" + object.getClass().getName() + ")" + " pos=" + output.position());
			    }

```

Thanks,
Menelaos

**Comment by NathanSweet** [comment]
I don't have a great grasp on your situation, but can't you write a serializer to handle this? The serializer could detect if it's a proxy object, get the implementation, and hand it off to another serializer. At any rate, this doesn't seem like a Kryo buy, but instead a configuration problem or approach to serializing your particular classes.
