### ISSUE TITLE
Difference of addDefaultSerializer and register ?

### ISSUE THREAD

**Issue by zhangminglei** [EsotericSoftware/kryo#581]
I found a website with this https://groups.google.com/forum/#!topic/kryo-users/mkX7OM_ks6s
But I still do not understand very well with the difference.

For example, when time to use ```addDefaultSerializer``` and when time to use ```register``` ?
And I found in ```kryo.java``` has the following.

```
addDefaultSerializer(byte[].class, ByteArraySerializer.class);
addDefaultSerializer(char[].class, CharArraySerializer.class);
addDefaultSerializer(short[].class, ShortArraySerializer.class);
addDefaultSerializer(int[].class, IntArraySerializer.class);
 
register(int.class, new IntSerializer()); 
register(String.class, new StringSerializer());
register(float.class, new FloatSerializer());
```
My question is,  why dont wrote like ```addDefaultSerializer(int.class, IntSerializer.class)``` ? Does it work if wrote like this ? And why ? 

Thanks in advance.

**Comment by magro** [comment]
With register you explicitly assign an id for that type + serializer. Setting the default serializer just tells kryo which serializer to use when this type has to be serialized, kryo will then implicitly register the serializer.

When setting setRegistrationRequired(true), which is recommended (and will be the default in 5.0), you'd have to register every occurring type explicitly.

Does this explain it?

**Comment by NathanSweet** [comment]
Please use the mailing list for support/questions. This is an issue tracker.

**Comment by zhangminglei** [comment]
Hi @magro Yea. That is very clear to me now. But I still do not know what the advantage of assign an id for that type + serializer. @NathanSweet  yea. Thanks. I know.

**Comment by magro** [comment]
One advantage is smaller serialized size: https://github.com/EsotericSoftware/kryo/blob/master/README.md#registration

**Comment by zhangminglei** [comment]
@magro Thank you so much, makes sense to me now. With a register id, we can write out this id for that class name instead of writing the full class name. 谢谢
