### ISSUE TITLE
bug in IntArray.addAll()

### ISSUE THREAD

**Issue by fangzheng** [EsotericSoftware/kryo#585]
https://github.com/EsotericSoftware/kryo/blob/master/src/com/esotericsoftware/kryo/util/IntArray.java#L98

In IntArray.addAll() method, the size needed is not calculated correctly:

		int sizeNeeded = size + length - offset;

It should be:

		int sizeNeeded = size + length;

**Comment by isaki-x** [comment]
I have to agree with your assessment.
