### ISSUE TITLE
Add serializer factory parameter for BindCollection annotation

### ISSUE THREAD

**Issue by baltiyskiy** [EsotericSoftware/kryo#588]
Currently, BindCollection always uses ReflectionSerializerFactory. This precludes from customizing serializers like Kryo.setDefaultSerializer() allows. 

Use case: use TaggedFieldSeralizer for collection elements with skipUnknownTags(true). The current limitation blocks adoption of BindCollection, which is desirable since it avoids per-element registration ID overhead.

**Comment by magro** [comment]
@NathanSweet Maybe interesting for 5.0?

**Comment by NathanSweet** [comment]
What exactly is the proposal here?

**Comment by baltiyskiy** [comment]
The proposal is to allow specifying serializer factory for collection elements. For example, add a serializer factory parameter for BindCollection annotation.

**Comment by NathanSweet** [comment]
You could subclass the serializer so you have a place to do your serialization. Using a factory is fine too. We could add a factory to `@DefaultSerializer` add FieldSerializer `@Bind` too.
