### ISSUE TITLE
"com.esotericsoftware.kryo.KryoException: Unknown offset" when running Kryo on Excelsior JET JVM

### ISSUE THREAD

**Issue by ugliansky** [EsotericSoftware/kryo#593]
Hello,

I'm one of the developers of Excelsior JET JVM ([https://www.excelsiorjet.com](https://www.excelsiorjet.com)).
Several our clients have recently faced a problem when running their applications that use Kryo library on our JVM. More specifically, they got the similar stack trace:

```
ERROR - com.esotericsoftware.kryo.KryoException: Unknown offset Serialization trace:
audioMap (net.iii.mote.model.Campaign)
com.esotericsoftware.kryo.KryoException: Unknown offset Serialization trace:
audioMap (net.iii.mote.model.Campaign)
        at com.esotericsoftware.kryo.serializers.UnsafeCacheFields$UnsafeObjectField.getField(Unknown Source)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(Unknown Source)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(Unknown Source)
        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Unknown Source)
```

Their applications worked fine with Oracle JDK, so it looked like the problem in JET.

----

However, the investigation showed that the problem is caused by this code in com.esotericsoftware.kryo.serializers.UnsafeCacheFields$UnsafeObjectField class: 

https://github.com/EsotericSoftware/kryo/blob/ac3f2b03cde6a31fa1ee326fd9272e4380a91db0/src/com/esotericsoftware/kryo/serializers/UnsafeCacheFields.java#L296-L301

In some reason offset (that was originally got by sun.misc.Unsafe) is considered to be non-negative.
Maybe it looks logically, but the fact is that it doesn't have to be a non-negative value.

Actually, this is JVM internal information, so its format can be different for different JVMs. For example, Excelsior JET uses high bits of reference field offset for its internal needs. It doesn't contradict the specification, but because of that these offsets can be "negative". This situation is handled correctly in Excelsior JET implementation of sun.misc.Unsafe native methods, so, Unsafe.getObject(...) and Unsafe.putObject(...) methods work correctly with such "negative" offsets. So, the only problem here is this check in UnsafeObjectField.getField(...) method where the value of an offset is expected to be non-negative.

On the other hand, I don't see why this value is actually checked to be non-negative here, while it is just checked not to be equal "-1" in all other cases. If a similar check for "-1" is used here, this will solve the problem.

----

The problem can be reproduced with attached sample [KryoSample.zip](https://github.com/EsotericSoftware/kryo/files/1965976/KryoSample.zip).

It works fine on Oracle JDK (e.g. when running the following mvn command):

    mvn install compile exec:java -Dexec.mainClass="Test"

but fails on Excelsior JET:

    mvn jet:build jet:run

----

We are really interested in fixing this problem, because Kryo library is popular among our customers, so we want it work with Excelsior JET. If you agree, please take a look at the following PR.

**Comment by NathanSweet** [comment]
Merged, cheers!

BTW, I'm an Excelsior fan! :)

**Comment by ugliansky** [comment]
Thanks a lot!
