### ISSUE TITLE
Inefficiency in Output.require() method

### ISSUE THREAD

**Issue by fangzheng** [EsotericSoftware/kryo#597]
In Output.require(int required) method, there is a loop to double the current capacity, allocate a new buffer, and copy contents over, until the required size is met (https://github.com/EsotericSoftware/kryo/blob/master/src/com/esotericsoftware/kryo/io/Output.java#L168).

If the loop goes multiple iterations, then the buffer allocation and memory copy are wasted in all but the last iteration. 

A better way would be to move the the buffer allocation and memory copy code out of the loop (lines 172-173).

Similar issue exists in ByteBufferOutput.require() method.

**Comment by NathanSweet** [comment]
Good find, thanks!
