### ISSUE TITLE
Suggestion: Kryo serializers modules

### ISSUE THREAD

**Issue by guidomedina** [EsotericSoftware/kryo#604]
Would it be possible to split https://github.com/magro/kryo-serializers into modules and move it to `EsotericSoftware` parent project?

For example:
- `kryo-serializers-jodatime`
- `kryo-serializers-guava`
- etc

I found them but if someone doesn't know the author it is hard to tell if one should use @magro kryo-serializers.

**Comment by guidomedina** [comment]
It will also add more visibility to more contributors.

**Comment by NathanSweet** [comment]
We had #151 for ~5 years and no one has wanted to move them over. I would merge a PR for them but 1) any serializer that is not safe (eg accesses a private, JRE specific API via reflection) needs to be quarantined, apart from the rest of the serializers, and 2) the serializers may need to be cleaned up to match the rest of the library, both code quality and javadocs (note this does not mean excessive javadocs).

**Comment by magro** [comment]
I like the idea of separate modules, because this would also allow to support multiple, incompatible versions of a single library.

**Comment by guidomedina** [comment]
To be honest I'm just copying from Jackson data type modules which follows a nice structure, core libraries + core modules + third party modules.
