### ISSUE TITLE
Kryo 4.0.2 class name bug

### ISSUE THREAD

**Issue by b0c1** [EsotericSoftware/kryo#606]
Hi!
I using Kryo 4.0.2. I serialize an object which contains a class name definition.
When I try to deserialize I got ClassNotFoundException. I dig a deeper and I found the problem in the ```DefaultClassResolver```. It's read a Class name at line 150. After some hour investigation, I found a className string started with a zero byte. If I trim the className the application can load the class.

The writeName method work's as expected it's written out the data without the leading zero byte

**Comment by NathanSweet** [comment]
Likely it is something *before* the class name that should have read the zero byte. Since it didn't, the class name reads the wrong byte and you get a failure.

Does it happens with Kryo 5?

You'll need to post an [SSCCE](http://sscce.org/) before anyone can work on your issue.
