### ISSUE TITLE
The example from the Quickstart section does not work

### ISSUE THREAD

**Issue by pavelrappo** [EsotericSoftware/kryo#609]
https://github.com/EsotericSoftware/kryo#quickstart

```java
import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.io.Output;
import com.esotericsoftware.kryo.io.Input;

Kryo kryo = new Kryo();

SomeClass object = ...

Output output = new Output(new FileOutputStream("file.bin"));
kryo.writeObject(output, object);
output.close();

Input input = new Input(new FileInputStream("file.bin"));
SomeClass object = kryo.readObject(input, SomeClass.class);
input.close();
```

I guess, the idea was to produce a really small snippet of code. However, it might've gone a bit too far. Ideally a copy-pasted snippet could require a simple substitution of `SomeClass` with a real class name and `...` with an expression. But it also requires an introduction of an enclosing class and a method (imports simply cannot dangle on the same level as statements).

Also, isn't it true that `SomeClass` requires a prior registration?
```java
Exception in thread "main" java.lang.IllegalArgumentException: Class is not registered: SomeClass
Note: To register this class use: kryo.register(SomeClass.class);
	at com.esotericsoftware.kryo.Kryo.getRegistration(Kryo.java:495)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:543)
```

**Comment by NathanSweet** [comment]
You're right, it would be nice that at least the first example can be copy/pasted. Cheers!
