### ISSUE TITLE
Generics Serializer bug

### ISSUE THREAD

**Issue by a62611323** [EsotericSoftware/kryo#611]
We found a sequential bug when using kryo 5.0.0-RC2 and a test case could be found as follows.

Attached is the excutable codes, please kindly find it.
classPath:com.alibaba.dubbo.demo.impl.DemoServiceImpl;

code:

public static void main(String[] args) throws FileNotFoundException {
		setSerializableObject();
		getSerializableObject();
	}

	public E getPermissions(Long id) {
		TestB testb = new TestB();
		List《TestC》 listc = new ArrayList《TestC》();
		listc.add(new TestC());
		testb.setList(listc);
		E e = new E();
		e.setTestb(testb);
		return e;
	}

	public static void setSerializableObject() throws FileNotFoundException {

		Kryo kryo = new Kryo();
		kryo.setReferences(false);
		kryo.setRegistrationRequired(false);
		kryo.setInstantiatorStrategy(new StdInstantiatorStrategy());
		kryo.register(E.class);
		Output output = new Output(new FileOutputStream("D:/file1.bin"));
		for (int i = 0; i 《 100000; i++) {
			Map《String, Integer》 map = new HashMap《String, Integer》(2);
			map.put("zhang0", i);
			map.put("zhang1", i);
			kryo.writeObject(output, new DemoServiceImpl().getPermissions(1L));
		}
		output.flush();
		output.close();
	}

	public static void getSerializableObject() {
		Kryo kryo = new Kryo();
		kryo.setReferences(false);
		kryo.setRegistrationRequired(false);
		kryo.setInstantiatorStrategy(new StdInstantiatorStrategy());
		Input input;
		try {
			input = new Input(new FileInputStream("D:/file1.bin"));
			E simple = null;
			while ((simple = kryo.readObject(input, E.class)) != null) {
				// System.out.println(simple.getAge() + " " + simple.getName() +
				// " " + simple.getMap().toString());
			}

			input.close();
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (KryoException e) {

		}
	}

bean:
public class E extends D《TestC》 {
	
	private Integer i;

	public Integer getI() {
		return i;
	}

	public void setI(Integer i) {
		this.i = i;
	}
	
	

}

public class D《K》 implements Serializable{
	TestA《K》 testb;
	public TestA《K》 getTestb() {
		return testb;
	}
	public void setTestb(TestA《K》 testb) {
		this.testb = testb;
	}
	
	
	
	

}

public class TestA《K》 implements Serializable {
	protected List《K》 list;

	public List《K》 getList() {
		return list;
	}

	public void setList(List《K》 list) {
		this.list = list;
	}
	
	

}

public class TestB extends TestA《TestC》 implements Serializable {
	
	
	

}

Exception in thread "main" com.esotericsoftware.kryo.KryoException: java.lang.ArrayIndexOutOfBoundsException: 0
Serialization trace:
testb (com.alibaba.dubbo.demo.bean.E)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:92)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:129)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:543)
	at com.alibaba.dubbo.demo.impl.DemoServiceImpl.setSerializableObject(DemoServiceImpl.java:49)
	at com.alibaba.dubbo.demo.impl.DemoServiceImpl.main(DemoServiceImpl.java:23)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.esotericsoftware.kryo.util.Generics.pushTypeVariables(Generics.java:134)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.pushTypeVariables(FieldSerializer.java:163)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:123)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:558)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
	... 4 more

**Comment by a62611323** [comment]
[DatatablesDemo.zip](https://github.com/EsotericSoftware/kryo/files/2175459/DatatablesDemo.zip)

**Comment by a62611323** [comment]
[kryoDemo.zip](https://github.com/EsotericSoftware/kryo/files/2175624/kryoDemo.zip)

**Comment by NathanSweet** [comment]
Thanks for the report and example. Your example is too complex, uses poor naming, and should be done in one class. Here it is rewritten:
```public class Issue611 {
	public static void main (String[] args) throws FileNotFoundException {
		Kryo kryo = new Kryo();
		kryo.setReferences(false);
		kryo.register(Root.class);
		kryo.register(Value.class);

		Root root = new Root();
		root.value = new Value();

		Output output = new Output(2048, -1);
		kryo.writeObject(output, root);
		output.flush();

		Input input = new Input(output.getBuffer(), 0, output.position());
		Root root2 = kryo.readObject(input, Root.class);
	}

	static public class RootSuper<T> {
		public ValueSuper<T> value;
	}

	static public class Root extends RootSuper<String> {
	}

	static public class ValueSuper<T> {
	}

	static public class Value extends ValueSuper<String> {
	}
}
```

**Comment by dmasyukov** [comment]
@NathanSweet Thank you for the fix! Any plans to cut a release soon?

**Comment by magro** [comment]
@dmasyukov There's now kryo-5.0.0-RC2 available.

**Comment by OrionDevelopment** [comment]
I still get this error in RC4. I will try to figure out why.
Has anybody else see this in 5.0.0-RC4?

**Comment by OrionDevelopment** [comment]
Also tried RC5 just now, and get the same error.
