### ISSUE TITLE
ArrayIndexOutOfBoundsException during serialization

### ISSUE THREAD

**Issue by marianadangelo** [EsotericSoftware/kryo#613]
I'm trying to serialize an object from the Soot program analysis framework, but I'm getting an array index out of bounds exception during serialization. I've added a link to the relevant documentation and GitHub repository, plus the error output and the small sample code triggering the error. Didn't spot any duplicate issues, apologies if there is one. 

documentation: https://www.sable.mcgill.ca/soot/doc/soot/Unit.html 
source code: https://github.com/Sable/soot/blob/develop/src/main/java/soot/Unit.java

error: 
[errortrace.txt](https://github.com/EsotericSoftware/kryo/files/2233108/errortrace.txt)

code snippet:

```import soot.Unit;
import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.io.ByteBufferOutput;
import com.esotericsoftware.kryo.io.Input;
import com.esotericsoftware.kryo.io.Output;

  private byte[] serialize(Unit unit) {
        Kryo kryo = new Kryo();
        kryo.setRegistrationRequired(false);`

        Output output = new ByteBufferOutput(100, -1);
        kryo.writeObject(output, unit);
        output.close();
        return output.toBytes();
    }

    private Unit deserialize(byte[] bytes) {
        Kryo kryo = new Kryo();
        kryo.setRegistrationRequired(false);

        Input input = new Input(bytes);
        Unit unit = kryo.readObject(input, Unit.class);
        input.close();   
        return unit;
    }

    private void serializationTest(Unit srcUnit) {
        System.out.println("Original stmt: " + srcUnit.toString());
        byte[] serializedStmt = serialize(srcUnit); // fails during this
        Unit deserializedStmt = deserialize(serializedStmt);
        System.out.println("Deserialized stmt: " + deserializedStmt.toString());
    }
```

**Comment by NathanSweet** [comment]
Unit is an interface. The implementations can have any kinds of fields and might require that you write serializers for each implementation. Kryo shouldn't crash, but there isn't enough info here to reproduce the problem. Please provide an [executable example](http://sscce.org/) and I'll reopen this issue.

**Comment by marianadangelo** [comment]
Hi NathanSweet, sorry about that, I had hoped that perhaps it was simply an error in my usage. I've gone ahead and updated my original issue post to include the full self contained project. If you have any issues running it just let me know, but hopefully it will just work out of the box. Thanks!

**Comment by NathanSweet** [comment]
The goal is to reproduce the problem using the least code in the simplest possible way. You can assume I have a Java installation and Kryo. I don't want a project or even JAR files, if that can be avoided. I just want a single class with a main method that shows the problem. Eg, this part of your project:
http://n4te.com/x/4626-Pr1S.txt

If I must have a Soot JAR, because Soot classes are involved in serialization, that is fine, but ideally the repro code should not need to run Soot. I'd prefer not to have a huge and complex library involved in what should be a simple reproduction case. Can you construct the problematic objects manually and then try to serialize them?

I tried running it (on Windows) and got: http://n4te.com/x/4627-TTyY.txt

**Comment by marianadangelo** [comment]
Soot is a pretty complex framework and trying to create a unit would be complicated. I’m actually not sure what the issue is since there are only two libraries: the JDK rt jar and the soot jar. 

This does work on Linux out of the box, but since I haven’t used Windows in years I’m afraid I can’t help with your issues.

I guess this issue will go unresolved and I will find another solution to my serialization problem. Cheers.

**Comment by marianadangelo** [comment]
Also, apologies, but just to provide some closure - I fear investing the time in constructing said statement object would risk not actually reproducing the issue (and in retrospect the CPU overhead of serialization may outweigh the overhead of my alternate approach to offloading the required information to disk). For your windows problem, that error stems from it not finding the main class of the tester program. If you’re trying to retrofit the commands to power shell/etc the class may not be being found or something to that effect. I appreciate you taking the time and we can let this issue sleep now. Cheers
