### ISSUE TITLE
Unreadable class name

### ISSUE THREAD

**Issue by jimbok8** [EsotericSoftware/kryo#624]
I have a KryoException - Unable to find class.
I am working through the TRACE Log to find the problem.
However, the Exception message is rather strange as it is unreadable:

Caused by: com.esotericsoftware.kryo.KryoException: Unable to find class: 
![kryo](https://user-images.githubusercontent.com/9551560/46469671-fd7e4700-c7cb-11e8-8b54-be7f28e81fd7.png)

**Comment by NathanSweet** [comment]
Please see this comment I just wrote:
https://github.com/EsotericSoftware/kryo/issues/623#issuecomment-431583014
Likely you have the same problem: something read the wrong number of bytes, then everything read after that is wrong. If you can show an [SSCCE](http://sscce.org/) I'll reopen this issue.

**Comment by jimbok8** [comment]
Sorry, it was totally my fault. Writing one file and then reading an older version in from a different location!
Apologies for wasting your time!
Jim
