### ISSUE TITLE
Kryo 5 Interface Registration Changes

### ISSUE THREAD

**Issue by crykn** [EsotericSoftware/kryo#627]
The following code snippet serializes an object of the class `TestObjectImpl` that implements the interface `TestObject`. In Kryo 4.0.2 this requires a registration for the interface, but not the class itself. In Kryo 5.0.0 the same example only works when both the class and the interface are registered. Is there any reason for this change?

```java
public class KryoInterfacesTest {
	@Test
	public void test() throws FileNotFoundException {
		Kryo kryo = new Kryo();
		kryo.register(TestObject.class);
		// kryo.register(TestObjectImpl.class); // is needed for Kryo 5.0.0

		TestObjectImpl obj = new TestObjectImpl();
		obj.testInt = 12;

		Output output = new Output(new FileOutputStream("test.tmp"));
		kryo.writeClassAndObject(output, (TestObject) obj);
		output.close();

		Input input = new Input(new FileInputStream("test.tmp"));
		TestObject readObj = (TestObject) kryo.readClassAndObject(input);
		input.close();

		assertEquals(obj.getInt(), readObj.getInt());
	}

	static public interface TestObject {
		public int getInt();
	}

	static public class TestObjectImpl implements TestObject {
		public int testInt;

		public int getInt() {
			return testInt;
		}
	}
}
```

**Comment by NathanSweet** [comment]
I don't believe Kryo 4 required the interface to be registered. Only the concrete class needs to be registered and this has not changed. However in v4 registration was not required by default, in Kryo v5 it is (for security reasons and because disabling registration is less efficient).

**Comment by sreejaggu** [comment]
Hi,
We had used Kryo 4.0.2 in our projects. V4 by default registration of classes is not required. We had lot of classes involved in a payload which was serialized with Kryo and then consumed on the other side for processing. 
1. Issue is now we can't upgrade Kryo version due to registration requirement in Kryo 5.0.0.
2. Its impractical to register that many number of classes.

What solution do you suggest for the issue here so that we don't end up changing the code to upgrade Kryo version.

**Comment by isaki** [comment]
I completely agree @sreejaggu, I wanted to look into registering an interface (for example, internally, I use an interface to denote what objects can be serialized) or adding an annotation that could be used. The issue I ran into was that you need consistent identification of the implementations for the ability deserialize data stored to disk. It can be worked around for network streams (the writer and reader can negotiate these numbers similar to non-registered Kryo in v4) but it's not ideal for disk storage as you would need to dump the registration codes in addition to the data for every stored file. I thought about having a serialized registration save that everything can reference, but I'm not sure if there is an appetite for that.
