### ISSUE TITLE
Support no arguments constructor 

### ISSUE THREAD

**Issue by charpty** [EsotericSoftware/kryo#630]
Hi,  D#-#
kryo is fast, but I doubt why kryo not support no arg constructor.

And kryo.addDefaultSerializer(java.lang.Throwable.class, new JavaSerializer()) is not fit for me, cost too much.

so I have to write this:

```
serialize() {
	if (class have no arg constructor) {
		use Kryo
	} else {
		use Jdk
	}
}

deserialize() {
	if (stream header is 0xaced) {
		use jdk
	} else {
		use Kryo
	}
}

```

looking for your reply. D#-#

**Comment by NathanSweet** [comment]
Please see here:
https://github.com/EsotericSoftware/kryo#object-creation
