### ISSUE TITLE
VersionFieldSerializer not respecting config

### ISSUE THREAD

**Issue by PrettyFlower** [EsotericSoftware/kryo#632]
I'm having an issue where VersionFieldSerializer is copying transient fields even though I've set that to false in the config I'm passing to it. Looks like the constructor for VersionFieldSerializer that accepts a config as the third argument isn't calling the super() method with the config parameter. TaggedFieldSerializer appears to do this so I'm guessing it just needs that argument passed in.

**Comment by NathanSweet** [comment]
Fixed in 3fb504ba3644aeb230715e5ff81525eec1c1cb50, thanks!
