### ISSUE TITLE
How to pronounce Kryo 😆

### ISSUE THREAD

**Issue by oldratlee** [EsotericSoftware/kryo#633]
I searched

- the latest [README.md](https://github.com/EsotericSoftware/kryo/blob/33dc2800b4b502c08ec1f6adfe0f6432a17c8923/README.md)
- [Kryo mailing list](https://groups.google.com/forum/#!searchin/kryo-users/pronounce%7Csort:date)
- [stackoverflow.com](https://stackoverflow.com/search?q=kryo+pronounce) 
- and google ( find https://www.howtopronounce.com/kryo/ , but this is not like the official version )

, didn't find the pronounce of `Kryo`.

What's the official pronounce of `Kryo` from the `Kryo` project members?

PS: **_`Kryo` rocks!_**

**Comment by NathanSweet** [comment]
Yep, like "cry-oh", short for [cryogenics](https://en.wikipedia.org/wiki/Cryogenics) as isaki said. Too bad it has a silly K, but finding a good name that isn't taken yet is hard/impossible!
