### ISSUE TITLE
[Question] Sniffing kryo serialization?

### ISSUE THREAD

**Issue by kkocel** [EsotericSoftware/kryo#645]
Is there any tool or deserialization mechanism (wireshark pluign?) to sniff kryo serialized objects?

**Comment by NathanSweet** [comment]
Nope. The best you can do is enable trace logging.

**Comment by NathanSweet** [comment]
Also, please use the mailing list for questions. This is an issue tracker for Kryo problems that need fixing. Cheers!

**Comment by kkocel** [comment]
Thanks for the info!
