### ISSUE TITLE
Can I have kryo registration required and skip registration of class

### ISSUE THREAD

**Issue by r0bb23** [EsotericSoftware/kryo#649]
In my current work I've run into 2 separate situations where a class needs to be registered according to kryo with that setting on. However in both those cases I don't really have the option to register those classes (both are private in different ways). So how does one not register a class/ignore the warning while using the registration required option?

**Comment by NathanSweet** [comment]
You can't serialize a class that isn't registered unless you use `kryo.setRegistrationRequired(false)`.

This is an issue tracker. Please use the mailing list for questions/discussion.

**Comment by krishna81m** [comment]
again, these classes could be coming from libraries and there are some unnecessary classes that should be ignored or specific ones that should only be serialized?
