### ISSUE TITLE
Trouble checking eof when using chunked input

### ISSUE THREAD

**Issue by aaudiber** [EsotericSoftware/kryo#651]
This test is failing in kryo 4.0.2 with `com.esotericsoftware.kryo.KryoException: Buffer underflow`

```java
  @Test
  public void test() {
    InputChunked input = new InputChunked(new ByteArrayInputStream(new byte[]{}));
    input.eof();
  }
```

Is there a better way to check for the end of the stream when reading chunked data?

**Comment by NathanSweet** [comment]
I've fixed this in the `master` (v5) and `kryo-4` branches.
