### ISSUE TITLE
Support for static registering?

### ISSUE THREAD

**Issue by Shaunwild97** [EsotericSoftware/kryo#657]
Would be great if we could call the static method

```
Kryo.registerGlobal(MyClass.class)
```

and it be added to each Kryo instance when it's created. I can't really see a reason why the Kryo registry is handled on the instance at all though to be honest.

**Comment by Shaunwild97** [comment]
I created a pull request for said change #658

**Comment by NathanSweet** [comment]
Moved discussion to PR.
