### ISSUE TITLE
Proguard code.

### ISSUE THREAD

**Issue by o2e** [EsotericSoftware/kryo#659]
Can get an annotation to specify the property name of the object? Used to support Proguard code. For example, Gson lib @SerializedName ("name")

**Comment by NathanSweet** [comment]
It's not much obfuscation to rename the fields, then put in an annotations that puts the original names back. Why not configure Proguard to not obfuscate field names? Something like:

```-keepclassmembers class com.example.YourClass { <fields>; }```

**Comment by o2e** [comment]
keepclassmembers Let me feel insecure

**Comment by o2e** [comment]
> 重命名字段并没有太多的混淆，然后放入一个将原始名称放回原处的注释。为什么不将Proguard配置为不混淆字段名称？就像是：
> 
> ```
> -keepclassmembers class com.example.YourClass { <fields>; }
> ```

keepclassmembers  Let me feel insecure

**Comment by NathanSweet** [comment]
Agreed with @isaki. You don't even need a separate project or module, you can configure the specific fields to keep, all the fields for a class, or all the fields for package.
