### ISSUE TITLE
Issue with Generics on Android 

### ISSUE THREAD

**Issue by Arthas26** [EsotericSoftware/kryo#661]
I have the following class(DictionaryKeyValue) as a field of another class which is sent via UDP

public class DictionaryKeyValue<K, V>
{
	public HashMap<K, V> hashMap
        ....
}

While de-serializing the inner hashMap field with type parameters, the de-serializer which is a MapSerializer fails to resolve the generic type of the key and value parameters.

Further digging in , I found that the 'typeVariable' of parameter "K" does not match with any parameter in arguments array of currently pushed generic type. Also note that the last pushed Generic arguments were for DictionaryKeyValue<K,V>, so the argument array has parameters named "K" and "V" along with the resolved types of both parameters but none of those match with parameter "K" of hashMap.

What concerns me that all of this works on the desktop build of the same project when both client and server are running on the desktop(parameters even have the same reference).

And it also works on android if I change "arguments[i] == typeVariable" to "arguments[i].equals(typeVariable)" in Generics.java -> resolveTypeVariable(typeVariable) but otherwise fails.
The class was serialized on desktop and de-serilization happens on android device running android 8.0.0(Samsung Galaxy S7) in the failure case.

**Comment by theigl** [comment]
Hi @Arthas26,

There have been many improvements to Kryo's generics handling in the latest RCs. A number of corner cases have been fixed and, as a last resort, you can now opt-out of generics optimization altogether.

If this is still relevant to you, please try again with the newest RC.

**Comment by magro** [comment]
Closed for now, please reopen if it's still occurring with the latest version.
