### ISSUE TITLE
Issue with deserializing files in kryo-5.0.0-RC3-SNAPSHOT 

### ISSUE THREAD

**Issue by ad-van-erp** [EsotericSoftware/kryo#666]
Good evening,

I think I might have ran into a bug in kryo-5.0.0-RC3-SNAPSHOT.

When I tried to deserialize a file created with this version (using readClassAndObject() in Kryo), I got a Kryo-exception: "Encountered unregistered class ID: 13994".
I then tried to debug the decompiled code and found out that Kryo was incorrectly interpreting (in DefaultClassResolver, readClass()) the standard serialization protocol bits (AC ED 00 05)) as classId's. These bytes were interpreted as 13996, and, when deduced with 2, considered as the registration id for the class to be deserialized. Hence the exception.

I'm not sure what the root cause of this is (maybe an underlying framework,, maybe Kryo, maybe I did something wrong), but I hope somebody could look into it.

If you need additional information, I would be glad to supply it, of course.

Kind regards,

Ad van Erp

**Comment by Arthas26** [comment]
Did you check the class registration order ?

**Comment by ad-van-erp** [comment]
I think so. I have create a GitHub project (https://github.com/ad-van-erp/Kryo_5_0_0_RC3_SNAPSHOT_SerialisatieTest) that replicates the error. Perhaps you could look at it.

**Comment by laymain** [comment]
This issue may happen when you try to deserialize an incomplete byte array.
You should properly close your streams, as I can see you forgot to:

```java
private static void serialseerObject(final Project actueelProject, final File file) throws IOException {

        FileOutputStream fo = new FileOutputStream(file);
        Output output = new Output(fo);
        ObjectOutputStream so = new ObjectOutputStream(fo);

        Kryo kryo = new Kryo();

        registreerKlassen(kryo);

        kryo.writeClassAndObject(output, actueelProject);
        output.close();
    }
```

Try with:

```java
private static void serialseerObject(final Project actueelProject, final File file) throws IOException {
  try (
    FileOutputStream fo = new FileOutputStream(file);
    Output output = new Output(fo)
  ) {
    Kryo kryo = new Kryo();
    registreerKlassen(kryo);
    kryo.writeClassAndObject(output, actueelProject);
  }
}
```

**Comment by ad-van-erp** [comment]
Thanks @laymain, it works. The actual code is:

```
        FileOutputStream fo = new FileOutputStream(file);
        Output output = new Output(fo);

        Kryo kryo = new Kryo();

        registreerKlassen(kryo);

        kryo.writeClassAndObject(output, actueelProject);
        output.close();
        fo.close();

```

**Comment by laymain** [comment]
Glad it worked.
Feel free to use [try-with-resource](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) 😉
