### ISSUE TITLE
A `System.out.println` has been forgotten in the Output.java class

### ISSUE THREAD

**Issue by laymain** [EsotericSoftware/kryo#668]
Hi,

I'm seeing debugging message when I'm using kryo serializer:

```
36
36
36
36
36
36
```

It seems that a `System.out.println` has been forgotten in the Output.java class

https://github.com/EsotericSoftware/kryo/blob/2824ca9398c5e400a824ff83edc9c1a6f492505b/src/com/esotericsoftware/kryo/io/Output.java#L261-L274

**Comment by laymain** [comment]
Someone has submitted a pull request: https://github.com/EsotericSoftware/kryo/pull/667

**Comment by magro** [comment]
I just released kryo-5.0.0-RC4 with a fix for this.
