### ISSUE TITLE
IdentityObjectIntMap.get slow due to System.identityHashCode perf bug

### ISSUE THREAD

**Issue by amuraru** [EsotericSoftware/kryo#671]
https://github.com/EsotericSoftware/kryo/blob/kryo-parent-4.0.2/src/com/esotericsoftware/kryo/util/IdentityObjectIntMap.java#L320 is using the `System.identityHashCode` that's being impacted by https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6378256

**Comment by isaki** [comment]
If you use a newer JVM (Java 11) or use the server JVM for Java 8, you should be fine.

If I understand correctly, this is an issue with the HotSpot JIT for Java 8 (or Java 9 prior to b108). If this is a long-lived backend process and this level of performance matters, you should be using the server JVM anyway as you will get better performance at the cost of a slower startup/warm up time (which is worth it for long lived processes). If this is a short lived process using a newer JVM should help.

A brief look at the code seems to imply that using `Object.hashCode()` is not ideal given Kryo has no control over how fast/well written (i.e. avoiding conflicts) custom versions of this method are written.

**Comment by dgrnbrg** [comment]
This is also affecting my Kryo workload on Java 1.8.0_201b09 using the `-server` argument.

**Comment by MarcMil** [comment]
This is not surprising, -server does nothing in most cases.
See https://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html
```
-client

    Selects the Java HotSpot Client VM. The 64-bit version of the Java SE Development Kit (JDK) currently ignores this option and instead uses the Server JVM.

    For default JVM selection, see Server-Class Machine Detection at
    http://docs.oracle.com/javase/8/docs/technotes/guides/vm/server-class.html
```
-> Server is used for 64 bit Java versions anyways, which most people (hopefully) use. For the others:
```
Starting with Java SE 5.0, when an application starts up, the launcher can attempt to detect whether the application is running on a "server-class" machine and, if so, use the Java HotSpot Server Virtual Machine (server VM) instead of the Java HotSpot Client Virtual Machine (client VM). The aim is to improve performance even if no one configures the VM to reflect the application it's running. In general, the server VM starts up more slowly than the client VM, but over time runs more quickly.
Note: For Java SE 6, the definition of a server-class machine is one with at least 2 CPUs and at least 2GB of physical memory.

In Java SE 6, server-class detection occurs if neither -server nor -client is specified when launching the application on an i586 or Sparc 32-bit machine running Solaris or Linux. 
```

These requirements are met by almost all somewhat modern computers. As such, -server can probably be omitted.
