### ISSUE TITLE
Can't serialize java.nio.file.Path

### ISSUE THREAD

**Issue by JamesArthurHolland** [EsotericSoftware/kryo#676]
Caused by: com.esotericsoftware.kryo.KryoException: java.lang.IllegalArgumentException: Class is not registered: sun.nio.fs.UnixPath
Note: To register this class use: kryo.register(sun.nio.fs.UnixPath.class);
Serialization trace

UnixPath.class is private and can't be accessed from outside sun.nio.fs,

looked at https://groups.google.com/forum/#!topic/kryo-users/hcn_Msy9Ai0 but setClass is no longer public.

**Comment by ericxsun** [comment]
hope `Class.forName` could be help.

**Comment by magro** [comment]
Closed for now, please reopen if this issue still exists.
