### ISSUE TITLE
Deserialization Results in Different HashCode 

### ISSUE THREAD

**Issue by trenton-uima** [EsotericSoftware/kryo#677]
What steps will reproduce the problem?
Run the sample file given in the readme, but printing out the hashcode of the Objects before and after deserializing. 

What is the expected output? What do you see instead?
    Expected: Same hash code for original object and de-serialized object
    Actual: Different hash codes

What version of the Kryo are you using?
    Newest version
================== Source Code ======================
```
public class KryoSerializationTest {
    static public void main (String[] args) throws Exception {
        Kryo kryo = new Kryo();
        kryo.register(SomeClass.class);

        SomeClass object = new SomeClass();
        object.value = "Hello Kryo!";
        System.out.println(object.hashCode());  // Hashcode is 979294118

        Output output = new Output(new FileOutputStream("file.bin"));
        kryo.writeObject(output, object);
        output.close();

        Input input = new Input(new FileInputStream("file.bin"));
        SomeClass object2 = kryo.readObject(input, SomeClass.class);
        System.out.println(object2.hashCode()); // Hashcode is 215145189, different!!
        input.close();
    }
    static public class SomeClass {
        String value;
    }
}
```

**Comment by piotr-j** [comment]
Since deserialization creates new object and the class doesnt override hashcode they will be different. This is very much expected. Thats why you override hashcode and equals.
