### ISSUE TITLE
Serializers for class hierarchies.

### ISSUE THREAD

**Issue by JonathanZarnstorff** [EsotericSoftware/kryo#678]
It would be nice if we could register a serializer for say an interface that could be used in situations where the number of concrete classes is too great. Or maybe an unhandled serializer that takes the type and can do a last stand attempt to serialize/deserialize.

**Comment by RiotR1cket** [comment]
As a workaround you can write your own SerializerFactory, the implementation would be something like:

```
public Serializer makeSerializer(Kryo kryo, Class<?> type) {
    if (FooInterface.class.isAssignableFrom(type)) {
        // return your desired serializer
    }
    // return a default serializer
}
```

**Comment by magro** [comment]
Closed for now, please reopen if this is still an issue.
