### ISSUE TITLE
JDK11 compatibility

### ISSUE THREAD

**Issue by Syed-SnapLogic** [EsotericSoftware/kryo#679]
Hi,
  Is the latest release of your kryo compatible with JDK11?  Also, is your library an alternate for https://github.com/magro/kryo-serializers?  If yes, do you have any guidelines to do the migration?

**Comment by theigl** [comment]
We are using Kryo 4 with JDK11 without any problems. Kryo 5 still has some issues with generics (#654, #655) so I would stick with Kryo 4 for now.

https://github.com/magro/kryo-serializers provides additional serializers for some JDK classes as well as external libraries like Guava.

**Comment by NathanSweet** [comment]
Thanks @theigl. Unfortunately I haven't been able to get to the generics problems for a long time.

There's this: https://github.com/EsotericSoftware/kryo/wiki/Migration-to-v5

**Comment by dano** [comment]
@NathanSweet Did you close this because you don't plan on making Kryo JDK11-compatible, or just because you answered the original question?

**Comment by ambition-consulting** [comment]
@Theigl obviously answered it? It is JDK11 compatible already now - the problems with generics are unrelated to the JDK.
