### ISSUE TITLE
Support Unaligned Unsafe

### ISSUE THREAD

**Issue by re-thc** [EsotericSoftware/kryo#682]
JDK10+ has a new jdk.internal.misc.Unsafe class (which sun.misc.Unsafe now proxies for). In this class there are new unaligned methods for basic unsafe operations that offer better performance. Possible to create an input/output for this? Thanks.

**Comment by theigl** [comment]
@hc-codersatlas: I added basic JDK11 support in #724 so it would now be possible to implement `UnalignedUsafeInput` and `UnalignedUsafeInput`. Do you want to submit a PR for this?
