### ISSUE TITLE
KryoException: Encountered unregistered class ID: 52

### ISSUE THREAD

**Issue by kdung** [EsotericSoftware/kryo#690]
I am using Kryo version 5.0-RC1 to serialize objects of type ConcurrentHashMap<String, ConcurrentHashMap<String, byte[]>>, encode it to String for storing. 
The same application running on another machine then take this same string and try to deserialize it (same Kryo version), and got this error:

Log:
com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 52.
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:155).
        at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:674).
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:785).
        at com.paypal.risk.simulation.utils.KryoSerializer.deserialize(KryoSerializer.java:42).

The class ID in stacktrace is random from 47 - 110++ 
While running unit test to trace log for the same code, my idToRegistration map has only 11 items.

My code to initialize Kryo and serialize/deserialize:

public class KryoSerializer {

    private static class SingletonHolder {
        private static KryoSerializer instance = new KryoSerializer();
    }

    private static final ThreadLocal<Kryo> kryoThreadLocal = ThreadLocal.withInitial(() -> {
        Kryo kryo = new Kryo();
        kryo.register(Map.class);
        kryo.register(ConcurrentHashMap.class);
        kryo.register(byte[].class);
        return kryo;
    });

    public static KryoSerializer getInstance() {
        return KryoSerializer.SingletonHolder.instance;
    }

    public byte[] serialize(Object object) throws IOException {
        try (ByteArrayOutputStream bos = new ByteArrayOutputStream();
             Output output = new Output(bos)) {
            kryoThreadLocal.get().writeClassAndObject(output, object);
            return output.toBytes();
        }
    }

    public Object deserialize(byte[] bytes) throws IOException {
        try (ByteArrayInputStream inputStream = new ByteArrayInputStream(bytes);
             Input input = new Input(inputStream)) {
            return kryoThreadLocal.get().readClassAndObject(input);  // line 42
        }
    }
}

**Comment by kdung** [comment]
The application has another library which also using Kryo of same version, could it be the reason that the same class might be registered with different id number?

**Comment by theigl** [comment]
@kdung: If this is still relevant to you, please try again with the latest RC. There have been many fixes and improvements in recent versions.

**Comment by kdung** [comment]
Thanks @theigl. I'll try out the new version.

**Comment by magro** [comment]
Closed for now, please reopen if it's still occurring with the latest version.
