### ISSUE TITLE
RC1 and RC4 serialization not compatible

### ISSUE THREAD

**Issue by dastultz** [EsotericSoftware/kryo#694]
Hello,

We recently upgraded our project from 5.0.5-RC1 to 5.0.5-RC4. We are serializing DTOs to Redis. We have run into a problem in that the 2 versions write different values. I have a Kotlin DTO that looks like this:

```
data class GlobalPropertyDto(
    val valueText: String? = null,
    val valueNumber: Double? = null,
    val valueTimestamp: Date? = null
)
```
Given a DTO that has "US/Eastern" as the "valueText" property

RC1 writes the following to Redis:
"\x01\x00\x01US/Easter\xee\x00"

RC4 writes this:
"\x00US/Easter\xee\x00"

The result is that when RC1 tries to deserialize something written by RC5, 2 characters are being lopped off. The DTO is properly created but the "valueText" property reads "/Eastern". I may be getting the details a little wrong.

At the present I have the option of stopping my application, clearing the Redis cache, deploying the new version and moving on. That won't be the case soon as we move towards rolling deploys of a clustered application. I'm going to have 2 version of the software running at the same time.

The documentation states that serialization is compatible across these version. Am I not understanding something.

**Comment by theigl** [comment]
This happened because RC3 disabled references by default. To produce the same output as RC1/RC2 you have to re-enable references using `Kryo.setReferences(true)`.

**Comment by magro** [comment]
Closed for now, please reopen if this is still an issue.
