### ISSUE TITLE
Guava MutableClassToInstanceMap serialization problem

### ISSUE THREAD

**Issue by a124t6io** [EsotericSoftware/kryo#700]
I used MutableClassToInstanceMap in my class to be serialized, which is a class in guava. Serialization is successful, but "Unable to evaluate the expression Method threw 'java.lang.NullPointerException' error" will be reported when deserializing. I traced the source code and found that the problem occurred in the instantiation of class MutableClassToInstanceMap, this problem occurs when running instantiation code T inst = (T) ca.newInstance(initargs);  in java/lang/reflect/Constructor.java
	
I wrote a test code to reproduce the problem.
	Kryo kryo = new Kryo();
	kryo.setReferences(false);
	kryo.setRegistrationRequired(false);
	kryo.setInstantiatorStrategy(new Kryo.DefaultInstantiatorStrategy(new StdInstantiatorStrategy()));
	MutableClassToInstanceMap result = kryo.newInstance(MutableClassToInstanceMap.class);

Similar problems occur in both 4. X.x and 5. X.x versions. I want to know what is the cause of the problem and how to fix it.

**Comment by magro** [comment]
You should write a custom serializer your that class.

There are guava related serializers in https://github.com/magro/kryo-serializers already - you might also submit a PR with your serializer then 😃

**Comment by magro** [comment]
Closed for now, please reopen if this is still an issue.
