### ISSUE TITLE
if I set bufferSize to -1,it will throw java.lang.NegativeArraySizeException

### ISSUE THREAD

**Issue by love390** [EsotericSoftware/kryo#701]
/** Creates a new Output for writing to a byte[].
	 * @param bufferSize The initial size of the buffer.
	 * @param maxBufferSize If {@link #flush()} does not empty the buffer, the buffer is doubled as needed until it exceeds
	 *           maxBufferSize and an exception is thrown. Can be -1 for no maximum. */
It doesn't correspond to the permission-1 mentioned in the comment

**Comment by theigl** [comment]
Which version of Kryo are you using? There are several passing tests that use `-1` for maximum size in the current codebase.

Please provide a testcase to reproduce this issue.

**Comment by magro** [comment]
Closed for now, please reopen if it's still occurring with the latest version.
