### ISSUE TITLE
Synchronized(RandomAccess)List in Kryonet

### ISSUE THREAD

**Issue by Dawidan-orig** [EsotericSoftware/kryo#732]
Hello. i'm trying to transfer SynchronizedList in my network and taking exception, that SynchronizedRandomAccessList is not registered.
So i tried this:
`kryo.register(Collections.synchronizedList(new ArrayList<>()).getClass());`
and this worked; but now there are other problem:

`com.esotericsoftware.kryonet.KryoNetException: Error during deserialization.
        at com.esotericsoftware.kryonet.TcpConnection.readObject(TcpConnection.java:141)
        at com.esotericsoftware.kryonet.Client.update(Client.java:255)
        at com.esotericsoftware.kryonet.Client.run(Client.java:338)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.esotericsoftware.kryo.KryoException: Class cannot be created (missing no-arg constructor): java.util.Collections$SynchronizedRandomAccessList`

how do i create zero-constructor?

**Comment by theigl** [comment]
There is no builtin serializer for these collections, but you can register the [`SynchronizedCollectionsSerializer`](https://github.com/magro/kryo-serializers/blob/master/src/main/java/de/javakaffee/kryoserializers/SynchronizedCollectionsSerializer.java) from the [kryo-serializers project](https://github.com/magro/kryo-serializers).

**Comment by Dawidan-orig** [comment]
Well, i tried
But Android Studio explosed with "Gradle duplicate" errors.

Maybe I simply add to my project incorrectly?
![image](https://user-images.githubusercontent.com/59401200/83325118-b2535a80-a272-11ea-945f-530bbd6da55a.png)

`dependencies {
    ***
    implementation 'de.javakaffee:kryo-serializers:0.45'
    ***
}
`

Errors:
![image](https://user-images.githubusercontent.com/59401200/83325171-03634e80-a273-11ea-9159-d1c6427b9ae3.png)

**Comment by theigl** [comment]
It seems you are using Kryo 2.24.0 in your project.

`kryo-serializers` transitively depends on Kryo 5.0.0. Try to exclude the transitive dependency.

**Comment by Dawidan-orig** [comment]
![image](https://user-images.githubusercontent.com/59401200/83328170-bb035b00-a289-11ea-9fbc-011cfa4fedaa.png)
my implementations, just in case.

Can you say please, where i can exclude it?

**Comment by theigl** [comment]
I don't know Android Studio at all but this seems to be the way to go:

https://developer.android.com/studio/build/dependencies#exclude_dependencies

**Comment by Dawidan-orig** [comment]
That worked! thank you!
