### ISSUE TITLE
Kryo Compatiblity between 4.0.x

### ISSUE THREAD

**Issue by daniel2009** [EsotericSoftware/kryo#741]
Currently I use Kryo as the serializer between my sprintboot services, but I also have to handle the compatibility issues. I have a serivce A which provides an RPC API, and another service B uses that API. And then I try to test if the serialization works. 

There are two changes in service A. Firstly, I add a new field(an arraylist<Integer>) in the RPC response class, named ResponseForB. The second one is that, I have a KryoPool and build a kryo instance with some registeration like:

// I cannot set readUnknownField because I am still using kyro:4.0.2
CompatibleFieldSerializer serializer = new CompatibleFieldSerializer(kryo, ResponseForB.class);
kryo.register(ResponseForB.class, serializer);
kryo.register(ArrayList.class);

But I don't mvn deploy for service A. Then service B and service A will use different structure of ResponseForB, and then produces incompatibility. And actually, it will produce a Kryo exception in service B, when it try to readObject. So do I have to make any changes in service B?

I guess since I don't set readUnknownField, so the additional field may serialize and write as string together with the original fields. It isn't ignored. I think it is a bug, becauce the expectation is that it should be ignored, which is also the requirement of backward compatibility.

So do you have any advices about this issue?

**Comment by daniel2009** [comment]
Now I update Kyro to 5.0.x, but KryoPool was removed from it. Is there any alternative way to make it?

**Comment by theigl** [comment]
> Now I update Kyro to 5.0.x, but KryoPool was removed from it. Is there any alternative way to make it?

See https://github.com/EsotericSoftware/kryo#pooling

**Comment by theigl** [comment]
> I guess since I don't set readUnknownField, so the additional field may serialize and write as string together with the original fields. It isn't ignored. I think it is a bug, becauce the expectation is that it should be ignored, which is also the requirement of backward compatibility.

In Kryo 4 it was the default behavior to ignore unknown fields so this is most likely not the issue.

Without a minimal example that shows exactly what and how you are serializing and deserializing this is going to be difficult to diagnose.

In many cases, Kryo 5 and Kryo 4 are *not* serialization compatible and you will have to:

- deploy the new version to all services at the same time OR
- include both Kryo 4 and Kryo 5 in the classpath and dynamically switch to Kryo 5 once all services have it on the classpath

 See https://github.com/EsotericSoftware/kryo/wiki/Migration-to-v5.

**Comment by theigl** [comment]
Closing for now. If you have further questions please reopen or create another ticket.
