### ISSUE TITLE
the latest version is still RC6 in maven central. 

### ISSUE THREAD

**Issue by lifeinwild** [EsotericSoftware/kryo#742]
https://search.maven.org/search?q=g:com.esotericsoftware%20AND%20a:kryo

No one can use RC7 from pom.xml.

**Comment by theigl** [comment]
@lifeinwild: There seems to have been some issue with the release. It made it to GitHub, but not to Maven Central. Should be fixed in a couple of days.

**Comment by magro** [comment]
Thanks for reporting! I just checked at Sonatype, and the version was closed but not released - most probably that was my fault.

I released again, now it's there: https://repo1.maven.org/maven2/com/esotericsoftware/kryo/5.0.0-RC7/
