### ISSUE TITLE
Illegal reflective access (kryo-5.0.0-RC7)

### ISSUE THREAD

**Issue by NoahR02** [EsotericSoftware/kryo#747]
I just started using kryo today and when I was running [the ](https://github.com/EsotericSoftware/kryo#user-content-quickstart)example from the website, I was getting these warnings :

`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.esotericsoftware.kryo.unsafe.UnsafeUtil (file:/C:/Gradle/caches/modules-2/files-2.1/com.esotericsoftware/kryo/5.0.0-RC7/2508d4e0c6c3317185f592eef3d7ff8afcfb61f5/kryo-5.0.0-RC7.jar) to method sun.nio.ch.DirectBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of com.esotericsoftware.kryo.unsafe.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release`

I downloaded kryo with Gradle via this [repo](https://mvnrepository.com/artifact/com.esotericsoftware/kryo/5.0.0-RC7).

**Comment by theigl** [comment]
@NoahR02: This is just a warning in current JDK versions. You can ignore it, or prevent Kryo from accessing Unsafe by starting your process with:

    -Dkryo.unsafe=false

See #626 and #543
