### ISSUE TITLE
binary equality of serialized byte[]

### ISSUE THREAD

**Issue by lifeinwild** [EsotericSoftware/kryo#748]
When serializing in any environment, if the original object is equivalent, is the byte [] created by kryo equivalent?

```
	public byte[] serializeByKryo(final Object o) throws IOException {
		Kryo kryo = new Kryo();
		kryo.setRegistrationRequired(false);
		final byte[] b;
		try (final ByteArrayOutputStream bos = new ByteArrayOutputStream();
				final Output output = new Output(bos)) {
			kryo.writeClassAndObject(output, o);
			output.flush();
			b = bos.toByteArray();
		}
		return b;
	}

	public byte[] serializeByKryoInOtherEnv(final Object o) throws IOException {
		//download serialized byte[] from other process in other env.
		return null;//mock
	}

	@Test
	public void test() throws IOException {
		Random rnd = new Random();
		HashMap<Long, String> o = new HashMap<>();
		o.put(rnd.nextLong(), "" + rnd.nextLong());
		o.put(rnd.nextLong(), "" + rnd.nextLong());
		o.put(rnd.nextLong(), "" + rnd.nextLong());
		byte[] serialized = serializeByKryo(o);
		byte[] serializedInOtherEnv = serializeByKryoInOtherEnv(o);
		assertEquals(true, Arrays.equals(serialized, serializedInOtherEnv));
	}
```

**Comment by theigl** [comment]
@lifeinwild: The byte array should be equivalent as long as you

- use the exact same Kryo configuration
- use the same Kryo version or serialization compatible versions of Kryo (see the release notes for more info on serialization compatibility)
- do not use Unsafe variants of Input and Output as they may produce different output on different architectures

**Comment by lifeinwild** [comment]
> do not use Unsafe variants of Input and Output as they may produce different output on different architectures

these are Unsafe variants?
- UnsafeByteBufferInput
- UnsafeInput
- UnsafeByteBufferOutput
- UnsafeOutput

I see, thx.
