### ISSUE TITLE
Kryo is reset twice when used in a pool

### ISSUE THREAD

**Issue by theigl** [EsotericSoftware/kryo#754]
Kryo 5 has a `Poolable` interface for objects that can be used with `Pool`.

When such an object is returned to the pool, `Poolable.reset()` is called:

	/** Called when an object is freed to clear the state of the object for possible later reuse. The default implementation calls
	 * {@link Poolable#reset()} if the object is {@link Poolable}. */
	protected void reset (T object) {
		if (object instanceof Poolable) ((Poolable)object).reset();
	}

This makes using `Input` und `Output` much easier in combination with pools.

The problem is that the `Kryo` class implements `Poolable` as well. So if `autoReset` is enabled (the default), `Kryo.reset()` will be called twice. First by auto-reset at the end of serialization, then when the object is returned to the pool.

This operation is potentially expensive, especially when references are enabled and class registration is not required.

We have two options to fix this:

1. Do not let `Kryo` implement `Poolable`
2. Document that `autoReset` should be disabled when Kryo is used in a pool

@magro: What do you think? We should address this before releasing 5.0 Final.

**Comment by magro** [comment]
For option 1 (Do not let Kryo implement Poolable) I'd say things would work as expected.
Probably I'm missing something - are there any drawbacks?

**Comment by theigl** [comment]
> Probably I'm missing something - are there any drawbacks?

There is only one potential issue: If `autoReset` is disabled and Kryo is not reset manually before it is returned to the pool. Currently, the pool would ensure that the Kryo instance is always reset.

I don't have a strong opinion on this. I'm OK with either option.

**Comment by magro** [comment]
Erm, right 😉

I'd think that users turning off `autoReset` do this for a good reason, for them it should be to manually reset the Kryo instance before returning it to the pool. We should only document this so that this is clear.

So I'd prefer option 1.

**Comment by theigl** [comment]
Agreed 😉

I'll create a PR tomorrow morning.

**Comment by magro** [comment]
👍 Awesome!

**Comment by theigl** [comment]
@magro: I just pushed #758.
