### ISSUE TITLE
Is it possible to change [--depth == 0] to [--depth <= 0]?

### ISSUE THREAD

**Issue by lsr-flying** [EsotericSoftware/kryo#762]
https://github.com/EsotericSoftware/kryo/blob/80fe965c507a8775e142264b79be3c3b1111749c/src/com/esotericsoftware/kryo/Kryo.java#L642
Kryo is not thread safe as designed. But as it comes to race condition(consider I'm not familiar with kryo), depth might be negative, and thus kryo will (most likely) not autoset, I assume it not a normal behavior.So is possible to change it to '<=' or fail fast when it comes to negative?

**Comment by Mr14huashao** [comment]
Hi lsr-flying,
beginObject () in this file, 
avoid negative depth due to multiple threads.
hope can help you

**Comment by lsr-flying** [comment]
Mr14huashao,thank you so mush for your answer. Just tell me if i got misunstandstood again :)~ 
here is my test code, beginObject will plus depth while finally clause will minus depth, but if beginObject under race condition, depth might not be added appropriately
here is my test code:
`
 @Data
    @NoArgsConstructor
    static class User {
        private String name;
        private Long age;
    }

    public static void main(String[] args) throws Exception{
        ExecutorService executors = Executors.newFixedThreadPool(1000);

        for (int i = 0; i < 1000; i++) {
            executors.submit(() -> serialize());
        }
    }

    private static void serialize() {
        User user = new User();
        user.setName("peter");
        user.setAge(18L);
        byte[] b = SerializeUtil.serialize(user);
        System.out.println(new String(b));
    }
`

eventually, there's a chance  as below, and I think autoreset won't work.
![image](https://user-images.githubusercontent.com/11512256/91535170-4f429400-e945-11ea-8690-01d535631725.png)

**Comment by lsr-flying** [comment]
`@Slf4j
public class SerializeUtil {

    private static final Kryo shouldThreadLocalKryo = new Kryo();
    @Data
    @NoArgsConstructor
    static class User {
        private String name;
        private Long age;
    }

    public static void main(String[] args) throws Exception{
        ExecutorService executors = Executors.newFixedThreadPool(1000);
        for (int i = 0; i < 1000; i++) {
            executors.submit(() -> serialize());
        }
    }

    private static void serialize() {
        User user = new User();
        user.setName("peter");
        user.setAge(18L);

        byte[] buffer = new byte[2048];
        try (Output output = new Output(buffer)) {
            shouldThreadLocalKryo.writeClassAndObject(output, user);
        } catch (Exception ex) {
            log.error("Exception!!!!", ex);
        }
    }
}`

**Comment by Mr14huashao** [comment]
I may have understood you.
According to the test cases provided by you, the depth is negative.
I only known depth of the object graph,but what does the negative depth affect?
Looking forward to your reply

**Comment by lsr-flying** [comment]
if it's negative, then we won't run into kryo#reset().
It affects cache(classToNameId, which will be reused for anothr serialization loop(should not!), then affects serialized bytes format. When being deserialized, same single jvm or another cluster peer, might cause deserialization exception. 
this looks something like, in clusterd enviroment, we can kryo.setRegistrationRequired(false), as registration id might be different in each jvm,thus kryo might be unable to deserialize bytes from another jvm.

more detail:
kryo#reset() ->classResolver.reset()->classToNameId.clear()
![image](https://user-images.githubusercontent.com/11512256/91650809-ee3acd80-eab6-11ea-88f3-788f2bd18d61.png)

classToNameId acts as a cache for class to id, for one object, it's ok to use cache id to minimize bytes size. 
if classToNameId is not clear for another serialzation loop, then the logic 'Only write the class name the first time encountered in object graph' will not happen. As printing test case serialized bytes:
![image](https://user-images.githubusercontent.com/11512256/91651000-95b8ff80-eab9-11ea-913b-2388f3571337.png)

We will not see this problem until we deserialize bytes next time. I just wonder if it should(or worth) to complain rather to swallow this behavior(content race caused rest failure)?

**Comment by theigl** [comment]
@lsr-flying: Kryo is [not thread-safe](https://github.com/EsotericSoftware/kryo#thread-safety) at all and has to be used as a `TheadLocal` or in a `Pool` for multi-threaded access. Unless you can demonstrate that this issue can happen using a single thread, I think we can safely ignore this.

**Comment by lsr-flying** [comment]
@theigl If this is the design principle, I agree with ignoring :)
Again, thanks a lot for discussing~
