### ISSUE TITLE
Dose kryo need to add test cases?

### ISSUE THREAD

**Issue by Mr14huashao** [EsotericSoftware/kryo#764]
I found that kryo still had some methods that didn't have test cases.

need add test cases?

**Comment by theigl** [comment]
@Mr14huashao: Test coverage is currently around 80%, which is OK but not too great. I'm planning to add automated coverage reports for CI builds using Codecov so we can monitor and improve the test coverage.

If you want to add some tests, please go ahead and create a PR!
