### ISSUE TITLE
How to use TreeMapSerializer ?

### ISSUE THREAD

**Issue by Mr14huashao** [EsotericSoftware/kryo#767]
Kryo doesn't serialize the TreeMapSerializer comparator.
How to reproduce:

            HashMap map = new HashMap();
		map.put(1,122);
		map.put(2,314);
		map.put(4,2511);
		map.put(8,"hello");
		map.put(10,"wasted");
		map.put(3,"Great");
		TreeMap treeMap = new TreeMap(Comparator.reverseOrder());
		treeMap.putAll(map);
               
            final Kryo kryo = new Kryo();
		kryo.register(TreeMap.class, new DefaultSerializers.TreeMapSerializer());
		kryo.writeClassAndObject(output, treeMap);
		Object o = kryo.readClassAndObject(new Input(output.getBuffer()));

Did I use it wrong?
Thanks in advance

**Comment by theigl** [comment]
@Mr14huashao: What happens? An error message? Is the comparator null after deserialization?

I'm guessing the problem is with `Comparator.reverseOrder()` and not the `TreeMapSerializer`. `reverseOrder()` is basically a singleton and maybe can't be instantiated correctly.

**Comment by Mr14huashao** [comment]
TreeMap treeMap = new TreeMap(); 
Not Comparator.reverseOrder() have the same problem.
Report a error message: output cannot be null.

You mean Object with comparator properties can't be serializer?
I tested it and only copy() works.
#660 have the similar issues.

**Comment by theigl** [comment]
You have to register the comparator as well. This test passes:

    @Test
    public void testTreeMapWithReverseComparator () {
	  kryo.register(TreeMap.class);
	  kryo.register(Comparator.reverseOrder().getClass());

	  HashMap<Integer, Integer> map = new HashMap<>();
	  map.put(1, 122);
	  map.put(2, 314);
	  map.put(4, 2511);

	  TreeMap<Integer, Integer> treeMap = new TreeMap<>(Comparator.reverseOrder());
	  treeMap.putAll(map);

	  roundTrip(18, treeMap);
    }

**Comment by Mr14huashao** [comment]
Thanks for your help! @theigl. Your code is available.
Now I want to add a ConcurrentSkipListMapSerializer. 
Do you think it is necessary?

**Comment by Mr14huashao** [comment]
@theigl Thank you very much for your reply and check.
I update #763  and submit a new PR #768 
Welcome to the PR to provide your valuable comments.
