### ISSUE TITLE
Explicit Serializer directives should be used.

### ISSUE THREAD

**Issue by nielsbasjes** [EsotericSoftware/kryo#771]
If you have a class that implementes/extends two classes/interfaces for which a predefined DefaulSerializer is available the priority is always a point for discussion.
However the KryoSerializable is one which is to be considered an "explicit" serializer choice.
At this moment if you have a class that does 
`class MyCustomMap extends TreeMap<String, String> implements KryoSerializable {`
then for some reason the serializer for the TreeMap 'wins' which I consider to be bad.

See https://github.com/nielsbasjes/BugReport-KryoMap

**Comment by theigl** [comment]
@nielsbasjes: I think your proposal makes sense. Could you provide a PR for this?

**Comment by nielsbasjes** [comment]
Yes, already working on it
