### ISSUE TITLE
Document error

### ISSUE THREAD

**Issue by yangbiny** [EsotericSoftware/kryo#781]
[Chunked encoding](https://github.com/EsotericSoftware/kryo#chunked-encoding)

When I use this case, the Buffer underflow exception will always be thrown. When I modify it to the following case, it can be used normally. When OutputChunked is closed, you need to call outputChunked.endChunk();

```
    FileOutputStream stream = new FileOutputStream("path");
    OutputChunked outputChunked = new OutputChunked(stream, 1024);
    outputChunked.writeInt(random.nextInt(1000000));
    outputChunked.endChunk();
    outputChunked.writeInt(random.nextInt(1000000));
    outputChunked.endChunk();
    outputChunked.writeInt(random.nextInt(1000000));
    outputChunked.endChunk();
    outputChunked.close();
```

**Comment by theigl** [comment]
Thanks @yangbiny!
