### ISSUE TITLE
automatic-module-name

### ISSUE THREAD

**Issue by jonathanlocke** [EsotericSoftware/kryo#785]
I added this to the manifest of a local copy of RC9:

    Automatic-Module-Name: com.esotericsoftware.kryo

and with this addition Kryo works fine as a Java module. 
Could this be added to 5.0.0 final or perhaps 5.0.1?

Thanks,

    Jon

**Comment by theigl** [comment]
@jonathanlocke: This will be fixed in 5.0.1. See #776.

**Comment by theigl** [comment]
5.0.1 was just released.
