### ISSUE TITLE
OutOfMemoryException because of very big Generic instance

### ISSUE THREAD

**Issue by knsa83** [EsotericSoftware/kryo#786]
Hello,
I have the problem that our VM crashes with an OutOfMemoryException, because of very big Generic instance (approximately 2 GB).

This instance contains a very large Array of GenericTypes (268.435.455 items). All of the Array values contain the same Type or null.  

Additionally we observe that we get following exception before the OOM-Exception happens (not always):

WARNING: java.lang.ArrayIndexOutOfBoundsException: Index 134217728 out of bounds for length 134217728
        at com.esotericsoftware.kryo.util.DefaultGenerics.popGenericType(DefaultGenerics.java:66)
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:163)
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:44)
        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:644)
        ...

I think the problem started as I switch from 5.0.0.RC1 to 5.0.0-Release.

Currently `kryo.setOptimizedGenerics(optimizedGenerics);` is not stated explicity. Maybe the problem won't occur if this is set to false. I will look into this.

Greetings Sandra

**Comment by theigl** [comment]
Hi @knsa83: Thanks for reporting this. 

Could you please try to reproduce the growing of `DefaultGenerics.genericTypes` in a test-case?

> Currently kryo.setOptimizedGenerics(optimizedGenerics); is not stated explicity. Maybe the problem won't occur if this is set to false. I will look into this.

Disabling generics optimization will most likely fix the issue, but it would be great if you could help us to find the root cause of this problem.

**Comment by theigl** [comment]
This issue was introduced in RC2 with https://github.com/EsotericSoftware/kryo/commit/14b47277b108beeba419c12a8cbb6298eb18cf2c.

Under some circumstances, generic types are pushed but never popped.

I suggest you disable generics optimization until this is fixed.

**Comment by theigl** [comment]
I created a PR to resolve this and will include it in the 5.0.1 release.
