### ISSUE TITLE
Buffer underflow when using CompatibleFieldSerializer

### ISSUE THREAD

**Issue by joeyleeeeeee97** [EsotericSoftware/kryo#793]
```
private static final ThreadLocal<Kryo> kryos = new ThreadLocal<Kryo>() {
        protected Kryo initialValue() {
            Kryo kryo = new Kryo();
            kryo.setRegistrationRequired(false);
            kryo.setReferences(false);
            SerializerFactory.CompatibleFieldSerializerFactory compatibleFieldSerializerFactory  = new SerializerFactory.CompatibleFieldSerializerFactory();
            kryo.setDefaultSerializer(compatibleFieldSerializerFactory);
            kryo.setInstantiatorStrategy(new DefaultInstantiatorStrategy(new StdInstantiatorStrategy()));
            return kryo;
        }
    };

 @Override
    public byte[] serialize(Object object, Stream stream) throws Exception {
        Output output = new Output(outputBufferInitSize, outputBufferMaxSize);
        KryoUtils.getKryo().writeClassAndObject(output, object);
        byte[] bytes = output.toBytes();
        output.close();
        return bytes;
    }

    @Override
    public Object deserialize(byte[] bytes, Class<?> type, Stream stream) throws Exception {
        Input input = new Input(bytes);
        try {
            return KryoUtils.getKryo().readClassAndObject(input);
        } finally {
            input.close();
        }
    }

```

The exception stack is 
![image](https://user-images.githubusercontent.com/30545334/100076713-79401f80-2e7c-11eb-89fb-adf0f28517bc.png)

It's possible that there are different fields between client and server, so I am using CompatibleFieldSerializerFactory.
Have anybody met this problem?

**Comment by theigl** [comment]
@joeyleeeeeee97: Which version of Kryo are you using? Do client and server use the exact same versions?

Please try to replicate this problem in a test-case.

**Comment by joeyleeeeeee97** [comment]
Server and client are both using kryo 5.0.1

**Comment by joeyleeeeeee97** [comment]
> @joeyleeeeeee97: Which version of Kryo are you using? Do client and server use the exact same versions?
> 
> Please try to replicate this problem in a test-case.

Yes. I am trying to reproduce this but it seems to happen by chance on my server. I will try to find out under which scenarios this occurs.

**Comment by joeyleeeeeee97** [comment]
I can't reproduce by test case yet, but I found it throws this exception when:
1. Deserialize a specific DAO, but this DAO is the same between client and Server, the client has a subclass for that type.
Client
```
class DAO {
String a;
String b;
String c;
}

class DAO1 extends DAO {
// no any fields defined in DAO1
}
```
server 
```
class DAO {
String a;
String b;
String c;
}
```

2. It always happens when CompatibleFieldSerializer trying to read fields the first time, by the document
```
Additionally, the first time the class is encountered in the serialized bytes, a simple schema is written containing the field name strings. Because field data is identified by name, if a super class has a field with the same name as a subclass, extendedFieldNames must be true.
```

**Comment by joeyleeeeeee97** [comment]
Does kryo rely on message sequence? For example, I a, using one specific netty IO threads to process one connection, but I dispatch all messages to separate worker threads.
That means if we rely on one kryo serializer for one connection, that is not true for my case. The first DAO may be deserialized by thread one but the following may be dispatched to thread two.

**Comment by joeyleeeeeee97** [comment]
Update: I have made sure all messages arrive in sequence and this problem still exists.I am using https://arthas.aliyun.com/doc/en/ to dump exception params and stack, here is what I got:
watch com.esotericsoftware.kryo.kryo5.io.Input  require "{params,throwExp, target}" -e -x 4
![image](https://user-images.githubusercontent.com/30545334/100195484-5cfeba00-2f32-11eb-9938-4f0c85284a0a.png)

param :  required = 1
@Object[][
        @Integer[1],
    ],

position=@Integer[0],
capacity=@Integer[71],
limit=@Integer[71],
total=@Long[71],

required = 1
When proceed remaining equals limit(71) minus position(0) -> 71
But this didn't return from 
```
		if (remaining >= required) return remaining;
```

I am quite confused. I am sure I got the right params.

**Comment by theigl** [comment]
@joeyleeeeeee97: Thank you for investigating further!

Issues like this are reported from time to time. See https://github.com/EsotericSoftware/kryo/issues?q=is%3Aissue+%22buffer+underflow%22. In most cases it turns out to be either a concurrency issue or wrong usage of Kryo.

If you can, try temporarily setting the number of worker threads to 1 so we can rule out any concurrency issues.

**Comment by theigl** [comment]
@joeyleeeeeee97: Did you manage to resolve this issue or find the root cause?

**Comment by npepinpe** [comment]
I think we ran into this problem as well, and from what I can tell it seems to be related to how chunked input is read. We have a class A, which has a field of class B, which has a byte array of length ~13k bytes. The buffer to deserialize has size 14718, which seems relatively OK. We use the `CompatibleFieldSerializer` with chunked input, and the chunk size is 1024.

When deserializing, it gets all the way to the byte array, and at that point the field input is of type `InputChunked`, which is wrapping another `InputChunked`, which is wrapping a `ByteBufferInput`. When deserializing the byte array field, it ends up in `Input#readBytes` - there doesn't seem to be a `InputChunked#readBytes` - and there after reading all the bytes of the chunk, it never asks for the next chunk, it just assumes a buffer underflow, throws that, and the exception just bubbles back up.

**Comment by MarcMil** [comment]
I'd test this without the network code if possible. If I were you, I would try to write the serialized data into files as well. Try to deserialize the files right after serializing on the same thread. Does it always work? -> it's probably your network code. You can compare the "broken" input against the files and figure out what went wrong.
It doesn't work? -> if possible, I'd create a minimal test case containing only the serialization and deserialization in order to allow reproduction of the problem.
