### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by mhuss** [EsotericSoftware/kryo#803]
Illegal reflective access by com.esotericsoftware.kryo.util.UnsafeUtil (file:/C:/Brinqa/connector-agent/lib/kryo.jar) to constructor java.nio.DirectByteBuffer(long,int,java.lang.Object)

**Comment by theigl** [comment]
This is just a warning in current JDK versions. You can ignore it, or prevent Kryo from accessing Unsafe by starting your process with:

    -Dkryo.unsafe=false

See #626 and #543
