### ISSUE TITLE
Kryo keeps reading the same instance on SocketTimeoutException

### ISSUE THREAD

**Issue by stigc** [EsotericSoftware/kryo#807]
I am using kryo to send classes through a socket. After I started using read timeouts, I see that kryo is reading the same class over and over again, even though it was only sent once from the other client.

Without setSoTimeout, I did not see this behavior. Is this expected?

I have added this to my socket

socket.setSoTimeout(60_000); //read() will timeout after 60 seconds

This function here is called from a loop.

The 1. time, the socket holds some bytes, and readClassAndObject returns the correct instance.
The 2. time, the socket is empty, and readClassAndObject throws a timeout after 60 seconds.
The 3. time, the socket is still empty, but readClassAndObject returns a instance, which is incorrect.

	public void readOne() throws InterruptedException
	{
		try
		{
			SocketPacket packet = (SocketPacket)kryo.readClassAndObject(input);
			Log.write(packet.toString());
		}
		catch (Exception ex) 
		{
			String msg = ex.getMessage();
			if (msg.contains("java.net.SocketTimeoutException"))
			{
				Log.write("SocketTimeoutException");
			}
			else 
			{
				Log.write("Something else");
			}
		}
	}

**Comment by stigc** [comment]
here is how input is created

Input input = new Input(socket.getInputStream());

and my Kryo instance is created like this.

Kryo kryo = new Kryo();
kryo.setRegistrationRequired(true);
kryo.register(Test.class, index++); 

I see this behavior with version 3x and now 5x

**Comment by stigc** [comment]
I now see in the source code that the Kryo Input class holds a buffer. This holds the last read bytes.

Should I create a new Input instance on Exceptions? Even on SocketTimeoutException, where the socket is fine and reusable?

```
public class Input extends InputStream {
	protected byte[] buffer;
```

**Comment by theigl** [comment]
@stigc: Kryo doesn't know anything about sockets and timeouts. It simply handles data or streams of data. It is your responsibility to handle and recover from exceptions thrown by your `InputStream`.

You can create a new `Input` on timeout or try to reset the existing input.

**Comment by stigc** [comment]
Yes it know, it only reads (and knows) the abstraction Inputstream. But isn't it odd behavior, that after an exception occur, it will return a object it has deserialized before? So every second call to readClassAndObject, if using a socket input stream with read timeouts (setSoTimeout), will return ghost objects.

The 1. time, the socket holds some bytes, and readClassAndObject returns the correct instance.
The 2. time, the socket is empty, and readClassAndObject throws a timeout after 60 seconds
The 3. time, the socket is still empty, but readClassAndObject returns a instance, which is incorrect.
The 4. time, the socket is still empty, and readClassAndObject throws a timeout after 60 seconds
The 5. time, the socket is still empty, but readClassAndObject returns a instance, which is incorrect.

**Comment by theigl** [comment]
@stigc: I still don't quite follow how Kryo should deal with this issue. Can you demonstrate this in a test using mock/double instead of a real socket?

**Comment by stigc** [comment]
Try this

import java.io.FilterInputStream;
import java.io.IOException;

import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.io.Input;
import com.esotericsoftware.kryo.io.Output;

public class Main
{
	public static void main(String[] args)
	{
		Kryo kryo = new Kryo();
		kryo.setRegistrationRequired(true);
		kryo.register(Entity.class, 1); 

		//Create Entity bytes of length 2
		byte[] buffer = new byte[2];
		Output out = new Output(buffer);
		kryo.writeClassAndObject(out, new Entity());
		
		//Create a input stream returning buffer on first read.
		//subsequent calls will throw an Exception
		Input input = new Input(new MyInputStream(buffer));
		
		for (int i=0; i<5; i++)
		{
			try
			{
				System.out.println("reading");
				Object obj = kryo.readClassAndObject(input);
				System.out.println("readClassAndObject: " + obj.getClass().getName());
			}
			catch (Exception ex)
			{
				System.out.println("readClassAndObject: " + ex.getMessage());
			}
		}
	}
}

class MyInputStream extends FilterInputStream
{
	byte[] buffer;
	int reads = 0;
	
	protected MyInputStream(byte[] buffer)
	{
		super(null); //we are not using this
		this.buffer = buffer;
	}
	
    @Override
    public int read(byte b[], int off, int len) throws IOException 
    {
    	reads++;
    	if (reads > 1)
    		throw new IOException("Timeout");

    	System.out.println("Read off: " +off + ", len: " + len);
    	
    	for (int i=0; i<buffer.length; i++)
    		b[i] = buffer[i];
    	
        return buffer.length;
    }
}

class Entity { }

**Comment by theigl** [comment]
@stigc: I guess you are expecting the following output in your test. Is that correct?

```
reading
Read off: 0, len: 4096
readClassAndObject: com.esotericsoftware.kryo.Entity
reading
readClassAndObject: null
reading
readClassAndObject: java.io.IOException: SocketTimeoutException
reading
readClassAndObject: java.io.IOException: SocketTimeoutException
reading
readClassAndObject: java.io.IOException: SocketTimeoutException
```

You can achieve this by changing your code to this:

```java
public class Main
{
	public static void main(String[] args)
	{
		Kryo kryo = new Kryo();
		kryo.setRegistrationRequired(true);
		kryo.register(Entity.class, 1); 

		//Create Entity bytes of length 2
		byte[] buffer = new byte[2];
		Output out = new Output(buffer);
		kryo.writeClassAndObject(out, new Entity());
		
		//Create a input stream returning buffer on first read.
		//subsequent calls will throw an Exception
		final MyInputStream inputStream = new MyInputStream(out.getBuffer());
		Input input = new Input(inputStream);
		
		for (int i=0; i<5; i++)
		{
			try
			{
				System.out.println("reading");
				Object obj = kryo.readClassAndObject(input);
				System.out.println("readClassAndObject: " + (obj != null ? obj.getClass().getName() : null));
			}
			catch (KryoException ex)
			{
				String msg = ex.getMessage();
				if (msg.contains("SocketTimeoutException")) {
					input.setInputStream(inputStream);
					System.out.println("readClassAndObject: " + ex.getMessage());
				} else {
					throw ex;
				}
			}
		}
	}
}
```

Since Kryo isn't aware of the implementation of you input stream and doesn't know if the stream can recover from certain exceptions, I see no way of handling this in Kryo itself.

**Comment by stigc** [comment]
@theigl I would expect the following (why should readClassAndObject ever return null?)

reading
Read off: 0, len: 4096
readClassAndObject: com.esotericsoftware.kryo.Entity
reading
readClassAndObject: java.io.IOException: SocketTimeoutException
reading
readClassAndObject: java.io.IOException: SocketTimeoutException
reading
readClassAndObject: java.io.IOException: SocketTimeoutException
reading

**Comment by stigc** [comment]
IMO if kryo is in a bad state, it should throw a bad-stream-state-Exception (or whatever) on subsequent calls. It should not return the last deserialized object due to an internal buffer, that is very unexpected.

I understand that you use setInputStream as a workaround, but this is not very intuitive.
