### ISSUE TITLE
Spark (Scala) error: Class is not registered

### ISSUE THREAD

**Issue by sadatnfs** [EsotericSoftware/kryo#808]
Hey all,

I apologize if this has already been explored, but I keep getting this error whenever I have the Kryo registration required in my Spark app. The error is below; I have tried many a different types of combination to register this class but I just can't get anything to work, and so any help will be highly appreciated!

```
Caused by: com.esotericsoftware.kryo.KryoException: java.lang.IllegalArgumentException: Class is not registered: org.apache.spark.sql.execution.datasources.InMemoryFileIndex$Seriali
zableBlockLocation[]
Note: To register this class use: kryo.register(org.apache.spark.sql.execution.datasources.InMemoryFileIndex$SerializableBlockLocation[].class);
Serialization trace:
blockLocations (org.apache.spark.sql.execution.datasources.InMemoryFileIndex$SerializableFileStatus)
array (scala.collection.mutable.ArrayBuffer)
```

I've tried all kinds of things to get these classes to be registered, but it's just not working for me..

**Comment by theigl** [comment]
@sadatnfs: The Kryo error message is not ideal. Some improvements have been made in #780 but as I see from your example, we could also improve it for array types.

This should work if `SerializableBlockLocation` is publicly accessible:

    kryo.register(org.apache.spark.sql.execution.datasources.InMemoryFileIndex.SerializableBlockLocation.class);

If `SerializableBlockLocation` is not public, you can use `Class.forName()`:

    kryo.register(Class.forName("org.apache.spark.sql.execution.datasources.InMemoryFileIndex.SerializableBlockLocation");

According to the [Spark Docs](https://spark.apache.org/docs/latest/configuration.html#compression-and-serialization), registration should not be required by default. So depending on your case, you might be able to set `spark.kryo.registrationRequired` to `false`.

**Comment by sadatnfs** [comment]
Thanks @theigl . So yeah if I do set that conf to `false`, I don't get any errors. But I don't know if that will actually use any of the registrations (hence I wanted to enforce it).

I tried the options you wrote above but using a `$` in the class name string; let me try with the `.` instead and report back to you (this is a private class, so I'll have to use the second method). Thanks!

**Comment by sadatnfs** [comment]
Yep so that doesn't work; apparently that class just "cannot be found". And even looking at the source code for spark.sql.execution, SerializableBlockLocation is just not defined there.. odd stuff.

**Comment by theigl** [comment]
@sadatnfs: I found this SO thread: https://stackoverflow.com/questions/54106392/spark-kryo-register-for-array-class

Can you give this a try?

```
kryo.register(Array.newInstance(Class.forName("org.apache.spark.sql.execution.datasources.InMemoryFileIndex$SerializableBlockLocation"), 0)
                        .getClass());
```

**Comment by sadatnfs** [comment]
@theigl hah that's the only result that ever pops up when I searched for this for hours; tried and did not work unfortunately :/

**Comment by theigl** [comment]
Then I'm out of ideas.

Are you using Spark 2.x? When looking at the sources for [InMemoryFileIndex](https://github.com/apache/spark/blob/branch-2.4/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/InMemoryFileIndex.scala) the private classes are there.

Could you check the JAR files for the Spark version you are using and look for the generated class names?

**Comment by sadatnfs** [comment]
Thanks for your time nonetheless! And I'm using Spark 3.x and a quick look at the branch shows them not being there, so I wonder if there's some versioning conflict somewhere...

And I personally have no clue on how to do the latter part; I'll Google around for some hints.

If there's nothing else that's doable, then I'm happy to close this issue (or you can do it as well if you'd prefer).

**Comment by theigl** [comment]
Closing for now. Please feel free to re-open or report back if you find out anything more about the issue.
