### ISSUE TITLE
Picking up the wrong serializer as interface(Map) is common interface for multiple classes

### ISSUE THREAD

**Issue by sandeep27st** [EsotericSoftware/kryo#810]
Kryo internally pushes default serializers while creating kryo instance. **MapSerializer** is one of them for type `java.util.Map` and additionally in our solution we have our own serializer for the `net.sf.JSONObject` we used to push after the Kryo instance gets created.

`net.sf.JSONObject` implements `java.util.Map`, 
Till some point, Kryo is uses correct serializers for the type `net.sf.JSONObject`. Suddenly is referring to **MapSerializer**.

Can you please suggest any solution for this, so that it should always pick up the right serializers?

**Comment by theigl** [comment]
@sandeep27st: 

>  Suddenly is referring to MapSerializer.

What do you mean by suddenly? Which exact version did you use before and which version changed the behavior?

**Comment by theigl** [comment]
@sandeep27st: Please provide the required info. Otherwise I'll close this ticket.

**Comment by theigl** [comment]
Closing due to lack of feedback. Please re-open if you can provide further details.
