### ISSUE TITLE
Request: OSGI compatibility for the versioned kryo5 jar

### ISSUE THREAD

**Issue by vikinghawk** [EsotericSoftware/kryo#811]
Looking at the Manfiest of the regular kryo-5.x dependency, it appears to be a valid OSGI bundle.

We would would like to use the versioned/shaded kryo5 dependency in our shared library, but we also need to support OSGI. Would it be possible to generate a valid OSGI manifest for the versioned jar as well?

**Comment by theigl** [comment]
@vikinghawk: I have no experience with OSGI and can't really validate any changes. 

Can you submit a PR that turns the versioned artifact into a valid OSGI bundle? It might suffice to add the `maven-bundle-plugin` from `pom-mail.xml` to `pom-versioned.xml`. And the `<Export-Package>` likely needs to change to the versioned package.

**Comment by vikinghawk** [comment]
Ya thats something we can do. I'll take that back to my team and we will work on getting that generated and tested. Thanks!

**Comment by Shradha-git** [comment]
@vikinghawk  and @theigl 
https://github.com/EsotericSoftware/kryo/pull/818
This is the PR created to add OSGI manifest to version kryo5 dependency and validated from our side.
![KRYO5-RESOLVED](https://user-images.githubusercontent.com/81883671/113596655-4131c000-9658-11eb-9fbe-380e367a25d1.png)

**Comment by theigl** [comment]
@Shradha-git: I merged your PR and applied some changes in https://github.com/EsotericSoftware/kryo/commit/56817af4ac4902671268a74dd3bec9d110fcbd61 to get rid of the bundle plugin warnings.

Could you please test against the master or latest SNAPSHOT if you can still resolve the OSGI bundle using the current approach?

**Comment by theigl** [comment]
Better test the current master. Travis doesn't seem to run at the moment and SNAPSHOTS haven't been published yet.

**Comment by theigl** [comment]
@Shradha-git: Did you get a chance to verify against the current master?

**Comment by Shradha-git** [comment]
@theigl  Verified osgi bundle against latest master code and bundle got resolved.
cc @vikinghawk 

**MANITEST.MF got generated:**
Manifest-Version: 1.0
Created-By: Apache Maven Bundle Plugin
Build-Jdk-Spec: 10
Automatic-Module-Name: com.esotericsoftware.kryo.kryo5
Bnd-LastModified: 1617812865273
Build-Jdk: 10.0.2
Built-By: SR068348
Bundle-Description: Fast, efficient Java serialization. This is the ve
 rsion specific Kryo artifact.
Bundle-License: https://opensource.org/licenses/BSD-3-Clause
Bundle-ManifestVersion: 2
Bundle-Name: Kryo 5
Bundle-SymbolicName: com.esotericsoftware.kryo.5
Bundle-Version: 5.0.5.SNAPSHOT
Export-Package: com.esotericsoftware.kryo.kryo5;version="5.0.5",com.es
 otericsoftware.kryo.kryo5.io;version="5.0.5",com.esotericsoftware.kry
 o.kryo5.serializers;version="5.0.5",com.esotericsoftware.kryo.kryo5.u
 nsafe;version="5.0.5",com.esotericsoftware.kryo.kryo5.util;version="5
 .0.5",com.esotericsoftware.kryo.kryo5.objenesis;version="5.0.5",com.e
 sotericsoftware.kryo.kryo5.objenesis.instantiator;version="5.0.5",com
 .esotericsoftware.kryo.kryo5.objenesis.strategy;version="5.0.5"
Import-Package: sun.misc;resolution:=optional,sun.nio.ch;resolution:=o
 ptional,sun.reflect;resolution:=optional
Originally-Created-By: Apache Maven Bundle Plugin
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
Tool: Bnd-4.2.0.201903051501

**Comment by theigl** [comment]
@Shradha-git: Perfect, thank you! I'll release Kryo 5.1.0 in the coming days.

**Comment by Shradha-git** [comment]
@theigl  What is the planned release date for Kryo 5.1.0

**Comment by theigl** [comment]
@Shradha-git: 5.1.0 has just been released and should be on Maven Central shortly.
