### ISSUE TITLE
Cannot read field "arguments" because "genericType" is null

### ISSUE THREAD

**Issue by punk8** [EsotericSoftware/kryo#816]
My project ran into this problem when deserializing a piece of data during operation, but after I captured the data, the deserialization succeeded in the unit test. What is the main cause of the problem?

**Comment by theigl** [comment]
@punk8: Which version of Kryo are you using? Please post the full stack trace when the error occurs and your Kryo configuration or a minimal unit test.

If you cannot reproduce this in a unit test, it might be a concurrency issue. Are you sharing Kryo or any of its data structures between threads?

**Comment by punk8** [comment]
![image](https://user-images.githubusercontent.com/26299922/113478874-24618500-94be-11eb-9924-ef3b6a04525e.png)
I use kryo 5.0.4, maybe it's concurrency issue, i will try again. When I tracked the problem before, I found that the "genericType" obtained in the picture was a null value. Therefore, after I added a judgment, it is currently working normally, but I still don't understand the workflow here.

**Comment by theigl** [comment]
I can add the additional null-check but I would prefer if we could reproduce this in a failing unit test. Maybe there is another underlying issue.

**Comment by theigl** [comment]
Please share the stacktrace of the exception.

**Comment by punk8** [comment]
![image](https://user-images.githubusercontent.com/26299922/113481756-000da480-94ce-11eb-919f-e5a02b9a59e4.png)

**Comment by punk8** [comment]
![image](https://user-images.githubusercontent.com/26299922/113481773-203d6380-94ce-11eb-9106-4654bf6adfd2.png)
![image](https://user-images.githubusercontent.com/26299922/113481784-2df2e900-94ce-11eb-863f-da8b915823d7.png)

**Comment by theigl** [comment]
@punk8: Thanks! This info doesn't tell us very much though, only that the error happens in `ReflectField`.

Please try again to reproduce this in a test-case. I don't really want to add a null-check without knowing the root cause. This might just hide other problems.

**Comment by NKame** [comment]
Same here, but in writing and not reading, Kryo 5.1.0.
References following is activated, and it happens serializing a mutual parent <-> child relationship.

```
Caused by: java.lang.NullPointerException
	at com.esotericsoftware.kryo.util.DefaultGenerics.nextGenericTypes(DefaultGenerics.java:77)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.pushTypeVariables(FieldSerializer.java:132)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:102)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:642)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
```

Looking at the cause.

**Comment by XuMinhan** [comment]
I had the same problem. Because kryo itself is thread-unsafe, create one instance of kryo for each thread. Or create an object pool for kryo.
