### ISSUE TITLE
VersionFieldSerializer does not work with hibernate + redisson?

### ISSUE THREAD

**Issue by EinBexiii** [EsotericSoftware/kryo#817]
What I using:
- kryo 5.0.0-RC9
- redisson 3.13.4 (second level cache with hibernate, Kryo5Codec)
- Hibernate 5.4.21.Final

I would first like to note that I do not know if this is a mistake on Kryo's part.

I have 2 Entity Versions:

Old one: 
https://ghostbin.co/paste/nmmnn

new one:
https://ghostbin.co/paste/r93g

If I load the old entity first it working. But if I load the new entity I am getting an ArrayIndexOutOfBoundsException. (https://ghostbin.co/paste/gwak8q)

I use the Kryo5Codec where I have overridden the createKryo method.

    protected Kryo createKryo(ClassLoader classLoader) {
        Kryo kryo = new Kryo();
        if (classLoader != null) {
            kryo.setClassLoader(classLoader);
        }

        kryo.setRegistrationRequired(false);
        kryo.setReferences(false);
        kryo.setDefaultSerializer(VersionFieldSerializer.class);
        kryo.setInstantiatorStrategy(new StdInstantiatorStrategy());
        return kryo;
    }

**Comment by theigl** [comment]
You will have to debug this and look at `StandardCacheEntryImpl#dissasembledState` after deserialization. This ist most likely not a Kryo issue but with dependencies on Hibernate and Redisson this is hard to diagnose.

I'm using Kryo 5 + Hibernate + Redisson myself and never had any problems, but I'm using `FieldSerializer` and do not need versioning.

**Comment by theigl** [comment]
Also `VersionFieldSerializer` will probably not work in your case. Hibernate isn't serializing the entities themselves, but only their disassembled state as part of `StandardCacheEntryImpl`. So Kryo never sees your annotations.

**Comment by EinBexiii** [comment]
@theigl The problem is why I need a VersionFieldSerializer is that it can happen that some applications of us still use the old entity so I tried it with Kryo but unfortunately without success. Do you have another idea how to solve this, that you can use 2 entity versions without problems with hibernate + redisson?

**Comment by EinBexiii** [comment]
I have also tried CompatibleFieldSerializer. But this even not works if I have only 1 version of the entity. I am getting this error:

https://ghostbin.co/paste/amxgmy

**Comment by theigl** [comment]
> @theigl The problem is why I need a VersionFieldSerializer is that it can happen that some applications of us still use the old entity so I tried it with Kryo but unfortunately without success. Do you have another idea how to solve this, that you can use 2 entity versions without problems with hibernate + redisson?

As I said above, `VersionedFieldSerializer` and `CompatibleFieldSerializer` won't be of much use because the entities themselves are not serialized,  only the disassembled fields. Kryo never sees the entities.  What happens if you use the default `FieldSerializer`?

Are you sure Hibernate even supports this? The `ArrayIndexOutOfBoundsException` looks like Hibernate expects a certain number of fields matching the current entity.

**Comment by EinBexiii** [comment]
Hibernate should support this. If I disable the second level cache I can use 2 entity versions without problems.

**Comment by theigl** [comment]
> Hibernate should support this. If I disable the second level cache I can use 2 entity versions without problems.

I meant re-assembling changed entities from the 2nd level cache. It's possible that this simply doesn't work.

**Comment by theigl** [comment]
I'd suggest you try to step through the whole re-assembly logic in `StandardCacheEntryImpl` in a debugger to see what's causing the exception.

**Comment by EinBexiii** [comment]
> > Hibernate should support this. If I disable the second level cache I can use 2 entity versions without problems.
> 
> I meant re-assembling changed entities from the 2nd level cache. It's possible that this simply doesn't work.

Not sure about it. I read this: https://github.com/redisson/redisson/issues/2378, and then I tried it.

**Comment by EinBexiii** [comment]
> > @theigl The problem is why I need a VersionFieldSerializer is that it can happen that some applications of us still use the old entity so I tried it with Kryo but unfortunately without success. Do you have another idea how to solve this, that you can use 2 entity versions without problems with hibernate + redisson?
> 
> As I said above, `VersionedFieldSerializer` and `CompatibleFieldSerializer` won't be of much use because the entities themselves are not serialized, only the disassembled fields. Kryo never sees the entities. What happens if you use the default `FieldSerializer`?
> 
> Are you sure Hibernate even supports this? The `ArrayIndexOutOfBoundsException` looks like Hibernate expects a certain number of fields matching the current entity.

Works with one entity version, but same exceptions with FieldSerializer if I use 2 versions of the entity.

if I load the new entity first and then the old I get this exeption:
https://ghostbin.co/paste/am2f3

If I load the old entity and then the new:
https://ghostbin.co/paste/h9vb5c

**Comment by theigl** [comment]
I'd like to help but this is not really in the scope of Kryo. 

If you serialize and deserialize the entities directly with `CompatibleFieldSerializer` or `VersionedFieldSerializer` it would work as expected.

The problem lies somewhere in Hibernate's disassemble/re-assemble logic. It probably depends on the exact order of fields.

**Comment by EinBexiii** [comment]
> I'd like to help but this is not really in the scope of Kryo.
> 
> If you serialize and deserialize the entities directly with `CompatibleFieldSerializer` or `VersionedFieldSerializer` it would work as expected.
> 
> The problem lies somewhere in Hibernate's disassemble/re-assemble logic. It probably depends on the exact order of fields.

Yea, do you know where I can create an issue in hibernate?

**Comment by theigl** [comment]
https://hibernate.atlassian.net/jira/software/c/projects/HHH/issues

**Comment by theigl** [comment]
There is a very old issue about the topic: https://hibernate.atlassian.net/browse/HHH-6600

**Comment by theigl** [comment]
You can try to turn set `hibernate.cache.use_structured_entries=true`. Supposedly, this stores cache properties by name instead of index, but adds some overhead.

**Comment by EinBexiii** [comment]
> You can try to turn set `hibernate.cache.use_structured_entries=true`. Supposedly, this stores cache properties by name instead of index, but adds some overhead.

tried it and yes it works. The only issue when the old entity get's updated and now I load the new entity the columns that are new are null.

**Comment by theigl** [comment]
Closing for now since this is not a Kryo issue. You can try to create a Hibernate issue or ask on SO if anyone has a better solution for rolling deploys with Hibernate caches.

**Comment by theigl** [comment]
@EinBexiii: I just stumbled upon another possible workaround for this issue: Change the Hibernate cache region if you change the entity. This way, old and new objects are never stored in the same cache.

**Comment by EinBexiii** [comment]
@theigl I already thought about it, but the problem there is the entity updating.
