### ISSUE TITLE
The references is true by default, while the docs says it's not enabled by default

### ISSUE THREAD

**Issue by pyb1993** [EsotericSoftware/kryo#820]
From the source code, we can see if create a kryo by the default constructor, the references is set to be **true**
but the doc say which is not enabled by default.
seems this doc is out of date.

**Comment by theigl** [comment]
@pyb1993: This is not correct. References have been disabled by default in #617.

The default constructor results in `references=false` and `referenceResolver=null`.

**Comment by pyb1993** [comment]
> @pyb1993: This is not correct. References have been disabled by default in #617.
> 
> The default constructor results in `references=false` and `referenceResolver=null`.

I see it. 
And maybe the behavior difference of version should be mentioned, my kryo is before 5.0
and I thought it will also be disabled according to this doc.
A little bit misleading.

**Comment by theigl** [comment]
> And maybe the behavior difference of version should be mentioned, my kryo is before 5.0
and I thought it will also be disabled according to this doc.
A little bit misleading.

Ah ok I haven't thought about that! We currently only have documentation for Kryo 5. I'll restore the Readme for Kryo 4 and add it to the Wiki.

**Comment by theigl** [comment]
I restored 4.x documentation [here](https://github.com/EsotericSoftware/kryo/wiki/Kryo-v4) and added a link to the main Readme.
