### ISSUE TITLE
Direct dependency in com.esotericsoftware.kryo:kryo5 

### ISSUE THREAD

**Issue by charphi** [EsotericSoftware/kryo#825]
**Describe the bug**
The documentation says that `com.esotericsoftware.kryo:kryo5` Maven package has no dependency so it can be used in a library.
But the latest version (v5.1.0) adds a dependency to `com.esotericsoftware:kryo`

**To Reproduce**
See https://search.maven.org/artifact/com.esotericsoftware.kryo/kryo5/5.1.0/jar

**Comment by theigl** [comment]
@charphi: Thanks for reporting this! 

Some recent cleanup in the build for the versioned artifact seems to have broken POM generation. I just pushed a fix and will release 5.1.1 in the next couple of days.

**Comment by theigl** [comment]
Looks better now: https://oss.sonatype.org/content/repositories/snapshots/com/esotericsoftware/kryo/kryo5/5.1.1-SNAPSHOT/kryo5-5.1.1-20210430.151902-13.pom
