### ISSUE TITLE
missing no-arg constructor error while serializing groovy.lang.Closure

### ISSUE THREAD

**Issue by Mahesh-Bantaram** [EsotericSoftware/kryo#828]
**Describe the bug**
Getting missing no-arg constructor error while serializing groovy.lang.Closure. Do we have other way to handle this case?

**To Reproduce**
```
package core
import com.esotericsoftware.kryo.Kryo
import com.esotericsoftware.kryo.io.Input
import com.esotericsoftware.kryo.io.Output
import org.junit.Test

class GClosureTest {
    @Test
    void testGClosure() {
        Kryo kryo = new Kryo()
        kryo.registrationRequired = false
        kryo.setReferences(true)

        Map methodMapper = [helloMethod: { name -> println("Hello ${name}") }]

        Output output = new Output(new FileOutputStream("file.bin"))
        kryo.writeClassAndObject(output, methodMapper);
        output.close()

        Input input = new Input(new FileInputStream("file.bin"))
        def object = kryo.readClassAndObject(input)
        input.close()
        println object
        println("done")
    }
}
```

**Environment:**
 - OS: Windows 10
 - JDK Version: 8
 - Kryo Version: 5.1.0

**Additional context**
As we have support for Java8 closures, Do we have any other serializer alternatives? Please help.

**Comment by theigl** [comment]
@Mahesh-Bantaram: Please try adding the following to your config:

    kryo.setInstantiatorStrategy(new DefaultInstantiatorStrategy(new StdInstantiatorStrategy()));

The fallback strategy works without invoking the constructor, but I'm not sure if it will work with Groovy closures.

**Comment by Mahesh-Bantaram** [comment]
Thanks @theigl .
