### ISSUE TITLE
Allowing to get some delta when testing equality between floats or doubles

### ISSUE THREAD

**Issue by pgrt** [EsotericSoftware/kryo#830]
Hello,

In a clean debian/unstable chroot, the some tests are not passing because floats or doubles are compared by assertEquals but no delta is allowed, although there should be as the float 0 may have various representations. The attached patch solves these issues.
[testing_floats_doubles_equality.txt](https://github.com/EsotericSoftware/kryo/files/6500963/testing_floats_doubles_equality.txt)

**Environment:**
 - OS:Debian/unstable
 - JDK Version: 11
 - Kryo Version: 5.1.0

Best regards,
Pierre

**Comment by theigl** [comment]
@pgrt: Thank you for reporting this! Could you provide a PR instead of a patch?

**Comment by pgrt** [comment]
Hi,
Sure! Yet my fix is unfortunately quite poor, just commenting out as I have no precise idea of the real problem. Well, I will submit a PR and then we can talk again about it.

**Comment by theigl** [comment]
Closing until somebody else runs into this or we can determine the root cause.
