### ISSUE TITLE
Support for Ion data type

### ISSUE THREAD

**Issue by r0b0ji** [EsotericSoftware/kryo#836]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I want to use kryo serialization for for spark project where my data is in Ion format.

**Describe alternatives you've considered**
Currently when we encounter Ion data type in our spark job, we convert that to string to serialize and then again back from string to Ion format. This is wasteful as Ion binary compresses well and to be able to work natively with the data format will simplify the workflow.

**Additional context**
Ion is a superset of Json data type developed by Amazon. It works well for compression and has support for some more data type than Json. There are bindings available for most popular languages.

Wiki: https://en.wikipedia.org/wiki/Ion_(serialization_format)
Specs: https://amzn.github.io/ion-docs/
Ion-java github: https://github.com/amzn/ion-java

**Comment by r0b0ji** [comment]
I have an implementation ready and willing to contribute. I contributed to magro/kryo-serializers repo some 2 months ago, but that repository seems to be inactive.

The pull request which I made in that repo: https://github.com/magro/kryo-serializers/pull/130

**Comment by theigl** [comment]
@r0b0ji: Kryo tries to avoid all third party dependencies so kryo-serializers is the right project for this.

@magro: Could you take a look at this PR?
