### ISSUE TITLE
CompatibleFieldSerializer use OutputChunked to warp the output project may cause nesting flush problem

### ISSUE THREAD

**Issue by jackjoesh** [EsotericSoftware/kryo#837]
**Describe the bug**
I think the CompatibleFieldSerializer use OutputChunked to warp the output project may cause nesting flush problem, it will cost lots of cpu usage.
![kryo-wrap](https://user-images.githubusercontent.com/28348638/123415142-6a267900-d5e7-11eb-9137-5a7251a5980b.jpg)

For example:
If I have an object A,  and A contains an object B, and B contains an object C.
These three objects all use the CompatibleFieldSerializer, because we can't avoid dependent micro-services modify these objects.
In the end,  if the object c starts flushing,   then the order of execution is as follow:  flush to the buffer array of C -> flush to the buffer array of B -> flush to the buffer array of A -> flush to the java io
Why we can't flush to the buffer array of C -> flush to the java io directly?

Proved by our performance test，the long flush chain costs lots of cpu usage.  
The following screenshot is our jmc analysis：

![kryo](https://user-images.githubusercontent.com/28348638/123414930-1582fe00-d5e7-11eb-9a8a-d1f9a5a043d7.jpg)

Is there any way to avoid this problem？  Thank you!

**Comment by theigl** [comment]
@jackjoesh: Can we close this issue in favour of #838?
