### ISSUE TITLE
OutputChunked don't need to do twice super.flush()

### ISSUE THREAD

**Issue by jackjoesh** [EsotericSoftware/kryo#838]
**Describe the bug**

I think the OutputChunked don't need to do twice super.flush(), it may waste cpu usage

![image](https://user-images.githubusercontent.com/28348638/123522554-79451e00-d6f0-11eb-98c2-7212cd99139a.png)

can we modify the code, as following:

![image](https://user-images.githubusercontent.com/28348638/123522586-abef1680-d6f0-11eb-842f-750463442e12.png)

Wait for help, thank you!

**Comment by theigl** [comment]
@jackjoesh: Thanks for your suggestion. Please provide a PR with your suggested changes so we can discuss it further and can see what issues it might cause.

**Comment by jackjoesh** [comment]
> @jackjoesh: Thanks for your suggestion. Please provide a PR with your suggested changes so we can discuss it further and can see what issues it might cause.

Thank you,  here is my pr:   https://github.com/EsotericSoftware/kryo/pull/839
Please check it.
