### ISSUE TITLE
Add a possibility to skip objects

### ISSUE THREAD

**Issue by ghost** [EsotericSoftware/kryo#84]
_From [romixlev](https://code.google.com/u/romixlev/) on August 21, 2012 14:16:39_

Add skip() method to all serializers and Kryo.
This way, one can skip objects in the input stream without first deserializing them into newly created objects.

The implementation should be straight forward. The skip() method method should do the same as the read method, but avoid storing read values anywhere.

_Original issue: http://code.google.com/p/kryo/issues/detail?id=84_

**Comment by magro** [comment]
Closing, reopen if still relevant.
