### ISSUE TITLE
Support for huge Objectgraphs

### ISSUE THREAD

**Issue by TheGoesen** [EsotericSoftware/kryo#842]
**Is your feature request related to a problem? Please describe.**
Kryos "Input" and "Output" Classes are using a bytearray as backbuffer. This works for small messages, but if you need to serialize huge Objectgraphs this is bad:

1. kryo needs to internally hold a bytearray that is large enough to fully read the serialization. That means high memory usage , since the raw bytes and the objects need to fully be in the memory at the same time, both for serialization and deserialization. Allocating huge bytearrays might be slow or even impossible. Also it means that serializing Objectgraphs that don't fit in byte[Integer.MaxValue] is simply not possible using kryo.

**Describe the solution you'd like**
Kryo should offer a way so that huge object graphs are internally splitted into small chunks and then directly send to a supplied stream, so the bytes are out of the memory and the application doesnt need to allocate huge byteblocks

Using kryo that way would break serializer that manipulate the position of the output/input, but thats just how it is.

**Comment by theigl** [comment]
@TheGoesen: Did you take a look at `ByteBufferInput` and `ByteBufferOutput`?  It's not really what you are asking for, but using those should get you around some of the limitations of `byte[]`.

I'm open for a PR with specialized `Input`/`Output` classes for large graphs, but this is not a feature we plan to work on.

**Comment by TheGoesen** [comment]
Hello,
Yes I looked at those classes.  To my understanding these classes do not change a thing because a Bytebuffer is either

1. a simple wrapper around a bytearray, so the byte array just gets moved from one class to another.
2.  Or alternatively its directly allocated in native memory. You still need to allocate enough memory for a full graph. Also pushing the bytes from java to native memory is not directly helpful, since I want to read the bytes in java not in native.

**Comment by theigl** [comment]
You are right, using a direct buffer isn't ideal, but it would at least get you around the size limitations of byte[].

For reference, this issue has been discussed a long time ago here: https://github.com/EsotericSoftware/kryo/issues/10

Periodic flushing was suggested as the most straight forward solution. Unfortunately, the sample code of such an implementation isn't available anymore.

**Comment by TheGoesen** [comment]
Hello,
I do not see how a direct buffer gets around the size limitation. The size parameter is an int, so its still limited to 2gb.

To be fully transparent, I opened this issue, because I was seeing jvm crashes that seemed to be linked to the byte[] required by kryo. After some more testing and evaluation I no longer think that kryos byte[] were the cause of these crashes. Instead -xmx was overallocated.
So currently this point seems more like an ivory tower problem for me -> Being able to serialize/deserialize huge messages without holding all bytes in memory should still improve realworld performance/memory consumption, but I am no longer too concerned about it.

**Comment by theigl** [comment]
>  I do not see how a direct buffer gets around the size limitation. The size parameter is an int, so its still limited to 2gb.

You are right. I was under the wrong impression that it was possible to allocate buffers larger than that!

> After some more testing and evaluation I no longer think that kryos byte[] were the cause of these crashes. Instead -xmx was overallocated.

Thats good to hear! I'll close this issue for now and we'll revisit it when someone actually has a need for serializing humongous object graphs.

**Comment by kwalcock** [comment]
Hey, I'm just trying to serialize my array of 550852200 floats (honestly).  When that number gets multiplied by 4 in Output.java, the result is negative and subsequent code crashes.  Wish I had known that before.  There is a need.  I'll have to make do with a different format.

```java
	public void writeFloats (float[] array, int offset, int count) throws KryoException {
		if (capacity >= count << 2) {
			require(count << 2);
```
