### ISSUE TITLE
Value changed after add a field

### ISSUE THREAD

**Issue by javalover123** [EsotericSoftware/kryo#846]
**Describe the bug**
Value changed after add a field

**To Reproduce**
1. A pojo use VersionFieldSerializer, have a Long field f1, then app1 write some data to Redis, app2 decode right
2. Add a new field updateTime use @Since(1), then app1 write some new dato to redis
3. app2 doesn't update nor restart, then the new data f1 field value is changed, old data f1 field value is right

**Environment:**
 - OS: Ubuntu
 - JDK Version: 11
 - Kryo Version: 5.1.1

**Additional context**

**Comment by theigl** [comment]
@javalover123: Please create a reproducible test-case for this issue.

See https://gist.github.com/theigl/9bdbd7e97113bc5c230ceb96f79367ad for an example of how field changes can be (manually) tested.

**Comment by theigl** [comment]
Closing for now. Please re-open if you can provide a reproducer.
