### ISSUE TITLE
how can I  upgrade from setReferences(true) to setReferences(false) when service is online

### ISSUE THREAD

**Issue by jackjoesh** [EsotericSoftware/kryo#855]
If service A invoke service B, and they all has setted setReferences(true) .
Now I want to upgrade from setReferences(true) to setReferences(false) .
If I set service B from setReferences(true) to setReferences(false) , then service A will throw exception: Caused by: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 96,   because service A is still setReferences(true).
How can I deal this situation, we can't stop all service for upgrading, because we are business company ,thank you!

**Comment by theigl** [comment]
@jackjoesh: This is going to be difficult. 

Do you include some kind of version information in your serialized data stream so you can determine *before* deserialization if an object has references or not? If so, you could add two instances of Kryo to your services. One that has references enabled, and one that does not and decide which one to use based on the version information.

If you do not have any version information, all you can do is catch the exception and retry with a different Kryo instance that has references enabled/disabled.

**Comment by jackjoesh** [comment]
> @jackjoesh: This is going to be difficult.
> 
> Do you include some kind of version information in your serialized data stream so you can determine _before_ deserialization if an object has references or not? If so, you could add two instances of Kryo to your services. One that has references enabled, and one that does not and decide which one to use based on the version information.
> 
> If you do not have any version information, all you can do is catch the exception and retry with a different Kryo instance that has references enabled/disabled.

Yes ,we use the distributed config center to solver this problem finally，I think use the retry strategy also has some risks, thank you
