### ISSUE TITLE
Javadoc issue at Input.java "int read (bytes[])"

### ISSUE THREAD

**Issue by birbilis** [EsotericSoftware/kryo#856]
https://github.com/EsotericSoftware/kryo/blob/a2dfa5c8c2ea6f6fbb264199ef7e2ab972424190/src/com/esotericsoftware/kryo/io/Input.java#L284 should write "or -1 if no more bytes are available." at the end since that is the javadoc of the method that it calls internally

**Comment by theigl** [comment]
Added, thanks.
