### ISSUE TITLE
NPE while de-serializing an ArrayList 

### ISSUE THREAD

**Issue by geekthread** [EsotericSoftware/kryo#858]
**Describe the bug**
We are getting NPE while we are trying to de-serialize an arraylist
{ "java.lang.NullPointerException" : 
["ArrayList.java",1240,"java.util.ArrayList$SubList.checkForComodification",
"ArrayList.java",1050,"java.util.ArrayList$SubList.size",
"AbstractList.java",108,"java.util.AbstractList.add",
"CollectionSerializer.java",134,"com.esotericsoftware.kryo.serializers.CollectionSerializer.read",
"CollectionSerializer.java",40,"com.esotericsoftware.kryo.serializers.CollectionSerializer.read",
"Kryo.java",787,"com.esotericsoftware.kryo.Kryo.readClassAndObject",
"ObjectSerializerKryoImpl.java",81,"hidden.object.serializer.impl.ObjectSerializerKryoImpl.lambda$deserialize$1",
"ObjectSerializerPool.java",99,"hidden.object.serializer.impl.ObjectSerializerPool.run",
"ObjectSerializerKryoImpl.java",81,"hidden.object.serializer.impl.ObjectSerializerKryoImpl.deserialize"]}}} }

We were able to serialize the same object but during de-serialization we are getting this exception.

**Environment:**
 - OS: [e.g. Linux]
 - JDK Version: [e.g. 8]
 - Kryo Version: [e.g. 3.0.1]

**Comment by theigl** [comment]
@geekthread: Kryo 3 is 6 years old and not maintained anymore. If you can, please move to Kryo 5.
