### ISSUE TITLE
Could  you add a link to session-compatible-fast-serializer in README.md?

### ISSUE THREAD

**Issue by lingjun-cg** [EsotericSoftware/kryo#861]
I implement a serializer [session-compatible-fast-serializer] (https://github.com/alibaba/session-compatible-fast-serializer) like CompatibleFieldSerializer but with a  better performance. Could you add a link to session-compatible-fast-serializer in the "Projects using Kryo" section of README.md?

**Comment by theigl** [comment]
@lingjun-cg: Sure! Please provide a PR that adds it to the README and I'll merge it.

**Comment by lingjun-cg** [comment]
OK. A PR was created: https://github.com/EsotericSoftware/kryo/pull/862

**Comment by theigl** [comment]
@lingjun-cg: Merged, thanks!
