### ISSUE TITLE
Nullponiter Exception after deserialized using kryo

### ISSUE THREAD

**Issue by loudongfeng** [EsotericSoftware/kryo#863]
**Describe the bug**
After serialization and deserialization of the same object (say A), invoking A's method causes null pointer exception.
It's OK to invoke before serialization and no fields is null after deserialization.
This issue was reported first to Apache Hive:
https://issues.apache.org/jira/browse/HIVE-25671

**To Reproduce**
git clone https://github.com/loudongfeng/kryo-bug-demo.git
cd kryo-bug-demo
mvn test

**Environment:**
 - OS: Ubuntu
 - JDK Version: 1.8
 - Kryo Version: 5.2.0,5.0.3,3.0.3

**Additional context**

**Comment by theigl** [comment]
@loudongfeng: The problem is that `FieldInfo` is a non-static inner class. By default, Kryo doesn't serialize synthetic fields, so the deserialized instance of `FieldInfo` is not able to access the outer class.

You can get around this by selectively serializing synthetics:

```
final FieldSerializer.FieldSerializerConfig cfg = new FieldSerializer.FieldSerializerConfig();
cfg.setIgnoreSyntheticFields(false);
kryo.register(ColumnarStructBase.FieldInfo.class, new FieldSerializer<>(kryo, ColumnarStructBase.FieldInfo.class, cfg));
```

But if you do that, you have to enable references. Otherwise, the serializer recurses infinitely.

See https://github.com/EsotericSoftware/kryo/issues/320

**Comment by theigl** [comment]
A more generic solution for inner and anonymous classes is a custom serializer factory that looks something like this:

```
	private Serializer<?> newDefaultSerializer(Kryo k, Class<?> t) {
		if (isAnonymousClass(t) || isInnerClass(t)) {
			final FieldSerializer.FieldSerializerConfig cfg = new FieldSerializer.FieldSerializerConfig();
			cfg.setIgnoreSyntheticFields(false);
			return new FieldSerializer<>(k, t, cfg);
		}
		return new FieldSerializer<>(k, t);
	}

	private static boolean isAnonymousClass(Class<?> clazz) {
		return clazz.isAnonymousClass();
	}

	private static boolean isInnerClass(Class<?> clazz) {
		return clazz.isMemberClass() && !Modifier.isStatic(clazz.getModifiers());
	}
```

**Comment by loudongfeng** [comment]
Thanks @theigl for your useful information. I will close this issue as not a kryo problem.
