### ISSUE TITLE
Can not deserialize kotlin-generated SAM from JVM bytecode in lambda notation

### ISSUE THREAD

**Issue by holgerbrandl** [EsotericSoftware/kryo#867]
**Describe the bug**
It fails to serialize a SAM instance created in place using lambda notation. Regular object SAM instances derserialize correctly using the same protocol.

**To Reproduce**
https://github.com/holgerbrandl/kryo-kotlin-sam/blob/master/src/main/java/KyroSimpleCQ.kt#L53

The line link points to the failing example. I've added a few experiments above that all work fine. I've also added a grade project context to the example for better reproducibility

As it might help to trace down the root cause, I've also added the generated JVM bytecode to the repo under https://github.com/holgerbrandl/kryo-kotlin-sam/tree/master/compiler_output

I'd think that the class/variable names created by the kotlin compiler are legit JVM bytecode, but are different compared to what the java compiler would typically create here.

**Environment:**
 - OS: Windows10
 - JDK Version: 11
 - Kryo Version: 5.2.0

**Comment by theigl** [comment]
You can make this work by using the same approach as for [Java Closures](https://github.com/EsotericSoftware/kryo#closures):

```kotlin
kryo.register(SerializedLambda::class.java)
kryo.register(ClosureSerializer.Closure::class.java, ClosureSerializer())
```

This only works for serializable lambdas, so you need to change your interface or cast the lambda accordingly:

```kotlin
fun interface SmthgSAMGeneric<T> : java.io.Serializable {
    fun foo(): (T, T) -> String
}
```

**Comment by holgerbrandl** [comment]
FYI, some more insightful info regarding this issue has been added in https://kotlinlang.slack.com/archives/C7L3JB43G/p1639127887185300?thread_ts=1636705880.135000&cid=C7L3JB43G
