### ISSUE TITLE
Source Jar for shaded kryo5 has wrong package declaration inside files

### ISSUE THREAD

**Issue by leonard84** [EsotericSoftware/kryo#870]
**Describe the bug**
The [sources jar](https://repo1.maven.org/maven2/com/esotericsoftware/kryo/kryo5/5.2.0/kryo5-5.2.0-sources.jar) has relocated the source files to the correct package folder, but it didn't modify the package declaration inside the packages.

It is `package com.esotericsoftware.kryo;` while it should be `package com.esotericsoftware.kryo.kryo5;`.

This is also the probable cause of an issue with IntelliJ. When both kryo 4 and the shaded kryo5 are used as dependencies, then Intellij has problems jumping to the correct sources.

**To Reproduce**
Download the jar and look at the sources and see the mismatch

**Environment:**
 - Kryo Version: 5.2.0

**Additional context**
This could be solved by modifying the sources before packaging them in the jar, e.g., https://stackoverflow.com/a/2196729/16358266.

**Comment by theigl** [comment]
@leonard84: Thanks for the info! 

This should be fixable by using the following option for the shade plugin:

https://maven.apache.org/plugins/maven-shade-plugin/shade-mojo.html#shadeSourcesContent

I'll look into this before I release the next minor version.

**Comment by theigl** [comment]
Resolved via https://github.com/EsotericSoftware/kryo/commit/bc6c8cad9b579db99ed17c4c5531f5c4d530798b.

I'll try to release Kryo 5.2.1 in the coming days.
