### ISSUE TITLE
"Buffer underflow." happen occasionally

### ISSUE THREAD

**Issue by jackjoesh** [EsotericSoftware/kryo#871]
We have deployed kryo to our online servers clusters.（thousands of servers）
But  "Buffer underflow" exception happens occasionally.  I think it is  random problem.
Because we have thousands of servers, even random problems cannot be tolerated.

1  What is the general reason for such a problem？
2  How can we solve this problem completely？
Can it be completely resolved by upgrading to kryo-5.2.1 or set some config?
I am very much looking forward to help, because there are many online servers, I am very anxious，thank you

**Comment by theigl** [comment]
Which version of Kryo are you using at the moment? What is your Kryo configuration?

Please provide some stacktraces you see in production.

**Comment by jackjoesh** [comment]
I use the kryo 5.2.0

These are several exception stacks I have seen, they are relatively random

1
Caused by: com.esotericsoftware.kryo.kryo5.KryoException: Buffer underflow.
	at com.esotericsoftware.kryo.kryo5.io.Input.require(Input.java:219)
	at com.esotericsoftware.kryo.kryo5.io.Input.readAscii_slow(Input.java:886)
	at com.esotericsoftware.kryo.kryo5.io.Input.readAsciiString(Input.java:879)
	at com.esotericsoftware.kryo.kryo5.io.Input.readString(Input.java:775)
	at com.esotericsoftware.kryo.kryo5.serializers.UnsafeField$StringUnsafeField.read(UnsafeField.java:237)
	at com.esotericsoftware.kryo.kryo5.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:185)

2
Caused by: com.esotericsoftware.kryo.kryo5.KryoException: Buffer underflow.
	at com.esotericsoftware.kryo.kryo5.io.Input.require(Input.java:219)
	at com.esotericsoftware.kryo.kryo5.io.Input.readVarInt(Input.java:407)
	at com.esotericsoftware.kryo.kryo5.Kryo.readReferenceOrNull(Kryo.java:910)
	at com.esotericsoftware.kryo.kryo5.Kryo.readObject(Kryo.java:794)
	at com.esotericsoftware.kryo.kryo5.serializers.ReflectField.read(ReflectField.java:134)
	at com.esotericsoftware.kryo.kryo5.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:185)
	at com.esotericsoftware.kryo.kryo5.Kryo.readObject(Kryo.java:796)
	at com.esotericsoftware.kryo.kryo5.serializers.CollectionSerializer.read(CollectionSerializer.java:241)
	at com.esotericsoftware.kryo.kryo5.serializers.CollectionSerializer.read(CollectionSerializer.java:44)
	at com.esotericsoftware.kryo.kryo5.Kryo.readObject(Kryo.java:796)
	at com.esotericsoftware.kryo.kryo5.serializers.ReflectField.read(ReflectField.java:134)
	at com.esotericsoftware.kryo.kryo5.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:185)
	at com.esotericsoftware.kryo.kryo5.Kryo.readObject(Kryo.java:796)
	at com.esotericsoftware.kryo.kryo5.serializers.ReflectField.read(ReflectField.java:123)
	at com.esotericsoftware.kryo.kryo5.serializers.VersionFieldSerializer.read(VersionFieldSerializer.java:131)
	at com.esotericsoftware.kryo.kryo5.Kryo.readClassAndObject(Kryo.java:877)

**Comment by jackjoesh** [comment]
> Which version of Kryo are you using at the moment? What is your Kryo configuration?
> 
> Please provide some stacktraces you see in production.

I use the kryo 5.2.0

These are several exception stacks I have seen, they are relatively random

1
Caused by: com.esotericsoftware.kryo.kryo5.KryoException: Buffer underflow.
at com.esotericsoftware.kryo.kryo5.io.Input.require(Input.java:219)
at com.esotericsoftware.kryo.kryo5.io.Input.readAscii_slow(Input.java:886)
at com.esotericsoftware.kryo.kryo5.io.Input.readAsciiString(Input.java:879)
at com.esotericsoftware.kryo.kryo5.io.Input.readString(Input.java:775)
at com.esotericsoftware.kryo.kryo5.serializers.UnsafeField$StringUnsafeField.read(UnsafeField.java:237)
at com.esotericsoftware.kryo.kryo5.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:185)

2
Caused by: com.esotericsoftware.kryo.kryo5.KryoException: Buffer underflow.
at com.esotericsoftware.kryo.kryo5.io.Input.require(Input.java:219)
at com.esotericsoftware.kryo.kryo5.io.Input.readVarInt(Input.java:407)
at com.esotericsoftware.kryo.kryo5.Kryo.readReferenceOrNull(Kryo.java:910)
at com.esotericsoftware.kryo.kryo5.Kryo.readObject(Kryo.java:794)
at com.esotericsoftware.kryo.kryo5.serializers.ReflectField.read(ReflectField.java:134)
at com.esotericsoftware.kryo.kryo5.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:185)
at com.esotericsoftware.kryo.kryo5.Kryo.readObject(Kryo.java:796)
at com.esotericsoftware.kryo.kryo5.serializers.CollectionSerializer.read(CollectionSerializer.java:241)
at com.esotericsoftware.kryo.kryo5.serializers.CollectionSerializer.read(CollectionSerializer.java:44)
at com.esotericsoftware.kryo.kryo5.Kryo.readObject(Kryo.java:796)
at com.esotericsoftware.kryo.kryo5.serializers.ReflectField.read(ReflectField.java:134)
at com.esotericsoftware.kryo.kryo5.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:185)
at com.esotericsoftware.kryo.kryo5.Kryo.readObject(Kryo.java:796)
at com.esotericsoftware.kryo.kryo5.serializers.ReflectField.read(ReflectField.java:123)
at com.esotericsoftware.kryo.kryo5.serializers.VersionFieldSerializer.read(VersionFieldSerializer.java:131)
at com.esotericsoftware.kryo.kryo5.Kryo.readClassAndObject(Kryo.java:877)


Below is my configuration：

Kryo kryo = new Kryo();
CompatibleFieldSerializer.CompatibleFieldSerializerConfig config =
       new CompatibleFieldSerializer.CompatibleFieldSerializerConfig();
config.setChunkedEncoding(true);
config.setReadUnknownFieldData(true);
kryo.setDefaultSerializer(new SerializerFactory.CompatibleFieldSerializerFactory(config));
kryo.setRegistrationRequired(false);
kryo.setOptimizedGenerics(false);
kryo.addDefaultSerializer(Throwable.class, new JavaSerializer());
kryo.setInstantiatorStrategy(new DefaultInstantiatorStrategy(new StdInstantiatorStrategy()));
kryo.setReferenceResolver(new MapReferenceResolver(){
    public boolean useReferences(Class type) {
        return type != InvocationHandler.class && type != BigInteger.class && type != BigDecimal.class && type != Number.class && type != Date.class && type != LocalDateTime.class && type != String.class && !Util.isWrapperClass(type) && !Util.isEnum(type);
    }
});

**Comment by theigl** [comment]
Please try upgrading to 5.2.1. It includes one fix for a buffer underflow for collection fields: #834.

Do these errors only happen when you add or remove fields from classes being serialized or do they happen without any changes to the data model?

**Comment by jackjoesh** [comment]
> 



> Please try upgrading to 5.2.1. It includes one fix for a buffer underflow for collection fields: #834.
> 
> Do these errors only happen when you add or remove fields from classes being serialized or do they happen without any changes to the data model?

I don’t think the current problem is caused by adding or deleting fields. About one in a million requests will happen occasionally.

**Comment by jackjoesh** [comment]
> 

I found a situation, if a new enum field is added, and the amount of data returned will cause this problem. The data returned by some of our interfaces will be several hundred KBs

**Comment by jackjoesh** [comment]
> Please try upgrading to 5.2.1. It includes one fix for a buffer underflow for collection fields: #834.
> 
> Do these errors only happen when you add or remove fields from classes being serialized or do they happen without any changes to the data model?

I found a situation, if a new enum field is added, and the amount of data returned will cause this problem. The data returned by some of our interfaces will be several hundred KBs

**Comment by theigl** [comment]
Any chance you can reproduce this in a test? Without a reproducer it's nearly impossible to fix these kinds of issues.

**Comment by jackjoesh** [comment]
> Any chance you can reproduce this in a test? Without a reproducer it's nearly impossible to fix these kinds of issues.

Ok, let me try, wait for me

**Comment by jackjoesh** [comment]
> Any chance you can reproduce this in a test? Without a reproducer it's nearly impossible to fix these kinds of issues.

**I have reproduced this problem because the provider service added an enumeration field, and the consumer service did not have this field(use kryo 5.2.0)**

It will cause the following errors。
com.esotericsoftware.kryo.KryoException: Buffer underflow.
Serialization trace:
endTime (TestVo)

**When upgrade to 5.2.1, the problem can be solved, but I think it is necessary to locate the real cause and scope of the problem. 
Because we have too many online services(thousands), I can't upgrade all at once，please help me, thank you**


### the provider service data structure (serialize):
import java.util.Date;

public class TestVo {
    private Date endTime;

    private Date createTime;

    private TestEnum disc; // this is the new add field

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public void setDisc(TestEnum disc) {
        this.disc = disc;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}



public enum TestEnum {

    OFFICIAL(0, "promo-recommend-info"),
    PAYMENT(1, "promo-pay-recommend-info");

    int value;
    String func;
    TestEnum(int value, String func) {
        this.value = value;
        this.func = func;
    }

    public int getValue() {
        return value;
    }
    public String getFunc() { return func; }

    public static TestEnum of(int value) {
        for (TestEnum disc : values()) {
            if(disc.value == value) {
                return disc;
            }
        }
        return null;
    }
}


    public static void testSerialize(){
        TestVo testVo = new TestVo();
        testVo.setDisc(TestEnum.OFFICIAL);
        testVo.setCreateTime(new Date());
        byte[] bytes = KryoUtil.serialize(testVo);
        String s = Base64.getEncoder().encodeToString(bytes);
        //Here is the serialized data (base64)
        //AQBUZXN0Vu8BA2NyZWF0ZVRpbeVkaXPjZW5kVGlt5QcVyfOL7twvAAsBAVRlc3RFbnXtAQABAAA=
        writeFile(s);
    }
**Here is the serialized data (base64)**
AQBUZXN0Vu8BA2NyZWF0ZVRpbeVkaXPjZW5kVGlt5QcVyfOL7twvAAsBAVRlc3RFbnXtAQABAAA=






### the consumer service data structure (deserialize):


import java.util.Date;

public class TestVo {
    private Date endTime;

    private Date createTime;

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}


    public static void testDeserialize(){
        try
        {
            TestVo testVo = KryoUtil.deserialize(Base64.getDecoder().decode(readFile()));
            System.out.println(testVo);
        }catch (Throwable ex){
            ex.printStackTrace();
        }
    }


### my kryo config:

       Kryo kryo = new Kryo();
        kryo.setInstantiatorStrategy(new DefaultInstantiatorStrategy(new StdInstantiatorStrategy()));
        kryo.setReferenceResolver(new MapReferenceResolver(){
            public boolean useReferences(Class type) {
                return type != BigInteger.class && type != BigDecimal.class && type != Number.class && type != Date.class && type != LocalDateTime.class && type != String.class && !Util.isWrapperClass(type) && !Util.isEnum(type);
            }
        });
        kryo.setRegistrationRequired(false);
        kryo.setOptimizedGenerics(false);
        kryo.addDefaultSerializer(Throwable.class, new JavaSerializer());
        CompatibleFieldSerializer.CompatibleFieldSerializerConfig config =
                new CompatibleFieldSerializer.CompatibleFieldSerializerConfig();
        config.setChunkedEncoding(true);
        config.setReadUnknownFieldData(true);
        kryo.setDefaultSerializer(new SerializerFactory.CompatibleFieldSerializerFactory(config));
        return kryo;



###  I think the last place where the problem occurred：
![image](https://user-images.githubusercontent.com/28348638/146643947-9a2b00ed-eb82-4b0e-a340-edd675b14083.png)

![image](https://user-images.githubusercontent.com/28348638/146643971-b6ae2c28-3e7d-4ca7-9a7d-b4cfbcc96783.png)


### Please help me see the root cause? I find it very strange, is there any problem with every new enumeration field, thank you

**Comment by theigl** [comment]
@jackjoesh: Thanks a lot for the reproducer. I will try to look into this.

Did I understand correctly that upgrading to 5.2.1 solves the problem for you and the chunk with the new enum value is skipped?

**Comment by jackjoesh** [comment]
> @jackjoesh: Thanks a lot for the reproducer. I will try to look into this.
> 
> Did I understand correctly that upgrading to 5.2.1 solves the problem for you and the chunk with the new enum value is skipped?



> @jackjoesh: Thanks a lot for the reproducer. I will try to look into this.
> 
> Did I understand correctly that upgrading to 5.2.1 solves the problem for you and the chunk with the new enum value is skipped?

Yes, after upgrading to 5.2.1, the newly added enum field can be skipped by normal chunks. 
But I am very worried whether this problem will be triggered as long as the enum field is added. 
It is currently difficult for me to upgrade all services in the production environment. 
And I have tried to add a common object field, and there is no problem in 5.2.0.

**Comment by jackjoesh** [comment]
> @jackjoesh: Thanks a lot for the reproducer. I will try to look into this.
> 
> Did I understand correctly that upgrading to 5.2.1 solves the problem for you and the chunk with the new enum value is skipped?

Thank you, very much looking forward to getting the cause of your problem.
I am very afraid of problems in the production environment :(

**Comment by jackjoesh** [comment]
> @jackjoesh: Thanks a lot for the reproducer. I will try to look into this.
> 
> Did I understand correctly that upgrading to 5.2.1 solves the problem for you and the chunk with the new enum value is skipped?

Sorry, have you found any clues? If upgrading to 5.2.1 can completely solve such problems, I am going to start the upgrade tomorrow.
I think it is relatively common to add enum fields, I am more worried about whether there are similar problems, thank you.

**Comment by theigl** [comment]
I'll try to look into it next week, but I can't promise anything.

In think you can safely go ahead with the upgrade. #834 will resolve most issues with underflows when data cannot be read.

**Comment by jackjoesh** [comment]
> I'll try to look into it next week, but I can't promise anything.
> 
> In think you can safely go ahead with the upgrade. #834 will resolve most issues with underflows when data cannot be read.

ok, thank you very much

**Comment by jackjoesh** [comment]
> I'll try to look into it next week, but I can't promise anything.
> 
> In think you can safely go ahead with the upgrade. #834 will resolve most issues with underflows when data cannot be read.

Make another confirm,  is  5.2.1 and 5.2.0 are completely compatible?

**Comment by theigl** [comment]
Yes, they should be 100% compatible.

**Comment by jackjoesh** [comment]
> @jackjoesh: Did you manage to upgrade all your services? Is this issue resolved with 5.2.1?

Yes, for 2000 servers, I have upgraded to kryo 5.2.1. I haven't found any problems so far, thank you very much, I will continue to observe.
In addition, I have a suggestion, kryo's default serialization for enum is based on ordinal, I think the default serialization should be based on name (EnumNameSerializer.class). Although this will reduce performance, it will avoid very serious accidents. Many people do not notice that the default method is based on ordinal when using it.
Finally, thank you very much, I use the dubbo rpc framework, and the use of kryo has greatly improved the performance of the server  :)

**Comment by theigl** [comment]
@jackjoesh: Great! I'm glad this worked out fine for you.

> In addition, I have a suggestion, kryo's default serialization for enum is based on ordinal, I think the default serialization should be based on name (EnumNameSerializer.class). Although this will reduce performance, it will avoid very serious accidents. Many people do not notice that the default method is based on ordinal when using it.

This is not something that can be easily changed, because it would break backwards compatibility. We can think about changing the default implementation for Kryo 6 and document the current behavior somewhere, so people are aware of this.
