### ISSUE TITLE
Custom exception for Buffer Underflow (like BufferUnderflowKryoException)

### ISSUE THREAD

**Issue by msx80** [EsotericSoftware/kryo#872]
So i'm implementing some kind of persistency system, and i'd like to be able to differentiate between Buffer Underflows from other kind of exceptions, which are treated differently.

If possible it would be awesome if those exception could be differentiated, perhaps with a subclass of KryoException like BufferUnderflowKryoException, so they can be catched separatedly.

Currently i'm checking the message of the exception (`if(e.getMessage().contains("Buffer underflow")`) but it's far from ideal.
As an alternative an error code could be added, but i think it's more work and less idiomatic.

If needed i could try and submit a PR

**Comment by theigl** [comment]
@msx80: What is your use-case where you expect underflows and how do you handle them differently than other exceptions?

**Comment by msx80** [comment]
I have a [project](https://github.com/msx80/Jouram) for a database based on system prevalence, basically it has a journal that is written incrementally. When i'm reading back the journal, a truncated last entry can be expected, for example if the program was killed halfway on a write. The database can still be considered sane and the truncated entry discarded. Other errors means the DB cannot be safely read back for whatever reason and has to be considered corrupted.

**Comment by theigl** [comment]
Ok, thanks a lot for the explanation.

I think it makes sense to provide a bit more fine-grained exceptions. I'd go for a `KryoIOException` that can be used for `Input` as well as `Output`. 

The only problem is that we have to do this in a fully backwards-compatible way. Sub-classing `KryoException` and using the exact same error messages should be relatively safe though.

Do you want to provide a PR for this?

**Comment by msx80** [comment]
You mean KryoIOException for bufferunderflow (and overflow), or are you proposing a hierarchy like KryoException -> KrioIOException -> KryoBufferUnderflowException?

If it's the formere as i think, the name looks a bit too generic to me. Perhaps KryoBufferIOException? (this would leave open for other IO exception should we need it).

Yes i'll gladly provide the PR.

**Comment by theigl** [comment]
@msx80: `KryoIOException` with sub-classes `KryoBufferUnderflowException` and `KryoBufferOverflowException` would be fine with me. All these exceptions could be put in the `io` package. `Input` and `Output` throw some other kinds of IO related exceptions, so `KryoIOException` makes sense as well.
