### ISSUE TITLE
How to resolve KryoException due to UnsupportedOperation?

### ISSUE THREAD

**Issue by uddhavarote** [EsotericSoftware/kryo#888]
Hello Community,

I am writing a Flink application which uses open tracing to inject a list of [DDSpanContext](https://github.com/DataDog/dd-trace-java/blob/master/dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java) 

However, the  application randomly throws following exception
```
com.esotericsoftware.kryo.KryoException: java.lang.UnsupportedOperationException
Serialization trace:
queue (datadog.trace.core.PendingTraceBuffer$DelayingPendingTraceBuffer)
pendingTraceBuffer (datadog.trace.core.PendingTrace)
trace (datadog.trace.core.DDSpanContext)
delegate (datadog.opentracing.OTSpanContext)
...
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:82)

Caused by: java.lang.UnsupportedOperationException
	at org.jctools.queues.MpscBlockingConsumerArrayQueue.iterator(MpscBlockingConsumerArrayQueue.java:247)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:81)
```

Could somebody help me understand the serialization trace?

**Comment by theigl** [comment]
@uddhavarote: You will need to write a custom serializer for `MpscBlockingConsumerArrayQueue`. The default `CollectionSerializer` iterates over the collection to serialize the entries, but the queue does not support it.

**Comment by theigl** [comment]
Thinking about this some more: You probably don't want to serialize open tracing information at all. You could register a no-op serializer for `OTSpanContext` that simply serializes the field as null.
