### ISSUE TITLE
Can BigDecimalSerializer support round_up or round_down features?

### ISSUE THREAD

**Issue by jackjoesh** [EsotericSoftware/kryo#893]
Can BigDecimalSerializer support round_up or round_down features?  Or is there any spi that can extend this kind of features?
Thank you

**Comment by theigl** [comment]
What do you mean by that? Can you give me an example of what you want Kryo to do?

**Comment by jackjoesh** [comment]
> What do you mean by that? Can you give me an example of what you want Kryo to do?

    @BigDecimalCut(accuracy=8, roundHalfUp=true)
    private BigDecimal value;
    
    Attributes can be annotated to control the number of digits after the decimal point and whether to round or not

**Comment by jackjoesh** [comment]
> What do you mean by that? Can you give me an example of what you want Kryo to do?

That means how can I define  customize Serializer/Deserializer for  a field  in  an object?

**Comment by jackjoesh** [comment]
> What do you mean by that? Can you give me an example of what you want Kryo to do?

Sorry, I changed the question, can I get the custom annotation on the field in my custom serializer? I hope some properties in these annotations will affect the serialization rules.
At present, I found that only annotation properties can be obtained in CachedFields, not in custom serializers.

**Comment by theigl** [comment]
> can I get the custom annotation on the field in my custom serializer? I hope some properties in these annotations will affect the serialization rules.

Unfortunately, this isn't possible at the moment. We would need to extend the `Serializer` interface with overloaded methods like this:

```java
public abstract void write (Kryo kryo, Output output, T object, CachedField field);

public abstract T read (Kryo kryo, Input input, Class<? extends T> type, CachedField field);
```

Or provide some type of `SerializerContext` object to the methods.

This would require some major changes, but could probably be solved in a backwards-compatible way by making the new methods `default` methods that simply delegate to the existing methods without the additional context parameter.

If you want, you can provide a PR for this for further discussion.

**Comment by jackjoesh** [comment]
> > can I get the custom annotation on the field in my custom serializer? I hope some properties in these annotations will affect the serialization rules.
> 
> Unfortunately, this isn't possible at the moment. We would need to extend the `Serializer` interface with overloaded methods like this:
> 
> ```java
> public abstract void write (Kryo kryo, Output output, T object, CachedField field);
> 
> public abstract T read (Kryo kryo, Input input, Class<? extends T> type, CachedField field);
> ```
> 
> Or provide some type of `SerializerContext` object to the methods.
> 
> This would require some major changes, but could probably be solved in a backwards-compatible way by making the new methods `default` methods that simply delegate to the existing methods without the additional context parameter.
> 
> If you want, you can provide a PR for this for further discussion.

thank you,  I will try it
