### ISSUE TITLE
Will TaggedFieldSerializer be able to skip null fields?

### ISSUE THREAD

**Issue by xuedonglxd** [EsotericSoftware/kryo#894]
**Is your feature request related to a problem? Please describe.**
We have some POJO classes with hundreds of fields defined, but in each instance maybe there are only a few fields which are not null. (well, things are like this for a reason, different users could have different views of the same entity) 
And we used "chunked " just to be safe, because we ofter add new fields.
What I'm trying to say is, serializing (and then deserializing) those null fields could be a big waste.

**Describe the solution you'd like**
When writing fields, firstly iterate all the fields and record all the tags for non-null fields.
And only deal will non-null fields after that (so the number of fields will differ between different instances of the same class)
I have implemented this by my own by in a quite ugly way because it is almost impossible to inherit from the TaggedFieldSerializer class (because of its private fields).

So will you consider this or should I initiate a pull request of my version?

**Comment by theigl** [comment]
@xuedonglxd: This sounds like a very specific use case. You can create a PR, but I cannot promise that I will merge it, if it adds too much complexity. What private fields do you need to access to implement this in your custom solution? Maybe we can expose them.

**Comment by NathanSweet** [comment]
I'm not sure if others would make use of this specific feature. It might be slightly more interesting to provide a way of skipping any field with user defined criteria (eg by overriding a method) rather that only fields that are null. I'm not convinced it needs to go in TaggedFieldSerializer though. If `writeTags` was protected, a subclass could do it. However, it's not really all that terrible to just copy/paste TaggedFieldSerializer and change it for a particular use case.
