### ISSUE TITLE
CompatibleFieldSerializer sets default value instead of original data

### ISSUE THREAD

**Issue by Balamurali-arumugam** [EsotericSoftware/kryo#897]
Application A creates an object and serializes using kryo 3.0.3

Application B, a new branch from A where the class have extra fields to deserialize it i am using 
CompatibleFieldSerializer and kryo 3.0.3.

but when analysed the data, kryo created just an empty object of pojo and not copied the data

**Environment:**
OS: Windows
Application A uses Java 8
Application B uses Java 11
Both uses.kryo 3.0.3

**Comment by theigl** [comment]
@Balamurali-arumugam: Kryo 3.0.3 is 7 years old and no longer supported. Please upgrade to Kryo 5.
