### ISSUE TITLE
Does kryo has some serialize feature to ignore the non-field-getter when deserialize 

### ISSUE THREAD

**Issue by kevinkwok326** [EsotericSoftware/kryo#904]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by theigl** [comment]
@kevinkwok326: What do you mean by this? Can you give me an example?

**Comment by theigl** [comment]
Closed due to missing feedback. Please re-open if you can provide a clear description of your request.
