### ISSUE TITLE
How to change KryoFactory of request 4 to upgrade to 5

### ISSUE THREAD

**Issue by JavaLionLi** [EsotericSoftware/kryo#918]
**Describe the bug**

**To Reproduce**
Provide a minimal reproducible example of the problem, ideally in the form of a runnable test-case.

**Environment:**
 - OS: [e.g. Ubuntu]
 - JDK Version: [e.g. 11]
 - Kryo Version: [e.g. 5.1.0]

**Additional context**

**Comment by theigl** [comment]
I don't quite understand your question. For upgrade infos see #796.

**Comment by theigl** [comment]
What is `KryoFactory`? What library are you using? Can you share some code?

**Comment by JavaLionLi** [comment]
> What is `KryoFactory`? What library are you using? Can you share some code?

![image](https://user-images.githubusercontent.com/31852897/192818804-04deaf2e-3d75-4954-9e06-a5f27f657587.png)
Code of 4.0.2

**Comment by theigl** [comment]
Ok, thanks.

Instead of `KryoFactory`, a pool is now created like this:

```java
Pool<Kryo> kryoPool = new Pool<Kryo>(true, false, 8) {
   protected Kryo create () {
      Kryo kryo = new Kryo();
      // Configure the Kryo instance.
      return kryo;
   }
};
```

See https://github.com/EsotericSoftware/kryo#pooling

**Comment by JavaLionLi** [comment]
> thanks

thank you
