### ISSUE TITLE
序列化Map StackOverflowError

### ISSUE THREAD

**Issue by JavaLionLi** [EsotericSoftware/kryo#919]
**Describe the bug**

![image](https://user-images.githubusercontent.com/31852897/193205781-89c028bb-f3ad-4b5e-85b9-76acc91583d6.png)
![image](https://user-images.githubusercontent.com/31852897/193206440-813d72e2-3bc5-45de-9ecb-a6d57c74decf.png)
![image](https://user-images.githubusercontent.com/31852897/193206608-556d6bdb-ac61-4aa1-846d-d2b5ff6eda7c.png)

**Comment by theigl** [comment]
In Kryo 5 references are disabled by default. You will need to enable references to support data structures with cycles.

**Comment by theigl** [comment]
Did the same test work with Kryo 4 with `setReferences(false)`?

**Comment by JavaLionLi** [comment]
4 It's OK to use the default

**Comment by theigl** [comment]
Ok that makes sense. References were enabled by default in 4. In 5, you have to enable them manually with `setReferences(true)`.

**Comment by JavaLionLi** [comment]
> Ok that makes sense. References were enabled by default in 4. In 5, you have to enable them manually with `setReferences(true)`.

Why is the request changed to false?
Is there any bad influence?

**Comment by theigl** [comment]
See this ticket: https://github.com/EsotericSoftware/kryo/issues/617
