### ISSUE TITLE
JDK 11 WARNING: Please consider reporting this to the maintainers of com.esotericsoftware.kryo.unsafe.UnsafeUtil

### ISSUE THREAD

**Issue by tietang** [EsotericSoftware/kryo#924]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.esotericsoftware.kryo.unsafe.UnsafeUtil (file:/Users/header/.m2/repository/com/esotericsoftware/kryo/5.3.0/kryo-5.3.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of com.esotericsoftware.kryo.unsafe.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Temurin [jdk-11.0.17+8](https://github.com/adoptium/temurin11-binaries/releases/tag/jdk-11.0.17%2B8)

MacOS

**Comment by theigl** [comment]
You currently have two options:

1. You can use `-Dkryo.unsafe=false` to avoid loading `UnsafeUtil`
2. You can add `--add-opens java.base/java.nio=ALL-UNNAMED` to allow access to `DirectByteBuffer`.

**Comment by theigl** [comment]
Should be resolved by #932. It would be great if you could verify the fix using the latest snapshot build.
