### ISSUE TITLE
Kryo 4.0.2 serialization issue from JDK 17 to 8

### ISSUE THREAD

**Issue by jzhuge** [EsotericSoftware/kryo#935]
**Describe the bug**
When objects are serialized in JDK 17, they failed to be deserialized in JDK 8. Details in https://issues.apache.org/jira/browse/SPARK-42036.

```
22/12/21 01:27:12 ERROR TaskResultGetter: Exception while getting task result
com.esotericsoftware.kryo.KryoException: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.nio.ByteBuffer
Serialization trace:
lowerBounds (org.apache.iceberg.GenericDataFile)
taskFiles (org.apache.iceberg.spark.source.SparkWrite$TaskCommit)
```

Same Spark job works when both driver and executors run the same JDK 8 or JDK 17.

Will Kryo 5 fix this issue?
Spark effort in https://issues.apache.org/jira/browse/SPARK-34023

**To Reproduce**
Spark job using Iceberg table.

**Environment:**
 - OS: Ubuntu 18.04
 - JDK Version: 17.0.5 and 1.8.0_352
 - Kryo Version: 4.0.2

**Comment by jzhuge** [comment]
```
22/12/21 01:27:12 ERROR TaskResultGetter: Exception while getting task result
com.esotericsoftware.kryo.KryoException: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.nio.ByteBuffer
Serialization trace:
lowerBounds (org.apache.iceberg.GenericDataFile)
taskFiles (org.apache.iceberg.spark.source.SparkWrite$TaskCommit)
```

**Comment by theigl** [comment]
Closing for now. Please re-open if you can create a reproducer.
