### ISSUE TITLE
wrong serializer in class serialization

### ISSUE THREAD

**Issue by taxiboy** [EsotericSoftware/kryo#937]
**Describe the bug**
When you want to serialize a Class, the serializer is not ClassSerializer.

**To Reproduce**
```java
package turbo.codec;

import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.io.Output;
import com.esotericsoftware.kryo.serializers.FieldSerializer;

public class KryoTest {
    static class KryoTestSerializer extends FieldSerializer<KryoTest> {
        public KryoTestSerializer(Kryo kryo) {
            super(kryo, KryoTest.class);
        }
    }

    public static void main(String[] args) {
        Kryo kryo = new Kryo();
        kryo.setRegistrationRequired(false);
        kryo.register(KryoTest.class, new KryoTestSerializer(kryo));

        Output output = new Output(256, -1);
        kryo.writeClassAndObject(output, KryoTest.class); //debug this line
        output.close();
    }
}
```
Debug in, writeClass is right, use ClassSerializer.
![image](https://user-images.githubusercontent.com/8414473/215311957-27637eaf-a322-41ad-a9ea-6eaa2e067361.png)

Debug in Kryo line 711 -> DefaultClassResolver line 113
![image](https://user-images.githubusercontent.com/8414473/215312292-066eb867-aa47-4374-a842-e1cce59382ff.png)
This type here in fact is value, real type is java.lang.Class, value is KryoTest. Expected serializer is ClassSerializer not KryoTestSerializer.

How about refactor this function
https://github.com/EsotericSoftware/kryo/blob/3fb0a624f094408f9360bff5f2d975facff3afa9/src/com/esotericsoftware/kryo/ClassResolver.java#L51
 like 
```java
public Registration writeClass (Output output, Class type, Class object)
```
?

**Environment:**
 - OS: win11
 - JDK Version: 17.0.2
 - Kryo Version: 5.3.0

**Additional context**

**Comment by taxiboy** [comment]
https://github.com/EsotericSoftware/kryo/blob/3fb0a624f094408f9360bff5f2d975facff3afa9/src/com/esotericsoftware/kryo/serializers/DefaultSerializers.java#L289-L306
Or change ClassSerializer#write(Kryo, Output, Class) and ClassSerializer#read(Kryo, Input, Class), don't use kryo.writeClass/readClass

**Comment by theigl** [comment]
I don't understand what you are trying to achieve here. 

If you want to serialize the class object, you don't need any custom serializers. You can just do this:

```java
    public static void main(String[] args) {
        Kryo kryo = new Kryo();
        kryo.setRegistrationRequired(false);

        Output output = new Output(256, -1);
        kryo.writeClassAndObject(output, KryoTest.class);
        output.close();

        final Input input = new Input(output.getBuffer());
        final Object o = kryo.readClassAndObject(input);
        assertEquals(o, KryoTest.class);
    }
```

**Comment by taxiboy** [comment]
> I don't understand what you are trying to achieve here.
> 
> If you want to serialize the class object, you don't need any custom serializers. You can just do this:
> 
> ```java
>     public static void main(String[] args) {
>         Kryo kryo = new Kryo();
>         kryo.setRegistrationRequired(false);
> 
>         Output output = new Output(256, -1);
>         kryo.writeClassAndObject(output, KryoTest.class);
>         output.close();
> 
>         final Input input = new Input(output.getBuffer());
>         final Object o = kryo.readClassAndObject(input);
>         assertEquals(o, KryoTest.class);
>     }
> ```


I described not clear before, please try this code again. I'm trying to serialize a class object not specific KryoTest instance, so I only regist Class.class.
```java
package turbo.codec;

import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.io.Output;
import com.esotericsoftware.kryo.serializers.DefaultSerializers;

public class KryoTest {
    public static void main(String[] args) {
        Kryo kryo = new Kryo();
        kryo.register(Class.class, new DefaultSerializers.ClassSerializer());

        Output output = new Output(256, -1);
        kryo.writeClassAndObject(output, KryoTest.class);
        output.close();
    }
}
```


```java
Exception in thread "main" java.lang.IllegalArgumentException: Class is not registered: turbo.codec.KryoTest
Note: To register this class use: kryo.register(turbo.codec.KryoTest.class);
	at com.esotericsoftware.kryo.Kryo.getRegistration(Kryo.java:579)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.writeClass(DefaultClassResolver.java:112)
	at com.esotericsoftware.kryo.Kryo.writeClass(Kryo.java:613)
	at com.esotericsoftware.kryo.serializers.DefaultSerializers$ClassSerializer.write(DefaultSerializers.java:287)
	at com.esotericsoftware.kryo.serializers.DefaultSerializers$ClassSerializer.write(DefaultSerializers.java:281)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:711)
	at turbo.codec.KryoTest.main(KryoTest.java:15)
```

**Comment by theigl** [comment]
OK thanks for clarifying. 

Kryo doesn't support. You have to `setRegistrationRequired(false)` or manually register every concrete class you want to serialize.

This works:

```java
public class KryoTest {
	public static void main (String[] args) {
		Kryo kryo = new Kryo();
		kryo.register(Class.class);
		kryo.register(KryoTest.class);

		Output output = new Output(256, -1);
		kryo.writeClassAndObject(output, KryoTest.class);
		output.close();

		final Input input = new Input(output.getBuffer());
		final Object o = kryo.readClassAndObject(input);
		assertEquals(o, KryoTest.class);
	}
}
```

**Comment by theigl** [comment]
@taxiboy: I don't have time at the moment to look into your issue. I'll try to get back to you in the coming weeks.
