### ISSUE TITLE
Serialization is broken on Android when desugaring of Java 8 APIs

### ISSUE THREAD

**Issue by filipebrandao** [EsotericSoftware/kryo#938]
**Describe the bug**
Java 8 API desugaring on Android, which allows to use the Java 8 API in older Android versions, causes the desugared classes to be located at `j$` root package instead of `java`.
Serializers such as TimeSerializers which check for `isClassAvailable("java.time.Duration")` before enabling a serializer will misbehave when running on older Android versions that rely on the desugared code.  

**To Reproduce**
Have an Android project with desugaring enabled:
```
    compileOptions {
        coreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
```

Call `TimeSerializers.addDefaultSerializers()` and notice that those serializers are not applied when running the app on Android 6. 
Then without decent serializers in place, in the specific case of a `ZonedDateTime` being serialized, I believe it will later fail to deserialize its' ZoneOffset and ZoneId. 

**Environment:**
 - OS: Android 6 ( API 23 )
 - Kryo Version: 4.0.1 but should happen in all more recent versions

**Additional context**
As a band-aid solution in my project, I copied the whole TimeSerializers and removed the `isClassAvailable()` checks. This approach works for me.

More info about D8 library desugaring on Android: https://jakewharton.com/d8-library-desugaring/#backporting-types

**Comment by theigl** [comment]
@filipebrandao: Android 6 is 7 years old and has a market share of ~1%. Is this issue relevant for any newer Android version?

What I could do in Kryo 5 is add a method `TimeSerializers.registerSerializers()`, that registers all `java.time` classes without the `isClassAvailable()` check. You could then call this method to force registration of these classes.

**Comment by filipebrandao** [comment]
@theigl fair point regarding the market share. From my research this issue happens until Android 7.1 (API Level 25) inclusive.
Nowadays it's still common that Android app projects  have a `minSdk` of 23 thus the apps are generally still supported in such devices.
Still, the % of end users running such old Android devices is small and just gets smaller over time (hopefully). So I do realize that this is a very small edge case for Kryo and maybe not worth a fix :)

**Comment by theigl** [comment]
> Still, the % of end users running such old Android devices is small and just gets smaller over time (hopefully). So I do realize that this is a very small edge case for Kryo and maybe not worth a fix :)

I think so too. So if you can live with your current workaround, I'd suggest we simply wait for Android 6 to go away. ;)
