### ISSUE TITLE
How to I can deserialize from serial bytes of version 4.0.1 by version 5.4.0

### ISSUE THREAD

**Issue by lazyduck037** [EsotericSoftware/kryo#945]
Hi, I have a serial bytes make by version 4.0.1. Now I want to upgrade to 5.4.0, I deserialize with 5.4.0 was wrong. How to I can deserialize from serial bytes of version 4.0.1  by 5.4.0?. Look like 5.4.0 didn't read chuck size in 4.0.1 serial bytes.

<img width="853" alt="Screenshot 2023-03-24 at 11 16 41" src="https://user-images.githubusercontent.com/32600174/227423183-b9880438-6156-4467-8b48-f6d490f28658.png">

**Comment by theigl** [comment]
Please see https://github.com/EsotericSoftware/kryo/issues/796
