### ISSUE TITLE
KryoBufferUnderflowException buffer underflow happend sometimes

### ISSUE THREAD

**Issue by shucsrain001** [EsotericSoftware/kryo#979]
**Describe the bug**
i meet an exception occurs occasionly.
the exception stack is below
com.esotericsoftware.kryo.io.KryoBufferUnderflowException: Buffer underflow.
Serialization trace:
mem (com.bocom.common.monitor.entity.HostInfoVo)
hostInfoVo (com.bocom.common.echo.EchoResponse)
 at com.esotericsoftware.kryo.io.Input.require(Input.java:221)
 at com.esotericsoftware.kryo.io.Input.readUtf8Chars_slow(Input.java:837)
 at com.esotericsoftware.kryo.io.Input.readUtf8Chars(Input.java:830)
 at com.esotericsoftware.kryo.io.Input.readString(Input.java:787)
 at com.esotericsoftware.kryo.serializers.UnsafeField$StringUnsafeField.read(UnsafeField.java:237)
 at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:129)
 at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:799)
 at com.esotericsoftware.kryo.serializers.ReflectField.read(ReflectField.java:124)
 at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:129)
 at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:799)
at com.esotericsoftware.kryo.serializers.ReflectField.read(ReflectField.java:124)
 at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:129)
 at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:880)
 at com.bocom.common.utils.SerializerUtils.deserialize(SerializerUtils.java:81)
 at com.bocom.common.echo.EchoDecoder.decode(EchoDecoder.java:58)

**To Reproduce**
public class SerializerUtils {

    private static final ThreadLocalKryoFactory factory = new ThreadLocalKryoFactory();
 
    public static byte[] serialize(Object data) {
        ByteArrayOutputStream bos = null;
        try {
            bos = new ByteArrayOutputStream();
 
            Output output = new Output(bos);
            factory.get().writeClassAndObject(output, data);
            output.flush();
            output.close();
            return bos.toByteArray();
        } finally {
            if (bos != null) {
                try {
                    bos.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
    }

   
    public static <T> T deserialize(byte[] data, Class<T> clz) {
        ByteArrayInputStream is = null;
        try {
            is = new ByteArrayInputStream(data);
 
            Input input = Input input = new Input(is);
            T t = (T) factory.get().readClassAndObject(input);
            return t;
      } finally {
            if (is != null) {
                try {
                    is.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }

    }

**Environment:**
 - OS:linux
 - JDK Version: jdk1.8.0_152
 - Kryo Version: 5.5.0

**Additional context**
the SerializerUtils is used in netty  decoder program to help desrialize bytes.

why it happend some times ,not everytime duiring work?

**Comment by shucsrain001** [comment]
the other key class is below

@Data
@Measurement(name = "mem")
public class MemVo implements Serializable {
    private static final long serialVersionUID = -8374968061642201135L;

    @Column(name = "time")
    @JsonFormat(pattern = "hh:mm:ss", timezone = "GMT+8")
    private Instant time;

    @Column(name = "ip", tag = true)
    private String ip;

    @Column(name = "total")
    @JsonSerialize(using = GSerialize.class)
    private long total = 0L;


    @Column(name = "ram")
    private long ram = 0L;

    @Column(name = "actualUsed")
    @JsonSerialize(using = GSerialize.class)
    private long actualUsed = 0L;//

    @Column(name = "actualFree")
    private long actualFree = 0L;//

    @Column(name = "usedPercent")
    @JsonSerialize(using = DoubleSerialize.class)
    private double usedPercent = 0.0D;//
 }

public class DoubleSerialize extends JsonSerializer<Object> {

    @Override
    public void serialize(Object value, JsonGenerator generator, SerializerProvider serializerProvider) throws IOException {
        if (value != null) {
            BigDecimal bigDecimal = new BigDecimal(value.toString()).setScale(0, BigDecimal.ROUND_HALF_UP);
            generator.writeNumber(bigDecimal.longValue());
        }
    }
}

public class GSerialize extends JsonSerializer<Object> {

    private static final BigDecimal TEMP = BigDecimal.valueOf(1024L * 1024 * 1024);

    @Override
    public void serialize(Object value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
        if (value != null) {
            BigDecimal bigDecimal = new BigDecimal(value.toString());

            gen.writeNumber(bigDecimal.divide(TEMP, 1, RoundingMode.HALF_UP));
        }
    }
}

**Comment by shucsrain001** [comment]
public abstract class KryoFactory {

    private final static KryoFactory threadFactory = new ThreadLocalKryoFactory();

    protected KryoFactory() {
    }

    public static KryoFactory getDefaultFactory() {
        return threadFactory;
    }


    protected Kryo createKryo() {
        Kryo kryo = new Kryo();
        kryo.setRegistrationRequired(false);
        kryo.register(MessageTypeEnum.class);
        kryo.register(SystemInfoVo.class);

        kryo.register(HostInfoVo.class);
        kryo.register(NetIoVo.class);
        kryo.register(MemVo.class);
        kryo.register(EchoRequest.class);
        kryo.register(EchoResponse.class);
 kryo.register(HashMap.class);
        kryo.register(ArrayList.class);
        kryo.register(LinkedList.class);
        kryo.register(HashSet.class);
        kryo.register(TreeSet.class);
        kryo.register(Hashtable.class);
        kryo.register(Date.class);
        kryo.register(Calendar.class);
        kryo.register(ConcurrentHashMap.class);
        kryo.register(SimpleDateFormat.class);
        kryo.register(GregorianCalendar.class);
        kryo.register(Vector.class);
        kryo.register(BitSet.class);
        kryo.register(StringBuffer.class);
        kryo.register(StringBuilder.class);
        kryo.register(Object.class);
        kryo.register(Object[].class);
        kryo.register(String[].class);
        kryo.register(byte[].class);
        kryo.register(char[].class);
        kryo.register(int[].class);
        kryo.register(float[].class);
        kryo.register(double[].class);
return kryo ;
}
}

**Comment by theigl** [comment]
@shucsrain001: This is impossible to diagnose from the code you have given. I would need a test-case that actually reproduces the issue.
